force-app/main/default/objects/Case/fields/Active_Form__c.field-meta.xml
<CustomField>
    <fullName>Active_Form__c</fullName>
    <description>For resuming the last worked on form in QFR.</description>
    <label>Active Form</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact, Record Id of the related Contact record.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>(Generic NAPS Position Name) The role of this contact</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Assessment Service Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Assessor</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Financial Management</fullName>
            </value>
            <value>
                <fullName>Funding Agreement Variations</fullName>
            </value>
            <value>
                <fullName>Funding Submissions</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Aged Care Program Contact</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Key Personnel</fullName>
            </value>
            <value>
                <fullName>General Staff</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>Applicant Representative</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Leader</fullName>
            </value>
            <value>
                <fullName>Activity Contact</fullName>
            </value>
            <value>
                <fullName>Acquittal/Financial Reporting</fullName>
            </value>
            <value>
                <fullName>Assessment Service Administrator</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate Support</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate</fullName>
            </value>
            <value>
                <fullName>Choice Attributes</fullName>
            </value>
            <value>
                <fullName>Care Services Management</fullName>
            </value>
            <value>
                <fullName>Remittance/RCTI</fullName>
            </value>
            <value>
                <fullName>High level contact</fullName>
                <label>High Level Contact</label>
            </value>
            <value>
                <fullName>Service Monitoring &amp; Reports</fullName>
            </value>
            <value>
                <fullName>Centre Management</fullName>
            </value>
            <value>
                <fullName>Aged Care Service Manager</fullName>
            </value>
            <value>
                <fullName>Financial Reporting Contact</fullName>
            </value>
            <value>
                <fullName>QFR Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Is_Complete__c.field-meta.xml
<CustomField>
    <fullName>Is_Complete__c</fullName>
    <description>Flag to store if the form has been completed or contains errors.</description>
    <label>Is Complete</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AcfrSidebarControllerTest.cls
@isTest
public with sharing class AcfrSidebarControllerTest {
	@TestSetup
	static void setup() {
		Account acc = TestDataFactory.createProviderRecords(1)[0];
		insert acc;

		Contact con = new Contact(
			FirstName = 'Test',
			LastName = 'Contact',
			Salutation = 'Ms',
			Email = 'test@email.com'
		);
		insert con;

		Contact_Relationship__c cr = new Contact_Relationship__c(
			Account__c = acc.Id,
			Contact__c = con.Id,
			Role__c = 'QFR Primary Contact'
		);
		insert cr;

		Case c = new Case(
			AccountId = acc.Id,
			Status = 'Submitted',
			Active_Form__c = 'STViabiltyQuestionsHomeCareProvider',
			RecordTypeId = [
				SELECT Id
				FROM RecordType
				WHERE SObjectType = 'Case' AND DeveloperName = 'QFR'
				LIMIT 1
			]
			.Id
		);
		insert c;

		Form__c f_resi = new Form__c(
			Type__c = 'Residential Labour Costs and Hours',
			Account__c = acc.Id,
			Case__c = c.Id,
			Is_Complete__c = 'false'
		);
		insert f_resi;

		Form__c f_home = new Form__c(
			Type__c = 'Home Care Labour Costs and Hours',
			Account__c = acc.Id,
			Case__c = c.Id,
			Is_Complete__c = 'true'
		);
		insert f_home;

		Account acc_non = TestDataFactory.createProviderRecords(2)[1];
		insert acc_non;

		Contact con_non = new Contact(
			FirstName = 'No',
			LastName = 'Primary',
			Salutation = 'Mr',
			Email = 'noprimarycontact@email.com'
		);
		insert con_non;

		Contact_Relationship__c cr_non = new Contact_Relationship__c(
			Account__c = acc_non.Id,
			Contact__c = con_non.Id,
			Role__c = 'Financial Reporting Contact'
		);
		insert cr_non;

		Case c_non = new Case(
			AccountId = acc_non.Id,
			Status = 'Draft',
			RecordTypeId = [
				SELECT Id
				FROM RecordType
				WHERE SObjectType = 'Case' AND DeveloperName = 'QFR'
				LIMIT 1
			]
			.Id
		);
		insert c_non;
	}

	@isTest
	static void testGetFormStates() {
		Id caseId = [SELECT Id FROM Case WHERE Status = 'Submitted' LIMIT 1].Id;

		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();
		List<Form__c> forms = [
			SELECT Id
			FROM Form__c
			ORDER BY CreatedDate DESC
		];
		for (Form__c form : forms) {
			form.OwnerId = healthUser.Id;
		}
		update forms;

		List<Form__c> result = new List<Form__c>();

		Test.startTest();
		System.runAs(healthUser) {
			result = AcfrSidebarController.getFormStates(caseId);
		}
		Test.stopTest();

		System.assertEquals(false, result.isEmpty());
		System.assertEquals('false', result[0].Is_Complete__c);
		System.assertEquals('true', result[1].Is_Complete__c);
	}

	@isTest
	static void testCheckPrimaryContact() {
		Id caseId = [SELECT Id FROM Case WHERE Status = 'Submitted' LIMIT 1].Id;
		Id caseId_non = [SELECT Id FROM Case WHERE Status = 'Draft' LIMIT 1].Id;

		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();
		List<Form__c> forms = [
			SELECT Id
			FROM Form__c
			ORDER BY CreatedDate DESC
		];
		for (Form__c form : forms) {
			form.OwnerId = healthUser.Id;
		}
		update forms;

		Boolean result = false;
		Boolean result_non = true;

		Test.startTest();
		System.runAs(healthUser) {
			result = AcfrSidebarController.checkPrimaryContact(caseId);
			result_non = AcfrSidebarController.checkPrimaryContact(caseId_non);
		}
		Test.stopTest();

		System.assertEquals(true, result);
		System.assertEquals(false, result_non);
	}

	@isTest
	static void testUpdateIsCompleteFlag() {
		Id caseId = [SELECT Id FROM Case WHERE Status = 'Submitted' LIMIT 1].Id;
		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();
		List<Form__c> forms = [
			SELECT Id
			FROM Form__c
			ORDER BY CreatedDate DESC
		];
		for (Form__c form : forms) {
			form.OwnerId = healthUser.Id;
		}
		update forms;

		Id form_change = forms[0].Id;
		Id form_same = forms[1].Id;

		Test.startTest();
		System.runAs(healthUser) {
			AcfrSidebarController.updateIsCompleteFlag(form_change, 'true');
			AcfrSidebarController.updateIsCompleteFlag(form_same, 'true');
		}
		Test.stopTest();

		List<Form__c> forms_results = [
			SELECT Id, Is_Complete__c
			FROM Form__c
			ORDER BY CreatedDate DESC
		];

		System.assertEquals('true', forms_results[0].Is_Complete__c);
		System.assertEquals('true', forms_results[1].Is_Complete__c);
	}

	@isTest
	static void testResumeForn() {
		Id caseId = [SELECT Id FROM Case WHERE Status = 'Submitted' LIMIT 1].Id;
		Id caseId_non = [SELECT Id FROM Case WHERE Status = 'Draft' LIMIT 1].Id;
		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();

		String result;
		String result_non;

		Test.startTest();
		System.runAs(healthUser) {
			result = AcfrSidebarController.resumeForm(caseId);
			result_non = AcfrSidebarController.resumeForm(caseId_non);
		}
		Test.stopTest();

		System.assertEquals('STViabiltyQuestionsHomeCareProvider', result);
		System.assertEquals('STBeforeYouStart', result_non);
	}

	@isTest
	static void testSaveActiveForm() {
		Id caseId = [SELECT Id FROM Case WHERE Status = 'Submitted' LIMIT 1].Id;
		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();

		String activeForm = 'ResidentialProviderFinancialPerformanceSurvey';

		Test.startTest();
		System.runAs(healthUser) {
			AcfrSidebarController.saveActiveForm(caseId, activeForm);
		}
		Test.stopTest();

		Case case_results = [
			SELECT Id, Active_Form__c
			FROM Case
			WHERE Id = :caseId
			LIMIT 1
		];

		System.assertEquals(
			'ResidentialProviderFinancialPerformanceSurvey',
			case_results.Active_Form__c
		);
	}
}