force-app/main/default/objects/Case/fields/Active_Form__c.field-meta.xml
<CustomField>
    <fullName>Active_Form__c</fullName>
    <description>For resuming the last worked on form in QFR.</description>
    <label>Active Form</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>(Generic NAPS Position Name) The role of this contact</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Assessment Service Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Assessor</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Financial Management</fullName>
            </value>
            <value>
                <fullName>Funding Agreement Variations</fullName>
            </value>
            <value>
                <fullName>Funding Submissions</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Aged Care Program Contact</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Key Personnel</fullName>
            </value>
            <value>
                <fullName>General Staff</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>Applicant Representative</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Leader</fullName>
            </value>
            <value>
                <fullName>Activity Contact</fullName>
            </value>
            <value>
                <fullName>Acquittal/Financial Reporting</fullName>
            </value>
            <value>
                <fullName>Assessment Service Administrator</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate Support</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate</fullName>
            </value>
            <value>
                <fullName>Choice Attributes</fullName>
            </value>
            <value>
                <fullName>Care Services Management</fullName>
            </value>
            <value>
                <fullName>Remittance/RCTI</fullName>
            </value>
            <value>
                <fullName>High level contact</fullName>
                <label>High Level Contact</label>
            </value>
            <value>
                <fullName>Service Monitoring &amp; Reports</fullName>
            </value>
            <value>
                <fullName>Centre Management</fullName>
            </value>
            <value>
                <fullName>Aged Care Service Manager</fullName>
            </value>
            <value>
                <fullName>QFR Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Is_Complete__c.field-meta.xml
<CustomField>
    <fullName>Is_Complete__c</fullName>
    <description>Flag to store if the form has been completed or contains errors.</description>
    <label>Is Complete</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AcfrSidebarController.cls
/**
 * @description       : For initialising sidebar states on load
 * @last modified on  : 29-May-2023
 * @TestClass AcfrSidebarControllerTest
 **/
public with sharing class AcfrSidebarController {
	@AuraEnabled
	public static List<Form__c> getFormStates(Id caseId) {
		List<Form__c> formStates = [
			SELECT Id, Type__c, Is_Complete__c
			FROM Form__c
			WHERE Case__c = :caseId
		];

		return formStates;
	}

	@AuraEnabled
	public static Boolean checkPrimaryContact(Id caseId) {
		List<Case> relatedAccount = [
			SELECT AccountId
			FROM Case
			WHERE Id = :caseId
		];

		List<Contact_Relationship__c> primaryContact = [
			SELECT Id
			FROM Contact_Relationship__c
			WHERE
				Account__c = :relatedAccount[0].AccountId
				AND Role__c = 'QFR Primary Contact'
		];

		Boolean primaryContactExists = false;
		if (!primaryContact.isEmpty()) {
			primaryContactExists = true;
		}

		return primaryContactExists;
	}

	@AuraEnabled
	public static void updateIsCompleteFlag(Id formId, String isCompleteValue) {
		Form__c formRecord = [
			SELECT Id, Is_Complete__c
			FROM Form__c
			WHERE Id = :formId
		];

		if (formRecord.Is_Complete__c != isCompleteValue) {
			formRecord.Is_Complete__c = isCompleteValue;
			update formRecord;
		}
	}

	@AuraEnabled
	public static string resumeForm(Id caseId) {
		Case currentCase = [
			SELECT Id, Active_Form__c
			FROM Case
			WHERE Id = :caseId
			LIMIT 1
		];

		if (currentCase.Active_Form__c == null) {
			return 'STBeforeYouStart';
		} else {
			return currentCase.Active_Form__c;
		}
	}

	@AuraEnabled
	public static void saveActiveForm(Id caseId, String activeForm) {
		Case currentCase = [
			SELECT Id, Active_Form__c
			FROM Case
			WHERE Id = :caseId
			LIMIT 1
		];

		currentCase.Active_Form__c = activeForm;
		update currentCase;
	}
}