force-app/main/default/objects/Case/fields/Current_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Current_Reporting_Period__c</fullName>
    <description>Display Current Reporting Period</description>
    <formula>Reporting_Period__r.Current_Reporting_Period__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Display Current Reporting Period</inlineHelpText>
    <label>Current Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull from Reporting Perion Object.</description>
    <label>Reporting Period ID</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/GL_Code_Line_Item__c.object-meta.xml
<CustomObject>
    <description>GL Code Line Item</description>
    <label>GL Code Line Item</label>
    <nameField>
        <displayFormat>GLI-{000000}</displayFormat>
        <label>GL Code Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Code Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/Service_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Line_Item__c</fullName>
    <label>Service Line Item</label>
    <referenceTo>Service_Line_Item__c</referenceTo>
    <relationshipLabel>GL Code Line Items</relationshipLabel>
    <relationshipName>GL_Code_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Current_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Current_Reporting_Period__c</fullName>
    <description>Displays true if current reporting period.</description>
    <formula>IF( TODAY( ) &gt;= Start_Date__c &amp;&amp; TODAY( ) &lt;= End_Date__c, True, False )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Line_Item__c/Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI-{00000}</displayFormat>
        <label>Service Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Line_Item__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField> 

force-app/main/default/objects/Service_Line_Item__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Line_Item__c/fields/Service_Category__c.field-meta.xml
<CustomField>
    <fullName>Service_Category__c</fullName>
    <description>A service category can be specified in place of a service.
This allows information to be collected from the QFR/ACFR reports in a broken down manner, but not necessarily by service.</description>
    <label>Service Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Total</fullName>
            </value>
            <value>
                <fullName>Centrally Held</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AcfrCreateQuaterlyGLCLineItemScheduler.cls
/**
 * @description       : This class will be the Batch class and Scheduler class for bulk case and form creation functionality.
 * @author            : Pinali Patel
 * @group             :
 * @last modified on  : 11-17-2022
 * @last modified by  : Ethan Sargent
 * @TestClass AcfrCreateQuaterlyCasesAndFormsTest
 **/

public with sharing class AcfrCreateQuaterlyGLCLineItemScheduler implements Schedulable, Database.Batchable<sObject> {
	public static final Integer DEFAULT_BATCH_SIZE = 110;
	public AcfrCreateQuaterlyGLCLineItemScheduler() {
	}

	public void execute(SchedulableContext context) {
	}
	public Database.QueryLocator start(Database.BatchableContext bc) {
		List<Reporting_Period__c> reportingPeriods = [
			SELECT Id
			FROM Reporting_Period__c
			WHERE Current_Reporting_Period__c = TRUE
		];
		return Database.getQueryLocator(
			[
				SELECT
					Id,
					Service__c,
					Service_Category__c,
					Form__c,
					Form__r.Type__c,
					Form__r.case__r.Reporting_Period__r.Current_Reporting_Period__c
				FROM Service_Line_Item__c
				WHERE
					Id NOT IN (
						SELECT Service_Line_Item__c
						FROM GL_Code_Line_Item__c
					)
			]
		);
	}

	public void execute(
		Database.BatchableContext bc,
		List<Service_Line_Item__c> serviceLineItems
	) {
		System.debug('serviceLineItem size in GLC:' + serviceLineItems.Size());
		AcfrCreateQuaterlyCasesAndFormsService createCasesAndForms = new AcfrCreateQuaterlyCasesAndFormsService(
			serviceLineItems
		);
		createCasesAndForms.performActionForGLCodeLineItems();
	}

	public void finish(Database.BatchableContext bc) {
	}
}