force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <formula>TEXT(Form__r.QA_Outcome__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QA Outcome</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Request_for_Information.recordType-meta.xml
<RecordType>
    <fullName>Request_for_Information</fullName>
    <active>true</active>
    <businessProcess>Request for Information Support Process</businessProcess>
    <label>Request_for_Information</label>
</RecordType>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <label>QA Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Re-Issue</fullName>
                <label>Reissue</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>More information required</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>ReIssued</fullName>
                <isActive>false</isActive>
                <label>ReIssued</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/classes/CaseTriggerService.cls
/****************************************************************************************************
 * @Description : New Service class for CaseTriggerHandler
 *****************************************************************************************************/
public with sharing class CaseTriggerService {
	public static void validateCaseStatusChanges(
		Map<Id, Sobject> newCaseMap,
		Map<Id, Sobject> oldCaseMap
	) {
		Map<Id, String> formQAOutcomeMap = new Map<Id, String>();
		Set<Id> reissuedCaseIds = new Set<Id>();

		Id qfrRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
			.get('QFR')
			.getRecordTypeId();
		for (Case c : (List<Case>) newCaseMap.values()) {
			Case oldcase = (Case) oldCaseMap.get(c.id);
			Case newCase = (Case) newCaseMap.get(c.id);

			if (
				(oldcase.status != newCase.status) &&
				(c.status == 'Reissued') &&
				c.RecordTypeId == qfrRecordTypeId
			) {
				reissuedCaseIds.add(c.id);
			}
		}

		for (Form__c form : [
			SELECT id, QA_Outcome__c, case__c
			FROM form__c
			WHERE case__c IN :reissuedCaseIds
		]) {
			if (form.QA_Outcome__c == 'Re-Issue') {
				formQAOutcomeMap.put(form.case__c, 'Reissued');
			} else if (!formQAOutcomeMap.containsKey(form.case__c)) {
				formQAOutcomeMap.put(form.case__c, 'Not Reissued');
			}
		}

		for (Case c : (List<Case>) newCaseMap.values()) {
			if (
				formQAOutcomeMap.size() > 0 &&
				formQAOutcomeMap.containsKey(c.Id) &&
				formQAOutcomeMap.get(c.id) == 'Not Reissued' &&
				c.RecordTypeId == qfrRecordTypeId
			) {
				c.addError(System.Label.QFR_Reissued_Case);
			}
		}
	}

	public static void invokeCaseAssignmentRule(
		Map<Id, Sobject> newCaseMap,
		Map<Id, Sobject> oldCaseMap
	) {
		if (!(Schema.sObjectType.AssignmentRule.isAccessible())) {
			return;
		} else {
			Id devRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
				.get('Request_for_Information')
				.getRecordTypeId();

			AssignmentRule AR = new AssignmentRule();
			AR = [
				SELECT id
				FROM AssignmentRule
				WHERE SobjectType = 'Case' AND Active = TRUE
				LIMIT 1
			];
			Database.DMLOptions dmlOpts = new Database.DMLOptions();
			dmlOpts.assignmentRuleHeader.assignmentRuleId = AR.id;

			Map<Id, String> ARnewCaseMap = new Map<Id, String>();
			List<Id> caseIdList = new List<Id>();
			List<Case> caseList = new List<Case>();

			for (Case c : (List<Case>) newCaseMap.values()) {
				Case oldcase = (Case) oldCaseMap.get(c.id);
				Case newCase = (Case) newCaseMap.get(c.id);

				if (
					(oldcase.status != newCase.status) &&
					((newCase.status == 'Send to Assessor') ||
					(newCase.status == 'Send to Reviewer') ||
					(newCase.status == 'Send to Delegate')) &&
					(devRecordTypeId == oldcase.RecordTypeId)
				) {
					caseIdList.add(c.id);
				}
			}

			for (Case c : [
				SELECT id, ownerid
				FROM Case
				WHERE Id IN :caseIdList
			]) {
				c.setOptions(dmlOpts);
				caseList.add(c);
			}
			update caseList;
		}
	}
}