force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <formula>TEXT(Form__r.QA_Outcome__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QA Outcome</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/QA_Comments__c.field-meta.xml
<CustomField>
    <fullName>QA_Comments__c</fullName>
    <inlineHelpText>Please note the provider will see your comment if the QFR is reissued.</inlineHelpText>
    <label>External QA Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <label>QA Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Re-Issue</fullName>
                <label>Reissue</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>More information required</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>ReIssued</fullName>
                <isActive>false</isActive>
                <label>ReIssued</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OmniFileUploadHelperTest.cls
//********************************************
//Apex Class		:OmniFileUploadHelper
//Test Classname	:OmniFileUploadHelperTest
//Author			:N Parsons
//Date Created		:
//
//Revision History 	:
//	20012023		:CJJOYA - Modify line 6 to include RecordTypeId for creating QFR case
//  20012024        :NPPARSONS - Changed input parameter from recordId to caseId
@isTest
public class OmniFileUploadHelperTest {
    @isTest static void OmniFileUploadHelperTest() {
        // Setup
        
        //Get QFR Case Record Type
        String strRecordTypeId = [Select Id from RecordType where SobjectType='Case' and Name ='QFR'].Id; //Added by CJ 20012023
        Case c = new Case();
        c.RecordTypeId = strRecordTypeId; //Added by CJ 20012023
        insert c;
        
        Form__c f = new Form__c();
        f.CreatedDate = Datetime.newInstance(2022, 9, 14);
        f.QA_Outcome__c = 'Re-Issue';
        f.QA_Comments__c = 'Re-Issue Form'; //Added by CJ 20012023 QA Comments Mandatory field
        f.Type__c = 'Declaration and Submission';
        f.Case__c = c.Id;
        insert f;

        ContentVersion cd = new ContentVersion();
        cd.title = 'PDFforQFR';
        cd.PathOnClient = 'test.pdf';
        cd.ContentLocation = 'S';
        cd.VersionData = Blob.valueOf('test file content');
        cd.FirstPublishLocationId = c.Id;
        insert cd;

        TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
        User healthUser = healthUserBuilder.createUser();

        // Given
        String titleTestValue = cd.title;
        String uploadClass = 'OmniFileUploadHelper';
        Boolean result;
        Map<String, Map<String, Object>> args = new Map<String, Map<String, Object>> {
                'output' => new Map<String, Object>(),
                'input' => new Map<String, Object> {
                    'caseId' => c.Id
                }  
        };

        // When
        Test.startTest();
            System.runAs(healthUser) {
                Callable extension = (Callable) 
                        Type.forName(uploadClass).newInstance();
                result = (Boolean)
                        extension.call('getRelatedFiles', args);
            }
        Test.stopTest();
                
        // Then
        system.assertEquals(true, result);
        String resultFilesJSON = (String) args.get('output').get('relatedFile');
        List<OmniFileUploadHelper.File> resultFiles = (List<OmniFileUploadHelper.File>) JSON.deserialize(resultFilesJSON, List<OmniFileUploadHelper.File>.class);
		system.assertEquals(1, resultFiles.size());
        system.assertEquals(titleTestValue, resultFiles.get(0).Title);
    }
}