force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <formula>TEXT(Form__r.QA_Outcome__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QA Outcome</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <label>QA Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Re-Issue</fullName>
                <label>Reissue</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>More information required</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>ReIssued</fullName>
                <isActive>false</isActive>
                <label>ReIssued</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OmniFileUploadHelper.cls
/* Author: Nick Parsons
   Date Created: 15/8/22
   User Story: 233634
   Revision History: 
   15/9/22 - Added field history query and cutoff date to limit results to after re-issue */

global with sharing class OmniFileUploadHelper implements Callable {
  public static List<file> getRelatedFiles(Id caseId) {
    // Set the Form record ID
    Form__c declarationForm;
    Id formId;
    try {
      declarationForm = [
        SELECT Id, CreatedDate
        FROM Form__c
        WHERE Case__c = :caseId AND Type__c = 'Declaration and Submission'
        LIMIT 1
      ];
    } catch (QueryException e) {
      System.debug('Error querying Form: ' + e.getMessage());
      /* return new List<File>(); */
    }
    formId = declarationForm?.Id;

    // Query the field history for QA_Outcome__c
    List<CaseHistory> fieldHistory = [
      SELECT Case.CreatedDate, Field, NewValue, OldValue, CreatedDate
      FROM CaseHistory
      WHERE CaseId = :caseId AND Field = 'Status'
      ORDER BY CreatedDate DESC
    ];

    // Filter the list for only results for Re-Issue instances
    List<CaseHistory> reIssuedHistory = new List<CaseHistory>();
    for (CaseHistory fh : fieldHistory) {
      if (fh.NewValue == 'Reissued') {
        reIssuedHistory.add(fh);
      }
    }

    // Create the cut off date variable
    DateTime CutOffDate = DateTime.now();

    // Check if there has been any Re-Issue
    if (reIssuedHistory.isEmpty()) {
      CutOffDate = declarationForm?.createdDate;
    } else {
      CutOffDate = reIssuedHistory[0].CreatedDate;
    }

    //Query the ContentDocument for the related files
    List<File> files = new List<File>();

    for (ContentDocumentLink conLink : [
      SELECT
        ContentDocument.Id,
        ContentDocument.Title,
        ContentDocument.CreatedDate,
        ContentDocument.FileType
      FROM ContentDocumentLink
      WHERE
        LinkedEntityId = :caseId
        AND ContentDocument.FileType IN ('pdf', 'png', 'jpg', 'jpeg')
        AND ContentDocument.CreatedDate >= :CutOffDate
    ]) {
      File file = new File();
      file.Title = conLink.ContentDocument.Title;
      file.Id = conLink.ContentDocument.Id;
      file.CreatedDate = conLink.ContentDocument.CreatedDate;
      file.Type = conLink.ContentDocument.FileType;
      files.add(file);
    }
    return files;
  }

  global class File {
    global String Title;
    global String Type;
    global Id Id;
    global Datetime CreatedDate;
  }

  global Object call(string action, Map<String, Object> args) {
    Map<String, Object> input = (Map<String, Object>) args.get('input');
    Map<String, Object> output = (Map<String, Object>) args.get('output');
    Map<String, Object> options = (Map<String, Object>) args.get('options');
    switch on action {
      when 'getRelatedFiles' {
        List<File> relatedFiles = getRelatedFiles((String) input.get('caseId'));
        output.put('relatedFile', JSON.serialize(relatedFiles));
        return true;
      }
      when 'isReadOnlyForms' {
        Boolean isReadOnly = isReadOnlyForms((String) input.get('caseId'));
        output.put('isReadOnly', JSON.serialize(isReadOnly));
        return true;
      }
      when 'checkHasPermission' {
        Boolean canSubmit = checkUserCanSubmit();
        output.put('hasPermission', canSubmit);
        return true;
      }
      when else {
        throw new ExtensionMalformedException('Method not implemented');
      }
    }
  }
  public class ExtensionMalformedException extends Exception {
  }

  public static Boolean isReadOnlyForms(Id caseId) {
    List<File> files = OmniFileUploadHelper.getRelatedFiles(caseId);
    return files.size() > 0 ? true : false;
  }

  public static Boolean checkUserCanSubmit() {
    Boolean hasPerm = FeatureManagement.checkPermission(
      'QFR_Finance_Data_Submission'
    );
    return hasPerm;
  }
}