force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/NAPSID__c.field-meta.xml
<CustomField>
    <fullName>NAPSID__c</fullName>
    <description>Use to pull in NAPS ID for QA View</description>
    <formula>Account.Integration_ID__c</formula>
    <label>NAPS ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull from Reporting Perion Object.</description>
    <label>Reporting Period ID</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Submission_Count__c.field-meta.xml
<CustomField>
    <fullName>Submission_Count__c</fullName>
    <description>Field to capture the number of submission count on a QFR case</description>
    <label>Submission Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Category__c/Question_Category__c.object-meta.xml
<CustomObject>
    <description>Parent object - Master object</description>
    <label>Question Category</label>
    <nameField>
        <label>Question Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quality Indicator</fullName>
            </value>
            <value>
                <fullName>Consumer Experience Interview</fullName>
            </value>
            <value>
                <fullName>Quality Standard</fullName>
            </value>
            <value>
                <fullName>Care Minutes</fullName>
            </value>
            <value>
                <fullName>Residential Viability and Prudential Reporting</fullName>
            </value>
            <value>
                <fullName>Home Care Viability and Prudential Reporting</fullName>
            </value>
            <value>
                <fullName>Quality Indicator Targets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Library__c/Question_Library__c.object-meta.xml
<CustomObject>
    <label>Question Library</label>
    <nameField>
        <displayFormat>QL-{000}</displayFormat>
        <label>Question Library</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions Library</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Library__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Library__c/fields/Question_Category__c.field-meta.xml
<CustomField>
    <fullName>Question_Category__c</fullName>
    <label>Question Category</label>
    <referenceTo>Question_Category__c</referenceTo>
    <relationshipLabel>Questions Library</relationshipLabel>
    <relationshipName>Questions_Library</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/RP_Quarter__c.field-meta.xml
<CustomField>
    <fullName>RP_Quarter__c</fullName>
    <formula>&apos;Q&apos; &amp; IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3 ,&apos;2&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6 ,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9 ,&apos;4&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12 ,&apos;1&apos;,null) ) ) )
+&quot; &quot;+&apos;FY&apos;&amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1), 2),RIGHT( TEXT(YEAR(End_Date__c)), 2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RP Quarter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <description>QFR Viability Responses</description>
    <label>Response</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <label>Additional Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Care_or_Services__c.field-meta.xml
<CustomField>
    <fullName>Care_or_Services__c</fullName>
    <description>What kind of care or service/s are contracted to the organisation under the business structure.</description>
    <label>Care or Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clinical Care</fullName>
            </value>
            <value>
                <fullName>Personal Care</fullName>
            </value>
            <value>
                <fullName>Allied Health</fullName>
            </value>
            <value>
                <fullName>Diversional Therapy</fullName>
            </value>
            <value>
                <fullName>Lifestyle/Recreation/Activities Officer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to be deprecated</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <description>The Form that the response was given in. </description>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Other_Business_Structure__c.field-meta.xml
<CustomField>
    <fullName>Other_Business_Structure__c</fullName>
    <description>Text field for explanation of what &apos;other business structure&apos; the organisation uses.</description>
    <label>Other Business Structure</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Other_Care_Services__c.field-meta.xml
<CustomField>
    <fullName>Other_Care_Services__c</fullName>
    <description>Text box for explanation of what other types of care/services the organisation provides when selecting the Other checkbox in the services section.</description>
    <label>Other Care Services</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Question_Category__c.field-meta.xml
<CustomField>
    <fullName>Question_Category__c</fullName>
    <formula>Question_Library__r.Question_Category__r.Name</formula>
    <label>Question Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Question_Library__c.field-meta.xml
<CustomField>
    <fullName>Question_Library__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Library</label>
    <referenceTo>Question_Library__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Response_Options__c.field-meta.xml
<CustomField>
    <fullName>Response_Options__c</fullName>
    <label>Response Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>x</fullName>
                <isActive>false</isActive>
                <label>x</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QFRLWCDownloadController.cls
public with sharing class QFRLWCDownloadController {
  @AuraEnabled(cacheable=true)
  public static List<FormDownloadDetail> getFormIdsForCase(Id caseId) {
    List<Form__c> forms = [
      SELECT
        Id,
        Type__c,
        Name,
        Case__r.RecordType.name,
        Case__r.NAPSID__c,
        Reporting_period__r.RP_Quarter__c,
        Case__r.Status,
        Case__r.Submission_count__c
      FROM Form__c
      WHERE Case__c = :caseId AND Type__c != 'Declaration and Submission'
      ORDER BY Type__c ASC
    ];
    List<FormDownloadDetail> results = new List<FormDownloadDetail>();
    for (Form__c form : forms) {
      FormDownloadDetail detail = new FormDownloadDetail();
      detail.formId = form.Id;
      detail.formName = form.Name;
      detail.recordTypeName = form.Case__r.RecordType.name;
      detail.providerID = form.Case__r.NAPSID__c;
      detail.currentQuarter = form.Reporting_period__r.RP_Quarter__c;
      detail.caseStatus = form.Case__r.Status;
      detail.submissionCount = form.Case__r.Submission_count__c;
      if (
        form.Type__c == 'Residential Viability and Prudential Reporting' ||
        form.Type__c == 'Home Care Viability and Prudential Reporting'
      ) {
        detail.downloaderType = FormVariation.VIABILITY;
      } else {
        detail.downloaderType = FormVariation.DATATABLE;
      }
      detail.formType = form.Type__c;
      results.add(detail);
    }
    system.debug(results);
    return results;
  }

  @AuraEnabled(cacheable=true)
  public static List<ViabilityResponse> getViabilityResponses(
    Id viabilityFormId
  ) {
    List<Response__c> responses = [
      SELECT
        Id,
        Response_Options__c,
        Question_Category__c,
        Additional_Information__c,
        Other_Business_Structure__c,
        Care_or_Services__c,
        Other_Care_Services__c,
        Question_Library__r.Question__c, //Modified this line of code to get the question from Question_Library__c
        Question_Library__r.Name
      FROM Response__c
      WHERE Form__c = :viabilityFormId
    ];
    List<ViabilityResponse> results = new List<ViabilityResponse>();
    for (Response__c response : responses) {
      ViabilityResponse viabilityResponse = new ViabilityResponse();
      viabilityResponse.question = response.Question_Library__r.Question__c;
      viabilityResponse.response = response.Response_Options__c;
      viabilityResponse.additionalInformation = response.Additional_Information__c;
      viabilityResponse.careServices = response.Care_or_Services__c;
      viabilityResponse.additionalCareServices = response.Other_Care_Services__c;
      viabilityResponse.additionalBusinessStructure = response.Other_Business_Structure__c;
      results.add(viabilityResponse);
    }
    return results;
  }

  @AuraEnabled
  public static void saveExcelFile(
    Id recordId,
    String b64FileContent,
    String fileName
  ) {
    Blob contentBody = EncodingUtil.base64Decode(b64FileContent);
    ContentVersion cv = new ContentVersion(
      ContentLocation = 'S',
      FirstPublishLocationId = recordId,
      PathOnClient = fileName,
      VersionData = contentBody
    );

    DMLImpl dmlinsert = new DMLImpl();
    dmlinsert.InsertRecord(cv);

    Id contentDocId = [
      SELECT ContentDocumentId
      FROM ContentVersion
      WHERE id = :cv.id
    ]
    .ContentDocumentId;

    List<Id> fileList = new List<Id>();
    fileList.add(contentDocId);

    calloutTRIMs(recordId, contentDocId);
  }

  @future(callout=true)
  public static void calloutTRIMs(Id parentId, Id contentDocId) {
    List<Id> contentDocList = new List<Id>();
    contentDocList.add(contentDocId);

    dohagedcare.FileStorageListController.uploadFilesToTRIMExt(
      parentId,
      contentDocList
    );
  }

  @AuraEnabled
  public static dohagedcare.FilePreviewUtility.PreviewResponseWrapper loadExcelFile(
    Id recordId
  ) {
    Id contentDocId = [
      SELECT ContentDocumentId
      FROM ContentDocumentLink
      WHERE
        LinkedEntityId = :recordId
        AND ContentDocument.FileExtension = 'xlsx'
      ORDER BY ContentDocument.LastModifiedDate DESC
      LIMIT 1
    ]
    .ContentDocumentId;

    dohagedcare.FilePreviewUtility.PreviewResponseWrapper result = dohagedcare.FilePreviewUtility.getFilePreviewDetailsExt(
      recordId,
      contentDocId
    );

    return result;
  }

  @JsonAccess(serializable='always')
  public class FormDownloadDetail {
    @AuraEnabled
    public String formId { get; set; }
    @AuraEnabled
    public String formName { get; set; }
    @AuraEnabled
    public String formType { get; set; }
    @AuraEnabled
    public String recordTypeName { get; set; }
    @AuraEnabled
    public String providerID { get; set; }
    @AuraEnabled
    public String currentQuarter { get; set; }
    @AuraEnabled
    public String caseStatus { get; set; }
    @AuraEnabled
    public Decimal submissionCount { get; set; }
    @AuraEnabled
    public transient FormVariation downloaderType { get; set; }

    @AuraEnabled
    public String downloader {
      get {
        return downloaderType.name().toLowerCase();
      }
      private set;
    }
  }

  public enum FormVariation {
    VIABILITY,
    DATATABLE
  }

  @JsonAccess(serializable='always')
  public class ViabilityResponse {
    @AuraEnabled
    public String question { get; set; }
    @AuraEnabled
    public String response { get; set; }
    @AuraEnabled
    public String additionalInformation { get; set; }
    @AuraEnabled
    public String careServices { get; set; }
    @AuraEnabled
    public String additionalCareServices { get; set; }
    @AuraEnabled
    public String additionalBusinessStructure { get; set; }
  }
}