force-app/main/default/objects/Case/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull from Reporting Perion Object.</description>
    <label>Reporting Period ID</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SkipLateSubmissionEmail__c.field-meta.xml
<CustomField>
    <fullName>SkipLateSubmissionEmail__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Exclude From Overdue Notice Email</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact, Record Id of the related Contact record.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>(Generic NAPS Position Name) The role of this contact</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Assessment Service Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Assessor</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Financial Management</fullName>
            </value>
            <value>
                <fullName>Funding Agreement Variations</fullName>
            </value>
            <value>
                <fullName>Funding Submissions</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Aged Care Program Contact</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Key Personnel</fullName>
            </value>
            <value>
                <fullName>General Staff</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>Applicant Representative</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Leader</fullName>
            </value>
            <value>
                <fullName>Activity Contact</fullName>
            </value>
            <value>
                <fullName>Acquittal/Financial Reporting</fullName>
            </value>
            <value>
                <fullName>Assessment Service Administrator</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate Support</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate</fullName>
            </value>
            <value>
                <fullName>Choice Attributes</fullName>
            </value>
            <value>
                <fullName>Care Services Management</fullName>
            </value>
            <value>
                <fullName>Remittance/RCTI</fullName>
            </value>
            <value>
                <fullName>High level contact</fullName>
                <label>High Level Contact</label>
            </value>
            <value>
                <fullName>Service Monitoring &amp; Reports</fullName>
            </value>
            <value>
                <fullName>Centre Management</fullName>
            </value>
            <value>
                <fullName>Aged Care Service Manager</fullName>
            </value>
            <value>
                <fullName>QFR Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reporting Period</relationshipLabel>
    <relationshipName>Reporting_Period</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AcfrEmailServiceTest.cls
@isTest
private class AcfrEmailServiceTest {
	private static final String TEST_EMAIL_DOT_COM = 'test@test.com;';

	@testSetup
	static void setup() {
		User adminUser = TestDataFactory.createSystemAdminUser();
		UserRole userRole = [
			SELECT Id, Name
			FROM UserRole
			WHERE Name = 'Health Staff'
			LIMIT 1
		];
		adminUser.isActive = true;
		adminUser.UserRoleId = userRole.Id;

		update adminUser;

		System.runAs(adminUser) {
			String accountStr = TestDataFactory.createACO();

			List<Account> acc = [
				SELECT id, name
				FROM Account
				WHERE id = :accountStr
			];
			Contact con1 = new Contact(
				FirstName = '1',
				LastName = 'Test',
				Salutation = 'Ms',
				Email = 'test@gmail.com'
			);
			insert con1;

			Contact con2 = new Contact(
				FirstName = '2',
				LastName = 'Test',
				Salutation = 'Ms',
				Email = 'test@gmail.com'
			);
			insert con2;

			Contact_Relationship__c cr1 = new Contact_Relationship__c(
				Account__c = acc[0].Id,
				Contact__c = con1.Id,
				Role__c = 'QFR Primary Contact'
			);
			insert cr1;

			Contact_Relationship__c cr2 = new Contact_Relationship__c(
				Account__c = acc[0].Id,
				Contact__c = con2.Id
			);
			insert cr2;

			Reporting_Period__c rp1 = new Reporting_Period__c();
			rp1.Reporting_Period_Type__c = 'Quarter';
			rp1.Start_Date__c = Date.Today().addDays(-12).addMonths(-3);
			rp1.End_Date__c = Date.Today().addDays(-12);
			insert rp1;

			Case cs = new Case(
				Status = 'New',
				AccountId = acc[0].Id,
				SkipLateSubmissionEmail__c = 'No',
				Reporting_Period__c = rp1.Id
			);
			insert cs;
		}
	}

	@isTest
	static void testGenerateReissueEmailTemplate() {
		user finQAAssessor = [
			SELECT id
			FROM user
			WHERE isActive = TRUE
			LIMIT 1
		];
		System.runAs(finQAAssessor) {
			List<Case> rec = [
				SELECT Id, AccountId
				FROM Case
				ORDER BY createddate ASC
				LIMIT 1
			];
			List<Account> acc = [
				SELECT Id
				FROM Account
				WHERE Id = :rec[0].AccountId
			];
			String emailSubject = AcfrEmailService.getEmailSubject(
				rec[0].Id,
				'Case',
				'QFR_Reissue_Email'
			);
			String emailContent = AcfrEmailService.getEmailContent(
				rec[0].Id,
				'Case',
				'QFR_Reissue_Email'
			);
			String primaryEmailAddress = AcfrEmailService.getPrimaryEmailAddress(
				rec[0].Id
			);
			String primaryandNonPrimaryEmailAddress = AcfrEmailService.getPrimaryandNonPrimaryEmailAddress(
				rec[0].Id,
				'test1@gmail.com'
			);
			emailContent = AcfrEmailService.hideConditions(
				emailContent,
				'TEST',
				true
			);
			emailContent = AcfrEmailService.hideConditions(
				emailContent,
				'TEST',
				false
			);

			List<String> invocableVariables = new List<String>();
			String var = 'recordId=' + rec[0].Id + ';';
			var = var + 'isStandard=true;';
			var = var + 'templateName=QFR_Reissue_Email;';
			var = var + 'toAddress=' + primaryEmailAddress + ';';
			var = var + 'ccAddress=' + primaryEmailAddress + ';';
			var = var + 'hasPrimaryMergeField=false;';
			var = var + 'toAddress1PrimaryOnly=false;';
			var = var + 'toAddressPrimaryAll=false;';
			var = var + 'toAddressAllContactRel=false;';
			var = var + 'toAddressVariable=false;';
			invocableVariables.add(var);
			AcfrEmailService.sendEmailMainInvocable(invocableVariables);

			Test.startTest();
			AcfrEmailService.sendEmailMain(
				true,
				'QFR_Reissue_Email',
				acc,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				true,
				false,
				false,
				false
			);
			AcfrEmailService.sendEmailMain(
				true,
				'QFR_Reissue_Email',
				acc,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				true,
				false,
				false
			);
			AcfrEmailService.sendEmailMain(
				true,
				'QFR_Reissue_Email',
				acc,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				false,
				true,
				false
			);
			AcfrEmailService.sendEmailMain(
				true,
				'QFR_Reissue_Email',
				acc,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				false,
				false,
				true
			);

			AcfrEmailService.sendEmailMain(
				false,
				'QFR_Reissue_Email',
				acc,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				true,
				false,
				false,
				false
			);
			AcfrEmailService.sendEmailMain(
				false,
				'QFR_Reissue_Email',
				acc,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				true,
				false,
				false
			);
			AcfrEmailService.sendEmailMain(
				false,
				'QFR_Reissue_Email',
				acc,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				false,
				true,
				false
			);
			AcfrEmailService.sendEmailMain(
				false,
				'QFR_Reissue_Email',
				acc,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				false,
				false,
				true
			);
			Test.stopTest();
			System.assert(emailSubject != '');
		}
	}

	@isTest
	static void testReissueTemplateConditions() {
		user finQAAssessor = [
			SELECT id
			FROM user
			WHERE isActive = TRUE
			LIMIT 1
		];
		System.runAs(finQAAssessor) {
			List<Case> rec = [
				SELECT Id, AccountId
				FROM Case
				ORDER BY createddate ASC
				LIMIT 1
			];
			List<Account> acc = [
				SELECT Id
				FROM Account
				WHERE Id = :rec[0].AccountId
			];
			String emailSubject = AcfrEmailService.getEmailSubject(
				rec[0].Id,
				'Case',
				'QFR_Reissue_Email'
			);
			String emailContent = AcfrEmailService.getEmailContent(
				rec[0].Id,
				'Case',
				'QFR_Reissue_Email'
			);
			String primaryEmailAddress = AcfrEmailService.getPrimaryEmailAddress(
				rec[0].Id
			);
			String nonPrimaryEmailAddress = AcfrEmailService.getNonPrimaryEmailAddress(
				rec[0].Id
			);
			String primaryandNonPrimaryEmailAddress = AcfrEmailService.getPrimaryandNonPrimaryEmailAddress(
				rec[0].Id,
				'test1@gmail.com'
			);
			emailContent = AcfrEmailService.hideConditions(
				emailContent,
				'TEST',
				true
			);
			emailContent = AcfrEmailService.hideConditions(
				emailContent,
				'TEST',
				false
			);
			List<String> invocableVariables = new List<String>();
			String var = 'recordId=' + acc[0].Id + ';';
			var = var + 'isStandard=true;';
			var = var + 'templateName=QFR_Reissue_Email;';
			var = var + 'toAddress=' + primaryEmailAddress + ';';
			var = var + 'ccAddress=' + primaryEmailAddress + ';';
			var = var + 'hasPrimaryMergeField=false;';
			var = var + 'toAddress1PrimaryOnly=false;';
			var = var + 'toAddressPrimaryAll=false;';
			var = var + 'toAddressAllContactRel=false;';
			var = var + 'toAddressVariable=false;';
			invocableVariables.add(var);
			AcfrEmailService.sendEmailMainInvocable(invocableVariables);
			Test.startTest();
			System.AssertEquals(primaryEmailAddress != null, true);
			AcfrEmailService.sendEmailMain(
				true,
				'QFR_Reissue_Email',
				rec,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				true,
				false,
				false,
				false
			);
			AcfrEmailService.sendEmailMain(
				true,
				'QFR_Reissue_Email',
				rec,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				true,
				false,
				false
			);
			AcfrEmailService.sendEmailMain(
				true,
				'QFR_Reissue_Email',
				rec,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				false,
				true,
				false
			);
			AcfrEmailService.sendEmailMain(
				true,
				'QFR_Reissue_Email',
				rec,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				false,
				false,
				true
			);

			AcfrEmailService.sendEmailMain(
				false,
				'QFR_Reissue_Email',
				rec,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				true,
				false,
				false,
				false
			);
			AcfrEmailService.sendEmailMain(
				false,
				'QFR_Reissue_Email',
				rec,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				true,
				false,
				false
			);
			AcfrEmailService.sendEmailMain(
				false,
				'QFR_Reissue_Email',
				rec,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				false,
				true,
				false
			);
			AcfrEmailService.sendEmailMain(
				false,
				'QFR_Reissue_Email',
				rec,
				primaryEmailAddress,
				primaryandNonPrimaryEmailAddress,
				true,
				false,
				false,
				false,
				true
			);

			Contact con = [SELECT Id FROM Contact LIMIT 1];
			AcfrEmailService.sendStandardSingleEmailMethod(
				rec[0].Id,
				con.Id,
				'QFR_Reissue_Email',
				TEST_EMAIL_DOT_COM,
				TEST_EMAIL_DOT_COM
			);

			AcfrEmailService.sendCustomSingleEmailMethod(
				rec[0].Id,
				'email body',
				TEST_EMAIL_DOT_COM,
				TEST_EMAIL_DOT_COM,
				'email subject'
			);

			Test.stopTest();
			System.assert(emailSubject != '');
			System.assert(nonPrimaryEmailAddress != '');
		}
	}
}