force-app/main/default/objects/Case/fields/Reporting_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Due_Date__c</fullName>
    <formula>Reporting_Period__r.QFR_Reporting_Due_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QFR Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/SkipLateSubmissionEmail__c.field-meta.xml
<CustomField>
    <fullName>SkipLateSubmissionEmail__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Exclude From Overdue Notice Email</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AcfrSendOverDueEmailController.cls
public with sharing class AcfrSendOverDueEmailController {
  @AuraEnabled
  public static List<String> getRecordCount() {
    List<String> recordCount = new List<String>();
    Date dueDateFirst = date.today().addDays(-13);
    String recordFirstCount = String.valueOf(
      [
          SELECT Id, Status, Reporting_Due_Date__c
          FROM Case
          WHERE
            SkipLateSubmissionEmail__c != 'Yes'
            AND Status != 'Submitted'
            AND Status != 'Re-Submitted'
            AND Reporting_Due_Date__c >= :dueDateFirst
            AND Reporting_Due_Date__c < today
            AND AccountId != NULL
        ]
        .size()
    );
    recordCount.add(recordFirstCount);

    Date dueDateFinal = date.today().addDays(-21);
    String recordFinalCount = String.valueOf(
      [
          SELECT Id, Status, Reporting_Due_Date__c
          FROM Case
          WHERE
            SkipLateSubmissionEmail__c != 'Yes'
            AND Status != 'Submitted'
            AND Status != 'Re-Submitted'
            AND Reporting_Due_Date__c >= :dueDateFinal
            AND Reporting_Due_Date__c < :dueDateFirst
            AND AccountId != NULL
        ]
        .size()
    );
    recordCount.add(recordFinalCount);
    return recordCount;
  }

  @AuraEnabled
  public static void sendOverDueEmail() {
    Database.executeBatch(
      new AcfrSendFirstOverdueEmailBatch(),
      10
    );
    Database.executeBatch(
      new AcfrSendFinalOverdueEmailBatch(),
      10
    );
  }
}