force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Code</description>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/Business_ID__c.field-meta.xml
<CustomField>
    <fullName>Business_ID__c</fullName>
    <description>Business ID</description>
    <externalId>true</externalId>
    <label>Business ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/fields/Line_Item_Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Value_Type__c</fullName>
    <inlineHelpText>Determines how line items under this GL code will be presented in the form front-end</inlineHelpText>
    <label>Line Item Value Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Numeric</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Minutes</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Hrs</fullName>
            </value>
            <value>
                <fullName>TestInactiveValue</fullName>
                <isActive>false</isActive>
                <label>TestInactiveValue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GL_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/GL_Code_Line_Item__c.object-meta.xml
<CustomObject>
    <description>GL Code Line Item</description>
    <label>GL Code Line Item</label>
    <nameField>
        <displayFormat>GLI-{000000}</displayFormat>
        <label>GL Code Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Code Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GL Code</description>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>GL Code Line Items</relationshipLabel>
    <relationshipName>GL_Code_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/Service_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Line_Item__c</fullName>
    <label>Service Line Item</label>
    <referenceTo>Service_Line_Item__c</referenceTo>
    <relationshipLabel>GL Code Line Items</relationshipLabel>
    <relationshipName>GL_Code_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/Service_GL_Code_Restriction__mdt.object-meta.xml
<CustomObject>
    <description>Indicates an allowlist/blocklist of Services for specified GL Codes

Specifying Excluded GL Codes will prevent that GL Code being generated for a Service Category, even if it is included.
Specifying Included GL Codes will ONLY create records for any included GL Codes for that Service Category.

Excluded = remove cell from service
Included = only show specified GL Codes for service (eg Centrally Held for QFR)</description>
    <label>Service GL Code Restriction</label>
    <pluralLabel>Service GL Code Restrictions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/fields/Restriction_Type__c.field-meta.xml
<CustomField>
    <fullName>Restriction_Type__c</fullName>
    <label>Restriction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclude</fullName>
                <default>true</default>
                <label>Exclude</label>
            </value>
            <value>
                <fullName>Include</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/fields/Service_Category__c.field-meta.xml
<CustomField>
    <fullName>Service_Category__c</fullName>
    <label>Service Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centrally Held</fullName>
                <default>true</default>
                <label>Centrally Held</label>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/fields/Summary_Only__c.field-meta.xml
<CustomField>
    <fullName>Summary_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies whether the GL Code specified should be created in the row-level total column only.</description>
    <label>Summary Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Line_Item__c/Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI-{00000}</displayFormat>
        <label>Service Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Line_Item__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField> 

force-app/main/default/objects/Service_Line_Item__c/fields/Service_Category__c.field-meta.xml
<CustomField>
    <fullName>Service_Category__c</fullName>
    <description>A service category can be specified in place of a service.
This allows information to be collected from the QFR/ACFR reports in a broken down manner, but not necessarily by service.</description>
    <label>Service Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Total</fullName>
            </value>
            <value>
                <fullName>Centrally Held</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GLCodeLineItemHelper.cls
/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 11-28-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public with sharing class GLCodeLineItemHelper {
	Set<String> serviceCategories = new Set<String>();
	Set<String> formTypes = new Set<String>();
	List<Service_line_item__c> serviceLineItems = new List<Service_line_item__c>();
	Map<Database.SaveResult, Id> allFailedResultsGLC = new Map<Database.SaveResult, Id>();
	List<Database.SaveResult> allSuccessResultsGLC = new List<Database.SaveResult>();
    private QueryService queryService = new QueryService();
	WithoutSharingDML withoutSharingDML = new WithoutSharingDML();

	public GLCodeLineItemHelper(
		List<Service_line_item__c> serviceLineItems,
		Set<String> formTypes
	) {
		this.formTypes = formTypes;
		this.serviceLineItems = serviceLineItems;
		System.debug('this.formTypes = formTypes;====' + formTypes);
		for (Service_Line_Item__c sli : this.serviceLineItems) {
			serviceCategories.add(sli.Service_Category__c);
			System.debug(
				'serviceCategories.add(sli.Service_Category__c);====' +
				sli.Service_Category__c
			);
		}
	}

	public void generateGLCodeLineItems() {
		List<Service_GL_Code_Restriction__mdt> restrictions = ServiceGLCodeRestrictionFactory.getRestrictions(
			serviceCategories
		);
		Map<String, Set<String>> glCodesByServiceCategoryInclusions = new Map<String, Set<String>>();
		Map<String, Set<String>> glCodesByServiceCategoryInclusionsSummaryOnly = new Map<String, Set<String>>();
		Map<String, Set<String>> glCodesByServiceCategoryExclusions = new Map<String, Set<String>>();
		for (Service_GL_Code_Restriction__mdt restriction : restrictions) {
			// add to inclusion or exclusion map appropriately
			Set<String> glCodeIds;
			if (
				restriction.Restriction_Type__c == 'Include' &&
				!restriction.Summary_only__c
			) {
				glCodeIds = glCodesByServiceCategoryInclusions.get(
					restriction.Service_Category__c
				);

				if (glCodeIds == null) {
					glCodeIds = new Set<String>();
					glCodesByServiceCategoryInclusions.put(
						restriction.Service_Category__c,
						glCodeIds
					);
				}
			} else if (
				restriction.Restriction_Type__c == 'Include' &&
				restriction.Summary_only__c
			) {
				glCodeIds = glCodesByServiceCategoryInclusionsSummaryOnly.get(
					restriction.Service_Category__c
				);

				if (glCodeIds == null) {
					glCodeIds = new Set<String>();
					glCodesByServiceCategoryInclusionsSummaryOnly.put(
						restriction.Service_Category__c,
						glCodeIds
					);
				}
			} else if (restriction.Restriction_Type__c == 'Exclude') {
				glCodeIds = glCodesByServiceCategoryExclusions.get(
					restriction.Service_Category__c
				);

				if (glCodeIds == null) {
					glCodeIds = new Set<String>();
					glCodesByServiceCategoryExclusions.put(
						restriction.Service_Category__c,
						glCodeIds
					);
				}
			}else{
				//Do nothing
			}

			glCodeIds.add(restriction.GL_Code__c);
		}

		List<GL_Code__c> glCodes =  getGLcodeRecords(this.formTypes);
		List<GL_Code_Line_Item__c> lineitems = new List<GL_Code_Line_Item__c>();

		for (Service_Line_Item__c sli : serviceLineItems) {
			for (GL_Code__c glCode : glCodes) {
				if (sli.Form__r.Type__c != glCode.Type__c) {
					continue;
				}

				// if this sli has a service category, filter GL Codes accordingly
				if (
					sli.Service_Category__c != null &&
					(sli.Form__r.Type__c ==
					'Approved Provider Quarterly Financial Statements' ||
					sli.Form__r.Type__c == 'MPS Food and Nutrition Reporting' ||
					sli.Form__r.Type__c ==
					'Residential Food and Nutrition Reporting' ||
					sli.Form__r.Type__c ==
					'NATSIFACP Food and Nutrition Reporting')
				) {
					Set<String> inclusions = glCodesByServiceCategoryInclusions.get(
						sli.Service_Category__c
					);
					if (
						inclusions != null &&
						!inclusions.contains(glCode.Business_ID__c)
					) {
						continue;
					}

					Set<String> exclusions = glCodesByServiceCategoryExclusions.get(
						sli.Service_Category__c
					);
					if (
						exclusions != null &&
						exclusions.contains(glCode.Business_ID__c)
					) {
						continue;
					}
				}
				// include the GL codes to summary only

				else if (
					sli.Service_Category__c == null ||
					sli.Service_Category__c != 'Total'
				) {
					Set<String> inclusionsSummaryOnly = glCodesByServiceCategoryInclusionsSummaryOnly.get(
						'Total'
					);

					if (
						inclusionsSummaryOnly != null &&
						inclusionsSummaryOnly.contains(glCode.Business_ID__c)
					) {
						continue;
					}
				}else{
					//Do nothing
				}
				GL_Code_Line_Item__c lineitem = new GL_Code_Line_Item__c(
					GL_Code__c = glCode.Id,
					Service_Line_Item__c = sli.Id
				);
				lineitems.add(lineItem);
			}
		}

		try {
            withoutSharingDML.insertRecords(lineitems, false);

		} catch (DmlException e) {
			dohagedcare.logger.error(e.getMessage(), e, 'QFR').log();
		}
	}

    public List<GL_Code__c> getGLcodeRecords(Set<String> formTypes) {
        return this.queryService.getGLCodes(formTypes);  
    }
    private without sharing class QueryService {
        private List<GL_Code__c> getGLCodes(Set<String> formTypes) {
			return [ SELECT Id, Type__c, Business_ID__c
                FROM GL_Code__c
                WHERE Type__c IN :formTypes AND Line_Item_Value_Type__c != NULL
			];
		}
    }
}