force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OmniPeriodEndingDateHelper.cls
/* Author: Nick Parsons
   Date Created: 15/8/22
   User Story: 233634
   Revision History: */

global with sharing class OmniPeriodEndingDateHelper implements Callable {

	public static Date getPeriodEndingDate(Id formId) {
        //Need to make the recordID context sensitive
        //String reportPeriodId = 'a2Y9h0000000KgHEAU';

        //Query to get the reporting period end date
        Date periodEndDate = [
            SELECT Reporting_Period__r.End_Date__c
            FROM Form__c
            WHERE Id =: formId
            LIMIT 1
        ].Reporting_Period__r.End_Date__c;

        //Return the date
        return periodEndDate;
    }


    global Object call(string action, Map<String, Object> args) {
        Map<String, Object> input = (Map<String, Object>)args.get('input');
        Map<String, Object> output = (Map<String, Object>)args.get('output');
        Map<String, Object> options = (Map<String, Object>)args.get('options');
        switch on action {
            when 'getPeriodEndingDate' {
                Date periodEndDate = getPeriodEndingDate((String)input.get('formId'));
                output.put('endingDate', periodEndDate);
                return true;
            }
            when else {
                throw new ExtensionMalformedException('Method not implemented');
            }
        }
    }
    public class ExtensionMalformedException extends Exception {}
}