force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/QI_Exempt__c.field-meta.xml
<CustomField>
    <fullName>QI_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QI Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_End_Date__c</fullName>
    <label>Association End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceAcctRelationshipHandler.cls
/*******************************************************************************************
* @Name             ServiceAcctRelationshipHandler
* @Test class       ServiceAcctRelationshipHandlerTest
* @Author           Gabriel Piragibe Cova Leda de Almeida
* @Date             23-09-2022
* @Story#           225789 (SR-QI ART Planning Sprint 4)
* @LWC Component    None
* @Description      SAR records that have association end date less than current date signals
                    that we need to update the STAR Rating History record associated with service
                    and set flag 'transferred' to true.
                    Services records that have their service status operational & residential signals that we need
                    to create a system exemption with reason 'Transferred Service'
*******************************************************************************************/
/* MODIFICATION LOG
 * Version       Developer                                Date                Description
 *-------------------------------------------------------------------------------------------
 *  1.0     		Gabriel Piragibe Cova Leda de Almeida    23-09-2022          Initial Creation
 *******************************************************************************************/
public with sharing class ServiceAcctRelationshipHandler implements afterUpdate {
	@testvisible
	private static Boolean fakeException = false;

	public void afterUpdate(Map<Id, SObject> newSARMap, Map<Id, SObject> oldSARMap) {
		// Cast SObject to SAR object so we can access lookup fieds
		Map<Id, Service_Account_Relationship__c> newSARMapInput = new Map<Id, Service_Account_Relationship__c>(
			(List<Service_Account_Relationship__c>) newSARMap.values()
		);
		Set<Id> serviceIDs = new Set<Id>();

		// Collects service IDs which association has ended
		for (Service_Account_Relationship__c sarRec : newSARMapInput.values()) {
			if (sarRec.Service_Name__c != null && sarRec.Association_End_Date__c < System.today()) {
				serviceIDs.add(sarRec.Service_Name__c);
			}
		}

		// return if there is no services with end date older than today
		if (serviceIDs.size() == 0) {
			return;
		}

		// Get services
		Map<Id, BusinessLicense> servicesMap = new Map<Id, BusinessLicense>(
			[
				SELECT Id, Status__c
				FROM BusinessLicense
				WHERE Id IN :serviceIDs AND Status__c = 'Operational' AND Care_Type__c = 'Residential'
			]
		);

		// return if there is no STAR Rating History record to update
		if (servicesMap.size() == 0)
			return;

		try {
			ServiceAcctRelationshipService.updateTransferRating(servicesMap);
			if (test.isRunningTest() && fakeException) {
				servicesMap.values()[20000].QI_Exempt__c = true;
			}
		} catch (Exception ex) {
			dohagedcare.Logger.error(ex.getMessage(), ex, 'Star Rating').log();
		}
	}
}