force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CountArchRegDecision__c.field-meta.xml
<CustomField>
    <fullName>CountArchRegDecision__c</fullName>
    <description>This field will take the number value of  how many Archived Regulatory Decisions Count for each service - will be updated by a trigger</description>
    <label>Archived Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Date_Decision_Applied__c.field-meta.xml
<CustomField>
    <fullName>Date_Decision_Applied__c</fullName>
    <label>Date Decision Applied</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Date_Decision_Ends__c.field-meta.xml
<CustomField>
    <fullName>Date_Decision_Ends__c</fullName>
    <label>Date Decision Ends</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test only</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Account_Relationship__c.Provider_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Compliance_Rating__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating__c</fullName>
    <description>Service Compliance Rating for an individual Reg Dec</description>
    <label>Service Compliance Rating</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>It determines if a service account relationship is active or not</description>
    <formula>IF( Association_Start_Date__c &lt;= TODAY() &amp;&amp;  (Association_End_Date__c &gt; TODAY() || ISNULL(Association_End_Date__c)), true, false)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_Start_Date__c</fullName>
    <label>Association Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountArchRegDecision__c.field-meta.xml
<CustomField>
    <fullName>CountArchRegDecision__c</fullName>
    <description>This field will take the number value of  how many Archived Regulatory Decision Count for each service - will be updated by a trigger</description>
    <label>Archived Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CurrentNonCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CurrentNonCurrentRegDec__c</fullName>
    <description>Stores count of non-current regulatory decisions which are flagged as relevant to rating. Value is updated when a new Regulatory Decision is created or existing decision is removed.</description>
    <label>Non Current Reg Dec Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Calc_Date__c</fullName>
    <description>Date time rating calculation occurred</description>
    <label>SCR Rating Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Exemption_Granted__c.field-meta.xml
<CustomField>
    <fullName>Rating_Exemption_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Rating Exemption Granted</description>
    <label>Rating Exemption Granted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Service Compliance Histories</relationshipLabel>
    <relationshipName>Service_Compliance_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service_Compliance_Rating__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating__c</fullName>
    <description>Service Compliance number rating, out of 5</description>
    <label>Service Compliance Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Publish</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
                <isActive>false</isActive>
                <label>Archive</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SCRRatingCalculationBatch.cls
/**
 * Author: Rami Zuhairi
 * Date: 26/10/2022
 * Description: to calculate SCR rating for current and active ratings
 * Related PBIs 207940  274594, 238026
 * PBI - 274594 has all related conditions mentioned in the comments.
 **/
public with sharing class SCRRatingCalculationBatch implements Database.Batchable<SObject> {

	public static String currentRating = 'Current Rating';
	public static String previousRating = 'Previous Rating';
    private static Set<Id> sarsWithCurrent = new Set<Id>();
    private static Set<Id> sarsWithNonCurrentEnd1to3Yr = new Set<Id>();
    private static Set<Id> sarsWithNonCurrentEndWithin1Yr = new Set<Id>();
	//Grap all required fields from BusinessLicense
	public Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(getQuery());
	}
	public void execute(Database.BatchableContext bc, List<BusinessLicense> scope) {
		try {
			
			Date currentDate = Date.today();
			Date dateOlderThan3Years = currentDate - (3 * 365); // 3 years older
			Date dateOlderThan1Year = currentDate - 365; // 1 year older
			Integer countSCHrecords = 0; // to check num of SCH records for each service
			List<BusinessLicense> serviceRecordsList = new List<BusinessLicense>();
			List<Service_Compliance_History__c> complianceHistoryListToInsert = new List<Service_Compliance_History__c>();
			List<Service_Compliance_History__c> complianceHistoryListToUpdate = new List<Service_Compliance_History__c>();

			serviceRecordsList = [
				SELECT
					Id,
					Status__c,
					Name,
					(
						SELECT
							Id,
							Association_Start_Date__c,
							CountArchRegDecision__c,
							CountCurrentRegDec__c,
							CurrentNonCurrentRegDec__c,
							Active__c,
							Provider_Name__c
						FROM Service_Account_Relationships__r
						WHERE Active__c = TRUE
					),
					(
						SELECT
							Service__c,
							Rating_Type__c,
							Service_Compliance_Rating__c,
							Rating_Exemption_Reason__c,
							Rating_Exemption_Granted__c
						FROM Service_Compliance_History__r
						WHERE Rating_Type__c = :currentRating
					)
				FROM BusinessLicense
				WHERE Id IN :scope
			];

			//Create set of BL Ids to cache it in StarRatingUtil.cacheAccredCertification
			Map<Id, BusinessLicense> services = new Map<Id, BusinessLicense>(serviceRecordsList);
			StarRatingUtil.cacheAccredCertification(services.keySet());
			setRegCounts(serviceRecordsList);
            Set<Id> serviceIdSet = new Set<Id>();
    		Set<Id> serviceAccountIds = new Set<Id>();

			for (BusinessLicense service : serviceRecordsList) {
				// Count number of SCH records for each service
				countSCHrecords = service.Service_Compliance_History__r.size();
				if (service.Service_Account_Relationships__r.isEmpty()) {
					continue;
				}

				Boolean setPrevious = false;

				// Outter if condition checks for new rating to be set. Inner if condition avoids duplicates as this batch runs every day.
				Service_Account_Relationship__c sar = service.Service_Account_Relationships__r[0];
				if ((sar.Association_Start_Date__c < dateOlderThan3Years) &&
					(StarRatingUtil.getServAccredCertStarDate(service.Id) < dateOlderThan3Years) &&
					(StarRatingUtil.getAccreditationDuration(service.Id) >= 1095) &&
					!sarsWithCurrent.contains(sar.Id) &&
					!sarsWithNonCurrentEnd1to3Yr.contains(sar.Id) &&
					!sarsWithNonCurrentEndWithin1Yr.contains(sar.Id)){
					if(countSCHrecords == 0 || service.Service_Compliance_History__r[0].Service_Compliance_Rating__c != 5){
						complianceHistoryListToInsert.add(createNewSch(service.Id, sar, 5,  null));
						setPrevious = true;
					}
				}
				else if ((sar.Association_Start_Date__c <= dateOlderThan1Year) &&
						(StarRatingUtil.getServAccredCertStarDate(service.Id) <= dateOlderThan1Year) &&
						!sarsWithCurrent.contains(sar.Id) &&
						!sarsWithNonCurrentEndWithin1Yr.contains(sar.Id)){
						if (countSCHrecords == 0 || service.Service_Compliance_History__r[0].Service_Compliance_Rating__c != 4) {
							complianceHistoryListToInsert.add(createNewSch(service.Id, sar, 4,  null));
							setPrevious = true;
						}
				}
				else if ((sar.Association_Start_Date__c <= dateOlderThan1Year) &&
						(StarRatingUtil.getServAccredCertStarDate(service.Id) <= dateOlderThan1Year) &&
						!sarsWithCurrent.contains(sar.Id)){
						if (countSCHrecords == 0 || service.Service_Compliance_History__r[0].Service_Compliance_Rating__c != 3) {
							complianceHistoryListToInsert.add(createNewSch(service.Id, sar, 3,  null));
							setPrevious = true;
						}
				}
				else if ((StarRatingUtil.getServAccredCertStarDate(service.Id) > dateOlderThan1Year) &&
						!sarsWithCurrent.contains(sar.Id)){
						if (countSCHrecords == 0 || (service.Service_Compliance_History__r[0].Service_Compliance_Rating__c != null &&
						service.Service_Compliance_History__r[0].Rating_Exemption_Reason__c != 'New Service')) {
							complianceHistoryListToInsert.add(createNewSch(service.Id, sar, null, 'New Service'));
							setPrevious = true;
						}
				}
				else if ((sar.Association_Start_Date__c > dateOlderThan1Year) &&
						!sarsWithCurrent.contains(sar.Id)){
						if (countSCHrecords == 0 || (service.Service_Compliance_History__r[0].Service_Compliance_Rating__c != null &&
						service.Service_Compliance_History__r[0].Rating_Exemption_Reason__c != 'Transferred Service')) {
							complianceHistoryListToInsert.add(createNewSch(service.Id, sar, null, 'Transferred Service'));
							setPrevious = true;
						}
				}
				else{
					setPrevious = false;
				}

				if(setPrevious){
					serviceIdSet.add(service.Id);
					serviceAccountIds.add(sar.Id);
					for (Service_Compliance_History__c schRec : service.Service_Compliance_History__r) {
						schRec.Rating_Type__c = previousRating;
						complianceHistoryListToUpdate.add(schRec);
					}
				}
			}

			//insert compliance History List
			Database.insert(complianceHistoryListToInsert, false);
			Database.update(complianceHistoryListToUpdate, false);

			// calls SSCRUtil.CurrentSRH to creat Star rating history each time SCH record created ---------
			SCRUtil.createNUpdateSCR( serviceIdSet, serviceAccountIds, complianceHistoryListToInsert );
		} catch (DmlException exp) {
			dohagedcare.Logger.error(exp.getMessage(), exp, 'QISR- SCRRatingCalculationBatch').Log();
		}
	}

	private static Service_Compliance_History__c createNewSch(
		String serviceId,
		Service_Account_Relationship__c sar,
		Integer rating,
		String exemptionRating	) {
		return new Service_Compliance_History__c(
			Service__c = serviceId,
			Provider__c = sar.Provider_Name__c,
			Service_Account__c = sar.Id,
			Rating_Calc_Date__c = datetime.now(),
        	Publication_Date__c = datetime.now(),
			Service_Compliance_Rating__c = rating,
			Rating_Type__c = currentRating,
			Availability_Status__c = 'LIVE',
			Rating_Exemption_Reason__c = exemptionRating,
			Rating_Exemption_Granted__c = (exemptionRating != null)
		);
	}
	private static void setRegCounts(List<BusinessLicense> serviceRecordsList){
		Map<Id,Service_Account_Relationship__c> sarMap = new Map<Id,Service_Account_Relationship__c>();
		for (BusinessLicense service : serviceRecordsList) {
			if (!service.Service_Account_Relationships__r.isEmpty()) {
				sarMap.put( service.Service_Account_Relationships__r[0].Id, service.Service_Account_Relationships__r[0]);
			}
		}
		
		for(RegulatoryCodeViolation regDec : [SELECT Id, Status, Date_Decision_Ends__c, Date_Decision_Applied__c, Service_Account_Relationship__c,
												Service_Account_Relationship__r.Association_Start_Date__c
												FROM RegulatoryCodeViolation 
												WHERE Service_Account_Relationship__c IN: sarMap.keySet() 
												AND ((Status = 'Current' AND Published__c = true) OR Status = 'Non-Current') 
												AND Service_Compliance_Rating__c != null AND Service_Compliance_Rating__c != 0]){
			if(regDec.Date_Decision_Applied__c >= regDec.Service_Account_Relationship__r.Association_Start_Date__c &&
				regDec.Status == 'Current'){
					sarsWithCurrent.add(regDec.Service_Account_Relationship__c);
			}
			else if(regDec.Date_Decision_Applied__c >= regDec.Service_Account_Relationship__r.Association_Start_Date__c &&
				regDec.Status == 'Non-Current' && regDec.Date_Decision_Ends__c != null && regDec.Date_Decision_Ends__c >= (Date.today().addDays(-1095)) &&
				regDec.Date_Decision_Ends__c < (Date.today().addDays(-365))){
					sarsWithNonCurrentEnd1to3Yr.add(regDec.Service_Account_Relationship__c);
			}
			else if(regDec.Date_Decision_Applied__c >= regDec.Service_Account_Relationship__r.Association_Start_Date__c &&
				regDec.Status == 'Non-Current' && regDec.Date_Decision_Ends__c != null && regDec.Date_Decision_Ends__c >= (Date.today().addDays(-365))){
					sarsWithNonCurrentEndWithin1Yr.add(regDec.Service_Account_Relationship__c);
			}
			else {
				continue;
			}
		}
	}

	public virtual String getQuery() {
		String retQuery = '';
		retQuery =
			retQuery +
			'SELECT Id FROM BusinessLicense WHERE Status__c IN (\'Operational\', \'Offline\')  AND Care_Type__c = \'Residential\' ';
		return (retQuery);
	}

	public void finish(Database.BatchableContext bc) {
		System.debug('Batch Job Completed!');
	}
}