force-app/main/default/objects/BusinessLicense/fields/CER_Exempt__c.field-meta.xml
<CustomField>
    <fullName>CER_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CER Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CM_Exempt__c.field-meta.xml
<CustomField>
    <fullName>CM_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CM Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/QI_Exempt__c.field-meta.xml
<CustomField>
    <fullName>QI_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QI Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/SCR_Exempt__c.field-meta.xml
<CustomField>
    <fullName>SCR_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCR Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/SRQI_Exemption__c.object-meta.xml
<CustomObject>
    <description>Exemption record for services that have been granted an exemption from either the CER, SCR, QI or CM rating domains</description>
    <label>Exemption</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Exemption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_Exemption__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Exemptions</relationshipLabel>
    <relationshipName>Service</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/recordTypes/CER_Exemption.recordType-meta.xml
<RecordType>
    <fullName>CER_Exemption</fullName>
    <active>true</active>
    <description>Exemption from CER requirements</description>
    <label>CER Exemption</label>
</RecordType>

force-app/main/default/objects/SRQI_Exemption__c/recordTypes/CM_Exemption.recordType-meta.xml
<RecordType>
    <fullName>CM_Exemption</fullName>
    <active>true</active>
    <description>Exemption from CM requirements</description>
    <label>CM Exemption</label>
</RecordType>

force-app/main/default/objects/SRQI_Exemption__c/recordTypes/QI_Exemption.recordType-meta.xml
<RecordType>
    <fullName>QI_Exemption</fullName>
    <active>true</active>
    <description>Exemption from QI Requirements</description>
    <label>QI Exemption</label>
</RecordType>

force-app/main/default/objects/SRQI_Exemption__c/recordTypes/SCR_Exemption.recordType-meta.xml
<RecordType>
    <fullName>SCR_Exemption</fullName>
    <active>true</active>
    <description>Exemption from SCR Requirements</description>
    <label>SCR Exemption</label>
</RecordType>

force-app/main/default/classes/StarRatingExemptionBatchUtil.cls
/*******************************************************************************************
 * @Name             StarRatingExemptionBatchUtil
 * @testClass       StarRatingExemptionBatchTest
 * @Author           Gabriel Piragibe Cova Leda de Almeida
 * @Date             12-10-2022
 * @Story#           TBA (SR-QI ART Planning Sprint 5)
 * @LWC Component    None
 * @Description		 utility class for StarRatingExemptionBatch
 *******************************************************************************************/
/* MODIFICATION LOG
 * Version       Developer                                Date                Description
 *-------------------------------------------------------------------------------------------
 *  1.0     		Gabriel Piragibe Cova Leda de Almeida    12-10-2022          Initial Creation
 *******************************************************************************************/
public with sharing class StarRatingExemptionBatchUtil {
	// Stores constant for cer exemption record type developer name
	private static final String CER_EXEMPTION = 'CER_Exemption';

	// Stores constant for cm exemption record type developer name
	private static final String CM_EXEMPTION = 'CM_Exemption';

	// Stores constant for qi exemption record type developer name
	private static final String QI_EXEMPTION = 'QI_Exemption';

	// Stores constant for scr exemption record type developer name
	private static final String SCR_EXEMPTION = 'SCR_Exemption';

	// Stores constant to indicate app name in exception log
	private static final String APP_NAME = 'Star Rating';

	// Enum to be used in switch statements as we cannot used constant in switch apex for now
	private enum ExemptionTypes {
		CER_EXEMPTION,
		CM_EXEMPTION,
		QI_EXEMPTION,
		SCR_EXEMPTION
	}

	// Stores constant message saying subdomain is not valid
	private static final String INVALID_SUBDOMAIN = 'Exemption subdomain is not valid';

	// Returns true if service exemption flag is checked for a particular subdomain
	public static Boolean isServiceExemptionFlagChecked(BusinessLicense service, SRQI_Exemption__c exemption) {
		Boolean flag = false;
		switch on ExemptionTypes.valueOf(exemption.RecordType.DeveloperName) {
			when CER_EXEMPTION {
				flag = service.CER_Exempt__c;
			}
			when CM_EXEMPTION {
				flag = service.CM_Exempt__c;
			}
			when QI_EXEMPTION {
				flag = service.QI_Exempt__c;
			}
			when SCR_EXEMPTION {
				flag = service.SCR_Exempt__c;
			}
			when else {
				dohagedcare.Logger.warn(INVALID_SUBDOMAIN).log();
			}
		}
		return flag;
	}

	// Set service flag exemption
	public static void setServiceFlag(BusinessLicense service, SRQI_Exemption__c exemption, Boolean isActive) {
		switch on ExemptionTypes.valueOf(exemption.RecordType.DeveloperName) {
			when CER_EXEMPTION {
				service.CER_Exempt__c = isActive;
			}
			when CM_EXEMPTION {
				service.CM_Exempt__c = isActive;
			}
			when QI_EXEMPTION {
				service.QI_Exempt__c = isActive;
			}
			when SCR_EXEMPTION {
				service.SCR_Exempt__c = isActive;
			}
			when else {
				dohagedcare.Logger.warn(INVALID_SUBDOMAIN).log();
			}
		}
	}

	/* Active exemption process will search for a SRH associated with a service, if it exists it will
	update the SRH and the associated subdomain. If SRH does not exist, it will create one and also create/update
	a subdomain.*/
	public static void activeExemptionProcess(List<SRQI_Exemption__c> exemptions) {
		Set<Id> serviceIDs = new Set<Id>();
		for (SRQI_Exemption__c exempRec : exemptions) {
			serviceIDs.add(exempRec.Service__c);
		}

		// Initialise required maps in star rating util class
		StarRatingUtil.cacheServiceAccRelationship(serviceIDs);
		StarRatingUtil.cacheAccredCertification(serviceIDs);
		StarRatingUtil.cacheCERData(serviceIDs);

		StarRatingUtil.srhUpdate(exemptions);
	}
}