force-app/main/default/objects/BusinessLicense/fields/CER_Exempt__c.field-meta.xml
<CustomField>
    <fullName>CER_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CER Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CM_Exempt__c.field-meta.xml
<CustomField>
    <fullName>CM_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CM Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/QI_Exempt__c.field-meta.xml
<CustomField>
    <fullName>QI_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QI Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/SCR_Exempt__c.field-meta.xml
<CustomField>
    <fullName>SCR_Exempt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCR Exempt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/Care_Minutes_Summary__c.object-meta.xml
<CustomObject>
    <label>Care Minutes Summary</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Care Minutes Summary Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Minutes Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Minutes Summary</relationshipLabel>
    <relationshipName>Care_Minutes_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Care Minutes Summary</relationshipLabel>
    <relationshipName>Care_Minutes_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Care Minutes Summary</relationshipLabel>
    <relationshipName>Care_Minutes_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/SRQI_CER__c.object-meta.xml
<CustomObject>
    <label>Consumer Experience Report</label>
    <nameField>
        <displayFormat>CER-{000000}</displayFormat>
        <label>Consumer Experience Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Experience Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_CER__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Under_Review__c.field-meta.xml
<CustomField>
    <fullName>Under_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Under Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/SRQI_Exemption__c.object-meta.xml
<CustomObject>
    <description>Exemption record for services that have been granted an exemption from either the CER, SCR, QI or CM rating domains</description>
    <label>Exemption</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Exemption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_Exemption__c/fields/Exemption_Finish__c.field-meta.xml
<CustomField>
    <fullName>Exemption_Finish__c</fullName>
    <description>Date exemption is no longer in force</description>
    <label>Exemption Finish</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It indicates which service account relationship record the exemption record is linked to.</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service in Service Account Relationship must match service in Exemption record.</errorMessage>
        <filterItems>
            <field>$Source.Service__c</field>
            <operation>equals</operation>
            <valueField>Service_Account_Relationship__c.Service_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Exemptions</relationshipLabel>
    <relationshipName>ExemptionsSAR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Care_Minutes_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Minutes_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Minutes</label>
    <referenceTo>Care_Minutes_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Consumer_Experience_Id__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Experience_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer Experience Report</label>
    <referenceTo>SRQI_CER__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Quality_Indicator_Id__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Under_Review__c.field-meta.xml
<CustomField>
    <fullName>Under_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Under Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StarRatingExemptionBatchTest.cls
@isTest
public with sharing class StarRatingExemptionBatchTest {
	static final String NEW_RATING = 'New Rating';
	static final String CURRENT_RATING = 'Current Rating';

	@isTest
	public static void testExpriedStarRatingExemptionBatch() {
		Integer recordCount = 2;
		User testUser = TestDataFactory.createSystemAdminUser();

		Test.startTest();
		System.runAs(testUser){

			// create report period type year
			Reporting_Period__c yearRP = TestDataFactory.createReportingPeriod('Year');
			Integer yearDate = System.today().Year() - 1;
			yearRP.Start_Date__c = date.newInstance(yearDate, 7, 1);
			yearRP.End_Date__c = date.newInstance(yearDate, 12, 31);
			insert yearRP;

			// create report period type quarter
			Reporting_Period__c quarterRP = TestDataFactory.createReportingPeriod('Quarter');
			quarterRP.Start_Date__c = (System.today() + 12 ).addMonths(-6);
			quarterRP.End_Date__c = (System.today() + 24).addMonths(-3);
			insert quarterRP;

			// create services
			List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);

			// update services exemption flags
			for (BusinessLicense servRec : services) {
				servRec.CER_Exempt__c = true;
				servRec.CM_Exempt__c = true;
				servRec.QI_Exempt__c = true;
				servRec.SCR_Exempt__c = true;
			}

			insert services;

			// create expired cer exemptions
			List<SRQI_Exemption__c> cerExemptionList = TestDataFactory.createCERExemptionRecords(recordCount, services);
			insert cerExemptionList;

			// create expired cm exemptions
			List<SRQI_Exemption__c> cmExemptionList = TestDataFactory.createCMExemptionRecords(recordCount, services);
			insert cmExemptionList;

			// create expired qi exemptions
			List<SRQI_Exemption__c> qiExemptionList = TestDataFactory.createQIExemptionRecords(recordCount, services);
			insert qiExemptionList;

			// create expired scr exemptions
			List<SRQI_Exemption__c> scrExemptionList = TestDataFactory.createSCRExemptionRecords(recordCount, services);
			insert scrExemptionList;

			// create providers
			List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
			insert providers;

			// create sar
			List<Service_Account_Relationship__c> sar = TestDataFactory.createServiceAccountRecords(
				recordCount,
				services,
				providers
			);
			insert sar;

			// create CER records
			List<SRQI_CER__c> cerRecords = TestDataFactory.createCERRecords(recordCount, sar, providers, services, yearRP);
			for (SRQI_CER__c cerRec : cerRecords) {
				cerRec.Rating_Type__c = NEW_RATING;
				cerRec.Under_Review__c = false;
			}
			insert cerRecords;

			// create CM records
			List<Care_Minutes_Summary__c> cmRecords = TestDataFactory.createCareMinuteSummary(recordCount, services);
			for (Care_Minutes_Summary__c cmRec : cmRecords) {
				cmRec.Under_Review__c = false;
				cmRec.Provider_Name__c = providers[0].Id;
				cmRec.Service_Account__c = sar[0].Id;
			}
			insert cmRecords;

			// create QI records
			List<Quality_Indicator_Summary__c> qiRecords = TestDataFactory.createQISummaryRecords(
				recordCount,
				providers,
				quarterRP,
				services,
				sar
			);
			for (Quality_Indicator_Summary__c qiRec : qiRecords) {
				qiRec.Rating_Type__c = NEW_RATING;
				qiRec.Under_Review__c = false;
			}
			insert qiRecords;

			// create star rating history records
			List<STAR_Rating_History__c> starRatingHistory = TestDataFactory.createStarRatingHistoryRecords(
				recordCount,
				services,
				providers,
				quarterRP
			);

			for (Integer i = 0; i < recordCount; i++) {
				starRatingHistory[i].Consumer_Experience_Id__c = cerRecords[i].Id;
				starRatingHistory[i].Care_Minutes_Id__c = cmRecords[i].Id;
				starRatingHistory[i].Quality_Indicator_Id__c = qiRecords[i].Id;
				starRatingHistory[i].Rating_Type__c = Math.mod(i, 2) == 0 ? NEW_RATING : CURRENT_RATING;
			}

			insert starRatingHistory;

		}
		StarRatingExemptionBatch batchJob = new StarRatingExemptionBatch();
		Database.executeBatch(batchJob);
		Test.stopTest();

		// Get services
		List<BusinessLicense> allServices = [
			SELECT Id, CER_Exempt__c, CM_Exempt__c, QI_Exempt__c, SCR_Exempt__c
			FROM BusinessLicense
		];

		// Check if exemption flags were reset
		for (BusinessLicense servRec : allServices) {
			System.assertEquals(false, servRec.CER_Exempt__c, 'CER exemption flag must be false');
			System.assertEquals(false, servRec.CM_Exempt__c, 'CM exemption flag must be false');
			System.assertEquals(false, servRec.QI_Exempt__c, 'QI exemption flag must be false');
			System.assertEquals(false, servRec.SCR_Exempt__c, 'SCR exemption flag must be false');
		}
	}

	@isTest
	public static void testActiveStarRatingExemptionBatch() {
		Integer recordCount = 10;
		User testUser = TestDataFactory.createSystemAdminUser();

		Test.startTest();
		System.runAs(testUser){

			// create report period type year
			Reporting_Period__c yearRP = TestDataFactory.createReportingPeriod('Year');
			Integer yearDate = System.today().Year() - 1;
			yearRP.Start_Date__c = date.newInstance(yearDate, 7, 1);
			yearRP.End_Date__c = date.newInstance(yearDate, 12, 31);
			insert yearRP;

			// create services
			List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
			insert services;

			// create active cm exemptions
			List<SRQI_Exemption__c> cmExemptionList = TestDataFactory.createCMExemptionRecords(recordCount, services);

			for (SRQI_Exemption__c exempRec : cmExemptionList) {
				exempRec.Exemption_Finish__c = System.today().addYears(2);
			}

			insert cmExemptionList;

		}
		StarRatingExemptionBatch batchJob = new StarRatingExemptionBatch();
		Database.executeBatch(batchJob);
		Test.stopTest();

		// Get services
		List<BusinessLicense> allServices = [
			SELECT Id, CER_Exempt__c, CM_Exempt__c, QI_Exempt__c, SCR_Exempt__c
			FROM BusinessLicense
		];

		// Check if exemption flags were reset
		for (BusinessLicense servRec : allServices) {
			System.assertEquals(true, servRec.CM_Exempt__c, 'CM exemption flag must be true');
		}
	}
}