force-app/main/default/objects/BusinessLicense/fields/CER_Consent_Revoked__c.field-meta.xml
<CustomField>
    <fullName>CER_Consent_Revoked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CER Consent Revoked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Previous_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Previous_Reporting_Period__c</fullName>
    <description>Displays true if dates match previous reporting period</description>
    <formula>IF( ISPICKVAL (Reporting_Period_Type__c, &quot;Quarter&quot;), 
IF( ADDMONTHS( TODAY( ), -3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ), -3 ) &lt;= End_Date__c, True, False ),
IF( ADDMONTHS( TODAY( ), -12 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ), -12 ) &lt;= End_Date__c, True, False )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Previous Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>It determines if a service account relationship is active or not</description>
    <formula>IF( Association_Start_Date__c &lt;= TODAY() &amp;&amp;  (Association_End_Date__c &gt; TODAY() || ISNULL(Association_End_Date__c)), true, false)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/SRQI_CER__c.object-meta.xml
<CustomObject>
    <label>Consumer Experience Report</label>
    <nameField>
        <displayFormat>CER-{000000}</displayFormat>
        <label>Consumer Experience Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Experience Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_CER__c/fields/Extant__c.field-meta.xml
<CustomField>
    <fullName>Extant__c</fullName>
    <description>Indicates if cer record is the latest one for the service for the quarterly reporting period record is linked to. If consent is revoked and cer record was loaded in previous reporting period, then this field should be false as the periodical apex will create a shell record for the service.</description>
    <formula>IF(AND(  Service__r.CER_Consent_Revoked__c = true, DATEVALUE(CreatedDate) &lt;  Quarterly_RP__r.CER_Calc_Date__c), false, IF (Service_Account__r.Most_Recent_CER__c = CASESAFEID(Id) , true, false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Extant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Quarterly_RP__c.field-meta.xml
<CustomField>
    <fullName>Quarterly_RP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the quarterly reporting period CER record was loaded.</description>
    <label>Quarterly RP</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value must be a quartely reporting period</errorMessage>
        <filterItems>
            <field>Reporting_Period__c.Reporting_Period_Type__c</field>
            <operation>equals</operation>
            <value>Quarter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Consumer Experience Reports (Quarterly RP)</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Rating_Exemption_Granted__c.field-meta.xml
<CustomField>
    <fullName>Rating_Exemption_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rating Exemption Granted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Rating_Exemption_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rating_Exemption_Reason__c</fullName>
    <label>Rating Exemption Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Service</fullName>
                <label>New provider</label>
            </value>
            <value>
                <fullName>Transferred Service</fullName>
                <label>Transfer of ownership</label>
            </value>
            <value>
                <fullName>Business Exemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Total_CER_Score__c.field-meta.xml
<CustomField>
    <fullName>Total_CER_Score__c</fullName>
    <formula>Respect_Score__c +
Food_Score__c +
Safety_Score__c +
Operation_Score__c +
Care_Need_Score__c +
Competent_Score__c +
Independent_Score__c +
Explain_Score__c +
Follow_Up_Score__c +
Caring_Score__c +
Voice_Score__c +
Home_Score__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total CER Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/SRQI_Exemption__c.object-meta.xml
<CustomObject>
    <description>Exemption record for services that have been granted an exemption from either the CER, SCR, QI or CM rating domains</description>
    <label>Exemption</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Exemption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_Exemption__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>It determines if the exemption is active or not based on start and finish date.</description>
    <formula>IF( Exemption_Start__c &lt;=  TODAY() &amp;&amp;  Exemption_Finish__c &gt;=  TODAY() , true, false)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>It describes reason for exemption, and it will also be used when generating CER Rating record for exempt services</description>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Service</fullName>
                <label>New provider</label>
            </value>
            <value>
                <fullName>Transferred Service</fullName>
                <label>Transfer of ownership</label>
            </value>
            <value>
                <fullName>Business Exemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Exemptions</relationshipLabel>
    <relationshipName>Service</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/recordTypes/CER_Exemption.recordType-meta.xml
<RecordType>
    <fullName>CER_Exemption</fullName>
    <active>true</active>
    <description>Exemption from CER requirements</description>
    <label>CER Exemption</label>
</RecordType>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Consumer_Experience_Id__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Experience_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer Experience Report</label>
    <referenceTo>SRQI_CER__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Rating_Exemption_Granted__c.field-meta.xml
<CustomField>
    <fullName>Rating_Exemption_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Rating Exemption Granted</description>
    <label>Rating Exemption Granted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CerHybridBatch.cls
/*******************************************************************************************
 * @Name             CerHybridBatch
 * @testClass CerHybridBatchTest
 * @Author           Gabriel Piragibe Cova Leda de Almeida
 * @Date             03-04-2023
 * @Story#           TBD
 * @LWC Component    None
 * @Description		 Calculates CER rating
 *******************************************************************************************/
/* MODIFICATION LOG
 * Version       Developer                                Date                Description
 *-------------------------------------------------------------------------------------------
 *  1.0     	 Gabriel Piragibe Cova Leda de Almeida    01-03-2023          Initial Creation
 *******************************************************************************************/
public with sharing class CerHybridBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
	private Set<Id> cerIdsForRecalculation = new Set<Id>();
	private Set<Id> serviceIdsForRecalculation = new Set<Id>();
	private Boolean isPeriodicalCalc = false;

	public CerHybridBatch(Set<Id> cerIds, Set<Id> serviceIds) {
		this.cerIdsForRecalculation = cerIds;
		this.serviceIdsForRecalculation = serviceIds;
	}

	public CerHybridBatch(Boolean isPeriod) {
		this.isPeriodicalCalc = isPeriod;
	}

	private void recalculateOverallSRH(List<SRQI_CER__c> cerToUpdate) {
		Map<Id, SRQI_CER__c> cers = new Map<Id, SRQI_CER__c>(cerToUpdate);
		Map<Id, Id> mostRecenSRH = new Map<Id, Id>();
		// Select most recent SRH linked to cer
		for (STAR_Rating_History__c rec : [
			SELECT Id, Consumer_Experience_Id__c
			FROM Star_Rating_History__c
			WHERE Consumer_Experience_Id__c IN :cers.keySet()
			ORDER BY CreatedDate DESC
		]) {
			if (!mostRecenSRH.containsKey(rec.Consumer_Experience_Id__c)) {
				mostRecenSRH.put(rec.Consumer_Experience_Id__c, rec.Id);
			}
		}

		// Recalculate overall
		String procedureName = 'SRQI_StarRatingCalculation';
		for (Id rec : mostRecenSRH.values()) {
			Map<String, Object> ipOutput;
			Map<String, Object> ipInput = new Map<String, Object>();
			Map<String, Object> ipOptions = new Map<String, Object>();
			ipInput.put('SRHID', rec);
			ipInput.put('IsRecalc', true);
			ipOutput = (Map<String, Object>) omnistudio.IntegrationProcedureService.runIntegrationService(
				procedureName,
				ipInput,
				ipOptions
			);
		}
	}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		if (!this.isPeriodicalCalc) {
			return Database.getQueryLocator(
				[
					SELECT
						Id,
						CER_Consent_Revoked__c,
						(
							SELECT Id, Total_CER_Score__c, Rating_Exemption_Reason__c, Rating_Exemption_Granted__c
							FROM Consumer_Experience_Reports__r
							WHERE Id IN :this.cerIdsForRecalculation
							LIMIT 1
						),
						(
							SELECT id, Reason__c
							FROM Service__r
							WHERE Active__c = TRUE AND RecordType.DeveloperName = 'CER_Exemption'
							LIMIT 1
						)
					FROM BusinessLicense
					WHERE Id IN :this.serviceIdsForRecalculation
				]
			);
		}

		return Database.getQueryLocator(
			[
				SELECT
					Id,
					CER_Consent_Revoked__c,
					(
						SELECT Id, Total_CER_Score__c, Rating_Exemption_Reason__c, Rating_Exemption_Granted__c
						FROM Consumer_Experience_Reports__r
						WHERE
							Quarterly_RP__r.Previous_Reporting_Period__c = TRUE
							AND Service_Account__r.Active__c = TRUE
							AND Extant__c = TRUE
						LIMIT 1
					),
					(
						SELECT id, Reason__c
						FROM Service__r
						WHERE Active__c = TRUE AND RecordType.DeveloperName = 'CER_Exemption'
						LIMIT 1
					)
				FROM BusinessLicense
				WHERE Status__c NOT IN ('Closed', 'Pre-operational') AND Operational_Two_Last_Quarters__c = TRUE
			]
		);
	}

	public void execute(Database.BatchableContext bc, List<BusinessLicense> scope) {
		List<SRQI_CER__c> cerToUpdate = new List<SRQI_CER__c>();
		for (BusinessLicense rec : scope) {
			if (rec.Consumer_Experience_Reports__r.isEmpty()) {
				continue;
			}

			for (SRQI_CER__c cerRecord : rec.Consumer_Experience_Reports__r) {
				cerRecord.Rating_Calc_Date__c = System.now();
				if (rec.CER_Consent_Revoked__c) {
					cerRecord.Consumer_Experience_Rating__c = 1;
					cerRecord.Rating_Exemption_Reason__c = null;
					cerRecord.Rating_Exemption_Granted__c = false;
				} else if (!rec.Service__r.isEmpty()) {
					cerRecord.Consumer_Experience_Rating__c = 0;
					cerRecord.Rating_Exemption_Reason__c = rec.Service__r[0].Reason__c;
					cerRecord.Rating_Exemption_Granted__c = true;
				} else {
					cerRecord.Consumer_Experience_Rating__c = CEIAlgorithmHelper.convertTotalCERScoreIntoStarRating(
						cerRecord
					);
					cerRecord.Rating_Exemption_Reason__c = null;
					cerRecord.Rating_Exemption_Granted__c = false;
				}

				cerToUpdate.add(cerRecord);
			}
		}

		if (!cerToUpdate.isEmpty()) {
			try {
				update cerToUpdate;
			} catch (Exception ex) {
				dohagedcare.Logger.error(ex.getMessage(), ex, 'recalculateCER - CEIAlgorithmHelper').Log();
			}
		}

		if (!this.isPeriodicalCalc) {
			recalculateOverallSRH(cerToUpdate);
		}
	}

	public void finish(Database.BatchableContext bc) {
		if (this.isPeriodicalCalc) {
			List<Reporting_Period__c> rpToUpdate = new List<Reporting_Period__c>();
			for (Reporting_Period__c rec : [
				SELECT Id, CER_Calculated__c
				FROM Reporting_Period__c
				WHERE Previous_Reporting_Period__c = TRUE AND Reporting_Period_Type__c = 'Quarter'
				LIMIT 1
			]) {
				rec.CER_Calculated__c = true;
				rpToUpdate.add(rec);
			}

			if (!rpToUpdate.isEmpty()) {
				try {
					update rpToUpdate;
				} catch (Exception ex) {
					dohagedcare.Logger.error(ex.getMessage(), ex, 'CerHybridBatch - finish method').Log();
				}
			}
		}
	}
}