force-app/main/default/objects/BusinessLicense/fields/CountArchRegDecision__c.field-meta.xml
<CustomField>
    <fullName>CountArchRegDecision__c</fullName>
    <description>This field will take the number value of  how many Archived Regulatory Decisions Count for each service - will be updated by a trigger</description>
    <label>Archived Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/NoOf_NonCurr_Rating_RegDecision__c.field-meta.xml
<CustomField>
    <fullName>NoOf_NonCurr_Rating_RegDecision__c</fullName>
    <description>Field updated by SCR Handler with no of non current Regulatory decisions relevant for SCR Rating i.e Non Current that count towards SCR</description>
    <label>NoOf NonCurr Rating RegDecision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Archived_Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Archived_Regulatory_Decision__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the regulatory decision has been archived</description>
    <label>Archived Regulatory Decision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Rating_Relevant__c.field-meta.xml
<CustomField>
    <fullName>Rating_Relevant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rating Relevant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test only</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Account_Relationship__c.Provider_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <description>Name of the Service to be Published</description>
    <label>Alternative Service Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Service care type is not Home Care or Residential</errorMessage>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Home Care</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountArchRegDecision__c.field-meta.xml
<CustomField>
    <fullName>CountArchRegDecision__c</fullName>
    <description>This field will take the number value of  how many Archived Regulatory Decision Count for each service - will be updated by a trigger</description>
    <label>Archived Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CurrentNonCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CurrentNonCurrentRegDec__c</fullName>
    <description>Stores count of non-current regulatory decisions which are flagged as relevant to rating. Value is updated when a new Regulatory Decision is created or existing decision is removed.</description>
    <label>Non Current Reg Dec Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegulatoryDecisionUtility.cls
/* 
    * Regulatory Decision Utility
    * Class provides library of functionality for Regulatory Decisions
    * Author: Matthew Wall
    * Date: 5/10/22
*/
/* MODIFICATION LOG
 * Version       Developer                   Date                Description
 *-------------------------------------------------------------------------------------------
 *  1.0     		Matthew Wall               05-10-2022          Initial Creation
 *  1.1             Matthew Wall               11-11-2022          Update to work on Service Account Relationship
 *******************************************************************************************/
public with sharing class RegulatoryDecisionUtility {
    public static final String CURRENT_STATUS = 'Current';
    public static final String NON_CURRENT_STATUS = 'Non-Current';
    public static final String DRAFT_STATUS = 'Draft';
    public static final String PUBLISH_STATUS = 'Published';

    public static Map<Id,Integer> getCurrentDecisionCount(List<RegulatoryCodeViolation> regDecList) {
        Integer count = 0;

        Map<Id,Integer> servAccIdWithCount = new Map<Id,Integer>();
        for (RegulatoryCodeViolation regDec : regDecList) {
            if (regDec.Status == CURRENT_STATUS) {
                count = 0;
                if(servAccIdWithCount.containsKey(regDec.Service_Account_Relationship__c)){
                    count = servAccIdWithCount.get(regDec.Service_Account_Relationship__c);
                }
                count++;
                servAccIdWithCount.put(regDec.Service_Account_Relationship__c, count);
            }
        }
        return servAccIdWithCount;
    }
    
    public static void setRegDecCount(Set<Id> serviceAccountIds, Map<Id,RegulatoryCodeViolation> regDecMap) { 
        List<Service_Account_Relationship__c> serviceAccountList = getServiceAccountList(serviceAccountIds);
        Map<Id,BusinessLicense> serviceMap = getServiceMap(serviceAccountList);
        List<RegulatoryCodeViolation> regDecList = regDecMap.values();
        Map<Id,Integer> servAccIdWithCount = getCurrentDecisionCount(regDecList); 

        for(Service_Account_Relationship__c sar : serviceAccountList) {
            sar.CountCurrentRegDec__c = (servAccIdWithCount.containsKey(sar.Id) ? servAccIdWithCount.get(sar.Id) : 0 );
            serviceMap.get(sar.Service_Name__c).CountCurrentRegDec__c = (servAccIdWithCount.containsKey(sar.Id) ? servAccIdWithCount.get(sar.Id) : 0 );
        }

        if (Schema.sObjectType.Service_Account_Relationship__c.isUpdateable()) {
            update serviceAccountList;
        }
        

        if (Schema.sObjectType.BusinessLicense.isUpdateable()) {
            update serviceMap.values();
        }
    }

    
    public static void updateNonCurrentCount(Set<Id> serviceAccountIds, Map<Id,RegulatoryCodeViolation> regDecMap) { 
        Integer nonCurrentCount;
        Integer archivedCount;
        List<Service_Account_Relationship__c> serviceAccountList = getServiceAccountList(serviceAccountIds);
        Map<Id,BusinessLicense> serviceMap = getServiceMap(serviceAccountList);
        Map<Id,Service_Account_Relationship__c> serviceToSarMap = new Map<Id,Service_Account_Relationship__c>();
        for (Service_Account_Relationship__c sar : serviceAccountList) {
            ServiceToSarMap.put(sar.Service_Name__c,sar);
        }

        for (Id id : serviceMap.keyset()) {
            nonCurrentCount = 0;
            archivedCount = 0;
            for (RegulatoryCodeViolation rd : regDecMap.values()) {
                if (rd.Service_Name_lookup__c == id && rd.Status == NON_CURRENT_STATUS 
                    && rd.Rating_Relevant__c == true) {  
                        nonCurrentCount++;
                }
                else if (rd.Service_Name_lookup__c == id && rd.Status == NON_CURRENT_STATUS
                        && rd.Archived_Regulatory_Decision__c == true) { 
                            archivedCount++;
                }
            }
            
            serviceToSarMap.get(id).CurrentNonCurrentRegDec__c = nonCurrentCount;
            serviceMap.get(id).NoOf_NonCurr_Rating_RegDecision__c = nonCurrentCount;
            serviceToSarMap.get(id).CountArchRegDecision__c = archivedCount;
            serviceMap.get(id).CountArchRegDecision__c = archivedCount;
        }
        
        update serviceToSarMap.values();
        update serviceMap.values();
    }
    
    public static List<Service_Account_Relationship__c> getServiceAccountList(Set<Id> serviceAccountIds) {
        return [SELECT Id, Name, CountCurrentRegDec__c, Service_Name__c, 
                CurrentNonCurrentRegDec__c 
                FROM Service_Account_Relationship__c
                WHERE Id IN: serviceAccountIds];
    }

    public static Map<Id,BusinessLicense> getServiceMap(List<Service_Account_Relationship__c> serviceAccountList) {
        Set<Id> serviceIds = new Set<Id>();
        for (Service_Account_Relationship__c sar : serviceAccountList) {
            serviceIds.add(sar.Service_Name__c);
        }
        Map<Id,BusinessLicense> serviceMap = new Map<Id,BusinessLicense>([SELECT Id, Name, CountCurrentRegDec__c
                                                                        FROM BusinessLicense
                                                                        WHERE Id IN: serviceIds]);
        return serviceMap;
    }

    public static Date convertDate(DateTime dt) {
        if (dt != null) {
            return date.newinstance(dt.year(), dt.month(), dt.day());
        }
        return null;
    }
}