force-app/main/default/objects/BusinessLicense/fields/Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Integration_ID__c</fullName>
    <formula>&apos;SRV-&apos;+IF(ISBLANK(Oracle_Service_ID__c),Service_Number__c,Oracle_Service_ID__c)</formula>
    <label>Integration ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull from Reporting Perion Object.</description>
    <label>Reporting Period ID</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/STAR_Rating_History__c.field-meta.xml
<CustomField>
    <fullName>STAR_Rating_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>STAR Rating History</label>
    <referenceTo>STAR_Rating_History__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Integration_ID__c</fullName>
    <formula>&apos;CON&apos;+&apos;-&apos;+if(ISBLANK(TEXT( Oracle_ID__c )),Contact_ID__c,TEXT( Oracle_ID__c ))</formula>
    <label>Integration ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Short__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Short__c</fullName>
    <description>Shortened version or Reporting Period to match Siebel</description>
    <formula>IF( ISPICKVAL(Reporting_Period_Type__c, &apos;Quarter&apos;),
&apos;Quarter &apos; &amp;
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3 ,&apos;3&apos;,
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6 ,&apos;4&apos;,
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9 ,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12 ,&apos;2&apos;,null) ) ) ) &amp;
&apos; FY &apos; &amp;
IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1), 2),
RIGHT( TEXT(YEAR(Start_Date__c)), 2)) &amp; &apos; - &apos; &amp;
IF(MONTH(End_Date__c) &gt;= 7, RIGHT( TEXT(YEAR(End_Date__c) +1), 2),
RIGHT( TEXT(YEAR(End_Date__c)), 2)),

TEXT(YEAR(Start_Date__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporting Period Short</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <description>Date STAR Rating is live on MAC</description>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Provider_Portal_Status__c.field-meta.xml
<CustomField>
    <fullName>Provider_Portal_Status__c</fullName>
    <formula>IF(
    AND(ISPICKVAL(Status__c, &quot;LIVE&quot;), NOT(Under_Review__c)),
    &quot;Publicly available&quot;,
    IF(
        AND(ISPICKVAL(Status__c, &quot;Published&quot;), NOT(Under_Review__c)),
        &quot;Preview&quot;,
        IF(
            OR(ISPICKVAL(Status__c, &quot;Published&quot;), ISPICKVAL(Status__c, &quot;LIVE&quot;)),
            &quot;Under review&quot;,
            &quot;&quot;
        )
    )
)</formula>
    <label>Provider Portal Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/ProviderPortal_RatingType__c.field-meta.xml
<CustomField>
    <fullName>ProviderPortal_RatingType__c</fullName>
    <formula>CASE(
    TEXT(Rating_Type__c),
    &quot;Current Rating&quot;, &quot;Current&quot;,
    &quot;New Rating&quot;, &quot;New&quot;,
    &quot;Previous Rating&quot;, &quot;Previous&quot;,
    &quot;Draft Rating&quot;, &quot;Draft&quot;,
    LEFT(TEXT(Rating_Type__c), FIND(&quot; &quot;, TEXT(Rating_Type__c)) - 1)
)</formula>
    <label>ProviderPortal RatingType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Rating_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Calc_Date__c</fullName>
    <description>DateTime STAR Rating was calculated</description>
    <label>Calculation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/SF_Service_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Service_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/STAR_Rating__c.field-meta.xml
<CustomField>
    <fullName>STAR_Rating__c</fullName>
    <formula>IMAGE(
IF( STAR_Rating_Calculation__c = 5, &quot;/img/samples/stars_500.gif&quot;,
IF( STAR_Rating_Calculation__c = 4, &quot;/img/samples/stars_400.gif&quot;,
IF( STAR_Rating_Calculation__c = 3, &quot;/img/samples/stars_300.gif&quot;,
IF( STAR_Rating_Calculation__c = 2, &quot;/img/samples/stars_200.gif&quot;,
IF( STAR_Rating_Calculation__c = 1, &quot;/img/samples/stars_100.gif&quot;, 
IF( ISBLANK(STAR_Rating_Calculation__c), &quot;/img/samples/stars_000.gif&quot;, &quot;/img/samples/stars_000.gif&quot;
)
)
)
)
)
), &quot;No rating available&quot;
)</formula>
    <label>STAR Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/STAR_Rating_Calculation__c.field-meta.xml
<CustomField>
    <fullName>STAR_Rating_Calculation__c</fullName>
    <label>STAR Rating Calculation</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of Star Rating calculation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availability_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Under_Review__c.field-meta.xml
<CustomField>
    <fullName>Under_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Under Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Availability_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Published</fullName>
    </customValue>
    <customValue>
        <fullName>LIVE</fullName>
    </customValue>
    <customValue>
        <fullName>Removed</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review/On Hold</fullName>
        <isActive>false</isActive>
        <label>Under Review/On Hold</label>
    </customValue>
    <description>Status for Overall &amp; subcategory StarRatings</description>
    <masterLabel>Availability Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/srqiSearchStarRating.cls
/**
 * @author Rami Zuhairi
 * @date 17-09-2022
 * @objects Reporting_Period_Short__c, BusinessLicense, STAR_Rating_History__c
 * @description Apex class that will query through STAR_Rating_History__c and get the required data
 * @testClass SrqiSearchStarRatingTest
 */
public with sharing class srqiSearchStarRating {
    private static final String LABEL_NO_RATING_AVAILABLE = 'No rating available';

    /**
     * Returns a map of filter values and default search results.
     * The method queries the Salesforce database to retrieve service rating data and
     * aggregates them to create filter values and default search results. It populates
     * sets of reporting periods, statuses, rating types, and ratings, as well as a
     * list of sorted ratings, and a map of latest rating history records by service ID.
     * @return a map of filter values and default search results.
     */
    @AuraEnabled
    public static Map<String, Object> getFilterValuesAndDefaultSearchResults() {

        Set<String> reportingPeriods = new Set<String>();
        Set<String> statuses = new Set<String>();
        Set<String> ratingTypes = new Set<String>();
        Set<String> ratings = new Set<String>();
        List<String> sortedRatings = new List<String>();
        Id mostRecentReportingPeriodId;

        List<STAR_Rating_History__c> srhListOfMostRecentReportingPeriod = new List<STAR_Rating_History__c>();

        try {
            Set<Id> sarIds = new Map<Id, Service_Account_Relationship__c>(
                SRProviderPortalUtil.getServiceAccountRelationships()
            ).keySet();

            if (!sarIds.isEmpty()) {
                for (STAR_Rating_History__c srh : [
                    SELECT
                        Id,
                        SF_Service_Id__c,
                        Rating_Type__c,
                        Status__c,
                        Rating_Calc_Date__c,
                        STAR_Rating_Calculation__c,
                        Provider_Portal_Status__c,
                        STAR_Rating__c,
                        Go_Live_Date__c,
                        Under_Review__c,
                        ProviderPortal_RatingType__c,
                        SF_Service_Id__r.Name,
                        SF_Service_Id__r.Integration_ID__c,
                        Reporting_Period__r.Reporting_Period_Short__c,
                        Reporting_Period__r.Start_Date__c,
                        Reporting_Period__c
                    FROM STAR_Rating_History__c
                    WHERE Reporting_Period__r.Reporting_Period_Short__c != NULL
                    AND Service_Account_Relationship__c IN :sarIds
                    AND Status__c NOT IN ('Removed', 'Draft', NULL )
                    AND (CreatedDate > LAST_N_YEARS:3 OR Go_Live_Date__c > LAST_N_YEARS:3)
                    ORDER BY Reporting_Period__r.Start_Date__c DESC //We need to get mostRecentReportingPeriodId
                ]) {
                    if (mostRecentReportingPeriodId == null) {
                        mostRecentReportingPeriodId = srh.Reporting_Period__c;
                    }
                    reportingPeriods.add(srh.Reporting_Period__r.Reporting_Period_Short__c);
                    statuses.add(srh.Provider_Portal_Status__c);
                    ratingTypes.add(srh.ProviderPortal_RatingType__c);
                    ratings.add(isNoDataAvailable(srh.STAR_Rating_Calculation__c));
                    if (srh.Reporting_Period__c == mostRecentReportingPeriodId) {
                        srhListOfMostRecentReportingPeriod.add(srh);
                    }
                }
                sortRating(ratings, sortedRatings);
                srhListOfMostRecentReportingPeriod = getSortedRecords(srhListOfMostRecentReportingPeriod);
            }
        } catch (Exception exp) {
            dohagedcare.Logger.error(exp.getMessage(), exp, 'QISR').log();
            throw new AuraHandledException(
                'Error in getting filter values and default search results. Please try again or contact system administrator.'
            );
        }

        return new Map<String, Object>{
            'reportingPeriods' => reportingPeriods,
            'statuses' => statuses,
            'ratingTypes' => ratingTypes,
            'ratings' => sortedRatings,
            'defaultSearchResults' => srhListOfMostRecentReportingPeriod
        };
    }

    /**
     * This method searches for Star Rating History records based on the provided SearchConfig object.
     * The method constructs a dynamic SOQL query based on the search criteria in the SearchConfig object,
     * executes the query and returns a list of STAR_Rating_History__c objects that match the search criteria.
     * @param searchConfig the SearchConfig object containing the search criteria
     * @return a list of STAR_Rating_History__c objects that match the search criteria
     */
    @AuraEnabled
    public static List<STAR_Rating_History__c> searchStarRatingHistories(SearchConfig searchConfig) {
        try {
            String soqlQuery = '';
            soqlQuery += 'SELECT Id, SF_Service_Id__c, Rating_Type__c, Status__c, Rating_Calc_Date__c, Under_Review__c, Provider_Portal_Status__c, ProviderPortal_RatingType__c, ';
            soqlQuery += 'STAR_Rating__c, STAR_Rating_Calculation__c, Go_Live_Date__c, SF_Service_Id__r.Name, SF_Service_Id__r.Integration_ID__c, ';
            soqlQuery += 'Reporting_Period__r.Reporting_Period_Short__c, Reporting_Period__r.Start_Date__c ';
            soqlQuery += 'FROM STAR_Rating_History__c ';
            soqlQuery += 'WHERE ';
            soqlQuery += 'SF_Service_Id__r.Name != NULL AND Status__c NOT IN (\'Removed\', \'Draft\', NULL) AND ';
            soqlQuery += 'Reporting_Period__r.Reporting_Period_Short__c != NULL AND ';
            soqlQuery += '(CreatedDate > LAST_N_YEARS:3 OR Go_Live_Date__c > LAST_N_YEARS:3) AND ';
            soqlQuery += 'Service_Account_Relationship__c IN ' + SRProviderPortalUtil.getSARIdsString();

            if (!searchConfig.statuses.isEmpty()) {
                soqlQuery += ' AND Provider_Portal_Status__c IN ' + getValuesInJointString(searchConfig.statuses, true);
            }

            if (!searchConfig.reportingPeriods.isEmpty()) {
                soqlQuery += ' AND Reporting_Period__r.Reporting_Period_Short__c IN ' + getValuesInJointString(searchConfig.reportingPeriods, true);
            }

            if (!searchConfig.ratingTypes.isEmpty()) {
                soqlQuery += ' AND ProviderPortal_RatingType__c IN ' + getValuesInJointString(searchConfig.ratingTypes, true);
            }

            if (!searchConfig.ratings.isEmpty()) {
                soqlQuery += ' AND STAR_Rating_Calculation__c IN ' + replaceNoDataAvailableSearchOptionToRatings(
                    getValuesInJointString(searchConfig.ratings, false)
                );
            }

            if (String.isNotBlank(searchConfig.serviceNamesOrIds)) {
                List<String> validSearchTerms = getValidSearchTerms(searchConfig.serviceNamesOrIds);
                soqlQuery += ' AND (';
                for (Integer i = 0; i < validSearchTerms.size(); i++) {
                    String searchTerm = validSearchTerms[i];
                    soqlQuery += ' (';
                    soqlQuery +=
                        'SF_Service_Id__r.Integration_ID__c LIKE \'%' +
                        String.escapeSingleQuotes(searchTerm) +
                        '%\' ';
                    soqlQuery +=
                        'OR SF_Service_Id__r.Name LIKE \'%' +
                        String.escapeSingleQuotes(searchTerm) +
                        '%\' ';
                    soqlQuery += ') ';
                    if (validSearchTerms.size() > 1 && i < validSearchTerms.size() - 1) {
                        soqlQuery += ' OR ';
                    }
                }
                soqlQuery += ') ';
            }

            return getSortedRecords(Database.query(soqlQuery));
        } catch (Exception ex) {
            dohagedcare.Logger.error(ex.getMessage(), ex, 'QISR').log();
            throw new AuraHandledException(
                'Error in Search! Please try again or contact system administrator.'
            );
        }
    }

    // Get all Service Names from BusinessLicense
    @AuraEnabled(Cacheable=true)
    public static List<BusinessLicense> getServiceNameRecords() {
        List<BusinessLicense> nameServiceNameList;
        try {
            nameServiceNameList = [
                SELECT Id, Integration_ID__c, Name
                FROM BusinessLicense
            ];
        } catch (Exception exp) {
            dohagedcare.Logger.error(exp.getMessage(), exp, 'QISR').log();
            throw new AuraHandledException(
                'Error in getting service names! Please try again or contact system administrator.'
            );
        }
        return nameServiceNameList;
    }

    // Get Service Name ID from BusinessLicense
    @AuraEnabled(Cacheable=true)
    public static Id getServiceNameIDRecord(String serviceName) {
        Id serviceID;
        try {
            serviceID = [
                SELECT Id, Integration_ID__c
                FROM BusinessLicense
                WHERE Name = :serviceName
            ]
                .Id;
        } catch (Exception exp) {
            dohagedcare.Logger.error(exp.getMessage(), exp, 'QISR').log();
            throw new AuraHandledException(
                'Error in getting service ID! Please try again or contact system administrator.'
            );
        }
        return serviceID;
    }

    public class SearchConfig {
        public SearchConfig() {
            this.reportingPeriods = new List<String>();
            this.statuses = new List<String>();
            this.ratingTypes = new List<String>();
            this.ratings = new List<String>();
        }
        @AuraEnabled
        public List<String> reportingPeriods { get; set; }
        @AuraEnabled
        public List<String> statuses { get; set; }
        @AuraEnabled
        public List<String> ratingTypes { get; set; }
        @AuraEnabled
        public List<String> ratings { get; set; }
        @AuraEnabled
        public String serviceNamesOrIds { get; set; }
    }

    private static String isNoDataAvailable(Decimal value) {
        if (value == 0 || value == null) {
            return LABEL_NO_RATING_AVAILABLE;
        } else {
            return String.valueOf(value);
        }
    }

    private static void sortRating(Set<String> ratings, List<String> sortedRatings) {
        if (!ratings.isEmpty()) {
            sortedRatings.addAll(ratings);
            sortedRatings.sort();
        }
    }

    private static String replaceNoDataAvailableSearchOptionToRatings(String ratings) {
        // When rating options from LWC includes 'No rating available', at backend, it can be 0 or NULL
        return ratings.replace(LABEL_NO_RATING_AVAILABLE, '0,NULL');
    }

    /**
     * Returns a formatted String of the values in the given List, with optional wrapping quotes for each value.
     * @param values the List of String values to format
     * @param wrapValueWithQuotes a Boolean flag indicating whether to wrap each value with single quotes
     * @return a formatted String of the values, with parentheses around them
     */
    private static String getValuesInJointString(List<String> values, Boolean wrapValueWithQuotes) {
        for (Integer i = 0; i < values.size(); i++) {
            values[i] = String.escapeSingleQuotes(values[i]);
        }
        String valuesInJointString;
        if (wrapValueWithQuotes) {
            valuesInJointString = '\'' + String.join(values, '\',\'') + '\'';
        } else {
            valuesInJointString = String.join(values, ',') ;
        }
        return '( ' + valuesInJointString + ' )';
    }

    /**
     * Returns a List of valid search terms from the given comma-separated String of search terms.
     * @param searchTerms a comma-separated String of search terms
     * @return a List of valid search terms, with leading/trailing whitespace removed
     */
    private static List<String> getValidSearchTerms(String searchTerms) {
        List<String> terms = searchTerms.split(',');
        List<String> validSearchTerms = new List<String>();
        for (String term : terms) {
            if (!String.isEmpty(term.trim())) {
                validSearchTerms.add(term.trim());
            }
        }
        return validSearchTerms;
    }

    private static List<STAR_Rating_History__c> getSortedRecords(List<STAR_Rating_History__c> records) {
        List<SortableStarRatingHistory> wrappers = new List<SortableStarRatingHistory>();
        for (STAR_Rating_History__c srh : records) {
            wrappers.add(new SortableStarRatingHistory(srh));
        }
        wrappers.sort();

        List<STAR_Rating_History__c> sortedRecords = new List<STAR_Rating_History__c>();
        for (SortableStarRatingHistory wrapper : wrappers) {
            sortedRecords.add(wrapper.record);
        }

        return sortedRecords;
    }

    public with sharing class SortableStarRatingHistory implements Comparable {
        public STAR_Rating_History__c record;
        public Integer ratingTypeOrder;
        public Integer statusOrder;

        public SortableStarRatingHistory(STAR_Rating_History__c record) {
            this.record = record;
            switch on record.Provider_Portal_Status__c {
                when 'Under review' {
                    statusOrder = 1;
                }
                when 'Preview' {
                    statusOrder = 2;
                }
                when 'Publicly available' {
                    statusOrder = 3;
                }
                when else {
                    statusOrder = 4;  // add default case to handle unexpected values
                }
            }
            switch on record.ProviderPortal_RatingType__c {
                when 'New' {
                    ratingTypeOrder = 1;
                }
                when 'Current' {
                    ratingTypeOrder = 2;
                }
                when 'Previous' {
                    ratingTypeOrder = 3;
                }
                when else {
                    ratingTypeOrder = 4;  // add default case to handle unexpected values
                }
            }
        }

        /**
         * This method is used to compare the current SortableStarRatingHistory instance with another instance.
         * The comparison is based on several fields, in the following priority order:
         * 1. Reporting_Period__r.Start_Date__c (Descending)
         * 2. SF_Service_Id__r.Integration_ID__c (Ascending)
         * 3. statusOrder (which is based on Provider_Portal_Status__c: 'Under review' -> 1, 'Preview' -> 2, 'Publicly available' -> 3)
         * 4. ratingTypeOrder (which is based on ProviderPortal_RatingType__c: 'New' -> 1, 'Current' -> 2, 'Previous' -> 3)
         * 5. Go_Live_Date__c (Descending)
         *
         * @param compareTo The Object that this instance should be compared to.
         *        It should be an instance of SortableStarRatingHistory; otherwise a ClassCastException will occur.
         *
         * @return Integer A negative integer if this instance should sort before compareTo,
         *        a positive integer if this instance should sort after compareTo.
         *        The absolute value of the returned integer does not have any specific meaning,
         *        as only the sign of the value (negative, zero, or positive) matters for sorting.
         */
        public Integer compareTo(Object compareTo) {
            SortableStarRatingHistory compareToWrapper = (SortableStarRatingHistory) compareTo;
            // Descending order for Reporting_Period__r.Start_Date__c
            if (record.Reporting_Period__r.Start_Date__c != compareToWrapper.record.Reporting_Period__r.Start_Date__c) {
                return record.Reporting_Period__r.Start_Date__c.daysBetween(compareToWrapper.record.Reporting_Period__r.Start_Date__c) > 0 ? 1 : -1;
            }
            // Ascending order for SF_Service_Id__r.Integration_ID__c
            if (record.SF_Service_Id__r.Integration_ID__c != compareToWrapper.record.SF_Service_Id__r.Integration_ID__c) {
                return record.SF_Service_Id__r.Integration_ID__c > compareToWrapper.record.SF_Service_Id__r.Integration_ID__c ? 1 : -1;
            }

            if (statusOrder != compareToWrapper.statusOrder) {
                return statusOrder > compareToWrapper.statusOrder ? 1 : -1;
            }

            if (ratingTypeOrder != compareToWrapper.ratingTypeOrder) {
                return ratingTypeOrder > compareToWrapper.ratingTypeOrder ? 1 : -1;
            }
            // Descending order for Go_Live_Date__c
            return record.Go_Live_Date__c.daysBetween(compareToWrapper.record.Go_Live_Date__c) > 0 ? 1 : -1;
        }
    }
}