force-app/main/default/objects/BusinessLicense/fields/Operational_Two_Last_Quarters__c.field-meta.xml
<CustomField>
    <fullName>Operational_Two_Last_Quarters__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates if service has or has not been operational for last 2 full quarters</description>
    <label>Operational Two Last Quarters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QISROfflineRatingCalclationBatch.cls
/**
* @Author             : smita kagde
* @Description        : Batch Class
* @Modification Log   : 
* ---------------------------------------------------
* Date           Author                Details
* ---------------------------------------------------
* 03/11/2022     smita kagde        PBI 269113 :Star Ratings algorithm define ratings for Offline services
*So that the MAC website always displays the correct Star ratings for a service that was previously offline but has resumed operations
**/
public with sharing class  QISROfflineRatingCalclationBatch implements Database.Batchable<SObject>{
    		
  		String Status1 = '\'Operational\'';  // to be used in running test
         String Status2 = '\'Offline\'';  // to be used in running test
    
    
            public Database.QueryLocator start(Database.BatchableContext context){  
               Database.QueryLocator result;
                result =  Database.getQueryLocator([Select Id,Status__c,Operational_Two_Last_Quarters__c,Status_Date__c From BusinessLicense Where Status__c IN ('Operational', 'Offline')]);
                return result;
         }
          
            public void execute(Database.BatchableContext context, List<BusinessLicense> scope){
                    try{
                        ServiceOperationalChecker.isOperationalForLastTwoFullQuarters(scope);
                    }catch(DmlException exp){
                        System.debug('somthing went wrong QISROfflineRatingCalclationBatch execute ' + exp.getMessage());
                        dohagedcare.Logger.error(exp.getMessage(),exp,'SCRUtil -createSRHWithSCR').Log();             
                    }
            }
        
            public void finish(Database.BatchableContext context){ 
                //no action required
            }

}