force-app/main/default/objects/BusinessLicense/fields/Operational_Two_Last_Quarters__c.field-meta.xml
<CustomField>
    <fullName>Operational_Two_Last_Quarters__c</fullName>
    <defaultValue>false</defaultValue>
    <description>indicates if service has or has not been operational for last 2 full quarters</description>
    <label>Operational Two Last Quarters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Current_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Current_Reporting_Period__c</fullName>
    <description>Displays true if current reporting period.</description>
    <formula>IF( TODAY( ) &gt;= Start_Date__c &amp;&amp; TODAY( ) &lt;= End_Date__c, True, False )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ServiceOperationalChecker.cls
/*******************************************************************************************
 * @Name             ServiceOperationalChecker
 * @Test class       ServiceOperationalCheckerTest
 * @Author           Gabriel Piragibe Cova Leda de Almeida
 * @Date             03-11-2022
 * @Story#
 * @LWC Component    None
 * @Description      Checks if service has been operational for a determined period of time
 *******************************************************************************************/
/* MODIFICATION LOG
 * Version       Developer                                Date                Description
 *-------------------------------------------------------------------------------------------
 *  1.0     	 Gabriel Piragibe Cova Leda de Almeida    03-11-2022          Initial Creation
 *  2.0     	 Sharevreet Singh						  20-05-2023          added isOperationalForLastFullQuarter(..) method
 *******************************************************************************************/
public with sharing class ServiceOperationalChecker {
	// Indicates if reporting periods have been loaded
	private static Boolean datesCacheLoaded = false;

	// Stores first reporting period start date
	private static Date earliestStDate;

	// Stores first reporting period start date for last quarter
	private static Date earliestStDateLastQuarter;

	// Stores second reporting period end date
	private static Date latestEndDate;

	// Stores first reporting period end date for last quarter
	private static Date latestEndDateLastQuarter;

	// Stores map containing reporting periods
	private static Map<Id, Reporting_Period__c> rps;

	//This method sets rps with the latest 2 reporting periods prior to current one
	private static void setReportingPeriodsDates() {
		if (datesCacheLoaded) {
			return;
		}

		rps = new Map<Id, Reporting_Period__c>(
			[
				SELECT Id, Start_Date__c, End_Date__c
				FROM Reporting_Period__c
				WHERE
					Start_Date__c < TODAY
					AND Current_Reporting_Period__c = FALSE
					AND Reporting_Period_Type__c = 'Quarter'
				ORDER BY Start_Date__c DESC
				LIMIT 2
			]
		);

		/* If 2 reporting periods are returned, then set both dates. Otherwise, do nothing*/
		if (rps.size() > 1) {
			if (rps.values()[0].End_Date__c != null) {
				latestEndDate = rps.values()[0].End_Date__c;
				latestEndDateLastQuarter = rps.values()[0].End_Date__c;
			}

			if (rps.values()[0].Start_Date__c != null) {
				earliestStDateLastQuarter = rps.values()[0].Start_Date__c;
			}

			if (rps.values()[1].Start_Date__c != null) {
				earliestStDate = rps.values()[1].Start_Date__c;
			}
		}
		else {
			if (rps.size() > 0 && rps.values()[0].End_Date__c != null) {
				latestEndDateLastQuarter = rps.values()[0].End_Date__c;
			}

			if (rps.size() > 0 && rps.values()[0].Start_Date__c != null) {
				earliestStDateLastQuarter = rps.values()[0].Start_Date__c;
			}
		}


		datesCacheLoaded = true;
	}

	private static Date getRPStartDateLastQuarter() {
		if (datesCacheLoaded) {
			return earliestStDateLastQuarter;
		}
		setReportingPeriodsDates();
		return earliestStDateLastQuarter;
	}

	private static Date getRPEndDateQuarter() {
		if (datesCacheLoaded) {
			return latestEndDateLastQuarter;
		}
		setReportingPeriodsDates();
		return latestEndDateLastQuarter;
	}

	// This method returns earliest start date amongst the two reporting periods selected in query
	@TestVisible
	private static Date getRPStartDate() {
		if (datesCacheLoaded) {
			return earliestStDate;
		}
		setReportingPeriodsDates();
		return earliestStDate;
	}

	// This method returns latest end date amongst the two reporting periods selected in query
	private static Date getRPEndDate() {
		if (datesCacheLoaded) {
			return latestEndDate;
		}
		setReportingPeriodsDates();
		return latestEndDate;
	}

	/* This method updates checkbox that indicates if service has or has not been operational for last
	   2 full quarters in service object according to service's status.
       Logic: current quarter == Q4, hence we need start date from Q2 and end date from Q3. 
       If status is OPERATIONAL and service's status effective date < Q2 start date and active association start date < Q2 start date, 
	   then tick checkbox as service was operating in Q2 & Q3 under its new provider.
       If status is OFFLINE and service's status effective date > Q3 end date, then tick checkbox as service was operating in Q2 & Q3.*/
	public static void isOperationalForLastTwoFullQuarters(List<BusinessLicense> services) {
		Map<Id, BusinessLicense> servicesMap = new Map<Id, BusinessLicense>(services);
		StarRatingUtil.cacheServiceAccRelationship(servicesMap.keySet());

		for (BusinessLicense servRecords : servicesMap.values()) {
			switch on servRecords.Status__c {
				when 'Operational' {
					if (
						servRecords.Status_Date__c < getRPStartDate() &&
						StarRatingUtil.getServAccRelStartDate(servRecords.Id) < getRPStartDate() &&
						rps.size() > 1
					) {
						servRecords.Operational_Two_Last_Quarters__c = true;
					} else {
						servRecords.Operational_Two_Last_Quarters__c = false;
					}
				}
				when 'Offline' {
					if (servRecords.Status_Date__c > getRPEndDate() && rps.size() > 1) {
						servRecords.Operational_Two_Last_Quarters__c = true;
					} else {
						servRecords.Operational_Two_Last_Quarters__c = false;
					}
				}
				when else {
					dohagedcare.Logger.warn('Invalid status').log();
				}
			}
		}

		if (!servicesMap.isEmpty()) {
			try {
				Database.update(servicesMap.values(), false);
			} catch (Exception ex) {
				dohagedcare.Logger.error(ex.getMessage(), ex, 'Star Rating').log();
			}
		}
	}

	/* This method updates checkbox that indicates if service has or has not been operational for last
	   full quarter in service object according to service's status.
       Logic: current quarter == Q4, hence we need start date from Q3 and end date from Q3. 
       If status is OPERATIONAL and service's status effective date < Q3 start date and active association start date < Q3 start date, 
	   then tick checkbox as service was operating in Q3 under its new provider.
       If status is OFFLINE and service's status effective date > Q3 end date, then tick checkbox as service was not operating in Q3.*/
	   public static Map<Id, Boolean> isOperationalForLastFullQuarter(List<BusinessLicense> services) {
		Map<Id, Boolean> isOperationalByServIdMap = new Map<Id, Boolean>();
		Map<Id, BusinessLicense> servicesMap = new Map<Id, BusinessLicense>(services);
		StarRatingUtil.cacheServiceAccRelationship(servicesMap.keySet());

		for (BusinessLicense servRecords : servicesMap.values()) {
			Boolean isOperational = null;
			switch on servRecords.Status__c {
				when 'Operational' {
					if (
						servRecords.Status_Date__c < getRPStartDateLastQuarter() &&
						StarRatingUtil.getServAccRelStartDate(servRecords.Id) < getRPStartDateLastQuarter()
					) {
						isOperational = true;
					} else {
						isOperational = false;
					}
				}
				when 'Offline' {
					if (servRecords.Status_Date__c > getRPEndDateQuarter()) {
						isOperational = true;
					} else {
						isOperational = false;
					}
				}
				when else {
					dohagedcare.Logger.warn('Invalid status').log();
				}
			}
			isOperationalByServIdMap.put(servRecords.Id, isOperational);
		}
		return isOperationalByServIdMap;
	}
}