force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact, Record Id of the related Contact record.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Portal_Service_Roles__c.field-meta.xml
<CustomField>
    <fullName>Portal_Service_Roles__c</fullName>
    <label>Portal Service Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Star Rating Reviewer - Service</fullName>
                <label>Star Rating Reviewer (Service)</label>
            </value>
            <value>
                <fullName>QI Role - Service</fullName>
                <label>QI Role (Service)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reporting Period</relationshipLabel>
    <relationshipName>Reporting_Period</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/QI_Submission_Due_Dt__c.field-meta.xml
<CustomField>
    <fullName>QI_Submission_Due_Dt__c</fullName>
    <description>capture the QI submission due date</description>
    <label>QI Submission Due Dt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Short__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Short__c</fullName>
    <description>Shortened version or Reporting Period to match Siebel</description>
    <formula>IF( ISPICKVAL(Reporting_Period_Type__c, &apos;Quarter&apos;),
&apos;Quarter &apos; &amp;
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3 ,&apos;3&apos;,
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6 ,&apos;4&apos;,
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9 ,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12 ,&apos;2&apos;,null) ) ) ) &amp;
&apos; FY &apos; &amp;
IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1), 2),
RIGHT( TEXT(YEAR(Start_Date__c)), 2)) &amp; &apos; - &apos; &amp;
IF(MONTH(End_Date__c) &gt;= 7, RIGHT( TEXT(YEAR(End_Date__c) +1), 2),
RIGHT( TEXT(YEAR(End_Date__c)), 2)),

TEXT(YEAR(Start_Date__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporting Period Short</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QIRemindersServiceTest.cls
/**
* author: Neha Malik
* date: 18/05/2023
* description: This is the Test service class for the QI notifications which will have all the data regarding Reporting
* Period and QI summary.
**/
@IsTest
public with sharing class  QIRemindersServiceTest {
    @TestSetup
    static void dataSetup(){
        Integer recordCount = 1;
        User testUser = TestDataFactory.createSystemAdminUser();
        System.runAs(testUser){
            //insert reporting period
            Reporting_Period__c rPeriod1 = new Reporting_Period__c();
            rPeriod1.Reporting_Period_Type__c = 'Quarter';
            Date todayDt = System.today();
            Date stDt = System.today() -10;
            rPeriod1.Start_Date__c = stDt.addMonths(-3);
            rPeriod1.End_Date__c = todayDt.addMonths(-3);
            rPeriod1.QI_Submission_Due_Dt__c = System.today();
            insert rPeriod1;
            // get providers
            List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
            insert providers;
            Account acct = providers.get(0);
            List<Contact> contToCreate = new List<Contact>();
            for (Integer i = 1; i <= 3; i++) {
                Contact testContact = new Contact();
                testContact.Salutation = 'Mr';
                testContact.FirstName = 'First Name' + i;
                testContact.LastName = 'Last Name';
                testContact.AccountId = providers[0].Id;
                testContact.Email = 'TestClassContact@health.gov.au';
                contToCreate.add(testContact);
            }
            insert contToCreate;
           	List<AccountContactRelation> acctList = new List<AccountContactRelation>();
    		List<AccountContactRelation> acrToUpdate = [SELECT Id, Account.RecordType.DeveloperName, Roles
      													FROM AccountContactRelation
      													WHERE Account.ParentId = :acct.Id OR AccountId = :acct.Id
    													];
            integer counter = 0;
    		for (AccountContactRelation iterAcr : acrToUpdate) {
                if(counter > 0) {
                   iterAcr.roles = 'QI Role - Service';
                } else {
        			iterAcr.roles = 'QI Role - Org';
                }
                	++counter ;
    		}
    		update (acrToUpdate);
        	// get services
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
            insert services;
            //List<Contact_Relationship__c> contReln = new List<Contact_Relationship__c>();
            Contact_Relationship__c cReln = new Contact_Relationship__c();
            //cReln.Account__r.Id = providers[0].Id;
            cReln.Contact__c = contToCreate[1].Id;
            cReln.Service__c = services[0].Id;
            cReln.Portal_Service_Roles__c = 'QI Role - Service';
            insert cReln;

            // get service account relationships
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(recordCount, services, providers);
            insert serviceAccountRecords;
            // get quality indicator summary
            List<Quality_Indicator_Summary__c> qisRecords = TestDataFactory.createQISummaryRecords(recordCount, providers, rPeriod1, services, serviceAccountRecords);
            insert qisRecords;
        }
    }

    @isTest
    static void testQIReminderDate(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<Reporting_Period__c> repPd = [SELECT End_Date__c,Start_Date__c,QI_Submission_Due_Dt__c FROM Reporting_Period__c];
        String notificationType = reminderService.calculateQIReminderDate(repPd);
        System.assertEquals('', notificationType);
        Test.stopTest();        
    }

    @isTest
    static void testSendReminders(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<AccountContactRelation> acrList = [SELECT AccountId, ContactId, Roles, Contact.Email FROM AccountContactRelation];
        EmailTemplate et = [SELECT Id,HtmlValue,Body from EmailTemplate WHERE DeveloperName = 'QI_Due_Date'];
        reminderService.sendReminders(acrList,et);
        System.assertEquals(1 , Limits.getEmailInvocations());
        Test.stopTest();
    }

    @isTest
    static void testAccountDataForDueDt(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<AccountContactRelation> acrList = [SELECT AccountId, ContactId, Roles, Contact.Email FROM AccountContactRelation];
        EmailTemplate et = [SELECT Id,HtmlValue,Body from EmailTemplate WHERE DeveloperName = 'QI_Due_Date'];
        List<Reporting_Period__c> repPd = [SELECT End_Date__c,Reporting_Period_Short__c,Start_Date__c,QI_Submission_Due_Dt__c FROM Reporting_Period__c];
        reminderService.prepareAccountDataForOrgRole(acrList,repPd,et);
        System.assertEquals(1 , Limits.getEmailInvocations());
        Test.stopTest();
    }

    @isTest
    static void testServiceDataForDueDt(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<AccountContactRelation> acrList = [SELECT AccountId, ContactId, Roles, Contact.Email FROM AccountContactRelation];
        EmailTemplate et = [SELECT Id,HtmlValue,Body from EmailTemplate WHERE DeveloperName = 'QI_Due_Date'];
        List<Reporting_Period__c> repPd = [SELECT Reporting_Period_Short__c,End_Date__c,Start_Date__c,QI_Submission_Due_Dt__c FROM Reporting_Period__c];
        reminderService.prepareContactDataForServiceRole(acrList,repPd,et);
        Test.stopTest();
    }

    @isTest
    static void testAccountData(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<AccountContactRelation> acrList = [SELECT AccountId, ContactId, Roles, Contact.Email FROM AccountContactRelation];
        EmailTemplate et = [SELECT Id,HtmlValue,Body from EmailTemplate WHERE DeveloperName = 'QI_Due_Date'];
        List<Reporting_Period__c> repPd = [SELECT Reporting_Period_Short__c,End_Date__c,Start_Date__c,QI_Submission_Due_Dt__c FROM Reporting_Period__c];
        reminderService.prepareAccountData(acrList,repPd,et,'submitQI');
        System.assertEquals(1 , Limits.getEmailInvocations());
        Test.stopTest();
    }

    @isTest
    static void testContactData(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<AccountContactRelation> acrList = [SELECT AccountId, ContactId, Roles, Contact.Email FROM AccountContactRelation];
        EmailTemplate et = [SELECT Id,HtmlValue,Body from EmailTemplate WHERE DeveloperName = 'QI_Due_Date'];
        List<Reporting_Period__c> repPd = [SELECT Reporting_Period_Short__c,End_Date__c,Start_Date__c,QI_Submission_Due_Dt__c FROM Reporting_Period__c];
        reminderService.prepareContactData(acrList,repPd,et,'submitQI');
        Test.stopTest();
    }

    @isTest
    static void testfetchDueTemplate(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<EmailTemplate> etList = reminderService.fetchDueTemplate();
        System.assertEquals(2,etList.size());
        Test.stopTest();
    }

    @isTest
    static void fetchQISubmitTemplate(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<EmailTemplate> etList = reminderService.fetchQISubmitTemplate();
        System.assertEquals(2,etList.size());
        Test.stopTest();
    }

    @isTest
    static void fetchOverdueTemplate(){
        Test.startTest();
        QIRemindersService reminderService = new QIRemindersService();
        List<EmailTemplate> etList = reminderService.fetchOverdueTemplate();
        System.assertEquals(2,etList.size());
        Test.stopTest();
    }
}