force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull from Reporting Perion Object.</description>
    <label>Reporting Period ID</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/Quality_Indicator_Details__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Details</label>
    <nameField>
        <label>Quality Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quality Indicator Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/Amended_after_Completion__c.field-meta.xml
<CustomField>
    <fullName>Amended_after_Completion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amended after Completion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/QI_Summary_Id__c.field-meta.xml
<CustomField>
    <fullName>QI_Summary_Id__c</fullName>
    <description>Master detail relation to Quality Indicator Summary.</description>
    <label>QI Parent Id</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Quality Indicator Details (QI Parent Id)</relationshipLabel>
    <relationshipName>Quality_Indicators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Late Completion</fullName>
                <isActive>false</isActive>
                <label>Late Completion</label>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <isActive>false</isActive>
                <label>Updated After Due Date</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Quality_Indicator_Details__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Details</label>
    <referenceTo>Quality_Indicator_Details__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Requested_by__c.field-meta.xml
<CustomField>
    <fullName>Requested_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Late Submission</fullName>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <label>Submitted - Updated After Due Date</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary_Version__c/Quality_Indicator_Summary_Version__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary Version</label>
    <nameField>
        <displayFormat>QISV-{0000}</displayFormat>
        <label>Quality Indicator Summary Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary_Version__c/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <description>Used to maintain a link to current (parent) Quality Indicator Summary record.</description>
    <inlineHelpText>Link to current (parent) Quality Indicator Summary record.</inlineHelpText>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary Versions</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary_Version__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary Version</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary_Version</relationshipName>
    <type>Lookup</type>
</CustomField> 

force-app/main/default/objects/Quality_Indicator_Summary_Version__c/fields/Requested_by__c.field-meta.xml
<CustomField>
    <fullName>Requested_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quality Indicator Summary Version</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary_Version</relationshipName>
    <type>Lookup</type>
</CustomField> 

force-app/main/default/objects/Quality_Indicator_Summary_Version__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Late Submission</fullName>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <label>Submitted - Updated After Due Date</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SRQISubmissionControllerTest.cls
/**
 * author: Yifei Pei
 * date: 10/03/2023
 * description: Test Class for SRQISubmissionController
 **/
@isTest
private with sharing class SRQISubmissionControllerTest {
    private static final String STATUS_COMPLETE = 'Completed';
    private static final String STATUS_NOT_STARTED = 'Not Started';
    private static final String STATUS_PROGRESS = 'In Progress';
    @TestSetup
    static void dataSetup() {
        Integer recordCount = 2;
        User testUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(testUser) {
            Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod('Quarter');
            insert rPeriod;
            List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
            insert providers;
            List<Contact> contacts = TestDataFactory.createContact(recordCount, providers);
            insert contacts;
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
            insert services;
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(
                recordCount,
                services,
                providers
            );
            insert serviceAccountRecords;
            List<Quality_Indicator_Summary__c> qisRecords = TestDataFactory.createQISummaryRecords(
                recordCount,
                providers,
                rPeriod,
                services,
                serviceAccountRecords
            );
            for (Integer i = 0; i < qisRecords.size(); i++) {
                qisRecords[i].Requested_by__c = contacts[i].Id;
            }
            insert qisRecords;
            List<Quality_Indicator_Summary__c> qisWithQIDs = new List<Quality_Indicator_Summary__c>();
            qisWithQIDs.add(qisRecords[0]);
            List<Quality_Indicator_Details__c> qidRecords = TestDataFactory.createQIDetailRecords(11, qisWithQIDs);
            Set<Id> allQIDRTIds = QIDynamicManagementController.getQIDRecordTypes();
            List<Id> allQIDRTIdList = new List<Id>();
            allQIDRTIdList.addAll(allQIDRTIds);
            for (Integer i = 0; i < qidRecords.size(); i++) {
                qidRecords[i].RecordTypeId = allQIDRTIdList[i];
            }
            insert qidRecords;
        }
        Test.stopTest();
    }
    @isTest
    static void testSubCtrl() {
        List<Quality_Indicator_Summary__c> allQISList = [SELECT Id FROM Quality_Indicator_Summary__c];
        List<Quality_Indicator_Details__c> allQIDList = [
            SELECT Id, Amended_after_Completion__c, QI_Summary_Id__c, Status__c
            FROM Quality_Indicator_Details__c
        ];
        List<Reporting_Period__c> allReportingPeriods = [
            SELECT Id, Start_Date__c, End_Date__c, QI_Submission_Due_Dt__c
            FROM Reporting_Period__c
        ];
        // assumption: all qid records have the same QI_Summary_Id__c
        Id qisIdwithQIDs = allQIDList[0].QI_Summary_Id__c;
        Quality_Indicator_Summary__c qisWithQIDs = new Quality_Indicator_Summary__c();
        Quality_Indicator_Summary__c qisWithoutQIDs = new Quality_Indicator_Summary__c();
        for (Quality_Indicator_Summary__c qisRecord : allQISList) {
            if (qisRecord.Id != qisIdwithQIDs) {
                qisWithoutQIDs = qisRecord;
            } else {
                qisWithQIDs = qisRecord;
            }
        }
        String ctrlResponse = '';
        String successResponse = '';
        Boolean isSubmitted = false;
        Test.startTest();

        Exception capturedException;
        try {
            ctrlResponse = SRQISubmissionController.getDomainInfo(qisWithoutQIDs.Id);
        } catch (Exception e) {
            capturedException = e;
        }

        /*ctrlResponse = SRQISubmissionController.getDomainInfo(qisIdwithQIDs);
        SRQISubmissionController.DomainInfo allUncompleted = (SRQISubmissionController.DomainInfo) JSON.deserializeStrict(
            ctrlResponse,
            SRQISubmissionController.DomainInfo.class
        );
        System.assertEquals(11, allUncompleted.uncompletedDomains.size(), 'SRQISubmissionControllerTest Case 1 assertion failed');
        isSubmitted = SRQISubmissionController.isSubmitted(qisIdwithQIDs);
        System.assertEquals(false, isSubmitted, 'SRQISubmissionControllerTest Case 1.1 assertion failed');

        for (Quality_Indicator_Details__c qidRecord : allQIDList) {
            qidRecord.Status__c = STATUS_COMPLETE;
        }
        update allQIDList;
        ctrlResponse = SRQISubmissionController.getDomainInfo(qisIdwithQIDs);
        SRQISubmissionController.DomainInfo allCompleted = (SRQISubmissionController.DomainInfo) JSON.deserializeStrict(
            ctrlResponse,
            SRQISubmissionController.DomainInfo.class
        );
        System.assertEquals(11, allCompleted.completedDomains.size(), 'SRQISubmissionControllerTest Case 2 assertion failed');
        ctrlResponse = SRQISubmissionController.submitRecord(qisIdwithQIDs, false);
        successResponse = (String) JSON.deserializeUntyped(ctrlResponse);
        System.assertEquals('Success', successResponse, 'SRQISubmissionControllerTest Case 3 assertion failed');*/

        /*Quality_Indicator_Summary_Version__c qisvRecord = [
            SELECT Id, LastModifiedDate, LastModifiedBy.Name, Quality_Indicator_Summary__c, Status__c, Version__c
            FROM Quality_Indicator_Summary_Version__c
            WHERE Quality_Indicator_Summary__c = :qisIdwithQIDs
            LIMIT 1
        ];
        qisvRecord.Status__c = STATUS_PROGRESS;
        update qisvRecord;
        ctrlResponse = SRQISubmissionController.submitVersionRecord(qisvRecord.Id, false);
        successResponse = (String) JSON.deserializeUntyped(ctrlResponse);
        System.assertEquals('Success', successResponse, 'SRQISubmissionControllerTest Case 8 assertion failed');*/

        /*ctrlResponse = SRQISubmissionController.getDomainInfo(qisIdwithQIDs);
        SRQISubmissionController.DomainInfo afterSubmission = (SRQISubmissionController.DomainInfo) JSON.deserializeStrict(
            ctrlResponse,
            SRQISubmissionController.DomainInfo.class
        );
        System.assertEquals(true, afterSubmission.isCompleted, 'SRQISubmissionControllerTest Case 4 assertion failed');
        isSubmitted = SRQISubmissionController.isSubmitted(qisIdwithQIDs);
        System.assertEquals(true, isSubmitted, 'SRQISubmissionControllerTest Case 4.1 assertion failed');

        try {
            ctrlResponse = SRQISubmissionController.submitRecord('abc', false);
        } catch (Exception e) {
            capturedException = e;
        }
        try {
            isSubmitted = SRQISubmissionController.isSubmitted('abc');
        } catch (Exception e) {
            capturedException = e;
        }

        allQIDList[1].Amended_after_Completion__c = true;
        update allQIDList[1];
        for (Reporting_Period__c reportingPeriod : allReportingPeriods) {
            reportingPeriod.QI_Submission_Due_Dt__c = (System.today() + 24).addMonths(-2);
        }
        update allReportingPeriods;
        ctrlResponse = SRQISubmissionController.getDomainInfo(qisIdwithQIDs);
        SRQISubmissionController.DomainInfo amendedSub = (SRQISubmissionController.DomainInfo) JSON.deserializeStrict(
            ctrlResponse,
            SRQISubmissionController.DomainInfo.class
        );
        System.assertEquals(true, amendedSub.isAmended, 'SRQISubmissionControllerTest Case 5 assertion failed');
        isSubmitted = SRQISubmissionController.isSubmitted(qisIdwithQIDs);
        System.assertEquals(false, isSubmitted, 'SRQISubmissionControllerTest Case 5.1 assertion failed');
        ctrlResponse = SRQISubmissionController.submitRecord(qisIdwithQIDs, false);
        successResponse = (String) JSON.deserializeUntyped(ctrlResponse);
        System.assertEquals('Success', successResponse, 'SRQISubmissionControllerTest Case 6 assertion failed');
        ctrlResponse = SRQISubmissionController.submitRecord(qisIdwithQIDs, true);
        successResponse = (String) JSON.deserializeUntyped(ctrlResponse);
        System.assertEquals('Success', successResponse, 'SRQISubmissionControllerTest Case 7 assertion failed');

        qisWithQIDs.Status__c = STATUS_NOT_STARTED;
        update qisWithQIDs;
        delete allQIDList[allQIDList.size() - 1];
        try {
            ctrlResponse = SRQISubmissionController.getDomainInfo(qisIdwithQIDs);
        } catch (Exception e) {
            capturedException = e;
        }*/

        Test.stopTest();
    }
}