force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/Quality_Indicator_Details__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Details</label>
    <nameField>
        <label>Quality Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quality Indicator Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Please do not include names or information that might identify an individual</description>
    <inlineHelpText>Please do not include names or information that might identify an individual</inlineHelpText>
    <label>Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <inlineHelpText>The date QI Detail record was marked as &quot;Completed&quot;</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/No_CR_Assessed__c.field-meta.xml
<CustomField>
    <fullName>No_CR_Assessed__c</fullName>
    <description>Number of care recipients assessed</description>
    <inlineHelpText>Number of care recipients assessed for selected QI.</inlineHelpText>
    <label>No. Care Recipients assessed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Late Completion</fullName>
                <isActive>false</isActive>
                <label>Late Completion</label>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <isActive>false</isActive>
                <label>Updated After Due Date</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Falls_and_Major_Injury.recordType-meta.xml
<RecordType>
    <fullName>Falls_and_Major_Injury</fullName>
    <active>true</active>
    <label>Falls and Major Injury</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Medication_Management.recordType-meta.xml
<RecordType>
    <fullName>Medication_Management</fullName>
    <active>true</active>
    <label>Medication Management</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Physical_Restraint.recordType-meta.xml
<RecordType>
    <fullName>Physical_Restraint</fullName>
    <active>true</active>
    <label>Physical Restraint</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Pressure_Injuries.recordType-meta.xml
<RecordType>
    <fullName>Pressure_Injuries</fullName>
    <active>true</active>
    <label>Pressure Injuries</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Unplanned_Weight_Loss.recordType-meta.xml
<RecordType>
    <fullName>Unplanned_Weight_Loss</fullName>
    <active>true</active>
    <label>Unplanned Weight Loss</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Settings__mdt/Quality_Indicator_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Quality Indicator Settings</label>
    <pluralLabel>Quality Indicator Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Settings__mdt/fields/Integer_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Integer_Error_Message__c</fullName>
    <description>Error message displayed when number is &lt; lower limit and &gt; upper limit</description>
    <label>Integer Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Settings__mdt/fields/Integer_Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Integer_Lower_Limit__c</fullName>
    <label>Integer Lower Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Settings__mdt/fields/Integer_Upper_Limit__c.field-meta.xml
<CustomField>
    <fullName>Integer_Upper_Limit__c</fullName>
    <label>Integer Upper Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/No_CR_Assessed__c.field-meta.xml
<CustomField>
    <fullName>No_CR_Assessed__c</fullName>
    <label>No CR Assessed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Quality_Indicator_Details__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Details</label>
    <referenceTo>Quality_Indicator_Details__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Late Submission</fullName>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <label>Submitted - Updated After Due Date</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Falls_and_Major_injury.recordType-meta.xml
<RecordType>
    <fullName>Falls_and_Major_injury</fullName>
    <active>false</active>
    <label>Falls and Major injury</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Medication_management.recordType-meta.xml
<RecordType>
    <fullName>Medication_management</fullName>
    <active>false</active>
    <label>Medication management</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Physical_restraint.recordType-meta.xml
<RecordType>
    <fullName>Physical_restraint</fullName>
    <active>false</active>
    <label>Physical restraint</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Pressure_injuries.recordType-meta.xml
<RecordType>
    <fullName>Pressure_injuries</fullName>
    <active>false</active>
    <label>Pressure injuries</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Unplanned_weight_loss.recordType-meta.xml
<RecordType>
    <fullName>Unplanned_weight_loss</fullName>
    <active>false</active>
    <label>Unplanned weight loss</label>
</RecordType>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QualityIndicatorValidationUtilTest.cls
/****************************************************************************************************
 * @CreatedBy   : Daniel Clift
 * @CreatedDate : 01/02/2023
 * @Description : Test class for QualityIndicatorValidationUtil
 *****************************************************************************************************/
@isTest
public with sharing class QualityIndicatorValidationUtilTest {
  private static final string NO_ERROR_STRING = 'Expected to receive an exception.';

  @TestSetup
  static void dataSetup() {
    Integer recordCount = 2;
    User testUser = TestDataFactory.createSystemAdminUser();

    System.runAs(testUser) {
      // reporting period
      Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod(
        'Quarter'
      );
      rPeriod.Start_Date__c = (System.today() + 12).addMonths(-6);
      rPeriod.End_Date__c = (System.today() + 24).addMonths(-3);
      insert rPeriod;
      // get providers
      List<Account> providers = TestDataFactory.createProviderRecords(
        recordCount
      );
      insert providers;
      // get services
      List<BusinessLicense> services = TestDataFactory.createServiceRecords(
        recordCount
      );
      insert services;
      // get service account relationships
      List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(
        recordCount,
        services,
        providers
      );
      insert serviceAccountRecords;
      // get quality indicator summary
      List<Quality_Indicator_Summary__c> qisRecords = TestDataFactory.createQISummaryRecords(
        recordCount,
        providers,
        rPeriod,
        services,
        serviceAccountRecords
      );
      insert qisRecords;
      // get quality indicator detail
      List<Quality_Indicator_Details__c> qidRecords = TestDataFactory.createQIDetailRecords(
        10,
        qisRecords
      );
      // Pressure_Injuries or Pressure_Injury
      List<String> recordTypes = new List<String>{
        'Pressure_Injuries',
        'Physical_Restraint',
        'Unplanned_Weight_Loss',
        'Falls_and_Major_Injury',
        'Medication_Management'
      };
      for (Integer i = 0; i < qidRecords.size(); i++) {
        if (i < 5) {
          String recordId = Schema.SObjectType.Quality_Indicator_Details__c.getRecordTypeInfosByDeveloperName()
            .get(recordTypes[i])
            .getRecordTypeId();
          qidRecords[i].RecordTypeId = recordId;
        } else {
          Integer k = i - 5;
          String recordId = Schema.SObjectType.Quality_Indicator_Details__c.getRecordTypeInfosByDeveloperName()
            .get(recordTypes[k])
            .getRecordTypeId();
          qidRecords[i].RecordTypeId = recordId;
        }
      }
      // test on trigger for completion date
      qidRecords[3].Status__c = 'Completed';
      insert qidRecords;
    }
  }
  @isTest
  public static void testCharacterLimit() {
    Quality_Indicator_Details__c qid = [
      SELECT Id
      FROM Quality_Indicator_Details__c
      LIMIT 1
    ];
    qid.Comments__c = generateRandomString(1001);

    Test.startTest();
    try {
      update qid;
      System.assert(false, NO_ERROR_STRING);
    } catch (Exception e) {
      System.assert(e.getMessage().contains('STRING_TOO_LONG'));
    }
    Test.stopTest();
  }

  @isTest
  public static void testLowerIntegerLimit() {
    Quality_Indicator_Settings__mdt qiMetaData = Quality_Indicator_Settings__mdt.getInstance(
      'Quality_Indicator_Detail_Error_Metadata'
    );

    Quality_Indicator_Details__c qid = [
      SELECT Id
      FROM Quality_Indicator_Details__c
      LIMIT 1
    ];

    qid.No_CR_Assessed__c = qiMetaData.Integer_Lower_Limit__c - 1;

    Test.startTest();
    try {
      update qid;
      System.assert(false, NO_ERROR_STRING);
    } catch (Exception e) {
      System.assert(
        e.getMessage().contains(qiMetaData.Integer_Error_Message__c)
      );
    }
    Test.stopTest();
  }

  @isTest
  public static void testUpperIntegerLimit() {
    Quality_Indicator_Settings__mdt qiMetaData = Quality_Indicator_Settings__mdt.getInstance(
      'Quality_Indicator_Detail_Error_Metadata'
    );

    Quality_Indicator_Details__c qid = [
      SELECT Id
      FROM Quality_Indicator_Details__c
      LIMIT 1
    ];

    qid.No_CR_Assessed__c = qiMetaData.Integer_Upper_Limit__c + 1;

    Test.startTest();
    try {
      update qid;
      System.assert(false, NO_ERROR_STRING);
    } catch (Exception e) {
      System.assert(
        e.getMessage().contains(qiMetaData.Integer_Error_Message__c)
      );
    }
    Test.stopTest();
  }

  @isTest
  public static void testUpdateField() {
    Quality_Indicator_Details__c qid = [
      SELECT Id, Status__c, Completion_Date__c
      FROM Quality_Indicator_Details__c
      LIMIT 1
    ];
    Test.startTest();
    qid.Status__c = 'Completed';
    update qid;
    qid = [
      SELECT Id, Status__c, Completion_Date__c
      FROM Quality_Indicator_Details__c
      WHERE Status__c = 'Completed'
      LIMIT 1
    ];
    System.assertEquals(date.today(), qid.Completion_Date__c);
    qid.Status__c = 'Not Started';
    update qid;
    Test.stopTest();
  }

  private static String generateRandomString(Integer len) {
    final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
    String randStr = '';
    while (randStr.length() < len) {
      Integer idx = Math.mod(
        Math.abs(Crypto.getRandomInteger()),
        chars.length()
      );
      randStr += chars.substring(idx, idx + 1);
    }
    return randStr;
  }

  @isTest static void testGetValidationErrorSetting() {
    Test.startTest();
    QualityIndicatorValidationUtil.ValidationSettingWrapper setting = QualityIndicatorValidationUtil.getValidationErrorSetting();
    Test.stopTest();

    Assert.isNotNull(setting.maxChar);
    Assert.isNotNull(setting.charError);
    Assert.isNotNull(setting.maxNumber);
    Assert.isNotNull(setting.minNumber);
    Assert.isNotNull(setting.numberError);
  }

  @isTest static void testGetValidationSettingsMap() {
    List<String> metadataNames = new List<String>{
      'QID_Warning_Recipients_Assessed_ADL',
      'QID_Warning_Recipients_Assessed_FMI'
    };

    Test.startTest();
    Map<String,QualityIndicatorValidationUtil.ValidationSettingWrapper> settingsMap = QualityIndicatorValidationUtil.getValidationSettingsMap(metadataNames);
    Test.stopTest();

    Assert.areEqual(2, settingsMap.size());
    Assert.isTrue(settingsMap.containsKey(metadataNames[0]));
    Assert.isNotNull(settingsMap.get(metadataNames[0]));
    Assert.isTrue(settingsMap.containsKey(metadataNames[1]));
    Assert.isNotNull(settingsMap.get(metadataNames[1]));
  }
}