force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/National_Statistic__c.object-meta.xml
<CustomObject>
    <label>National Statistic</label>
    <nameField>
        <displayFormat>NS-{00000}</displayFormat>
        <label>National Statistic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Statistics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_falls__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_falls__c</fullName>
    <label>National percentage falls</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_Percentage_falls_Major_Injury__c.field-meta.xml
<CustomField>
    <fullName>National_Percentage_falls_Major_Injury__c</fullName>
    <label>National Percentage falls Major Injury</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Deep_Tissue__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Deep_Tissue__c</fullName>
    <label>National percentage PI Deep Tissue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Stage2__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Stage2__c</fullName>
    <label>National percentage PI Stage2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Stage3__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Stage3__c</fullName>
    <label>National percentage PI Stage3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Stage4__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Stage4__c</fullName>
    <label>National percentage PI Stage4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Unstageable__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Unstageable__c</fullName>
    <label>National percentage PI Unstageable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_significant_UWL__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_significant_UWL__c</fullName>
    <description>National Percentage significant unplanned weight loss</description>
    <label>National percentage significant UWL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>National Statistics</relationshipLabel>
    <relationshipName>National_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/National_Statistic__c.field-meta.xml
<CustomField>
    <fullName>National_Statistic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Statistic</label>
    <referenceTo>National_Statistic__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_APSY__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_APSY__c</fullName>
    <label>QI Observed APSY</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_FALLS__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_FALLS__c</fullName>
    <label>QI Observed FALLS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_Falls_MI__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_Falls_MI__c</fullName>
    <label>QI Observed Falls MI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_Physical_Restraint__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_Physical_Restraint__c</fullName>
    <label>QI Observed Physical Restraint</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_PI_S2__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_PI_S2__c</fullName>
    <label>QI Observed PI S2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_PI_S3__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_PI_S3__c</fullName>
    <label>QI Observed PI S3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_PI_S4__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_PI_S4__c</fullName>
    <label>QI Observed PI S4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_PI_SDT__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_PI_SDT__c</fullName>
    <label>QI Observed PI SDT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_PI_unstageable__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_PI_unstageable__c</fullName>
    <label>QI Observed PI unstageable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_Polypharmacy__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_Polypharmacy__c</fullName>
    <label>QI Observed Polypharmacy</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Observed_WL_SIG__c.field-meta.xml
<CustomField>
    <fullName>QI_Observed_WL_SIG__c</fullName>
    <label>QI Observed WL SIG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Predicted_FALLS__c.field-meta.xml
<CustomField>
    <fullName>QI_Predicted_FALLS__c</fullName>
    <label>QI Predicted FALLS</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Predicted_FALLS_MI__c.field-meta.xml
<CustomField>
    <fullName>QI_Predicted_FALLS_MI__c</fullName>
    <label>QI Predicted FALLS MI</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Predicted_PI_S2__c.field-meta.xml
<CustomField>
    <fullName>QI_Predicted_PI_S2__c</fullName>
    <label>QI Predicted PI S2</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Predicted_PI_S3__c.field-meta.xml
<CustomField>
    <fullName>QI_Predicted_PI_S3__c</fullName>
    <label>QI Predicted PI S3</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Predicted_PI_S4__c.field-meta.xml
<CustomField>
    <fullName>QI_Predicted_PI_S4__c</fullName>
    <label>QI Predicted PI S4</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/QI_Predicted_WL_SIG__c.field-meta.xml
<CustomField>
    <fullName>QI_Predicted_WL_SIG__c</fullName>
    <label>QI Predicted WL SIG</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Risk_Adjusted_DT_PI__c.field-meta.xml
<CustomField>
    <fullName>Risk_Adjusted_DT_PI__c</fullName>
    <description>Risk Adjusted Suspected deep tissue injuries</description>
    <label>Risk Adjusted DT PI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Risk_Adjusted_PI_Level2__c.field-meta.xml
<CustomField>
    <fullName>Risk_Adjusted_PI_Level2__c</fullName>
    <description>Risk Adjusted Pressure Injuries Level 2</description>
    <label>Risk Adjusted PI Level2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Risk_Adjusted_PI_Level3__c.field-meta.xml
<CustomField>
    <fullName>Risk_Adjusted_PI_Level3__c</fullName>
    <description>Risk Adjusted Pressure injuries Level 3</description>
    <label>Risk Adjusted PI Level3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Risk_Adjusted_Unstageable_PI__c.field-meta.xml
<CustomField>
    <fullName>Risk_Adjusted_Unstageable_PI__c</fullName>
    <description>Risk Adjusted Unstageable pressure injury</description>
    <label>Risk Adjusted Unstageable PI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RiskAdjustedCalculatorTest.cls
/**
* author: Sharevreet Singh
* date: 14/10/2022
* description: Test class for RiskAdjustedCalculator.
**/ 
@IsTest
public with sharing class RiskAdjustedCalculatorTest {
    @TestSetup
    static void makeData(){
        Integer recordCount = 1;
        User testUser = TestDataFactory.createSystemAdminUser();

		Test.startTest();
		System.runAs(testUser){
            // reporting period
            Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod('Quarter');
            rPeriod.Start_Date__c = (System.today() + 12 ).addMonths(-6);
            rPeriod.End_Date__c = (System.today() + 24).addMonths(-3);
            insert rPeriod;
            // get providers
            List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
            insert providers;
            // get services
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
            insert services;
            // get service account relationships
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(recordCount, services, providers);
            insert serviceAccountRecords;
            // get quality indicator summary
            List<Quality_Indicator_Summary__c> qisRecords = TestDataFactory.createQISummaryRecords(recordCount, providers, rPeriod, services, serviceAccountRecords);
            qisRecords[0].QI_Observed_PI_S2__c = 5;
            qisRecords[0].QI_Observed_PI_S3__c = 5;
            qisRecords[0].QI_Observed_PI_S4__c = 5;
            qisRecords[0].QI_Observed_WL_SIG__c = 10;
            qisRecords[0].QI_Observed_FALLS__c = 15;
            qisRecords[0].QI_Observed_Falls_MI__c = 20;
            qisRecords[0].QI_Observed_PI_unstageable__c = 20;
            qisRecords[0].QI_Observed_PI_SDT__c = 20;

            qisRecords[0].QI_Predicted_PI_S2__c = 10;
            qisRecords[0].QI_Predicted_PI_S3__c = 10;
            qisRecords[0].QI_Predicted_PI_S4__c = 10;
            qisRecords[0].QI_Predicted_WL_SIG__c = 15;
            qisRecords[0].QI_Predicted_FALLS__c = 20;
            qisRecords[0].QI_Predicted_FALLS_MI__c = 25;
            qisRecords[0].QI_Observed_Polypharmacy__c = 4;
            qisRecords[0].QI_Observed_Physical_Restraint__c = 4;
            qisRecords[0].QI_Observed_APSY__c = 4;
            insert qisRecords;

            //Create and calculate National_Statistic__c
            NationalStatistics.calcNationalAverage(qisRecords);
        }
        Test.stopTest();
    }

    @IsTest
    static void  calculateRiskAdjustedTest() {
        National_Statistic__c nsRecord = [SELECT National_percentage_PI_Stage2__c, National_percentage_PI_Stage3__c, National_percentage_PI_Stage4__c, National_percentage_significant_UWL__c, National_percentage_falls__c, National_Percentage_falls_Major_Injury__c,
                                            National_percentage_PI_Deep_Tissue__c, National_percentage_PI_Unstageable__c
                                            FROM National_Statistic__c 
                                            LIMIT 1];
        Quality_Indicator_Summary__c qiRecord = [SELECT QI_Observed_PI_S2__c, QI_Observed_PI_S3__c, QI_Observed_PI_S4__c, QI_Observed_WL_SIG__c, QI_Observed_FALLS__c, QI_Observed_Falls_MI__c,
                                                    QI_Predicted_PI_S2__c, QI_Predicted_PI_S3__c, QI_Predicted_PI_S4__c, QI_Predicted_WL_SIG__c, QI_Predicted_FALLS__c, QI_Predicted_FALLS_MI__c, 
                                                    QI_Observed_PI_unstageable__c, QI_Observed_PI_SDT__c, Risk_Adjusted_DT_PI__c, Risk_Adjusted_Unstageable_PI__c,
                                                    Risk_Adjusted_PI_Level2__c, Risk_Adjusted_PI_Level3__c, Risk_Adjusted_PI_Level4__c, Risk_Adjusted_SUWL__c, Risk_Adjusted_Falls_with_injury__c, Risk_Adjusted_Falls_with_Major_injury__c
                                                    FROM Quality_Indicator_Summary__c 
                                                    LIMIT 1];
        System.assertEquals(null, qiRecord.Risk_Adjusted_PI_Level2__c, 'The field should be null');

        RiskAdjustedCalculator raCal = new RiskAdjustedCalculator(qiRecord, nsRecord);
        qiRecord = raCal.calculateRiskAdjusted();
        
        System.assertNotEquals(null, qiRecord.Risk_Adjusted_PI_Level2__c, 'The field should not be null');

        qiRecord.QI_Observed_PI_S2__c = null;
        update qiRecord;

        raCal = new RiskAdjustedCalculator(qiRecord, nsRecord);
        qiRecord = raCal.calculateRiskAdjusted();

        System.assertEquals(null, qiRecord.Risk_Adjusted_PI_Level2__c, 'The field should be null if QI_Observed_PI_S2__c is null');
    }
}