force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/Care_Minutes_Summary__c.object-meta.xml
<CustomObject>
    <label>Care Minutes Summary</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Care Minutes Summary Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Minutes Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Minutes Summary</relationshipLabel>
    <relationshipName>Care_Minutes_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Care Minutes Summary</relationshipLabel>
    <relationshipName>Care_Minutes_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Care Minutes Summary</relationshipLabel>
    <relationshipName>Care_Minutes_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Service Compliance Histories</relationshipLabel>
    <relationshipName>Service_Compliance_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/SRQI_CER__c.object-meta.xml
<CustomObject>
    <label>Consumer Experience Report</label>
    <nameField>
        <displayFormat>CER-{000000}</displayFormat>
        <label>Consumer Experience Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Experience Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_CER__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Care_Minutes_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Minutes_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Minutes</label>
    <referenceTo>Care_Minutes_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Consumer_Experience_Id__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Experience_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer Experience Report</label>
    <referenceTo>SRQI_CER__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Quality_Indicator_Id__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Compliance_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Compliance</label>
    <referenceTo>Service_Compliance_History__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RatingsStatusHelperTest.cls
/**
* author: Daniel Clift
* date: 14/10/2022
* description: test class for RatingsStatusHelper
**/

@isTest
public with sharing class RatingsStatusHelperTest {

    @TestSetup
    public static void dataSetup(){

        Integer recordCount = 20;
        User testUser = TestDataFactory.createSystemAdminUser();

		Test.startTest();
		System.runAs(testUser){
            // get reporting period
            Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod('Quarter');
            insert rPeriod;
            // get providers
            List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
            insert providers;
            // get services
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
            insert services;
            // get service account relationships
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(recordCount, services, providers);
            insert serviceAccountRecords;
            // get Service Compliance History
            List<Service_Compliance_History__c> schRecords = TestDataFactory.createServiceComplianceHistory(recordCount);
            insert schRecords;
            // get quality indicator summary
            List<Quality_Indicator_Summary__c> qisRecords = TestDataFactory.createQISummaryRecords(recordCount, providers, rPeriod, services, serviceAccountRecords);
            insert qisRecords;
            // get consumer experience reports
            List<SRQI_CER__c> cerRecords = TestDataFactory.createCERRecords(recordCount, serviceAccountRecords, providers, services, rPeriod);
            insert cerRecords;
            // get care minutes summary
            List<Care_Minutes_Summary__c> cmsRecords = TestDataFactory.createCareMinuteSummary(recordCount, services);
            for(Integer i = 0; i < recordCount; i++){
                cmsRecords[i].Provider_Name__c = providers[i].Id;
                cmsRecords[i].Service_Account__c = serviceAccountRecords[i].Id;
            }
            insert cmsRecords;
            // get star rating history records
            List<STAR_Rating_History__c> srhRecords = TestDataFactory.createStarRatingHistoryRecords(recordCount, services, providers, rPeriod);
            for(Integer i = 0; i < srhRecords.size(); i++) {
                srhRecords[i].Care_Minutes_Id__c = cmsRecords[i].Id;
                srhRecords[i].Service_Compliance_Id__c = schRecords[i].Id;
                srhRecords[i].Quality_Indicator_Id__c = qisRecords[i].Id;
                srhRecords[i].Consumer_Experience_Id__c = cerRecords[i].Id;
                // srhRecords[i].Rating_Type__c = math.mod(i,2) == 0 ? 'New Rating' : 'Current Rating';
                srhRecords[i].Rating_Type__c = 'New Rating';
                srhRecords[i].Status__c = 'Published';
            }
            insert srhRecords;
        }
        Test.stopTest();
    }

    @isTest
    public static void testUpdateSubRatingRecords() {

        Map<String, Map<Id, String>> ratingsMap = InitiateRatingsMap();

        List<STAR_Rating_History__c> srhList = [SELECT Id, Care_Minutes_Id__c, Service_Compliance_Id__c, Quality_Indicator_Id__c, Consumer_Experience_Id__c, Rating_Type__c, Status__c FROM STAR_Rating_History__c];

        for(STAR_Rating_History__c srh : srhList) {
            if(srh.Consumer_Experience_Id__c != null) {
                ratingsMap.get('CER').put(srh.Consumer_Experience_Id__c, srh.Status__c);
            }
            if(srh.Care_Minutes_Id__c != null) {
                ratingsMap.get('CM').put(srh.Care_Minutes_Id__c, srh.Status__c);
            }
            if(srh.Quality_Indicator_Id__c != null) {
                ratingsMap.get('QI').put(srh.Quality_Indicator_Id__c, srh.Status__c);
            }
        }
        Test.startTest();
        RatingsStatusHelper.UpdateSubRatingRecords(ratingsMap);
        Test.stopTest();
		// here
        Care_Minutes_Summary__c cm = [SELECT Id, Availability_Status__c, Rating_Type__c FROM Care_Minutes_Summary__c  WHERE Id = :srhList[0].Care_Minutes_Id__c LIMIT 1];
        System.debug('cm: ' + cm);
        String assertMessage = 'Availability_Status__c should be Published';
        System.assertEquals('Published', cm.Availability_Status__c, assertMessage);
    }

    @isTest
    public static void testRatingType() {

        Test.startTest();
        // Service_Compliance_History__c
        List<Service_Compliance_History__c> schList = [SELECT Id, Availability_Status__c, Rating_Type__c, Service__c FROM Service_Compliance_History__c LIMIT 5];
        for(Service_Compliance_History__c sch : schList) {
            sch.Service__c = schList[0].Service__c;
            sch.Rating_Type__c = 'Current Rating';
        }
        update schList;
        Map<Id, Id> schMap = new Map<Id, Id>();
        schMap.put(schList[0].Id, schList[0].Service__c);
        RatingsStatusHelper.UpdateSCRRatingType(schMap);
        
        // Quality_Indicator_Summary__c
        List<Quality_Indicator_Summary__c> qiList = [SELECT Id, Availability_Status__c, Rating_Type__c, Service__c FROM Quality_Indicator_Summary__c LIMIT 5];
        for(Quality_Indicator_Summary__c qi : qiList) {
            qi.Service__c = qiList[0].Service__c;
            qi.Rating_Type__c = 'Current Rating';
        }
        update qiList;
        Map<Id, Id> qiMap = new Map<Id, Id>();
        qiMap.put(qiList[0].Id, qiList[0].Service__c);
        RatingsStatusHelper.UpdateQIRatingType(qiMap);
        
        // SRQI_CER__c
        List<SRQI_CER__c> cerList = [SELECT Id, Availability_Status__c, Rating_Type__c, Service__c FROM SRQI_CER__c LIMIT 5];
        for(SRQI_CER__c cer : cerList) {
            cer.Service__c = cerList[0].Service__c;
            cer.Rating_Type__c = 'Current Rating';
        }
        update cerList;
        Map<Id, Id> cerMap = new Map<Id, Id>();
        cerMap.put(cerList[0].Id, cerList[0].Service__c);
        RatingsStatusHelper.UpdateCERRatingType(cerMap);

        // Care_Minutes_Summary__c
        List<Care_Minutes_Summary__c> cmList = [SELECT Id, Availability_Status__c, Rating_Type__c, Service__c FROM Care_Minutes_Summary__c LIMIT 5];
        for(Care_Minutes_Summary__c cm : cmList) {
            cm.Service__c = cmList[0].Service__c;
            cm.Rating_Type__c = 'Current Rating';
        }
        update cmList;
        Map<Id, Id> cmMap = new Map<Id, Id>();
        cmMap.put(cmList[0].Id, cmList[0].Service__c);
        RatingsStatusHelper.UpdateCMRatingType(cmMap);

        // STAR_Rating_History__c
        List<STAR_Rating_History__c> srhList = [SELECT Id, Status__c, Rating_Type__c, SF_Service_Id__c FROM STAR_Rating_History__c LIMIT 5];
        for(STAR_Rating_History__c srh : srhList) {
            srh.SF_Service_Id__c = srhList[0].SF_Service_Id__c;
            srh.Rating_Type__c = 'Current Rating';
        }
        update srhList;
        Map<Id, Id> srhMap = new Map<Id, Id>();
        cmMap.put(srhList[0].Id, srhList[0].SF_Service_Id__c);
        RatingsStatusHelper.UpdateSRHRatingType(srhMap);
        Test.stopTest();

        Quality_Indicator_Summary__c qiTest = [SELECT Id, Availability_Status__c, Rating_Type__c, Service__c FROM Quality_Indicator_Summary__c WHERE Id = :qiList[1].Id LIMIT 1];
        SRQI_CER__c cerTest = [SELECT Id, Availability_Status__c, Rating_Type__c, Service__c FROM SRQI_CER__c WHERE Id = :cerList[1].Id LIMIT 1];

        String assertMessage = 'Rating_Type__c should be Previous Rating';
        System.assertEquals('Previous Rating', qiTest.Rating_Type__c, assertMessage);
        System.assertEquals('Previous Rating', cerTest.Rating_Type__c, assertMessage);

    }

    public static Map<String, Map<Id, String>> InitiateRatingsMap() {
        Map<String, Map<Id, String>> initiateMap = new Map<String, Map<Id, String>>();
        initiateMap.put('CER', new Map<Id, String>());
        initiateMap.put('CM', new Map<Id, String>());
        // initiateMap.put('SCR', new Map<Id, String>());
        initiateMap.put('QI', new Map<Id, String>());
        return initiateMap;
    }
}