force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/PROVIDER_ID__c.field-meta.xml
<CustomField>
    <fullName>PROVIDER_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Provider Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/SERVICE_ACCOUNT_ID__c.field-meta.xml
<CustomField>
    <fullName>SERVICE_ACCOUNT_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField> 

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Quality_Indicator_Id__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Compliance_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Compliance</label>
    <referenceTo>Service_Compliance_History__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QISummaryTriggerHandlerTest.cls
/**
* author: Daniel Clift
* date: 28/09/2022
* description: Test class for QualityIndicatorSummaryTriggerHandler
**/
@isTest
public with sharing class QISummaryTriggerHandlerTest {
    // Quality_Indicator_Summary__c
    @TestSetup
    public static void dataSetup() {
        Integer recordCount = 20;
        User testUser = TestDataFactory.createSystemAdminUser();

		Test.startTest();
		System.runAs(testUser){
            // get reporting period
            Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod('Quarter');
            insert rPeriod;
            // get providers
            List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
            insert providers;
            // get services
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
            insert services;
            // get service account relationships
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(recordCount, services, providers);
            insert serviceAccountRecords;
            // get quality indicator summary
            List<Quality_Indicator_Summary__c> qisRecords = TestDataFactory.createQISummaryRecords(recordCount, providers, rPeriod, services, serviceAccountRecords);
            insert qisRecords;
            // get service complaince hisotry records
            List<Service_Compliance_History__c> schRecords = TestDataFactory.createServiceComplianceHistory(recordCount);
            insert schRecords;
            // get star rating history records
            List<STAR_Rating_History__c> srhRecords = TestDataFactory.createStarRatingHistoryRecords(recordCount, services, providers, rPeriod);
            for(Integer i = 0; i < srhRecords.size(); i++) {
                srhRecords[i].Quality_Indicator_Id__c = qisRecords[i].Id;
                srhRecords[i].Service_Compliance_Id__c = schRecords[i].Id;
                srhRecords[i].Rating_Type__c = math.mod(i,2) == 0 ? 'New Rating' : 'Current Rating';
            }
            insert srhRecords;
        }
        Test.stopTest();
    }

    @isTest
    public static void testPublishedStatus() {
        List<Quality_Indicator_Summary__c> qisList = [SELECT Id, Name, Availability_Status__c, Rating_Type__c, Service__c FROM Quality_Indicator_Summary__c LIMIT 20];
        System.debug(qisList);
        for(Quality_Indicator_Summary__c qis : qisList) {
            qis.Availability_Status__c = 'Draft';
        }
        update qisList;
        test.startTest();
        for (Quality_Indicator_Summary__c qis : qisList) {
            qis.Availability_Status__c = 'Published';
        }
        update qisList;
        test.stopTest();

        AggregateResult count = [SELECT COUNT(Id) FROM Quality_Indicator_Summary__c WHERE Availability_Status__c = 'Published' GROUP BY Availability_Status__c  LIMIT 20];

        System.assertEquals(20, count.get('expr0'), 'The number of published records is incorrect');
    }

    @isTest
    public static void testLiveStatus() {
        List<Quality_Indicator_Summary__c> qisList = [SELECT Id, Name, Availability_Status__c, Rating_Type__c, Service__c FROM Quality_Indicator_Summary__c LIMIT 20];
        System.debug(qisList);
        for(Quality_Indicator_Summary__c qis : qisList) {
            qis.Availability_Status__c = 'Published';
            qis.Rating_Type__c = 'New Rating';
        }
        update qisList;
        test.startTest();
        for (Quality_Indicator_Summary__c qis : qisList) {
            qis.Availability_Status__c = 'Live';
        }
        update qisList;
        test.stopTest();

        AggregateResult count = [SELECT COUNT(Id) FROM Quality_Indicator_Summary__c WHERE Availability_Status__c = 'LIVE' GROUP BY Availability_Status__c  LIMIT 20];

        System.assertEquals(20, count.get('expr0'), 'The number of live records is incorrect');
    }

    @isTest
    public static void testCurrentRating() {
        Quality_Indicator_Summary__c qisCurrent = [SELECT Id, Name, Availability_Status__c, Rating_Type__c, External_ID__c, Service__c, PROVIDER_ID__c, SERVICE_ACCOUNT_ID__c, REPORTING_PERIOD__c FROM Quality_Indicator_Summary__c LIMIT 1];
        qisCurrent.Availability_Status__c = 'LIVE';
        qisCurrent.Rating_Type__c = 'Current Rating';
        update qisCurrent;

        Quality_Indicator_Summary__c qisNewCurrent = new Quality_Indicator_Summary__c();
        qisNewCurrent.Availability_Status__c = 'Published';
        qisNewCurrent.Rating_Type__c = 'New Rating';
        qisNewCurrent.External_ID__c = 'ExternalId2';
        qisNewCurrent.PROVIDER_ID__c = qisCurrent.PROVIDER_ID__c;
        qisNewCurrent.Service__c = qisCurrent.Service__c;
        qisNewCurrent.SERVICE_ACCOUNT_ID__c = qisCurrent.SERVICE_ACCOUNT_ID__c;
        qisNewCurrent.Reporting_Period__c = qisCurrent.Reporting_Period__c;
        insert qisNewCurrent;

        test.startTest();
        qisNewCurrent.Availability_Status__c = 'LIVE';
        update qisNewCurrent;
        test.stopTest();
    }
}