force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/National_Statistic__c.object-meta.xml
<CustomObject>
    <label>National Statistic</label>
    <nameField>
        <displayFormat>NS-{00000}</displayFormat>
        <label>National Statistic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Statistics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_ADL_DEC__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_ADL_DEC__c</fullName>
    <label>National percentage ADL DEC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_falls__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_falls__c</fullName>
    <label>National percentage falls</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_Percentage_falls_Major_Injury__c.field-meta.xml
<CustomField>
    <fullName>National_Percentage_falls_Major_Injury__c</fullName>
    <label>National Percentage falls Major Injury</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Deep_Tissue__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Deep_Tissue__c</fullName>
    <label>National percentage PI Deep Tissue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Stage1__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Stage1__c</fullName>
    <label>National percentage PI Stage1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Stage2__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Stage2__c</fullName>
    <label>National percentage PI Stage2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Stage3__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Stage3__c</fullName>
    <label>National percentage PI Stage3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Stage4__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Stage4__c</fullName>
    <label>National percentage PI Stage4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PI_Unstageable__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PI_Unstageable__c</fullName>
    <label>National percentage PI Unstageable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_PIs__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_PIs__c</fullName>
    <label>National percentage PIs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/National_percentage_significant_UWL__c.field-meta.xml
<CustomField>
    <fullName>National_percentage_significant_UWL__c</fullName>
    <description>National Percentage significant unplanned weight loss</description>
    <label>National percentage significant UWL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/National_Statistic__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>National Statistics</relationshipLabel>
    <relationshipName>National_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/Quality_Indicator_Details__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Details</label>
    <nameField>
        <label>Quality Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quality Indicator Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Activities_of_daily_living_ADLs.recordType-meta.xml
<RecordType>
    <fullName>Activities_of_daily_living_ADLs</fullName>
    <active>true</active>
    <label>Activities of Daily Living (ADLs)</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Consumer_Experience.recordType-meta.xml
<RecordType>
    <fullName>Consumer_Experience</fullName>
    <active>true</active>
    <label>Consumer Experience</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Continence.recordType-meta.xml
<RecordType>
    <fullName>Continence</fullName>
    <active>true</active>
    <label>Incontinence Care</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Falls_and_Major_Injury.recordType-meta.xml
<RecordType>
    <fullName>Falls_and_Major_Injury</fullName>
    <active>true</active>
    <label>Falls and Major Injury</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Hospitalisation.recordType-meta.xml
<RecordType>
    <fullName>Hospitalisation</fullName>
    <active>true</active>
    <label>Hospitalisation</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Medication_Management.recordType-meta.xml
<RecordType>
    <fullName>Medication_Management</fullName>
    <active>true</active>
    <label>Medication Management</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Physical_Restraint.recordType-meta.xml
<RecordType>
    <fullName>Physical_Restraint</fullName>
    <active>true</active>
    <label>Physical Restraint</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Pressure_Injuries.recordType-meta.xml
<RecordType>
    <fullName>Pressure_Injuries</fullName>
    <active>true</active>
    <label>Pressure Injuries</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Quality_of_life.recordType-meta.xml
<RecordType>
    <fullName>Quality_of_life</fullName>
    <active>true</active>
    <label>Quality of life</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Unplanned_Weight_Loss.recordType-meta.xml
<RecordType>
    <fullName>Unplanned_Weight_Loss</fullName>
    <active>true</active>
    <label>Unplanned Weight Loss</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Workforce.recordType-meta.xml
<RecordType>
    <fullName>Workforce</fullName>
    <active>true</active>
    <label>Workforce</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/National_Statistic__c.field-meta.xml
<CustomField>
    <fullName>National_Statistic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Statistic</label>
    <referenceTo>National_Statistic__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Quality_Indicator_Details__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Details</label>
    <referenceTo>Quality_Indicator_Details__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Falls_and_Major_injury.recordType-meta.xml
<RecordType>
    <fullName>Falls_and_Major_injury</fullName>
    <active>false</active>
    <label>Falls and Major injury</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Medication_management.recordType-meta.xml
<RecordType>
    <fullName>Medication_management</fullName>
    <active>false</active>
    <label>Medication management</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Physical_restraint.recordType-meta.xml
<RecordType>
    <fullName>Physical_restraint</fullName>
    <active>false</active>
    <label>Physical restraint</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Pressure_injuries.recordType-meta.xml
<RecordType>
    <fullName>Pressure_injuries</fullName>
    <active>false</active>
    <label>Pressure injuries</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Unplanned_weight_loss.recordType-meta.xml
<RecordType>
    <fullName>Unplanned_weight_loss</fullName>
    <active>false</active>
    <label>Unplanned weight loss</label>
</RecordType>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QIObservedBatchTest.cls
/**
* author: Daniel Clift
* date: 02/10/2022
* description: Test Class for QIObservedBatch, QIObservedHelper, NationalStatistics
**/
@isTest
public with sharing class QIObservedBatchTest {
    @TestSetup
    static void dataSetup(){
        Integer recordCount = 2;
        User testUser = TestDataFactory.createSystemAdminUser();

		Test.startTest();
		System.runAs(testUser){
            // reporting period
            Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod('Quarter');
            rPeriod.Start_Date__c = (System.today() + 12 ).addMonths(-6);
            rPeriod.End_Date__c = (System.today() + 24).addMonths(-3);
            insert rPeriod;
            // get providers
            List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
            insert providers;
            // get services
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
            insert services;
            // get service account relationships
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(recordCount, services, providers);
            insert serviceAccountRecords;
            // get quality indicator summary
            List<Quality_Indicator_Summary__c> qisRecords = TestDataFactory.createQISummaryRecords(recordCount, providers, rPeriod, services, serviceAccountRecords);
            insert qisRecords;
            // get quality indicator detail
            List<Quality_Indicator_Details__c> qidRecords = TestDataFactory.createQIDetailRecords(22, qisRecords);
            List<String> recordTypes = new List<String>{'Pressure_Injuries', 
            'Physical_Restraint', 
            'Unplanned_Weight_Loss', 
            'Falls_and_Major_Injury', 
            'Medication_Management', 
            'Workforce',
            'Activities_of_daily_living_ADLs',
            'Consumer_Experience',
            'Hospitalisation',
            'Continence',
            'Quality_of_life'};
            for(Integer i = 0; i < qidRecords.size(); i++) {
                if(i < 11) {
                    String recordId = Schema.SObjectType.Quality_Indicator_Details__c.getRecordTypeInfosByDeveloperName().get(recordTypes[i]).getRecordTypeId();
                    qidRecords[i].RecordTypeId = recordId;
                }
                else {
                    Integer k = i - 11;
                    String recordId = Schema.SObjectType.Quality_Indicator_Details__c.getRecordTypeInfosByDeveloperName().get(recordTypes[k]).getRecordTypeId();
                    qidRecords[i].RecordTypeId = recordId;
                }
            }
            insert qidRecords;
        }
        Test.stopTest();

    }
    @isTest
    public static void testQIObserved() {
        Test.startTest();
        Database.executeBatch(new QIObservedBatch(), 200);
        Test.stopTest();
        List<National_Statistic__c> nsRecords = [SELECT Id, National_percentage_PI_Stage2__c,
                                                National_percentage_PI_Stage3__c, National_percentage_PI_Stage4__c, 
                                                National_percentage_PI_Deep_Tissue__c, National_percentage_PI_Unstageable__c, 
                                                National_percentage_significant_UWL__c, National_percentage_falls__c, 
                                                National_Percentage_falls_Major_Injury__c, National_percentage_ADL_DEC__c, 
                                                National_percentage_PIs__c, National_percentage_PI_Stage1__c
                                                FROM National_Statistic__c];
        // should only be one National_Statistic__c
        /*System.assertEquals(1, nsRecords.size(), 'There should only be one National Statistic record');
        System.assertEquals(50, nsRecords[0].National_percentage_PI_Stage2__c, 'PIS2 Percentage should be 50%');
        System.assertEquals(50, nsRecords[0].National_percentage_PI_Stage3__c, 'PIS3 Percentage should be 50%');
        System.assertEquals(50, nsRecords[0].National_percentage_PI_Stage4__c, 'PIS4 Percentage should be 50%');
        System.assertEquals(50, nsRecords[0].National_percentage_PI_Deep_Tissue__c, 'Deep Tissue Percentage should be 50%');
        System.assertEquals(50, nsRecords[0].National_percentage_PI_Unstageable__c, 'PI Unstageable Percentage should be 50%');
        System.assertEquals(50, nsRecords[0].National_percentage_significant_UWL__c, 'UPWL Percentage should be 50%');
        System.assertEquals(50, nsRecords[0].National_percentage_falls__c, 'Falls Percentage should be 50%');
        System.assertEquals(50, nsRecords[0].National_Percentage_falls_Major_Injury__c, 'Falls MI Percentage should be 50%');
        System.assertEquals(50, nsRecords[0].National_percentage_PI_Stage1__c, 'WF Stopped PC Percentage should be 50%');*/
    }
}