force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Calc_Date__c</fullName>
    <description>Date time rating calculation occurred</description>
    <label>SCR Rating Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Exemption_Granted__c.field-meta.xml
<CustomField>
    <fullName>Rating_Exemption_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Rating Exemption Granted</description>
    <label>Rating Exemption Granted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Publish</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
                <isActive>false</isActive>
                <label>Archive</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Care_Minutes_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Minutes_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Minutes</label>
    <referenceTo>Care_Minutes_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Consumer_Experience_Id__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Experience_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer Experience Report</label>
    <referenceTo>SRQI_CER__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <description>Date STAR Rating is live on MAC</description>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Quality_Indicator_Id__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Rating_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Calc_Date__c</fullName>
    <description>DateTime STAR Rating was calculated</description>
    <label>Calculation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Rating_Exemption_Granted__c.field-meta.xml
<CustomField>
    <fullName>Rating_Exemption_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Rating Exemption Granted</description>
    <label>Rating Exemption Granted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Compliance_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Compliance</label>
    <referenceTo>Service_Compliance_History__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/SF_Provider_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Provider_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/SF_Service_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Service_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of Star Rating calculation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availability_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Availability_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Published</fullName>
    </customValue>
    <customValue>
        <fullName>LIVE</fullName>
    </customValue>
    <customValue>
        <fullName>Removed</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review/On Hold</fullName>
        <isActive>false</isActive>
        <label>Under Review/On Hold</label>
    </customValue>
    <description>Status for Overall &amp; subcategory StarRatings</description>
    <masterLabel>Availability Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SCRUtil.cls
/**
 * @author    Smita Kagde
 * @date      13/10/2022
 * @testClass SCRUtilTest
 **/
/* MODIFICATION LOG
 * Version       Developer                   Date                Description
 *-------------------------------------------------------------------------------------------------------------------------------------------------------
 *  1.0     	 Rami Zuhairi                27-04-2023          Updated the fix related to Bug - 355791
 ******************************************************************************************************************************************************** */
public with sharing class SCRUtil {
	static final String CURRENT_RATING = 'Current Rating';
	static final String NEW_RATING = 'New Rating';
	static final String DRAFT_RATING = 'Draft Rating';
	// Stores list of maps of service IDs that will need their CER rating recalculated
	public static Id cerRecalcServiceIds;

	// Stores key constant for list of service ids used in recalculation IP
	private static final String SRH_ID = 'SRHID';

	//this method gets called from RegulatoryDecisionEventTriggerHelper class
	public static String createNUpdateSCR(
		Set<Id> serviceIdSet,
		Set<Id> serviceRelationIdSet,
		List<Service_Compliance_History__c> sCHList
	) {
		List<STAR_Rating_History__c> currentSRHlist = new List<STAR_Rating_History__c>();
		List<STAR_Rating_History__c> newSRHlist = new List<STAR_Rating_History__c>();
		String response = '';
		Map<Id, List<STAR_Rating_History__c>> sarWithSRH = new Map<Id, List<STAR_Rating_History__c>>();

		for (STAR_Rating_History__c rec : getExistingSRH(serviceIdSet, serviceRelationIdSet)) {
			if (!sarWithSRH.containsKey(rec.Service_Account_Relationship__c)) {
				sarWithSRH.put(rec.Service_Account_Relationship__c, new List<STAR_Rating_History__c>{ rec });
			} else {
				sarWithSRH.get(rec.Service_Account_Relationship__c).add(rec);
			}
		}
		try {
			for (Id sarId : serviceRelationIdSet) {
				if (sarWithSRH.containsKey(sarId)) {
					List<STAR_Rating_History__c> srhList = sarWithSRH.get(sarId);
					for (STAR_Rating_History__c srh : srhList) {
						if (srh.Rating_Exemption_Granted__c == false) {
							if (srh.Rating_Type__c == NEW_RATING || srh.Rating_Type__c == DRAFT_RATING) {
								newSRHlist.add(srh);
							} else if (srh.Rating_Type__c == CURRENT_RATING) {
								currentSRHlist.add(srh);
							} else {
								continue;
							}
						} else {
							newSRHlist.add(srh);
						}
					}
				}
			}
			if (newSRHlist.size() > 0) {
				//Updating SRH record if latest Rating Type is New Rating or Draft Rating
				response = updateSRHWithSCR(newSRHlist, sCHList);
			}
			if (currentSRHlist.size() > 0) {
				//Creating SRH record if Rating Type is Current Rating
				response = createSRHWithSCR(currentSRHlist, sCHList);
			}
		} catch (DmlException exp) {
			dohagedcare.Logger.error(exp.getMessage(), exp, 'SCRUtil -createNUpdateSCR').log();
			response = 'Failed';
		}
		return response;
	}
	private static List<STAR_Rating_History__c> getExistingSRH(Set<Id> serviceIdSet, Set<Id> serviceRelationIdSet) {
		return [
			SELECT
				Id,
				Rating_Type__c,
				Rating_Exemption_Granted__c,
				SF_Service_Id__c,
				SF_Provider_Id__c,
				Service_Account_Relationship__c,
				Care_Minutes_Id__c,
				Consumer_Experience_Id__c,
				Quality_Indicator_Id__c,
				Status__c,
				Service_Compliance_Id__c,
				Publication_Date__c,
				Rating_Calc_Date__c
			FROM STAR_Rating_History__c
			WHERE
				Service_Account_Relationship__c IN :serviceRelationIdSet
				AND SF_Service_Id__c IN :serviceIdSet
				AND Status__c != 'Removed'
			ORDER BY CreatedDate DESC
		];
	}

	private static Map<Id, Id> getServiceToSchMap(List<Service_Compliance_History__c> sCHList) {
		Map<Id, Id> schMap = new Map<Id, Id>();
		for (Service_Compliance_History__c chId : sCHList) {
			schMap.put(chId.Service__c, chId.Id);
		}
		return schMap;
	}
	private static String createSRHWithSCR(
		List<STAR_Rating_History__c> currentSRH,
		List<Service_Compliance_History__c> sCHList
	) {
		Map<Id, Id> schMap1 = getServiceToSchMap(sCHList);
		String response = '';
		List<STAR_Rating_History__c> sRHList = new List<STAR_Rating_History__c>();
		for (STAR_Rating_History__c csrh : currentSRH) {
			STAR_Rating_History__c srh = new STAR_Rating_History__c();
			srh.Care_Minutes_Id__c = csrh.Care_Minutes_Id__c;
			srh.Consumer_Experience_Id__c = csrh.Consumer_Experience_Id__c;
			srh.Quality_Indicator_Id__c = csrh.Quality_Indicator_Id__c;
			srh.Status__c = 'Draft';
			srh.Rating_Type__c = 'Draft Rating';
			srh.Reporting_Period__c = ReportingPeriodUtil.previousQuarterReportingPeriod?.Id;
			srh.Service_Compliance_Id__c = schMap1.get(csrh.SF_Service_Id__c);
			srh.SF_Service_Id__c = csrh.SF_Service_Id__c;
			srh.SF_Provider_Id__c = csrh.SF_Provider_Id__c;
			srh.Service_Account_Relationship__c = csrh.Service_Account_Relationship__c;
			srh.Go_Live_Date__c = System.today();
			sRHList.add(srh);

			csrh.Rating_Type__c = 'Previous Rating';
		}
		try {
			if (StarRatingExemptionCustomMetadata.goLiveSetting == false) {
				insert sRHList;
				update currentSRH;
				if (SRHList.size() > 0) {
					for (STAR_Rating_History__c srh : SRHList) {
						cerRecalcServiceIds = srh.Id;
						recalculateSRH();
					}
				}
			}

			response = 'Successful';
		} catch (DmlException exp) {
			dohagedcare.Logger.error(exp.getMessage(), exp, 'SCRUtil -createSRHWithSCR').log();
			response = 'Failed';
		}
		return response;
	}
	private static String updateSRHWithSCR(
		List<STAR_Rating_History__c> newSRH,
		List<Service_Compliance_History__c> sCHList
	) {
		String response = '';
		Map<Id, Id> schMap1 = getServiceToSchMap(sCHList);
		List<STAR_Rating_History__c> updSRHList = new List<STAR_Rating_History__c>();
		for (STAR_Rating_History__c srh : newSRH) {
			srh.Service_Compliance_Id__c = schMap1.get(srh.SF_Service_Id__c);
			srh.Rating_Calc_Date__c = System.today();
			updSRHList.add(srh);
		}
		try {
			if (StarRatingExemptionCustomMetadata.goLiveSetting == false) {
				update updSRHList;
				if (updSRHList.size() > 0) {
					for (STAR_Rating_History__c srh : updSRHList) {
						cerRecalcServiceIds = srh.Id;
						recalculateSRH();
					}
				}
			}

			response = 'Successful';
		} catch (DmlException exp) {
			dohagedcare.Logger.error(exp.getMessage(), exp, 'SCRUtil -updateSRHWithSCR').log();
			response = 'Failed';
		}
		return response;
	}

	// Recalculate rating for CER subdomain
	private static void recalculateSRH() {
		String procedureName = 'SRQI_StarRatingCalculation';
		Map<String, Object> ipOutput;
		Map<String, Id> ipInput = new Map<String, Id>();
		Map<String, Object> ipOptions = new Map<String, Object>();
		ipInput.put(SRH_ID, cerRecalcServiceIds);
		ipOutput = (Map<String, Object>) omnistudio.IntegrationProcedureService.runIntegrationService(
			procedureName,
			ipInput,
			ipOptions
		);
	}
}