force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Previous_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Previous_Reporting_Period__c</fullName>
    <description>Displays true if dates match previous reporting period</description>
    <formula>IF( ISPICKVAL (Reporting_Period_Type__c, &quot;Quarter&quot;), 
IF( ADDMONTHS( TODAY( ), -3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ), -3 ) &lt;= End_Date__c, True, False ),
IF( ADDMONTHS( TODAY( ), -12 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ), -12 ) &lt;= End_Date__c, True, False )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Previous Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReportingPeriodUtil.cls
/**
 * @Author           Kai-Fan Hsieh
 * @Date             21-12-2022
 * @Description      Utility class to be used within STAR Rating application
*/
public with sharing class ReportingPeriodUtil {
    public static final String REPORTING_PERIOD_TYPE_QUARTER = 'Quarter';

    public static Reporting_Period__c previousQuarterReportingPeriod {
        get {
            if (previousQuarterReportingPeriod == null) {
                List<Reporting_Period__c> rpList = [
                    SELECT Id
                    FROM Reporting_Period__c
                    WHERE Previous_Reporting_Period__c = TRUE
                    AND Reporting_Period_Type__c = :REPORTING_PERIOD_TYPE_QUARTER
                    LIMIT 1
                ];
                if (rpList.size() > 0) {
                    previousQuarterReportingPeriod = rpList.get(0);
                }
            }
            return previousQuarterReportingPeriod;
        }
        private set;
    }
}