force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/CER_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>CER_Calc_Date__c</fullName>
    <description>CER Calc Date</description>
    <label>CER Calc Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/CER_Calculated__c.field-meta.xml
<CustomField>
    <fullName>CER_Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CER Calculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/CM_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>CM_Calc_Date__c</fullName>
    <label>CM Calc Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/CM_Calculated__c.field-meta.xml
<CustomField>
    <fullName>CM_Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CM Calculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Previous_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Previous_Reporting_Period__c</fullName>
    <description>Displays true if dates match previous reporting period</description>
    <formula>IF( ISPICKVAL (Reporting_Period_Type__c, &quot;Quarter&quot;), 
IF( ADDMONTHS( TODAY( ), -3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ), -3 ) &lt;= End_Date__c, True, False ),
IF( ADDMONTHS( TODAY( ), -12 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ), -12 ) &lt;= End_Date__c, True, False )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Previous Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/QI_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>QI_Calc_Date__c</fullName>
    <description>QI Calc Date</description>
    <label>QI Calc Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/QI_Calculated__c.field-meta.xml
<CustomField>
    <fullName>QI_Calculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QI Calculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/StarRating_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>StarRating_Calc_Date__c</fullName>
    <label>Star Rating Calc Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RatingsCalculationHandler.cls
/**
 * author: Daniel Clift
 * date: 18/08/2022
 * description: checks if ratings calculations are required, passes to true conditions to IntegrationProcedureHandler, which calls omnistudio integration procedure(s)
 * @testClass RatingsCalculationHandlerTest
 **/

public with sharing class RatingsCalculationHandler {
	// Initiale Variables
	@TestVisible
	public static date cmCalcDate;
	@TestVisible
	public static date qiCalcDate;
	@TestVisible
	public static date cerCalcDate;
	@TestVisible
	public static date srhCalcDate;

	public static void executeHandler() {
		Set<String> algorithms = new Set<String>{ 'CER', 'QI', 'CM' };
		Set<String> algorithmsCompleted = new Set<String>();
		List<Reporting_Period__c> rPeriods = [
			SELECT
				Id,
				Reporting_Period_Type__c,
				CER_Calc_Date__c,
				CM_Calc_Date__c,
				QI_Calc_Date__c,
				StarRating_Calc_Date__c,
				CM_Calculated__c,
				CER_Calculated__c,
				QI_Calculated__c
			FROM Reporting_Period__c
			WHERE Previous_Reporting_Period__c = TRUE AND Reporting_Period_Type__c = 'Quarter'
			LIMIT 1
		];

		try {
			for (Reporting_Period__c rPeriod : rPeriods) {
				cmCalcDate = rPeriod.CM_Calc_Date__c;
				qiCalcDate = rPeriod.QI_Calc_Date__c;
				cerCalcDate = rPeriod.CER_Calc_Date__c;
				srhCalcDate = rPeriod.StarRating_Calc_Date__c;
				if (rPeriod.CER_Calculated__c) {
					algorithmsCompleted.add('CER');
				}

				if (rPeriod.CM_Calculated__c) {
					algorithmsCompleted.add('CM');
				}

				if (rPeriod.QI_Calculated__c) {
					algorithmsCompleted.add('QI');
				}
			}

			// run method to check if rating calculation is required
			if (algorithmsCompleted.containsAll(algorithms)) {
				checkSRHDate();
			} else {
				checkCalcDates();
			}
		} catch (Exception exp) {
			dohagedcare.Logger.error(exp.getMessage(), exp, 'RatingsCalculationHandler').Log();
		}
	}

	public static void checkCalcDates() {
		// if care minutes requires calc today
		if (cmCalcDate == System.today() || qiCalcDate == System.today() || cerCalcDate == System.today()) {
			RatingsCalculationService.starRatingRecords();

			if (cmCalcDate == System.today()) {
				IntegrationProcedureHandler ipHandler = new IntegrationProcedureHandler(
					IntegrationProcedureHandler.RUNCM
				);
				ipHandler.executeIp();
			}
			// if quality indicator requires calc today
			if (qiCalcDate == System.today()) {
				Database.executeBatch(new QIObservedBatch());
			}
			// if consumer experience report requires calc today
			if (cerCalcDate == System.today()) {
				Database.executeBatch(new CEIAlgorithmBatch());
			}
		}
	}

	public static void checkSRHDate() {
		Boolean cerHasRun = false;
		Boolean cmHasRun = false;
		Boolean qiHasRun = false;
		List<Reporting_Period__c> rPeriods = [
			SELECT
				Id,
				Reporting_Period_Type__c,
				CER_Calc_Date__c,
				CM_Calc_Date__c,
				QI_Calc_Date__c,
				StarRating_Calc_Date__c,
				CM_Calculated__c,
				CER_Calculated__c,
				QI_Calculated__c
			FROM Reporting_Period__c
			WHERE Previous_Reporting_Period__c = TRUE AND Reporting_Period_Type__c = 'Quarter'
			LIMIT 1
		];

		for (Reporting_Period__c rPeriod : rPeriods) {
			srhCalcDate = rPeriod.StarRating_Calc_Date__c;
			if (rPeriod.CER_Calculated__c == true) {
				cerHasRun = true;
			}

			if (rPeriod.CM_Calculated__c == true) {
				cmHasRun = true;
			}

			if (rPeriod.QI_Calculated__c == true) {
				qiHasRun = true;
			}
		}

		/*overall star rating batch
		 *this is also called by a trigger, on reporting period
		 */
		if (srhCalcDate == System.today() && cerHasRun == true && cmHasRun == true && qiHasRun == true) {
			try {
				Database.executeBatch(new SRHCalcPrepBatch());
			} catch (Exception exp) {
				dohagedcare.Logger.error(exp.getMessage(), exp, 'RatingsCalculationHandler - SRHCalcPrepBatch').Log();
			}
		}
	}
}