force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/QI_Submission_Due_Dt__c.field-meta.xml
<CustomField>
    <fullName>QI_Submission_Due_Dt__c</fullName>
    <description>capture the QI submission due date</description>
    <label>QI Submission Due Dt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QiFileUploadControllerTest.cls
@isTest
public with sharing class QiFileUploadControllerTest {
    @TestSetup
    static void dataSetup() {
        User testUser = TestDataFactory.createSystemAdminUser();
        Integer currentYear = System.Today().year();
        Integer lastYear = currentYear - 1;
        System.runAs(testUser) {
            insert new Contentversion(
                Title = 'Quality indicator file upload template',
                PathOnClient = 'test',
                VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body')
            );
            List<Reporting_Period__c> quarters = new List<Reporting_Period__c>();
            // create Q1
            Reporting_Period__c q1 = new Reporting_Period__c();
            q1.Reporting_Period_Type__c = 'Quarter';
            q1.Start_Date__c = Date.newInstance(lastYear, 7, 1);
            q1.End_Date__c = Date.newInstance(lastYear, 9, 31);
            q1.QI_Submission_Due_Dt__c = Date.newInstance(lastYear, 10, 21);
            quarters.add(q1);

            // create Q2
            Reporting_Period__c q2 = new Reporting_Period__c();
            q2.Reporting_Period_Type__c = 'Quarter';
            q2.Start_Date__c = Date.newInstance(lastYear, 10, 1);
            q2.End_Date__c = Date.newInstance(lastYear, 12, 31);
            q2.QI_Submission_Due_Dt__c = Date.newInstance(currentYear, 1, 21);
            quarters.add(q2);

            // create Q3
            Reporting_Period__c q3 = new Reporting_Period__c();
            q3.Reporting_Period_Type__c = 'Quarter';
            q3.Start_Date__c = Date.newInstance(currentYear, 1, 1);
            q3.End_Date__c = Date.newInstance(currentYear, 3, 31);
            q3.QI_Submission_Due_Dt__c = Date.newInstance(currentYear, 4, 21);
            quarters.add(q3);

            // create Q4
            Reporting_Period__c q4 = new Reporting_Period__c();
            q4.Reporting_Period_Type__c = 'Quarter';
            q4.Start_Date__c = Date.newInstance(currentYear, 4, 1);
            q4.End_Date__c = Date.newInstance(currentYear, 6, 31);
            q4.QI_Submission_Due_Dt__c = Date.newInstance(currentYear, 7, 21);
            quarters.add(q4);

            insert quarters;
        }
    }

    @isTest static void testGetOrgNameWhenNotExists() {
        // Create contact that is not linked to an approved provider or benchmarking org
        String agedCareOrgId = TestDataFactory.createACO();
        List<Account> accounts = [SELECT Id FROM Account WHERE Id = :agedCareOrgId];
        List<Contact> contacts = TestDataFactory.createContact(1, accounts);
        insert contacts;

        try {
            String orgName = QiFileUploadController.getOrgName(contacts.get(0).Id);
            Assert.fail();
        } catch (Exception ex) {
            Assert.areEqual('System.AuraHandledException', ex.getTypeName());
        }
    }

    @isTest static void testGetOrgNameWhenExists() {
        // Create contact linked to an approved provider
        List<Account> providers = TestDataFactory.createProviderRecords(1);
        insert providers;
        List<Contact> contacts = TestDataFactory.createContact(1, providers);
        insert contacts;

        String orgName = QiFileUploadController.getOrgName(contacts.get(0).Id);

        Assert.isNotNull(orgName);
    }
}