force-app/main/default/objects/Financial_Reporting_Rule__c/Financial_Reporting_Rule__c.object-meta.xml
<CustomObject>
    <label>Financial Reporting Rule</label>
    <nameField>
        <label>Financial Reporting Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Reporting Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Reporting_Rule__c/fields/Form_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Type__c</fullName>
    <label>Form Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Reporting_Rule_Details__c/Financial_Reporting_Rule_Details__c.object-meta.xml
<CustomObject>
    <label>Financial Reporting Rule Detail</label>
    <nameField>
        <displayFormat>FRRD-{0000000}</displayFormat>
        <label>FRRD</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Reporting Rule Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Reporting_Rule_Details__c/fields/Financial_Reporting_Rule__c.field-meta.xml
<CustomField>
    <fullName>Financial_Reporting_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Reporting Rule</label>
    <referenceTo>Financial_Reporting_Rule__c</referenceTo>
    <relationshipLabel>Financial Reporting Rule Details</relationshipLabel>
    <relationshipName>Financial_Reporting_Rule_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Reporting_Rule_Details__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Financial Reporting Rules</relationshipLabel>
    <relationshipName>Financial_Reporting_Rule_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Reporting_Rule_Details__c/fields/Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Rule_Name__c</fullName>
    <label>Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <label>QA Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Re-Issue</fullName>
                <label>Reissue</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>More information required</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>ReIssued</fullName>
                <isActive>false</isActive>
                <label>ReIssued</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Code</description>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/GL_Code_Line_Item__c.object-meta.xml
<CustomObject>
    <description>GL Code Line Item</description>
    <label>GL Code Line Item</label>
    <nameField>
        <displayFormat>GLI-{000000}</displayFormat>
        <label>GL Code Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Code Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/Amended_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Amended_Explanation__c</fullName>
    <description>Refers to the providers amended explanation</description>
    <label>Amended Explanation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GL Code</description>
    <label>GL Code</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>GL Code Line Items</relationshipLabel>
    <relationshipName>GL_Code_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/Line_Item_Value__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Value__c</fullName>
    <description>To store the values entered by Provider for each data table cell.</description>
    <label>Line Item Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/provider_explanation__c.field-meta.xml
<CustomField>
    <fullName>provider_explanation__c</fullName>
    <label>Provider Explanation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/QA_External_Comments__c.field-meta.xml
<CustomField>
    <fullName>QA_External_Comments__c</fullName>
    <description>Refers to QA Assessors external comments for rejected provider explanation</description>
    <label>QA External Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <description>QA outcome for QA Assessors to select on each provider explanation they review</description>
    <label>QA Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Reject - Low Percentage of Non-Care Wages</fullName>
            </value>
            <value>
                <fullName>Reject - Only 3 Months of Data</fullName>
            </value>
            <value>
                <fullName>Reject - Pay Periods</fullName>
            </value>
            <value>
                <fullName>Reject - Agency Staff not Included as Wages in QFS</fullName>
            </value>
            <value>
                <fullName>Reject - Total and Care Wages are Equal</fullName>
            </value>
            <value>
                <fullName>Reject - YTD Wages are less than QTR Wages</fullName>
            </value>
            <value>
                <fullName>Reject - Alternative EOFY</fullName>
            </value>
            <value>
                <fullName>Reject - Care Wages are Greater than Total Wages</fullName>
            </value>
            <value>
                <fullName>Reject - Higher than Usual RN Hours</fullName>
            </value>
            <value>
                <fullName>Reject - Zero PCW Hours</fullName>
            </value>
            <value>
                <fullName>Reject - No Reference to Sick or Annual Leave</fullName>
            </value>
            <value>
                <fullName>Reject - Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GL_Code_Line_Item__c/fields/Service_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Line_Item__c</fullName>
    <label>Service Line Item</label>
    <referenceTo>Service_Line_Item__c</referenceTo>
    <relationshipLabel>GL Code Line Items</relationshipLabel>
    <relationshipName>GL_Code_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Line_Item__c/Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI-{00000}</displayFormat>
        <label>Service Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Line_Item__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField> 

force-app/main/default/objects/Service_Line_Item__c/fields/Service_Label__c.field-meta.xml
<CustomField>
    <fullName>Service_Label__c</fullName>
    <formula>Service_Region__c +  TEXT(Service_Category__c) + Service__r.Name</formula>
    <label>Service Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AcfrReviewProviderExplanation.cls
/* @TestClass AcfrReviewProviderExplanationTest */
public with sharing class AcfrReviewProviderExplanation {
	public static final String ACCEPTED_OUTCOME = 'Accepted' + ',' + 'Review';

	@AuraEnabled(cacheable=true)
	public static List<responsesWrapper> getProviderExplanation(Id recordId) {
		Set<Id> glCodeIds = new Set<Id>();
		String formType = getFormType(recordId);
		List<ResponsesWrapper> responsesWrap = new List<ResponsesWrapper>();

		if (getFormType(recordId) != null) {
			for (Financial_Reporting_Rule_Details__c getRuleDetails : [
				SELECT Id, Error_Message__c, Rule_Name__c, GL_Code__c
				FROM Financial_Reporting_Rule_Details__c
				WHERE
					GL_Code__c != NULL
					AND Financial_Reporting_Rule__r.Form_Type__c = :formType
			]) {
				glCodeIds.add(getRuleDetails.GL_Code__c);
			}

			List<Financial_Reporting_Rule_Details__c> finRuleDetails = [
				SELECT Id, Rule_Name__c, Error_Message__c, GL_Code__c
				FROM Financial_Reporting_Rule_Details__c
				WHERE
					GL_Code__c != NULL
					AND Financial_Reporting_Rule__r.Form_Type__c = :formType
			];

			for (GL_Code_Line_Item__c glItem : [
				SELECT
					Id,
					Service_Line_item__r.Service_Label__c,
					Line_Item_Value__c,
					provider_explanation__c,
					QA_Outcome__c,
					QA_External_Comments__c,
					Amended_Explanation__c,
					GL_Code__c
				FROM GL_Code_Line_Item__c
				WHERE
					provider_explanation__c != NULL
					AND GL_Code__c IN :glCodeIds
					AND service_line_item__r.Form__r.Id = :recordId
				ORDER BY QA_Outcome__c
			]) {
				for (Financial_Reporting_Rule_Details__c f : finRuleDetails) {
					if (glItem.GL_Code__c == f.GL_Code__c) {
						ResponsesWrapper responses = new ResponsesWrapper();
						responses.glcodelineitemId = glItem.Id;
						responses.errorMessage = f.Error_Message__c;
						responses.validationRule = f.Rule_Name__c;
						responses.dataInput = glItem.Line_Item_Value__c;
						responses.serviceName = glItem.Service_Line_item__r.Service_Label__c;
						responses.providerExplanation = glItem.provider_explanation__c;
						responses.qaOutcome = glItem.QA_Outcome__c;
						responses.qaExternalComments = glItem.QA_External_Comments__c;
						responses.amendedExplanation = glItem.Amended_Explanation__c;
						responses.glCodeId = glItem.GL_Code__c;
						responsesWrap.add(responses);
					}
				}
			}
		}
		return responsesWrap;
	}

	@AuraEnabled(cacheable=true)
	public static List<GL_Code_Line_Item__c> getRejectedProviderExplanation(
		Id recordId
	) {
		return [
			SELECT Id, QA_External_Comments__c
			FROM GL_Code_Line_Item__c
			WHERE
				provider_explanation__c != NULL
				AND QA_Outcome__c NOT IN ('Accepted', 'Review')
				AND service_line_item__r.Form__r.Id = :recordId
			ORDER BY QA_Outcome__c
		];
	}

	public static string getFormType(Id recordId) {
		string formType = '';
		List<Form__c> getForms = [
			SELECT Type__c
			FROM Form__c
			WHERE Id = :recordId
		];
		if (getForms.size() > 0) {
			formType = getForms[0].Type__c;
		}
		return formType;
	}

	public class ResponsesWrapper {
		@AuraEnabled
		public Id glcodelineitemId { get; set; }
		@AuraEnabled
		public String errorMessage { get; set; }
		@AuraEnabled
		public String validationRule { get; set; }
		@AuraEnabled
		public String serviceName { get; set; }
		@AuraEnabled
		public String dataInput { get; set; }
		@AuraEnabled
		public String providerExplanation { get; set; }
		@AuraEnabled
		public String qaOutcome { get; set; }
		@AuraEnabled
		public String qaExternalComments { get; set; }
		@AuraEnabled
		public String amendedExplanation { get; set; }
		@AuraEnabled
		public Id glCodeId { get; set; }
	}
}