force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <description>Date STAR Rating is live on MAC</description>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <description>Date STAR rating is to be published to the provider portal</description>
    <label>Publish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/STAR_Rating_Calculation__c.field-meta.xml
<CustomField>
    <fullName>STAR_Rating_Calculation__c</fullName>
    <label>STAR Rating Calculation</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of Star Rating calculation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availability_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STARRating_Settings__mdt/STARRating_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Use this metadata type to store period of time to Go Live and Publish status for SCR Records</description>
    <label>STARRating Settings</label>
    <pluralLabel>STARRating Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/STARRating_Settings__mdt/fields/Days_to_Go_Live__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Go_Live__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Stores the number days from rating calculation to Go Live.</description>
    <label>Days to Go Live</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STARRating_Settings__mdt/fields/Days_to_Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Publish_Date__c</fullName>
    <defaultValue>14</defaultValue>
    <description>Stores the number of days to Publish Date</description>
    <label>Days to Publish Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Availability_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Published</fullName>
    </customValue>
    <customValue>
        <fullName>LIVE</fullName>
    </customValue>
    <customValue>
        <fullName>Removed</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review/On Hold</fullName>
        <isActive>false</isActive>
        <label>Under Review/On Hold</label>
    </customValue>
    <description>Status for Overall &amp; subcategory StarRatings</description>
    <masterLabel>Availability Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestStarRatingTriggerHelper.cls
@IsTest
public with sharing class TestStarRatingTriggerHelper {
	@TestSetup
	static void makeData() {
		STAR_Rating_History__c srh = new STAR_Rating_History__c(Status__c = 'Published');
		insert srh;
	}

	@IsTest
	static void testSetCalculation() {
		STAR_Rating_History__c srh = [
			SELECT Status__c, STAR_Rating_Calculation__c, Publish_Date__c, Go_Live_Date__c
			FROM STAR_Rating_History__c
			WHERE Status__c = 'Published'
			LIMIT 1
		];
        System.debug('Query1: ' + srh);
		Test.startTest();
		srh.STAR_Rating_Calculation__c = 4;
		update srh;
		
		STAR_Rating_History__c srh2 = [
			SELECT Status__c, STAR_Rating_Calculation__c, Publish_Date__c, Go_Live_Date__c
			FROM STAR_Rating_History__c 
			LIMIT 1
		];
        System.debug('Query2: ' + srh2);
		Integer goLiveDays = (Integer) STARRating_Settings__mdt.getInstance('Status_Change_Dates').Days_to_Go_Live__c;
		Integer publishDateDays = (Integer) STARRating_Settings__mdt.getInstance('Status_Change_Dates')
			.Days_to_Publish_Date__c;
        Test.stopTest();
		/* QISR - To fix 
		System.assertEquals(
			srh2.Publish_Date__c.addDays(goLiveDays),
			srh2.Go_Live_Date__c,
			'Go Live date should be ' +
			goLiveDays +
			' days from publish date'
		);
		System.assertEquals(
			Date.today().addDays(publishDateDays),
			srh2.Publish_Date__c,
			'Publish date should be ' +
			publishDateDays +
			' days from today'
		);*/
	}

	@IsTest
	static void testUpdateWithoutCalculation() {
		STAR_Rating_History__c srh = [
			SELECT Status__c, STAR_Rating_Calculation__c, Publish_Date__c, Go_Live_Date__c
			FROM STAR_Rating_History__c
			WHERE Status__c = 'Published'
			LIMIT 1
		];
		Test.startTest();
		update srh;
		Test.stopTest();
		srh = [
			SELECT Status__c, STAR_Rating_Calculation__c, Publish_Date__c, Go_Live_Date__c
			FROM STAR_Rating_History__c
			WHERE Status__c = 'Published'
			LIMIT 1
		];
		System.assertEquals(null, srh.Go_Live_Date__c, 'Go Live date should not be set');
		System.assertEquals(null, srh.Publish_Date__c, 'Publish date should not be set');
	}
}