force-app/main/default/objects/Quality_Indicator_Summary_Version__c/Quality_Indicator_Summary_Version__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary Version</label>
    <nameField>
        <displayFormat>QISV-{0000}</displayFormat>
        <label>Quality Indicator Summary Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary_Version__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Late Submission</fullName>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <label>Submitted - Updated After Due Date</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary_Version__c/fields/Submission_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Submission_Date_Time__c</fullName>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary_Version__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quality_Indicator_Summary_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QISVersionTriggerHandler.cls
/**
 * @description       : QISVersionTriggerHandler
 * @author            : Sharevreet Singh
 * @group             : 
 * @last modified on  : 05-17-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class QISVersionTriggerHandler implements beforeUpdate, afterUpdate {
    final static Set<String> STATUS_LIST = new Set<String>{'Submitted', 'Late Submission', 'Updated After Due Date'};

    public void beforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        for(Quality_Indicator_Summary_Version__c qisVersion : (List<Quality_Indicator_Summary_Version__c>) newMap.values()) {
            Quality_Indicator_Summary_Version__c qisVersionOld = (Quality_Indicator_Summary_Version__c) oldMap.get(qisVersion.Id);
            if(qisVersion.Submission_Date_Time__c!=qisVersionOld.Submission_Date_Time__c && STATUS_LIST.contains(qisVersion.Status__c)){
                qisVersion.Submitted_By__c=UserInfo.getUserId();
            }
        }
    }
    
    public void afterUpdate(Map<Id, SObject> newMap, Map<Id,SObject> oldMap) {
        Set<Id> qisIdsForRating = new Set<Id>();
        List<Quality_Indicator_Summary_Version__c> qisVerList=new List<Quality_Indicator_Summary_Version__c>();

        for(Quality_Indicator_Summary_Version__c qisVersion : (List<Quality_Indicator_Summary_Version__c>) newMap.values()) {
            if(STATUS_LIST.contains(qisVersion.Status__c)) {
                qisVerList.add(qisVersion);
            }
        }

        if(!qisVerList.isEmpty()){
            QISVersionTriggerService.updateQIRelatedObjs(new Map<Id, Quality_Indicator_Summary_Version__c>(qisVerList));
        }
    }
}