force-app/main/default/objects/National_Statistic__c/National_Statistic__c.object-meta.xml
<CustomObject>
    <label>National Statistic</label>
    <nameField>
        <displayFormat>NS-{00000}</displayFormat>
        <label>National Statistic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Statistics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Statistic__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>National Statistics</relationshipLabel>
    <relationshipName>National_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/National_Statistic__c.field-meta.xml
<CustomField>
    <fullName>National_Statistic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>National Statistic</label>
    <referenceTo>National_Statistic__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Quality_Indicator_Rating__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Rating__c</fullName>
    <description>Quality Indicator number rating, out of 5</description>
    <label>Quality Indicator Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Late Submission</fullName>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <label>Submitted - Updated After Due Date</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QualityIndicatorService.cls
/**
* author: Sharevreet Singh
* date: 14/10/2022
* description: Service class for calculating QI scores
**/
public with sharing class QualityIndicatorService {
    @TestVisible private static final String STATUS_NS = 'Not Started';
    private static final String STATUS_IP = 'In Progress';
    public static final String STATUS_NSUB = 'Not Submitted';

    public static void qualityIndicatorRatings(Map<Id, Quality_Indicator_Summary__c> qiMap, National_Statistic__c natStatRecord, Reporting_Period__c reportPeriod, Boolean lateUpdate) {
        List<Quality_Indicator_Summary__c> updateQI = new List<Quality_Indicator_Summary__c>();

        for(Quality_Indicator_Summary__c qiRecord : qiMap.values()) {
            RiskAdjustedCalculator racObj = new RiskAdjustedCalculator(qiRecord, natStatRecord);
            updateQI.add(racObj.calculateRiskAdjusted());
            qiRecord.National_Statistic__c = natStatRecord.Id;
            qiRecord = checkQiStatusAndRating(qiRecord);
        }
        
        if(updateQI.size() > 0) {
            try {
                update updateQI;
            } catch(Exception ex) {
                dohagedcare.Logger.error(ex.getMessage(), ex, 'QualityIndicatorService - update QI').log();
            }
        }

        if(!System.isQueueable()) {
            try {
                System.enqueueJob(new QuintileScoreCalculator(qiMap.keySet(), natStatRecord, reportPeriod, lateUpdate));
            } catch(Exception ex) {
                dohagedcare.Logger.error(ex.getMessage(), ex, 'QualityIndicatorService - enqueue QuintileScoreCalculator').log();
            }
        }
    }


    /**
     * @description - setting status an rating based on current status
     */
    public static Quality_Indicator_Summary__c checkQiStatusAndRating(Quality_Indicator_Summary__c qiRecord) {
        if(qiRecord.Status__c == STATUS_NS || qiRecord.Status__c == STATUS_IP) {
            qiRecord.Status__c = STATUS_NSUB;
            qiRecord.Quality_Indicator_Rating__c = 1;
        }
        return qiRecord;
    }
}