force-app/main/default/objects/Quality_Indicator_Details__c/Quality_Indicator_Details__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Details</label>
    <nameField>
        <label>Quality Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quality Indicator Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <inlineHelpText>The date QI Detail record was marked as &quot;Completed&quot;</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/QI_Summary_Id__c.field-meta.xml
<CustomField>
    <fullName>QI_Summary_Id__c</fullName>
    <description>Master detail relation to Quality Indicator Summary.</description>
    <label>QI Parent Id</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Quality Indicator Details (QI Parent Id)</relationshipLabel>
    <relationshipName>Quality_Indicators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/quality_indicator_ext_id__c.field-meta.xml
<CustomField>
    <fullName>quality_indicator_ext_id__c</fullName>
    <externalId>true</externalId>
    <label>Quality Indicator External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Activities_of_daily_living_ADLs.recordType-meta.xml
<RecordType>
    <fullName>Activities_of_daily_living_ADLs</fullName>
    <active>true</active>
    <label>Activities of Daily Living (ADLs)</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Consumer_Experience.recordType-meta.xml
<RecordType>
    <fullName>Consumer_Experience</fullName>
    <active>true</active>
    <label>Consumer Experience</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Continence.recordType-meta.xml
<RecordType>
    <fullName>Continence</fullName>
    <active>true</active>
    <label>Incontinence Care</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Falls_and_Major_Injury.recordType-meta.xml
<RecordType>
    <fullName>Falls_and_Major_Injury</fullName>
    <active>true</active>
    <label>Falls and Major Injury</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Hospitalisation.recordType-meta.xml
<RecordType>
    <fullName>Hospitalisation</fullName>
    <active>true</active>
    <label>Hospitalisation</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Medication_Management.recordType-meta.xml
<RecordType>
    <fullName>Medication_Management</fullName>
    <active>true</active>
    <label>Medication Management</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Physical_Restraint.recordType-meta.xml
<RecordType>
    <fullName>Physical_Restraint</fullName>
    <active>true</active>
    <label>Physical Restraint</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Pressure_Injuries.recordType-meta.xml
<RecordType>
    <fullName>Pressure_Injuries</fullName>
    <active>true</active>
    <label>Pressure Injuries</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Quality_of_life.recordType-meta.xml
<RecordType>
    <fullName>Quality_of_life</fullName>
    <active>true</active>
    <label>Quality of life</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Unplanned_Weight_Loss.recordType-meta.xml
<RecordType>
    <fullName>Unplanned_Weight_Loss</fullName>
    <active>true</active>
    <label>Unplanned Weight Loss</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Details__c/recordTypes/Workforce.recordType-meta.xml
<RecordType>
    <fullName>Workforce</fullName>
    <active>true</active>
    <label>Workforce</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Quality_Indicator_Details__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Details</label>
    <referenceTo>Quality_Indicator_Details__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Falls_and_Major_injury.recordType-meta.xml
<RecordType>
    <fullName>Falls_and_Major_injury</fullName>
    <active>false</active>
    <label>Falls and Major injury</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Medication_management.recordType-meta.xml
<RecordType>
    <fullName>Medication_management</fullName>
    <active>false</active>
    <label>Medication management</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Physical_restraint.recordType-meta.xml
<RecordType>
    <fullName>Physical_restraint</fullName>
    <active>false</active>
    <label>Physical restraint</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Pressure_injuries.recordType-meta.xml
<RecordType>
    <fullName>Pressure_injuries</fullName>
    <active>false</active>
    <label>Pressure injuries</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Summary__c/recordTypes/Unplanned_weight_loss.recordType-meta.xml
<RecordType>
    <fullName>Unplanned_weight_loss</fullName>
    <active>false</active>
    <label>Unplanned weight loss</label>
</RecordType>

force-app/main/default/classes/QualityIndicatorDetailsTriggerHandler.cls
/****************************************************************************************************
 * @CreatedBy   : Daniel Clift
 * @CreatedDate : 01/02/2023
 * @Description : trigger handler for Quality_Indicator_Details__c
 * @Test Class  : QualityIndicatorDetailsTrigHandlerTest
 * @modified by: Yifei Pei on 01/03/2023 add funtion to update Completion_Date__c when the status equals to 'Completed'
 * @modified by: Jamil Khaki on 14/03/2023 Update calling renamed ValidationUtil method qidFieldValidation
 *****************************************************************************************************/

public with sharing class QualityIndicatorDetailsTriggerHandler implements beforeUpdate, beforeInsert {
    private static final Map<String, String> DOMAIN_PREFIX = new Map<String, String>{
        'Activities_of_daily_living_ADLs' => 'ADL',
        'Consumer_Experience' => 'CEI',
        'Falls_and_Major_Injury' => 'FMI',
        'Hospitalisation' => 'HP',
        'Continence' => 'IAD',
        'Medication_Management' => 'MM',
        'Physical_Restraint' => 'PR',
        'Pressure_Injuries' => 'PI',
        'Quality_of_life' => 'QOL',
        'Unplanned_Weight_Loss' => 'UPWL',
        'Workforce' => 'WF'
    };

    public void beforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        List<Quality_Indicator_Details__c> qidList = (List<Quality_Indicator_Details__c>) newMap.values();
        Map<Id, Quality_Indicator_Details__c> oldQIMap = (Map<Id, Quality_Indicator_Details__c>) oldMap;

        QualityIndicatorValidationUtil.qidFieldValidation(qidList);
        QualityIndicatorValidationUtil.fieldUpdate(qidList, oldQIMap);
    }

    public void beforeInsert(List<SObject> newList) {
        List<Quality_Indicator_Details__c> qidList = (List<Quality_Indicator_Details__c>) newList;

        QualityIndicatorValidationUtil.qidFieldValidation(qidList);
        QualityIndicatorValidationUtil.fieldUpdate(qidList, null);

        // 393628 add external Id in trigger assumption: the related Quality Indicator Summary should have external Id already
        Map<Id, String> qidPrefixMap = new Map<Id, String>();
        List<Schema.RecordTypeInfo> rtInfo = Quality_Indicator_Details__c.SObjectType.getDescribe().getRecordTypeInfos();
        for (Schema.RecordTypeInfo rtRecord : rtInfo) {
            qidPrefixMap.put(rtRecord.getRecordTypeId(), DOMAIN_PREFIX.get(rtRecord.getDeveloperName()));
        }
        Map<Id, Quality_Indicator_Summary__c> qisQIDMap = new Map<Id, Quality_Indicator_Summary__c>();
        for (Quality_Indicator_Details__c qidRecord : qidList) {
            qisQIDMap.put(qidRecord.QI_Summary_Id__c, null);
        }
        qisQIDMap.putAll([SELECT Id, External_ID__c FROM Quality_Indicator_Summary__c WHERE Id IN :qisQIDMap.keySet()]);
        for (Quality_Indicator_Details__c qidRecord : qidList) {
            qidRecord.quality_indicator_ext_id__c =
                qidPrefixMap.get(qidRecord.RecordTypeId) +
                '-' +
                qisQIDMap.get(qidRecord.QI_Summary_Id__c).External_ID__c;
        }
    }
}