force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Code</description>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/Service_GL_Code_Restriction__mdt.object-meta.xml
<CustomObject>
    <description>Indicates an allowlist/blocklist of Services for specified GL Codes

Specifying Excluded GL Codes will prevent that GL Code being generated for a Service Category, even if it is included.
Specifying Included GL Codes will ONLY create records for any included GL Codes for that Service Category.

Excluded = remove cell from service
Included = only show specified GL Codes for service (eg Centrally Held for QFR)</description>
    <label>Service GL Code Restriction</label>
    <pluralLabel>Service GL Code Restrictions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/fields/Restriction_Type__c.field-meta.xml
<CustomField>
    <fullName>Restriction_Type__c</fullName>
    <label>Restriction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclude</fullName>
                <default>true</default>
                <label>Exclude</label>
            </value>
            <value>
                <fullName>Include</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/fields/Service_Category__c.field-meta.xml
<CustomField>
    <fullName>Service_Category__c</fullName>
    <label>Service Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centrally Held</fullName>
                <default>true</default>
                <label>Centrally Held</label>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_GL_Code_Restriction__mdt/fields/Summary_Only__c.field-meta.xml
<CustomField>
    <fullName>Summary_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies whether the GL Code specified should be created in the row-level total column only.</description>
    <label>Summary Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ServiceGLCodeRestrictionFactory.cls
public with sharing class ServiceGLCodeRestrictionFactory {
    /** 
     * Replaces the custom metadata type query with a list of restrictions defined in a test class.
     */
    @TestVisible
    private static List<Service_GL_Code_Restriction__mdt> testRestrictions = new List<Service_GL_Code_Restriction__mdt>();

    public static List<Service_GL_Code_Restriction__mdt> getRestrictions(Set<String> serviceCategories) {
        // return testRestrictions if specified, otherwise run as normal 
        if (Test.isRunningTest() && testRestrictions.size() != 0) {
            return testRestrictions;
        }
        
        return [SELECT Id, Service_Category__c, Restriction_Type__c, GL_Code__c,Summary_only__c FROM Service_GL_Code_Restriction__mdt WHERE Service_Category__c IN :serviceCategories];
    }
}