force-app/main/default/objects/ContentVersion/fields/dohagedcare__Source__c.field-meta.xml
<CustomField>
    <fullName>dohagedcare__Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>MuleSoft Error File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Staging__c/File_Staging__c.object-meta.xml
<CustomObject>
    <description>This is the object for File Staging</description>
    <label>File Upload</label>
    <nameField>
        <label>File Upload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Uploads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Staging__c/fields/Error_FileId__c.field-meta.xml
<CustomField>
    <fullName>Error_FileId__c</fullName>
    <description>Error_FileId  will hold the Id of the result file that will come from Mule - after the file upload gets processed</description>
    <label>Error_FileId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>File Stagings</relationshipLabel>
    <relationshipName>File_Stagings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/recordTypes/QI.recordType-meta.xml
<RecordType>
    <fullName>QI</fullName>
    <active>true</active>
    <label>QI</label>
</RecordType>

force-app/main/default/objects/Quality_Indicator_Settings__mdt/Quality_Indicator_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Quality Indicator Settings</label>
    <pluralLabel>Quality Indicator Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Settings__mdt/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <defaultValue>365</defaultValue>
    <description>Batch job will delete records older than a certain number of days. This field is used to configure the number of days. As of April 6th, 2023, the default date is set to 365.</description>
    <label>QI Versioning Deletion Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QIErrorFileDelBatch.cls
/**
* author: Sharevreet Singh
* date: 06/05/2023
* description: Batch job to delete error files that are older than 12 months
    Criteria:
    --> ‘Reporting Period’ on ‘File Staging’ record is earlier than 4 quarters.
    --> ‘File Staging’ record type = QI
    --> Related error files exist on ‘File Staging’ records matching above criteria. Check 'Error_FileId__c' field
    --> Batch job to run quarterly
**/
public with sharing class QIErrorFileDelBatch implements Database.Batchable<sObject>{
    final static String MULE_ERROR = 'MuleSoft Error File';
    static Integer monthsInPast = (Integer) Quality_Indicator_Settings__mdt.getInstance('Error_File_Del_Month').Number_of_Days__c;
    static Date pastDate = Date.today().addMonths(-monthsInPast);
    static Id recordTypeId = Schema.SObjectType.File_Staging__c.getRecordTypeInfosByDeveloperName().get('QI').getRecordTypeId();

    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator(getQuery());
    }

    public void execute(Database.BatchableContext bc, List<File_Staging__c> scope)
    {
        if(!scope.isEmpty()) {
            Set<Id> latestConVerIds = new Set<Id>();
            List<ContentDocument> conDocToDel = new List<ContentDocument>();
            Map<Id, File_Staging__c> fileStagingRecords = new Map<Id, File_Staging__c> (scope);

            for(ContentDocumentLink cdl : [SELECT Id, ContentDocumentId, ContentDocument.LatestPublishedVersionId
                                            FROM ContentDocumentLink
                                            WHERE LinkedEntityId IN :fileStagingRecords.keySet()]) {
                latestConVerIds.add(cdl.ContentDocument.LatestPublishedVersionId);
            }

            for(ContentVersion conVer : [SELECT dohagedcare__Source__c, ContentDocumentId, CreatedDate 
                                        FROM ContentVersion 
                                        WHERE Id IN: latestConVerIds]) {
                if(conVer.dohagedcare__Source__c == MULE_ERROR) {
                    conDocToDel.add(new ContentDocument(Id = conVer.ContentDocumentId));
                }
            }

            if(conDocToDel.size() > 0) {
                try {
                    Database.delete(conDocToDel, false);
                }
                catch(Exception ex) {
                    dohagedcare.Logger.error(ex.getMessage(), ex, 'QIErrorFileDelBatch').log();
                }
            }
        }
    }

    public static String getQuery()
    {
        String query = 'SELECT Id ';
        query += 'FROM File_Staging__c ';
        query += 'WHERE RecordTypeId = \'' + recordTypeId  + '\' ';
        query += 'AND Reporting_Period__r.End_Date__c <= :pastDate';

        return query;
    }

    public void finish(Database.BatchableContext bc){
        //do nothing
    }
}