force-app/main/default/objects/Allotment__c/Allotment__c.object-meta.xml
<CustomObject>
    <label>Allotment</label>
    <nameField>
        <displayFormat>ALMT-{00000}</displayFormat>
        <label>Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allotment__c/recordTypes/Approved_Provider_Residential_ALM.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Residential_ALM</fullName>
    <active>true</active>
    <label>Approved Provider Residential</label>
</RecordType>

force-app/main/default/objects/BusinessLicense/recordTypes/Approved_Provider_Service.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Service</fullName>
    <active>true</active>
    <label>Approved Provider Service</label>
</RecordType>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{00000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/recordTypes/Variations_by_Provider_Secretary.recordType-meta.xml
<RecordType>
    <fullName>Variations_by_Provider_Secretary</fullName>
    <active>true</active>
    <label>Variations by Provider &amp; Secretary</label>
</RecordType>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GPMSCreateUpdatePlaceStatusTest.cls
@IsTest
public class GPMSCreateUpdatePlaceStatusTest {
    
    private static User currentUser = [SELECT Id From User WHERE Id = :UserInfo.getUserId()];
    
    @testSetup static void setup() {
        
        BusinessLicense serviceToInsert = GPMSTestUtility.getServiceByRecordType('Approved_Provider_Service');
        insert serviceToInsert;
        
        Allotment__c Allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',serviceToInsert.Id);
        insert Allotment;

        Integer placesCount = 5;
        List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
        insert places;
        
        Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
        insert evt;
                
    }
    
    @isTest static void testGPMSCreatePlaces() {
        
        Map<String,Object> inputMap = new Map<String,Object>();
        Map<String,Object> outMap = new Map<String,Object>();
        Map<String,Object> options = new Map<String,Object>();
        
        Event__c evt = [SELECT Id FROM Event__c LIMIT 1];
        Allotment__c Allotment = [SELECT Id FROM Allotment__c LIMIT 1];
        Places_Allotment__c place = [SELECT Id FROM Places_Allotment__c LIMIT 1];
        
        List<Map<String,Object>> places = new List<Map<String,Object>>();
        places.add(formatOmniPlace(place.Id));
        places.add(formatOmniPlace(place.Id));
        
        inputMap.put('Places', places);
        inputMap.put('AllotmentId', Allotment.Id);
        inputMap.put('EventId', evt.Id);
        inputMap.put('UpdateParentPacket', 'Yes');
        
        Map<String, Object> args = new Map<String, Object>();
        args.put('input', inputMap);
        args.put('output', outMap);
        args.put('options', options);
        
        GPMSCreateUpdatePlaceStatus getplaces = new GPMSCreateUpdatePlaceStatus();
        Object result = getplaces.call('getplaces',args);
        System.assertEquals(true, (Boolean)result,'Upsert places failed');
    }
    
    private static Map<String,Object> formatOmniPlace(String placeId){
        
        Map<String,Object> placeMAP = new Map<String,Object>();
        
        placeMAP.put('CareLevel', 'Residential');
        placeMAP.put('CareSetting', 'Residential');
        placeMAP.put('CareType', 'Flexible-MPS');
        placeMAP.put('NumberOfChanges', '3');
        placeMAP.put('Id', placeId);
       	return placeMAP;
        
    }

}