force-app/main/default/objects/Allotment__c/Allotment__c.object-meta.xml
<CustomObject>
    <label>Allotment</label>
    <nameField>
        <displayFormat>ALMT-{00000}</displayFormat>
        <label>Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allotment__c/fields/Care_Level__c.field-meta.xml
<CustomField>
    <fullName>Care_Level__c</fullName>
    <label>Care Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short Term Restorative Care(STRC)</fullName>
            </value>
            <value>
                <fullName>Transition</fullName>
            </value>
            <value>
                <fullName>High(Innovative Pool)</fullName>
            </value>
            <value>
                <fullName>Low(Innovative Pool)</fullName>
            </value>
            <value>
                <fullName>Community(Innovative Pool)</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Residential(MPS)</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care(MPS)</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Multiple-Purpose Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/recordTypes/Approved_Provider_Residential_ALM.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Residential_ALM</fullName>
    <active>true</active>
    <label>Approved Provider Residential</label>
</RecordType>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/CHSP_Service.recordType-meta.xml
<RecordType>
    <fullName>CHSP_Service</fullName>
    <active>true</active>
    <label>CHSP Service</label>
</RecordType>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{00000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Batch_Event_Completed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Event_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Event Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Cessation_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Cessation_Effective_Date__c</fullName>
    <label>Cessation Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Care_Setting_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Care_Setting_Effective_Date__c</fullName>
    <description>The date to change the care setting</description>
    <label>Care Setting Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Conversion_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Conversion_Effective_Date__c</fullName>
    <description>The date to convert care level mix</description>
    <label>Conversion Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Date_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Date_Effective_From__c</fullName>
    <description>Indicates the date that the ceasing took effect.</description>
    <label>Date Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Proposed_Operational_Date__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Proposed_Operational_Date__c</fullName>
    <description>The proposed operation date for bring online event</description>
    <label>Proposed Operational Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Proposed_Variation_Day__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Proposed_Variation_Day__c</fullName>
    <label>Proposed Variation Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to show the Status of the Event.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting Response to Notice to Resolve</fullName>
            </value>
            <value>
                <fullName>Vetoed</fullName>
            </value>
            <value>
                <fullName>Transfer: Activated</fullName>
            </value>
            <value>
                <fullName>Transfer: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Pending RFI</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not Revoked</fullName>
            </value>
            <value>
                <fullName>Revoked: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cessation Applied</fullName>
            </value>
            <value>
                <fullName>Automatic Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Vetoed by Department</fullName>
            </value>
            <value>
                <fullName>Vetoed by AAT</fullName>
            </value>
            <value>
                <fullName>Variation: Activated</fullName>
            </value>
            <value>
                <fullName>Variation: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Variation: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Approved by Department</fullName>
            </value>
            <value>
                <fullName>Not Approved by AAT</fullName>
            </value>
            <value>
                <fullName>Approved: Activated</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
                <isActive>false</isActive>
                <label>Ceased</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Variations_by_Provider_Secretary.recordType-meta.xml
<RecordType>
    <fullName>Variations_by_Provider_Secretary</fullName>
    <active>true</active>
    <label>Variations by Provider &amp; Secretary</label>
</RecordType>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Care_Level__c.field-meta.xml
<CustomField>
    <fullName>Care_Level__c</fullName>
    <label>Care Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Transition Care</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>STRC</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <label>Current</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Parent_Packet__c.field-meta.xml
<CustomField>
    <fullName>Parent_Packet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent place of the current place</description>
    <label>Parent Packet</label>
    <referenceTo>Places_Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Status_of_Places__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Places__c</fullName>
    <description>Status of current place packet</description>
    <label>Status of Places</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GPMSScheduledEventActionsBatchTest.cls
/****************************************************************************************************
* @CreatedBy   : Yohan Perera
* @CreatedDate : 11-01-2023
* @Description : Test class for GPMSScheduledEventActionsBatch
* @Test Class  : GPMSScheduledEventActionsBatchTest
*****************************************************************************************************/
@isTest
private class GPMSScheduledEventActionsBatchTest {

    public static final String TEST_SERVICE = 'Squad C Residential Care Testing';

    private static User currentUser = TestDataFactory.createGPMSTestUser();

    @isTest
    static void testBringOnlineEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processBringOnlineEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testEventsBatchSchedule() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_BRING_ONLINE;
            evt.GPMS_Proposed_Operational_Date__c = Date.today() - 1;

            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            String jobId = System.schedule('GPMSScheduledEventActionsBatchX', '0 0 0 3 9 ? 2050', new GPMSScheduledEventActionsBatch());

            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
            System.assertEquals(0, ct.TimesTriggered);

            Test.stopTest();
        }

    }

    @isTest
    static void testBringOnlineEventsBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_BRING_ONLINE;
            evt.GPMS_Proposed_Operational_Date__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_APPROVED;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }

    @isTest
    static void testCeaseS14EventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Operational';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processCeaseS14_9Events',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testCeaseS14Batch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_CEASE_S14_9;
            evt.Cessation_Effective_Date__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_PENDING;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Operational';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }

    @isTest
    static void testSurrenderEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processSurrenderEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testSurrenderBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_SURRENDER;
            evt.GPMS_Date_Effective_From__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_PENDING;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }

    @isTest
    static void testRelinquishEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Operational';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processRelinquishEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testRelinquishBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_RELINQUISH;
            evt.GPMS_Date_Effective_From__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_APPROVED;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Operational';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }

    @isTest
    static void testRevocationEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processRevocationEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testRevocationBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_REVOKE;
            evt.GPMS_Date_Effective_From__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_REVOKED;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }


    @isTest
    static void testDeedofVariationEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processDeedOfVariationEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testDeedofVariationBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_DEED_OF_VARIATION;
            evt.GPMS_Conversion_Effective_Date__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_PENDING;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
                pa.Care_Level__c = 'Residential';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }

    @isTest
    static void testChangeCareSettingsEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processChangeCareSettingsEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testChangeCareSettingsBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_CHANGE_CARE_SETTING;
            evt.GPMS_Care_Setting_Effective_Date__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_PENDING;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
                pa.Care_Level__c = 'Residential';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }

    @isTest
    static void testNATSIFACCeaseEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Operational';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processNATSIFACCeaseEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testNATSIFACCeaseBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_NATSIFAC_CEASE;
            evt.GPMS_Date_Effective_From__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_APPROVED;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Operational';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }

    @isTest
    static void testNATSIFACReinstateEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Ceased';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processNATSIFACReinstateEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testNATSIFACReinstateBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_NATSIFAC_REINSTATE_PLACES;
            evt.GPMS_Date_Effective_From__c = Date.today() - 1;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_APPROVED;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Ceased';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);

        }

    }

    @isTest
    static void testCeaseEventsIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processCeaseEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

    @isTest
    static void testVariationBatch() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.RecordTypeId = GPMSScheduledEventActionsBatch.RT_EVENT_VARIATION;
            evt.Status__c = GPMSScheduledEventActionsBatch.EVENT_STATUS_VARIATION_ACTIVATED;
            evt.GPMS_Proposed_Variation_Day__c = System.Today()-2;
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
                pa.Event__c = evt.Id;
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;


            Test.startTest();

            GPMSScheduledEventActionsBatch b = new GPMSScheduledEventActionsBatch();
            Database.executeBatch(b);

            Test.stopTest();

            Event__c evtResult = [SELECT Activated_Date__c, GPMS_Proposed_Variation_Day__c, Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
            System.assertEquals(true, evtResult.Activated_Date__c == evtResult.GPMS_Proposed_Variation_Day__c);

        }

    }

	@isTest
    static void testVariationIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processVariationEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }

	@isTest
    static void testPAVariationIP() {

        System.runAs(currentUser){

            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational');
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            insert service;

            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;

            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            insert evt;

            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
            }
            insert places;

            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;

            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();


            inputMap.put('EventId', evt.Id);

            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);

            Test.startTest();

            GPMSPerformEventAction performAction = new GPMSPerformEventAction();
            performAction.call('processPAVariationEvents',args);

            Test.stopTest();

            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }

    }
}