force-app/main/default/objects/Allotment__c/Allotment__c.object-meta.xml
<CustomObject>
    <label>Allotment</label>
    <nameField>
        <displayFormat>ALMT-{00000}</displayFormat>
        <label>Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allotment__c/fields/Number_of_Places__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Places__c</fullName>
    <label>Number of Places</label>
    <summarizedField>Places_Allotment__c.GPMS_Number_of_Remaining__c</summarizedField>
    <summaryFilterItems>
        <field>Places_Allotment__c.Current__c</field>
        <operation>equals</operation>
        <value>Yes</value>
    </summaryFilterItems>
    <summaryForeignKey>Places_Allotment__c.Allotment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S15-1 Provisional allocation (Provisional)</fullName>
            </value>
            <value>
                <fullName>S15-1 Determined to be in effect at time of allocation (Operational)</fullName>
            </value>
            <value>
                <fullName>Funding agreement signed (operational)</fullName>
            </value>
            <value>
                <fullName>Expired under S14-9(4)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{00000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to show the Status of the Event.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting Response to Notice to Resolve</fullName>
            </value>
            <value>
                <fullName>Vetoed</fullName>
            </value>
            <value>
                <fullName>Transfer: Activated</fullName>
            </value>
            <value>
                <fullName>Transfer: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Pending RFI</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not Revoked</fullName>
            </value>
            <value>
                <fullName>Revoked: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cessation Applied</fullName>
            </value>
            <value>
                <fullName>Automatic Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Vetoed by Department</fullName>
            </value>
            <value>
                <fullName>Vetoed by AAT</fullName>
            </value>
            <value>
                <fullName>Variation: Activated</fullName>
            </value>
            <value>
                <fullName>Variation: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Variation: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Approved by Department</fullName>
            </value>
            <value>
                <fullName>Not Approved by AAT</fullName>
            </value>
            <value>
                <fullName>Approved: Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <description>Places: Transfer - S16-13/S16-1</description>
    <label>Transfer</label>
</RecordType>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <label>Current</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/GPMS_Number_of_Remaining__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Number_of_Remaining__c</fullName>
    <description>Number of remaining places in the variation process</description>
    <formula>Number_of_Places__c -  GPMS_Number_of_Variation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Number_of_Places__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Places__c</fullName>
    <label>Number of Places</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Parent_Packet__c.field-meta.xml
<CustomField>
    <fullName>Parent_Packet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent place of the current place</description>
    <label>Parent Packet</label>
    <referenceTo>Places_Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Status_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Effective_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <description>Status reason of current place packet</description>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S15-1 Provisional allocation (Provisional)</fullName>
            </value>
            <value>
                <fullName>S15-1 Determined to be in effect at time of allocation (Operational)</fullName>
            </value>
            <value>
                <fullName>Funding agreement signed (operational)</fullName>
            </value>
            <value>
                <fullName>S15-5 provider reduces number of places in provisional allocation</fullName>
            </value>
            <value>
                <fullName>S15-6 Provider surrenders provisional allocation</fullName>
            </value>
            <value>
                <fullName>S15-2 Not action taken in relation to provisional allocation</fullName>
                <label>S15-2 No action taken in relation to provisional allocation</label>
            </value>
            <value>
                <fullName>Places transferred in as offline</fullName>
            </value>
            <value>
                <fullName>Places varied in as offline</fullName>
            </value>
            <value>
                <fullName>Offline at time of migration</fullName>
            </value>
            <value>
                <fullName>Rebuilding</fullName>
            </value>
            <value>
                <fullName>Places not being used</fullName>
            </value>
            <value>
                <fullName>Provider expected to apply for transfer of places</fullName>
            </value>
            <value>
                <fullName>Provider expected to apply for variation of places</fullName>
            </value>
            <value>
                <fullName>Provider undertaking strategic review</fullName>
            </value>
            <value>
                <fullName>S18-2 Provider relinquishes places</fullName>
            </value>
            <value>
                <fullName>Funding agreement ceased</fullName>
            </value>
            <value>
                <fullName>Funding agreement reinstated</fullName>
            </value>
            <value>
                <fullName>Expired under S14-9(4)</fullName>
            </value>
            <value>
                <fullName>Places ceased under s18-1(c)</fullName>
            </value>
            <value>
                <fullName>Revocation of Provider’s Approval Status[s10-3]</fullName>
            </value>
            <value>
                <fullName>Revocation of Provisional Places, conditions not met[s15-4(1)]</fullName>
            </value>
            <value>
                <fullName>Revocation of Places [S66- 1(D)]</fullName>
            </value>
            <value>
                <fullName>Revocation of unused Places [S18-5(1)]</fullName>
            </value>
            <value>
                <fullName>S15-3 Application for determination approved</fullName>
            </value>
            <value>
                <fullName>Offline places made operational</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Delivery_Area__c/Service_Delivery_Area__c.object-meta.xml
<CustomObject>
    <label>Service Delivery Area</label>
    <nameField>
        <displayFormat>SDA-{0000000}</displayFormat>
        <label>Service Delivery Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Delivery Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Delivery_Area__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipLabel>Service Delivery Area</relationshipLabel>
    <relationshipName>Service_Delivery_Area</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Delivery_Area__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Service Delivery Area</relationshipLabel>
    <relationshipName>Service_Delivery_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Delivery_Area__c/fields/Number_of_Places__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Places__c</fullName>
    <label>Number of Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Delivery_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Non-current</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Approved-not activated</fullName>
            </value>
            <value>
                <fullName>Not approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GPMSTransferEventUpdatePA.cls
/****************************************************************************************************
* @CreatedBy   : Accenture Development Team
* @CreatedDate : 02-FEB-2023
* @Description : Handles the Logic to Update Places Allotment for Transfer Event.
* @Test Class  : GPMSTransferEventUpdatePATest
*****************************************************************************************************/
global with sharing class GPMSTransferEventUpdatePA implements Callable{


    public Object call(String action, Map<String, Object> args) {

        try {
            Map<String, Object> input = (Map<String, Object>)args.get('input');
            Map<String, Object> output = (Map<String, Object>)args.get('output');
            return invokeMethod(action, input, output);
        } catch (exception exp) {
            dohagedcare.Logger.error(exp.getMessage(),exp,'GPMS').Log();
            return true;
        }

    }

    public Boolean invokeMethod(String methodName, Map<String,Object> input, Map<String,Object> output) {

        boolean result = false;

        if (input.get('EventId') != null) {
            Event__c ev = new Event__c(Id = (String)input.get('EventId'));

            List<Places_Allotment__c> placesToUpdateList = new List<Places_Allotment__c>();
            List<Event__c> eventsToUpdateList = new List<Event__c>();
            List<Service_Delivery_Area__c> sdasToUpdateList = new List<Service_Delivery_Area__c>();

            Map<String, Object>inputEvents = new Map<String, Object>();
            inputEvents.put(ev.Id, ev);

            try {
                if ('processTranferEvents'.equalsIgnoreCase(methodName)) {
                    processTranferEvents(inputEvents, placesToUpdateList, sdasToUpdateList, eventsToUpdateList, true);
                }
                result = true;

            } catch (Exception e){
                dohagedcare.Logger.error(e.getMessage(),e, 'GPMS').Log();
                result = false;
            }

        }

        return result;
    }

    public void processTranferEvents(Map<String,Object> inputEvents, List<Places_Allotment__c> placesToUpdateList, List<Service_Delivery_Area__c> sdasToUpdateList, List<Event__c> eventsToUpdateList, boolean isIP) {
        Set<String> eventsSet = new Set<String>(inputEvents.keySet());
        updatePendingPlacesAllotment(eventsSet, placesToUpdateList, eventsToUpdateList, isIP);

        GPMSPerformEventAction.updateTransferSDAs(eventsSet, sdasToUpdateList, isIP);
    }

    //******************Update Places Allotment**********************//
    private void updatePendingPlacesAllotment(Set<String> eventIdSet, List<Places_Allotment__c> placesToUpdateList, List<Event__c> eventsToUpdateList, boolean isIP) {

        List<Places_Allotment__c> placesList = [SELECT Id,Number_of_Places__c,Allotment__c,Parent_Packet__c,Current__c, Event__r.Status__c,
                                                GPMS_Number_of_Remaining__c, Status_Effective_Date__c,
                                                Status_Reason__c,Status_of_Places__c,First_Brought_into_Effect_Date__c, GPMS_Number_of_Variation__c
                                                FROM Places_Allotment__c WHERE Event__c IN :eventIdSet
                                                AND (Current__c = 'Pending')
                                                AND (Event__r.Status__c = 'Transfer: Not to be Activated')];

        if(placesList != null && !placesList.isEmpty()) {
            for(Places_Allotment__c newPlace : placesList) {
                newPlace.Current__c = 'Removed';
                placesToUpdateList.add(newPlace);
            }
        }

        for (String eventId : eventIdSet) {
            eventsToUpdateList.add(new Event__c(Id = eventId, Batch_Event_Completed__c = true));
        }

        if (isIP) {
            if(!placesToUpdateList.isEmpty()) {
                update placesToUpdateList;
            }

            if(!eventsToUpdateList.isEmpty()) {
                update eventsToUpdateList;
            }
        }
    }
}