force-app/main/default/objects/Allotment__c/Allotment__c.object-meta.xml
<CustomObject>
    <label>Allotment</label>
    <nameField>
        <displayFormat>ALMT-{00000}</displayFormat>
        <label>Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allotment__c/fields/Care_Level__c.field-meta.xml
<CustomField>
    <fullName>Care_Level__c</fullName>
    <label>Care Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short Term Restorative Care(STRC)</fullName>
            </value>
            <value>
                <fullName>Transition</fullName>
            </value>
            <value>
                <fullName>High(Innovative Pool)</fullName>
            </value>
            <value>
                <fullName>Low(Innovative Pool)</fullName>
            </value>
            <value>
                <fullName>Community(Innovative Pool)</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Residential(MPS)</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care(MPS)</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Multiple-Purpose Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Care_Setting__c.field-meta.xml
<CustomField>
    <fullName>Care_Setting__c</fullName>
    <label>Care Setting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>To be confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>NATSIFAC</fullName>
            </value>
            <value>
                <fullName>Innovative Pool</fullName>
                <isActive>false</isActive>
                <label>Innovative Pool</label>
            </value>
            <value>
                <fullName>Multiple-Purpose Service</fullName>
                <isActive>false</isActive>
                <label>Multiple-Purpose Service</label>
            </value>
            <value>
                <fullName>Short Term Restorative Care(STRC)</fullName>
                <isActive>false</isActive>
                <label>Short Term Restorative Care(STRC)</label>
            </value>
            <value>
                <fullName>Transition Care</fullName>
                <isActive>false</isActive>
                <label>Transition Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Number_of_Places__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Places__c</fullName>
    <label>Number of Places</label>
    <summarizedField>Places_Allotment__c.GPMS_Number_of_Remaining__c</summarizedField>
    <summaryFilterItems>
        <field>Places_Allotment__c.Current__c</field>
        <operation>equals</operation>
        <value>Yes</value>
    </summaryFilterItems>
    <summaryForeignKey>Places_Allotment__c.Allotment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/PA_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>PA_Period_End_Date__c</fullName>
    <label>PA Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <description>The name of the related Service.</description>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Allotments</relationshipLabel>
    <relationshipName>Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Allotment__c/Event_Allotment__c.object-meta.xml
<CustomObject>
    <label>Event Allotment</label>
    <nameField>
        <displayFormat>EVAT-{000000}</displayFormat>
        <label>Event Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipLabel>Event Summary</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Allotment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Allotments</relationshipLabel>
    <relationshipName>Allotments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Care_Level__c.field-meta.xml
<CustomField>
    <fullName>Care_Level__c</fullName>
    <label>Care Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Transition Care</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>STRC</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Care_Setting__c.field-meta.xml
<CustomField>
    <fullName>Care_Setting__c</fullName>
    <label>Care Setting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>To be Confirmed</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Care_Setting_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Care_Setting_Effective_Date__c</fullName>
    <label>Care Setting Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <label>Current</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/First_Brought_into_Effect_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Brought_into_Effect_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>First Brought into Effect Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Number_of_Places__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Places__c</fullName>
    <label>Number of Places</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Status_of_Places__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Places__c</fullName>
    <description>Status of current place packet</description>
    <label>Status of Places</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Event__c/Service_Event__c.object-meta.xml
<CustomObject>
    <label>Service Event</label>
    <nameField>
        <displayFormat>SEVT-{000000}</displayFormat>
        <label>Service Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Service Events</relationshipLabel>
    <relationshipName>Service_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GPMSCeasePlacesAllotmentBatch.cls
/****************************************************************************************************
* @CreatedBy   : Yohan Perera
* @CreatedDate : 6-12-2022
* @Description : Batch class for ceasing Provisional PAs
* @Test Class  : 
*****************************************************************************************************/
public with sharing class GPMSCeasePlacesAllotmentBatch implements Database.Batchable<sObject>,Database.Stateful {
    
    public static final String PA_STATUS_PROVISIONAL = 'Provisional';
    public static final String PA_STATUS_CEASED = 'Ceased';
    public static final String PA_STATUS_REASON = 'S15-2 Not action taken in relation to provisional allocation';
    public static final String PA_CURRENT = 'Yes';
    public static final String PA_CURRENT_NO = 'No';
    public static final String PA_CEASE = 'Cease PA';
    public static final String EVENT_STATUS_PENDING = 'Pending';
    public static final String PA_CURRENT_PENDING = 'Pending';

    public static final Id RT_EVENT_CEASE = Schema.SObjectType.Event__c.getRecordTypeInfosByDeveloperName().get('GPMS_Cease_Places').getRecordTypeId();
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Current__c, Care_Type__c, Care_Level__c, Care_Setting__c, Care_Setting_Effective_Date__c, Number_of_Places__c, First_Brought_into_Effect_Date__c, Allotment__c,'
            		+ ' Allotment__r.PA_Period_End_Date__c, Allotment__r.Service_Name__c, Allotment__r.Service_Name__r.AccountId FROM Places_Allotment__c'
            		+ ' WHERE Status_of_Places__c = :PA_STATUS_PROVISIONAL AND Current__c = :PA_CURRENT AND Allotment__r.PA_Period_End_Date__c < TODAY';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Places_Allotment__c> scope) {
        
        Map<Id, Places_Allotment__c> allotmentToPa = new Map<Id, Places_Allotment__c>();
        for (Places_Allotment__c pa : scope) {
            allotmentToPa.put(pa.Allotment__c, pa);
        }

        GPMSEventStatusCheck statusCheck = new GPMSEventStatusCheck();
        Map<Id, Places_Allotment__c> paIdToPaMap = new Map<Id, Places_Allotment__c>();
        
        Map<Id, Event__c> serviceToPendingEventsMap = new Map<Id, Event__c>();
        
        try{
            for (Places_Allotment__c pa : allotmentToPa.values()) {
                if (pa.Allotment__r.Service_Name__c != null) {
                    serviceToPendingEventsMap.put(pa.Allotment__r.Service_Name__c, null);
                }
            }
            
            List<String> statusList = statusCheck.getStatusesList(PA_CEASE);
            for (Event__c event : [SELECT Id, Service__c FROM Event__c WHERE Service__c IN :serviceToPendingEventsMap.keySet() AND Status__c IN :statusList]) {
                serviceToPendingEventsMap.put(event.Service__c, event);
            }
            
            Map<Id, Event__c> paToNewEventRecords = new Map<Id, Event__c>();
            
            for (Places_Allotment__c pa : allotmentToPa.values()) {
                //Create the Event only when there are no Pending Events related to the Allotment and one event per Allotments even thought multiple Pending PAs exist under a single Allotment
                if (serviceToPendingEventsMap.get(pa.Allotment__r.Service_Name__c) == null) {
                    Event__c ceaseStatus = new Event__c(); 
                    ceaseStatus.Status__c = EVENT_STATUS_PENDING;
                    ceaseStatus.Service__c = pa.Allotment__r.Service_Name__c; 
                    ceaseStatus.Account_From__c = pa.Allotment__r.Service_Name__r.AccountId;
                    ceaseStatus.Status_Date__c = Date.today();
                    ceaseStatus.Event_Type__c = PA_CEASE;
                    ceaseStatus.RecordTypeId= RT_EVENT_CEASE;
                    paToNewEventRecords.put(pa.Id, ceaseStatus);
                    
                    paIdToPaMap.put(pa.Id, pa);
                }
            }
            insert paToNewEventRecords.values();
            
            List<Service_Event__c> serviceEventsToInsert = new List<Service_Event__c>();
            List<Event_Allotment__c> eventAllotmentsToInsert = new List<Event_Allotment__c>();
            List<Places_Allotment__c> pasToInsert = new List<Places_Allotment__c>();
            
            for (Id paId: paToNewEventRecords.keySet()) {
                Service_Event__c se = new Service_Event__c();
                se.Service__c = paToNewEventRecords.get(paId).Service__c;
                se.Event__c = paToNewEventRecords.get(paId).Id;
                serviceEventsToInsert.add(se);
                
                Places_Allotment__c source = paIdToPaMap.get(paId);
                
                Event_Allotment__c ea = new Event_Allotment__c();
                ea.Event__c = paToNewEventRecords.get(paId).Id;
                ea.Allotment__c = source.Allotment__c;
                eventAllotmentsToInsert.add(ea);
                          
                Places_Allotment__c paPending = new Places_Allotment__c(Allotment__c = source.Allotment__c
                                                                        , Event__c = paToNewEventRecords.get(paId).Id, Current__c = PA_CURRENT_PENDING
                                                                        , Status_of_Places__c = PA_STATUS_CEASED, Parent_Packet__c = paId
                                                                        , Care_Type__c = source.Care_Type__c
                                                                        , Care_Level__c = source.Care_Level__c
                                                                        , Care_Setting__c = source.Care_Setting__c, Care_Setting_Effective_Date__c = source.Care_Setting_Effective_Date__c
                                                                        , Number_of_Places__c = source.Number_of_Places__c, First_Brought_into_Effect_Date__c = source.First_Brought_into_Effect_Date__c
                                                                        , Status_Reason__c = PA_STATUS_REASON);
                pasToInsert.add(paPending);
            }
            
            insert eventAllotmentsToInsert;
            upsert pasToInsert;
        } catch(Exception exp) {
            dohagedcare.Logger.error(exp.getMessage(),exp,'GPMS').Log(); 
        }
    }
    
    public void finish(Database.BatchableContext bc) {
        //Nothing to do here
    }
}