force-app/main/default/objects/Allotment__c/Allotment__c.object-meta.xml
<CustomObject>
    <label>Allotment</label>
    <nameField>
        <displayFormat>ALMT-{00000}</displayFormat>
        <label>Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allotment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/recordTypes/Approved_Provider_Residential_ALM.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Residential_ALM</fullName>
    <active>true</active>
    <label>Approved Provider Residential</label>
</RecordType>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/CHSP_Service.recordType-meta.xml
<RecordType>
    <fullName>CHSP_Service</fullName>
    <active>true</active>
    <label>CHSP Service</label>
</RecordType>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{00000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Batch_Event_Completed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Event_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Event Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to show the Status of the Event.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting Response to Notice to Resolve</fullName>
            </value>
            <value>
                <fullName>Vetoed</fullName>
            </value>
            <value>
                <fullName>Transfer: Activated</fullName>
            </value>
            <value>
                <fullName>Transfer: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Pending RFI</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not Revoked</fullName>
            </value>
            <value>
                <fullName>Revoked: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cessation Applied</fullName>
            </value>
            <value>
                <fullName>Automatic Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Vetoed by Department</fullName>
            </value>
            <value>
                <fullName>Vetoed by AAT</fullName>
            </value>
            <value>
                <fullName>Variation: Activated</fullName>
            </value>
            <value>
                <fullName>Variation: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Variation: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Approved by Department</fullName>
            </value>
            <value>
                <fullName>Not Approved by AAT</fullName>
            </value>
            <value>
                <fullName>Approved: Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <description>Places: Transfer - S16-13/S16-1</description>
    <label>Transfer</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/Variations_by_Provider_Secretary.recordType-meta.xml
<RecordType>
    <fullName>Variations_by_Provider_Secretary</fullName>
    <active>true</active>
    <label>Variations by Provider &amp; Secretary</label>
</RecordType>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <label>Current</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Parent_Packet__c.field-meta.xml
<CustomField>
    <fullName>Parent_Packet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent place of the current place</description>
    <label>Parent Packet</label>
    <referenceTo>Places_Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Status_of_Places__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Places__c</fullName>
    <description>Status of current place packet</description>
    <label>Status of Places</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GPMSTransferEventUpdatePATest.cls
/****************************************************************************************************
* @CreatedBy   : Namrata Gurjar
* @CreatedDate : 03-02-2023
* @Description : Test class for GPMSTransferEventUpdatePA
* @Test Class  : GPMSTransferEventUpdatePATest
*****************************************************************************************************/
@isTest
private class GPMSTransferEventUpdatePATest {
    
    public static final String TEST_SERVICE = 'Squad C Residential Care Testing';
    
    private static User currentUser = TestDataFactory.createGPMSTestUser();
    
    @isTest
    static void testUpdateTransferEventsPA() {
        
        System.runAs(currentUser){
            
            BusinessLicense service = new BusinessLicense(Name = TEST_SERVICE, Status = 'Operational'); 
            service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
            service.Status_Date__c =  Date.today();
            insert service;
            
            Allotment__c allotment = GPMSTestUtility.getAllotment('Approved_Provider_Residential_ALM',service.Id);
            insert Allotment;
            
            Event__c evt = GPMSTestUtility.getPlaceEvent('Variations_by_Provider_Secretary');
            evt.Status__c = 'Transfer: Not to be Activated';
            insert evt;
            
            Integer placesCount = 5;
            List<Places_Allotment__c> places = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : places) {
                pa.Status_of_Places__c = 'Provisional';
                pa.Event__c = evt.Id;
            }
            insert places;
            
            List<Places_Allotment__c> childPlaces = GPMSTestUtility.getPlaces(placesCount,Allotment.Id);
            for (Places_Allotment__c pa : childPlaces) {
                pa.Current__c = 'Pending';
                pa.Parent_Packet__c = places.get(0).Id;
                pa.Event__c = evt.Id;
            }
            insert childPlaces;
            
            Map<String,Object> inputMap = new Map<String,Object>();
            Map<String,Object> outMap = new Map<String,Object>();
            Map<String,Object> options = new Map<String,Object>();
            

            inputMap.put('EventId', evt.Id);
            
            Map<String, Object> args = new Map<String, Object>();
            args.put('input', inputMap);
            args.put('output', outMap);
            args.put('options', options);
            
            Test.startTest();
            
            GPMSTransferEventUpdatePA updatePA = new GPMSTransferEventUpdatePA();
            updatePA.call('processTranferEvents',args);
            
            Test.stopTest();
            
            Event__c evtResult = [SELECT Batch_Event_Completed__c FROM Event__c WHERE Id = :evt.Id];
            System.assertEquals(true, evtResult.Batch_Event_Completed__c);
        }
    }

  }