force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/Contact/fields/GPMS_myGov_Vanguard_Id__c.field-meta.xml
<CustomField>
    <fullName>GPMS_myGov_Vanguard_Id__c</fullName>
    <description>Used for storing mygov/vanguard Id</description>
    <externalId>true</externalId>
    <label>myGov/Vanguard Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/GPMS_Portal_Role__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Portal_Role__c</fullName>
    <description>Role of the portal users. Used for determining their access.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Organisation Administrator</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Staff Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Self_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Self_Registration_Status__c</fullName>
    <description>Used for determining if the user has completed verification</description>
    <label>Self Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Verified</fullName>
                <default>true</default>
                <label>Not Verified</label>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/GPMS_Portal_Role__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Portal_Role__c</fullName>
    <description>Role of the portal users. Used for determining their access.</description>
    <label>Portal Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Organisation Administrator</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Staff Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SAMLSSOJITHandlerVanguardTest.cls
@isTest
public class SAMLSSOJITHandlerVanguardTest {
    @testSetup
    static void jitTestSetup() {
        User testUser = TestDataFactory.createSystemAdminUser();

        Test.startTest();
        System.runAs(testUser){
            final String fedId = 'jitHandlerUser30@gmail.com';
            Account newAPAccount = new Account();
            newAPAccount.Name = 'Dummy Shell Account';
            newAPAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Approved_Provider').getRecordTypeId();
            insert newAPAccount;
            Contact newPortalContact = new Contact();
            newPortalContact.Salutation = 'Mr';
            newPortalContact.FirstName = 'new portal contact';
            newPortalContact.LastName = 'Last Name';
            newPortalContact.AccountId = newAPAccount.Id;
            newPortalContact.Email = fedId;
            newPortalContact.GPMS_myGov_Vanguard_Id__c = fedId;
            newPortalContact.GPMS_Portal_Role__c = 'Organisation Administrator';
            newPortalContact.Self_Registration_Status__c = 'Not Verified';
            insert newPortalContact;

            final String email = 'service_provider_portal@gpms.force.com';
            Profile guestUserProfile = [SELECT Id FROM profile WHERE name =: 'Service Provider Portal Profile' LIMIT 1];
            User guestUser = new User();
            guestUser.FirstName = 'guest User01';
            guestUser.LastName = 'last name';
            guestUser.Email = email;
            guestUser.Username = email;
            guestUser.ProfileId = guestUserProfile.Id;
            guestUser.TimeZoneSidKey = 'Australia/Sydney';
            guestUser.LocaleSidKey = 'en_AU';
            guestUser.LanguageLocaleKey = 'en_US';
            guestUser.EmailEncodingKey = 'UTF-8';
            guestUser.IsActive = TRUE;
            guestUser.Alias = 'guest01';
            insert(guestUser);
        }
        Test.stopTest();
    }
    @isTest
    static void testCreateUser() {
        User guestUser = [SELECT Id FROM User WHERE email =:'service_provider_portal@gpms.force.com' LIMIT 1];
        Map<String,String> attributes = new Map < String, String > {
            'http://vanguard.ebusiness.gov.au/2008/06/identity/claims/abn' => '12345678978',
                'http://vanguard.ebusiness.gov.au/2008/06/identity/claims/givennames' => 'prospect cont FName',
                'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname' => 'prospect cont LName'
                };
        SAMLSSOJITHandlerVanguard jitHandler = new SAMLSSOJITHandlerVanguard();
        test.startTest();
        system.runAs(guestUser){
            jitHandler.createUser(null, null, null, 'jitHandlerUser30@gmail.com', attributes, null);
        }
        test.stopTest();
    }
}