force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Commonwealth_Home_Support_Programme.recordType-meta.xml
<RecordType>
    <fullName>Commonwealth_Home_Support_Programme</fullName>
    <active>true</active>
    <description>Commonwealth Home Support Programme</description>
    <label>Commonwealth Home Support Programme</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/National_Aboriginal_and_Torres_Strait_Islander_Flexible_Aged_Care.recordType-meta.xml
<RecordType>
    <fullName>National_Aboriginal_and_Torres_Strait_Islander_Flexible_Aged_Care</fullName>
    <active>true</active>
    <description>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</description>
    <label>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</label>
</RecordType>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Accounts</label>
    <nameField>
        <displayFormat>ARL-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/Account_From_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_From_Id__c</fullName>
    <description>Parent account record to link another account record.</description>
    <label>Account From</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 AND 4) OR (1 AND 2)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account, Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation, Provider to Management Company, Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account From)</relationshipLabel>
    <relationshipName>Account_Relationship_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Account_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_To_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account To</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Management Company, Administrative Organisation, Service Delivery Organisation, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Management Company</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Management Company</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Delivery Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account To)</relationshipLabel>
    <relationshipName>Account_Relationship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ACO_Group__c/ACO_Group__c.object-meta.xml
<CustomObject>
    <label>ACO Group</label>
    <nameField>
        <label>ACO Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACO Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ACO_Group__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Provide any additional comments to why group was created or how it should be used</description>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ACO_Group__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Provide insight to why group was formed to help inform usage</description>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Common controlling interest</fullName>
            </value>
            <value>
                <fullName>Financial dependencies</fullName>
            </value>
            <value>
                <fullName>Common Ownership</fullName>
            </value>
            <value>
                <fullName>Common Key Personnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACO_Group_Member__c/ACO_Group_Member__c.object-meta.xml
<CustomObject>
    <description>Acts as a junction between ACO Group and Account</description>
    <label>ACO Group Member</label>
    <nameField>
        <displayFormat>ACGM-{00000}</displayFormat>
        <label>ACO Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACO Group Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ACO_Group_Member__c/fields/ACO_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>ACO_Group_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACO Group Name</label>
    <referenceTo>ACO_Group__c</referenceTo>
    <relationshipLabel>ACO Group Members (ACO Group Name)</relationshipLabel>
    <relationshipName>ACO_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ACO_Group_Member__c/fields/ACOs_to_link__c.field-meta.xml
<CustomField>
    <fullName>ACOs_to_link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Allows users to select from existing ACOs</description>
    <label>ACO to link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ACO Group Members (ACOs to link)</relationshipLabel>
    <relationshipName>ACO_Group_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GPMSRelatedProviderController.cls
global with sharing class GPMSRelatedProviderController implements omnistudio.VlocityOpenInterface{
    
    global Boolean invokeMethod (String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options){
        Boolean result=true;
        
        try{
            if(methodName.equals('fetchAcoGrpMember')){
                fetchAcoGrpMember(inputMap,outMap);
            }else if(methodName.equals('fetchSingleAcoGrpMember')){
                fetchSingleAcoGrpMember(inputMap,outMap);
            }else if(methodName.equals('fetchAcoGrp')){
                fetchAcoGrp(inputMap,outMap);
            }
        } catch (Exception e){
            result = false;
        }
        return result;
    }
    
    public void fetchAcoGrp ( Map<String,Object> inputMap,Map<String,Object> outMap){
        
        String accid = (String)inputMap.get('AccountId');
        System.debug(accid);
        List<Account> accs = new List<Account>();
        List<ACO_Group_Member__c> acogrpmember = new List<ACO_Group_Member__c>();
        Set<Id> groupIds = new Set<Id>();
        try{
            List<Account_Relationship__c> providerACO = [SELECT id, Account_From_Id__c, Account_To_Id__c FROM Account_Relationship__c where Account_To_Id__c=:accid];        
            if(providerACO.isEmpty()) return;
            System.debug(providerACO);
            List<ACO_Group_Member__c> ACOGroupMember = [SELECT id, ACOs_to_link__c,ACOs_to_link__r.name,ACO_Group_Name__c,ACO_Group_Name__r.name,ACO_Group_Name__r.id,Name FROM ACO_Group_Member__c where ACOs_to_link__c=:providerACO[0].Account_From_Id__c];
            if(ACOGroupMember.isEmpty()) return;
            System.debug(ACOGroupMember);
            for(ACO_Group_Member__c member : ACOGroupMember){
                groupIds.add(member.ACO_Group_Name__c);
            }
            System.debug(groupIds);
            
			List<ACO_Group__c> groups = [SELECT Id,Name,Reason__c,Comments__c,CreatedById,CreatedBy.Name,CreatedDate FROM ACO_Group__c WHERE Id in :groupIds];
            if(groups.isEmpty()) return;
            
            List < Map < String, String >> result = new List < Map < String,String >> ();
            Map<Id,Set<Id>> ACOGroupIdMap = new Map<Id,Set<Id>>();
            For(ACO_Group__c acogroup : groups){
                Map < String, String > tempMap = new Map < String, String > ();
                
                tempMap.put('ACOGroupName', acogroup.Name);
                tempMap.put('ACOGroupId', acogroup.Id);
                tempMap.put('ACOGroupReason', acogroup.Reason__c);
                tempMap.put('ACOGroupComments', acogroup.Comments__c);
                tempMap.put('ACOGroupCreatedById', acogroup.CreatedById);
                tempMap.put('ACOGroupCreatedBy', acogroup.CreatedBy.Name);
                date createdDate = acogroup.CreatedDate.dateGMT();
                Integer day = createdDate.day();
                Integer month = createdDate.month();
                Integer year = createdDate.year();
                tempMap.put('ACOGroupCreatedDate', String.valueOf(day)+'/'+String.valueOf(month)+'/'+year);
                result.add(tempMap);
            }
            
            outMap.put('result', result);
            
        }catch(Exception e){
            System.debug(e.getMessage());
            System.debug(e.getLineNumber());
        }
    }
    
    public void fetchAcoGrpMember ( Map<String,Object> inputMap,Map<String,Object> outMap){
        
        String accid = (String)inputMap.get('AccountId');
        System.debug(accid);
        List<Account> accs = new List<Account>();
        List<ACO_Group_Member__c> acogrpmember = new List<ACO_Group_Member__c>();
        Set<Id> groupIds = new Set<Id>();
        try{
            List<Account_Relationship__c> providerACO = [SELECT id, Account_From_Id__c, Account_To_Id__c FROM Account_Relationship__c where Account_To_Id__c=:accid];        
            if(providerACO.isEmpty()) return;
            System.debug(providerACO);
            List<ACO_Group_Member__c> ACOGroupMember = [SELECT id, ACOs_to_link__c,ACOs_to_link__r.name,ACO_Group_Name__c,ACO_Group_Name__r.name,ACO_Group_Name__r.id,Name FROM ACO_Group_Member__c where ACOs_to_link__c=:providerACO[0].Account_From_Id__c];
            if(ACOGroupMember.isEmpty()) return;
            System.debug(ACOGroupMember);
            for(ACO_Group_Member__c member : ACOGroupMember){
                groupIds.add(member.ACO_Group_Name__c);
            }
            System.debug(groupIds);
            getRelatedProvider(groupIds,outMap);
        }catch(Exception e){
            System.debug(e.getMessage());
            System.debug(e.getLineNumber());
        }
    }
    
    public void getRelatedProvider(set<Id> groupIds,Map<String,Object> outMap){
        Map<Id,ACO_Group__c> groups = new Map<Id,ACO_Group__c>([SELECT Id,Name,Reason__c,Comments__c,CreatedById,CreatedBy.Name,CreatedDate,(SELECT Id,Name,ACOs_to_link__c FROM ACO_Group_Members__r) FROM ACO_Group__c WHERE Id in :groupIds]);
        if(groups.isEmpty()) return;
        
        Map<Id,Set<Id>> ACOGroupIdMap = new Map<Id,Set<Id>>();
        For(ACO_Group__c acogroup : groups.values()){
            for(ACO_Group_Member__c acomember : acogroup.ACO_Group_Members__r){
                Set<Id> temp = new Set<Id>();
                if(ACOGroupIdMap.get(acomember.ACOs_to_link__c) != null){
                    temp = ACOGroupIdMap.get(acomember.ACOs_to_link__c);
                }
                temp.add(acogroup.Id);
                ACOGroupIdMap.put(acomember.ACOs_to_link__c,temp);
            }
        }
        
        List<Account_Relationship__c> ACOs = [SELECT Id, Name,Account_From_Id__c,Account_From_Id__r.Name,Account_To_Id__c,Account_To_Id__r.Name FROM Account_Relationship__c WHERE Account_From_Id__c in:ACOGroupIdMap.keyset() AND Account_To_Id__r.RecordType.DeveloperName in ('Approved_Provider','Commonwealth_Home_Support_Programme','National_Aboriginal_and_Torres_Strait_Islander_Flexible_Aged_Care')];
        
        Map<String,List<Account_Relationship__c>> ACOGroupProviders = new Map<String,List<Account_Relationship__c>>();
        for(Account_Relationship__c ar : ACOs){
            for(Id ACOGroupId : ACOGroupIdMap.get(ar.Account_From_Id__c)){
                List<Account_Relationship__c> tmp = new List<Account_Relationship__c>();
                if(ACOGroupProviders.get(ACOGroupId) != null){
                    tmp = ACOGroupProviders.get(ACOGroupId);
                }
                tmp.add(ar);
                ACOGroupProviders.put(ACOGroupId,tmp);
            }
        }
        
        List < Map < String, String >> result = new List < Map < String,String >> ();
        for (String groupId: ACOGroupProviders.keyset()) {
            for(Account_Relationship__c ar : ACOGroupProviders.get(groupId)){
                Map < String, String > tempMap = new Map < String, String > ();
                
                tempMap.put('ACOGroupName', groups.get(groupId).Name);
                tempMap.put('ACOGroupId', groups.get(groupId).Id);
                tempMap.put('ACOGroupReason', groups.get(groupId).Reason__c);
                tempMap.put('ACOGroupComments', groups.get(groupId).Comments__c);
                tempMap.put('ACOGroupProvider', ar.Account_To_Id__r.Name +' ('+ar.Account_From_Id__r.Name+')');
                tempMap.put('ACOGroupProviderId', ar.Account_To_Id__c);
                tempMap.put('ACOGroupProviderName', ar.Account_To_Id__r.Name);
                tempMap.put('ACOGroupACOName', ar.Account_From_Id__r.Name);
                tempMap.put('ACOGroupACOId', ar.Account_From_Id__c);
                tempMap.put('ACOGroupCreatedById', groups.get(groupId).CreatedById);
                tempMap.put('ACOGroupCreatedBy', groups.get(groupId).CreatedBy.Name);
                date createdDate = groups.get(groupId).CreatedDate.dateGMT();
                Integer day = createdDate.day();
                Integer month = createdDate.month();
                Integer year = createdDate.year();
                tempMap.put('ACOGroupCreatedDate', String.valueOf(day)+'/'+String.valueOf(month)+'/'+year);
                result.add(tempMap);
            }
        }        
        outMap.put('result', result);
    }
    
    public void fetchSingleAcoGrpMember (Map<String,Object> inputMap,Map<String,Object> outMap){
        String accid = (String)inputMap.get('AccountId');
        Set<Id> groupIds = new Set<Id>();
        groupIds.add(accid);
        getRelatedProvider(groupIds,outMap);
    }
    
}