force-app/main/default/objects/Account/fields/ABN_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>ABN_Entity_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ABN Entity Name</label>
    <referenceTo>Registered_ABN_Name__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Accounts</label>
    <nameField>
        <displayFormat>ARL-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/Account_From_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_From_Id__c</fullName>
    <description>Parent account record to link another account record.</description>
    <label>Account From</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 AND 4) OR (1 AND 2)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account, Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation, Provider to Management Company, Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account From)</relationshipLabel>
    <relationshipName>Account_Relationship_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Account_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_To_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account To</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Management Company, Administrative Organisation, Service Delivery Organisation, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Management Company</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Management Company</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Delivery Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account To)</relationshipLabel>
    <relationshipName>Account_Relationship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <formula>Account_To_Id__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/Address_Location__c.object-meta.xml
<CustomObject>
    <label>Address Location</label>
    <nameField>
        <displayFormat>ALN-{00000}</displayFormat>
        <label>Address Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/fields/Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Relationship</label>
    <referenceTo>Contact_Relationship__c</referenceTo>
    <relationshipLabel>Address Locations</relationshipLabel>
    <relationshipName>Address_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipName>Service_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Types</relationshipLabel>
    <relationshipName>Care_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <formula>Account__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Relationship</label>
    <referenceTo>Contact_Relationship__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/SDO_Contract_Service__c/SDO_Contract_Service__c.object-meta.xml
<CustomObject>
    <label>Attached Services</label>
    <nameField>
        <displayFormat>SCS-{0000000}</displayFormat>
        <label>SDO Contract Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SDO Contract Service</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SDO_Contract_Service__c/fields/Associated_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Associated_Accounts__c</fullName>
    <complianceGroup>HIPAA</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Accounts</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account_Relationship__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account_Relationship__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Provider to Management Company</value>
        </filterItems>
        <filterItems>
            <field>Account_Relationship__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Relationship__c</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Attached_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SDO_Contract_Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>SDO Contract Service</relationshipLabel>
    <relationshipName>SDO_Contract_Service</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slowly_Changing_Dimension__c/Slowly_Changing_Dimension__c.object-meta.xml
<CustomObject>
    <description>Enables display and search of changes which occur slowly and unpredictably over time - such as a person&apos;s family name.</description>
    <label>Slowly Changing Dimension</label>
    <nameField>
        <displayFormat>SCD-{0000000}</displayFormat>
        <label>Slowly Changing Dimension</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slowly Changing Dimension</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Slowly_Changing_Dimension__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Slowly Changing Dimension</relationshipLabel>
    <relationshipName>Slowly_Changing_Dimension</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GPMSAccountPayload.cls
/****************************************************************************************************
* @CreatedBy   : Accenture Developer Team
* @CreatedDate : 19-Jul-2022
* @Description : Handles the data structure for the account payload
* @Test Class  : GPMSAccountPayloadResponseTest
*****************************************************************************************************/
global with sharing class GPMSAccountPayload {
    
    public String accountId;
    
    public SObject account; //Current Account
    public SObject abn; // Account ABN
    
    public List<SObject> parentRelationships;//Parent account relationship
    public List<SObject> parentAccounts;//Parent ACO
    
    public List<SObject> childRelationships;//Child account relationship
    public List<SObject> childAccounts;//Child TPO
    
    public List<SObject> contactRelationships;
    public List<SObject> contacts;
    public List<SObject> contactPreviousName;//previous name history
    public List<SObject> contactCredentials;
    
    public List<SObject> managementCompanyContactRelationships;
    public List<SObject> managementCompanyContacts;
    public List<SObject> managementCompanyContactPreviousName;
    
    public List<SObject> locations;
    public List<SObject> addresses;
    
    public List<SObject> accountServiceRelationships;
    public List<SObject> services;
    public List<SObject> serviceLocations;
    public List<SObject> serviceAddresses;
    
    public List<SObject> previousNames;//previous name history
    public List<SObject> tradingNames;// trading name
    
    public List<SObject> prudentials;
    public List<SObject> careTypes;
    
    public List<SObject> subContracts;
    
    public List<SObject> tpoContracts;
    public List<SObject> tpoContractServices;
    
    public List<SObject> accountHistory;
    
    public GPMSAccountPayload(String accountId){
        this.accountId = accountId;
    }
    
    public GPMSAccountPayload(){
        
    }
    
    //Account
    public void setAccount(GPMSPayloadHelper helper){
        
        GPMSPayloadHelper.QueryBundle accountBundle = new GPMSPayloadHelper.QueryBundle('Account','Id',accountId);
        account = helper.queryResultSingle(accountbundle);
    }
    
    //ABN
    public void setABN(GPMSPayloadHelper helper){
        
        if(null != account.get('ABN_Entity_Name__c')){
            
            String abnId = (String)account.get('ABN_Entity_Name__c');
            
            GPMSPayloadHelper.QueryBundle abnBundle = new GPMSPayloadHelper.QueryBundle('Registered_ABN_Name__c','Id',abnId);
            abn = helper.queryResultSingle(abnBundle);
        }
        
    }
    
    public void setParentAccounts(GPMSPayloadHelper helper){
        
        //Parent Account Relationships
        GPMSPayloadHelper.QueryBundle parentRelationshipBundle = 
            new GPMSPayloadHelper.QueryBundle('Account_Relationship__c','Account_To_Id__c',accountId);
        parentRelationships = helper.queryResultList(parentRelationshipBundle);
        
        //Parent Account
        Set<String> parentAccountIds = helper.generateIds(parentRelationships,'Account_From_Id__c');
        GPMSPayloadHelper.QueryBundle parentAccountBundle = 
            new GPMSPayloadHelper.QueryBundle('Account','Id',parentAccountIds);
        parentAccounts = helper.queryResultList(parentAccountBundle);
        
        //Third Party organization contract
        Set<String> tpoContractIds = helper.generateIds(parentRelationships,'Id');
        GPMSPayloadHelper.QueryBundle subContractBundle = 
            new GPMSPayloadHelper.QueryBundle('SDO_Contract_Service__c','Associated_Accounts__c',tpoContractIds);
        tpoContracts = helper.queryResultList(subContractBundle);
        
        Set<String> serviceIds = helper.generateIds(tpoContracts,'Service__c');
        GPMSPayloadHelper.QueryBundle serviceBundle = 
            new GPMSPayloadHelper.QueryBundle('BusinessLicense','Id',serviceIds);
        tpoContractServices = helper.queryResultList(serviceBundle);
        
    }
    
    public void setChildAccounts(GPMSPayloadHelper helper){
        
        //Child Account Relationships
        GPMSPayloadHelper.QueryBundle childAccountRelationshipBundle = 
            new GPMSPayloadHelper.QueryBundle('Account_Relationship__c','Account_From_Id__c',this.accountId);
        childRelationships = helper.queryResultList(childAccountRelationshipBundle);
        
        //Child Accounts
        Set<String> childAccountIds = helper.generateIds(childRelationships,'Account_To_Id__c');
        GPMSPayloadHelper.QueryBundle childAccountBundle = 
            new GPMSPayloadHelper.QueryBundle('Account','Id',childAccountIds);
        childAccounts = helper.queryResultList(childAccountBundle);
        
        Set<String> subContractIds = helper.generateIds(childRelationships,'Id');
        GPMSPayloadHelper.QueryBundle subContractBundle = 
            new GPMSPayloadHelper.QueryBundle('SDO_Contract_Service__c','Associated_Accounts__c',subContractIds);
        subContracts = helper.queryResultList(subContractBundle);
        
    }
    
    public void setManagementCompanys(GPMSPayloadHelper helper){
        
        //Child Account Relationships
        List<Object> managementCompanys = helper.filterList(childRelationships,'Entity_Type__c','Management Company');
        Set<String> managementCompanyIds = helper.generateIds(childRelationships,'Account_To_Id__c');
        
        GPMSPayloadHelper.QueryBundle managementCompanysContactRelationshipBundle = 
            new GPMSPayloadHelper.QueryBundle('Contact_Relationship__c','Account__c',managementCompanyIds);
        managementCompanyContactRelationships = helper.queryResultList(managementCompanysContactRelationshipBundle);
        
        //Child Accounts
        Set<String> managementCompanysContactIds = helper.generateIds(managementCompanyContactRelationships,'Contact__c');
        GPMSPayloadHelper.QueryBundle managementCompanysContactBundle = 
            new GPMSPayloadHelper.QueryBundle('Contact','Id',managementCompanysContactIds);
        managementCompanyContacts = helper.queryResultList(managementCompanysContactBundle);
        
        GPMSPayloadHelper.QueryBundle managementCompanysContactPrevioudNameBundle = 
            new GPMSPayloadHelper.QueryBundle('Slowly_Changing_Dimension__c','Contact__c',managementCompanysContactIds);
        managementCompanyContactPreviousName = helper.queryResultList(managementCompanysContactPrevioudNameBundle);
        
    }
    
    public void setContacts(GPMSPayloadHelper helper){
        
        //Contact Relationships
        GPMSPayloadHelper.QueryBundle contactRelationshipBundle = 
            new GPMSPayloadHelper.QueryBundle('Contact_Relationship__c','Account__c',accountId);
        contactRelationships = helper.queryResultList(contactRelationshipBundle);
        
        //Contacts
        Set<String> contactIds = helper.generateIds(contactRelationships,'Contact__c');
        GPMSPayloadHelper.QueryBundle contactBundle = 
            new GPMSPayloadHelper.QueryBundle('Contact','Id',contactIds);
        contacts = helper.queryResultList(contactBundle);
        
        //Contacts Previous Name
        GPMSPayloadHelper.QueryBundle contactPreviousNameBundle = 
            new GPMSPayloadHelper.QueryBundle('Slowly_Changing_Dimension__c','Contact__c',contactIds);
        contactPreviousName = helper.queryResultList(contactPreviousNameBundle);
        
        //Contacts Credentials
        GPMSPayloadHelper.QueryBundle contactCredentialBundle = 
            new GPMSPayloadHelper.QueryBundle('PersonEducation','Contact__c',contactIds);
        contactCredentials = helper.queryResultList(contactCredentialBundle);
        
    }
    
    public void setAddresses(GPMSPayloadHelper helper){
        
        //Account Location
        GPMSPayloadHelper.QueryBundle locationBundle = 
            new GPMSPayloadHelper.QueryBundle('Address_Location__c','Account__c',accountId);
        locations = helper.queryResultList(locationBundle);
        
        //Account Address 
        Set<String> addressIds = helper.generateIds(locations,'Address__c');
        GPMSPayloadHelper.QueryBundle addressBundle = 
            new GPMSPayloadHelper.QueryBundle('Address__c','Id',addressIds);
        addresses = helper.queryResultList(addressBundle);
        
    }
    
    public void setServices(GPMSPayloadHelper helper){
        
        //Account Services Relationships
        GPMSPayloadHelper.QueryBundle accountServiceBundle = 
            new GPMSPayloadHelper.QueryBundle('Service_Account_Relationship__c','Provider_Name__c',accountId);
        accountServiceRelationships = helper.queryResultList(accountServiceBundle);
        
        //Services
        Set<String> serviceIds = helper.generateIds(accountServiceRelationships,'Service_Name__c');
        GPMSPayloadHelper.QueryBundle serviceBundle = 
            new GPMSPayloadHelper.QueryBundle('BusinessLicense','Id',serviceIds);
        services = helper.queryResultList(serviceBundle);
        
        //Service Locations
        GPMSPayloadHelper.QueryBundle locationBundle = 
            new GPMSPayloadHelper.QueryBundle('Address_Location__c','Service__c',serviceIds);
        serviceLocations = helper.queryResultList(locationBundle);
        
        //Service Address
        Set<String> addressIds = helper.generateIds(serviceLocations,'Address__c');
        GPMSPayloadHelper.QueryBundle addressBundle = 
            new GPMSPayloadHelper.QueryBundle('Address__c','Id',addressIds);
        serviceAddresses = helper.queryResultList(addressBundle);
        
    }
    
    //Account Previous Name
    public void setPreviousName(GPMSPayloadHelper helper){
        
        GPMSPayloadHelper.QueryBundle scdBundle = 
            new GPMSPayloadHelper.QueryBundle('Slowly_Changing_Dimension__c','Account__c',accountId);
        previousNames = helper.queryResultList(scdBundle);
        
    }
    
    //Account Care Type
    public void setCareTypes(GPMSPayloadHelper helper){
        
        GPMSPayloadHelper.QueryBundle careTypeBundle = 
            new GPMSPayloadHelper.QueryBundle('Care_Type__c','Account__c',accountId);
        careTypes = helper.queryResultList(careTypeBundle);
        
    }
    
    //Account Trading Name
    public void setTradingName(GPMSPayloadHelper helper){
        
        GPMSPayloadHelper.QueryBundle tnBundle = 
            new GPMSPayloadHelper.QueryBundle('Trading_Name__c','Account__c',accountId);
        tradingNames = helper.queryResultList(tnBundle);
        
    }
    
        
	//Account prudentials
    public void setPrudentials(GPMSPayloadHelper helper){
        
        GPMSPayloadHelper.QueryBundle prudentialsBundle = 
            new GPMSPayloadHelper.QueryBundle('Prudential_Detail__c','Account__c',accountId);
        prudentials = helper.queryResultList(prudentialsBundle);
        
    }
    
    //Account History
    public void setHistory(GPMSPayloadHelper helper){
        
        GPMSPayloadHelper.QueryBundle historyBundle = 
            new GPMSPayloadHelper.QueryBundle('GPMS_Account_History__c','Account__c',accountId);
        accountHistory = helper.queryResultList(historyBundle);
        
    }
    
}