force-app/main/default/objects/Account/fields/Administrator_Liquidator_Record_Exists__c.field-meta.xml
<CustomField>
    <fullName>Administrator_Liquidator_Record_Exists__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Administrator Liquidator Record Exists?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Aged_Care_Organisation.recordType-meta.xml
<RecordType>
    <fullName>Aged_Care_Organisation</fullName>
    <active>true</active>
    <description>Aged Care Organisation</description>
    <label>Aged Care Organisation</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Accounts</label>
    <nameField>
        <displayFormat>ARL-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/Account_From_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_From_Id__c</fullName>
    <description>Parent account record to link another account record.</description>
    <label>Account From</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 AND 4) OR (1 AND 2)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account, Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation, Provider to Management Company, Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account From)</relationshipLabel>
    <relationshipName>Account_Relationship_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Account_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_To_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account To</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Management Company, Administrative Organisation, Service Delivery Organisation, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Management Company</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Management Company</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Delivery Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account To)</relationshipLabel>
    <relationshipName>Account_Relationship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/recordTypes/ACO_to_Account.recordType-meta.xml
<RecordType>
    <fullName>ACO_to_Account</fullName>
    <active>true</active>
    <label>ACO to Account</label>
</RecordType>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Administrator_Liquidator_Record_Exists__c.field-meta.xml
<CustomField>
    <fullName>Administrator_Liquidator_Record_Exists__c</fullName>
    <formula>IF( Account__r.Administrator_Liquidator_Record_Exists__c = True, True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Administrator Liquidator Record Exists?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Effect_on_Suitability__c.field-meta.xml
<CustomField>
    <fullName>Effect_on_Suitability__c</fullName>
    <label>Effect on Suitability</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/recordTypes/Administrator_Liquidator_CR.recordType-meta.xml
<RecordType>
    <fullName>Administrator_Liquidator_CR</fullName>
    <active>true</active>
    <label>Administrator Liquidator</label>
</RecordType>

force-app/main/default/classes/GPMSUpdateAdminLiquidatorFlagBatchTest.cls
@isTest
public class GPMSUpdateAdminLiquidatorFlagBatchTest {
    @TestSetup
    static void setup() 
    { 
       User gpmsUser = TestDataFactory.createGPMSTestUser();
       System.runAs(gpmsUser)
       {
           Test.startTest();
           Account aco = new Account(Name = 'ACO',Incorporation_ID_Type__c='Not Incorporated');
           aco.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Aged_Care_Organisation').getRecordTypeId();
           Insert aco;
           
           Account approvedProviderA = new Account(Name = 'Approved Provider A',Incorporation_ID_Type__c='Other',Purpose__c='Private for Profit');
           approvedProviderA.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Approved_Provider').getRecordTypeId();
           Insert approvedProviderA;
            
           Account approvedProviderB = new Account(Name = 'Approved Provider B',Incorporation_ID_Type__c='Other',Purpose__c='Private for Profit');
           approvedProviderB.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Approved_Provider').getRecordTypeId();
           Insert approvedProviderB;
            
           Account_Relationship__c acoToProviderA = new Account_Relationship__c(Account_From_Id__c = aco.Id,Account_To_Id__c = approvedProviderA.Id);
           acoToProviderA.recordTypeId = Schema.SObjectType.Account_Relationship__c.getRecordTypeInfosByDeveloperName().get('ACO_to_Account').getRecordTypeId();
           insert acoToProviderA;
           
           Account_Relationship__c acoToProviderB = new Account_Relationship__c(Account_From_Id__c = aco.Id,Account_To_Id__c = approvedProviderB.Id);
           acoToProviderB.recordTypeId = Schema.SObjectType.Account_Relationship__c.getRecordTypeInfosByDeveloperName().get('ACO_to_Account').getRecordTypeId();
           insert acoToProviderB;       
        
           Contact_Relationship__c adminLiquidator = new Contact_Relationship__c(Account__c = approvedProviderA.Id);
           adminLiquidator.recordTypeId = Schema.SObjectType.Contact_Relationship__c.getRecordTypeInfosByDeveloperName().get('Administrator_Liquidator_CR').getRecordTypeId();
           insert adminLiquidator;
           
           adminLiquidator.End_Date__c = System.today()-1;
           adminLiquidator.Effect_on_Suitability__c = 'Some effect on Suitaible';
           update adminLiquidator;  
            
           approvedProviderA.Administrator_Liquidator_Record_Exists__c = true;
           update approvedProviderA; 
            
           aco.Administrator_Liquidator_Record_Exists__c = true;
           update aco; 
           Test.stopTest();
       }
    }
    static testmethod void testGPMSUpdateAdminLiquidatorFlagBatch()
    {
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        System.runAs(gpmsUser)
        {
            Test.startTest();
            GPMSUpdateAdminLiquidatorFlagBatch adminLiquidatorFlagUpdateBatch = new GPMSUpdateAdminLiquidatorFlagBatch();
            Database.executeBatch(adminLiquidatorFlagUpdateBatch,1);   
            Test.stopTest();
        }       
        
    }
    static testmethod void testGPMSUpdateAdminLiquidatorFlagBatchManualExecution()
    {
        Contact_Relationship__c cr = [select Id,End_Date__c,Account__c,RecordType.Name,
                                      Administrator_Liquidator_Record_Exists__c 
                                      from Contact_Relationship__c Limit 1];        
             
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        System.runAs(gpmsUser)
        {
            Test.startTest();
            Set<Id> recIdSet = new Set<Id>{cr.Id};
            GPMSUpdateAdminLiquidatorFlagBatch.executeByIds(recIdSet,1); 
            Test.stopTest();
        }       
        
    }
}