force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CountArchRegDecision__c.field-meta.xml
<CustomField>
    <fullName>CountArchRegDecision__c</fullName>
    <description>This field will take the number value of  how many Archived Regulatory Decisions Count for each service - will be updated by a trigger</description>
    <label>Archived Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/NoOf_NonCurr_Rating_RegDecision__c.field-meta.xml
<CustomField>
    <fullName>NoOf_NonCurr_Rating_RegDecision__c</fullName>
    <description>Field updated by SCR Handler with no of non current Regulatory decisions relevant for SCR Rating i.e Non Current that count towards SCR</description>
    <label>NoOf NonCurr Rating RegDecision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/Approved_Provider_Service.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Service</fullName>
    <active>true</active>
    <label>Approved Provider Service</label>
</RecordType>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Archived_Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Archived_Regulatory_Decision__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the regulatory decision has been archived</description>
    <label>Archived Regulatory Decision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Date_Decision_Applied__c.field-meta.xml
<CustomField>
    <fullName>Date_Decision_Applied__c</fullName>
    <label>Date Decision Applied</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Decision_Details__c.field-meta.xml
<CustomField>
    <fullName>Decision_Details__c</fullName>
    <label>Decision Details</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Rating_Relevant__c.field-meta.xml
<CustomField>
    <fullName>Rating_Relevant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rating Relevant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Reason_for_issuing_Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_issuing_Regulatory_Decision__c</fullName>
    <label>Reason for issuing Regulatory Decision</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/SCR_Rating__c.field-meta.xml
<CustomField>
    <fullName>SCR_Rating__c</fullName>
    <description>calculated SCR rating for the record</description>
    <label>SCR Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Compliance_Rating_Effect</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test only</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Account_Relationship__c.Provider_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Service care type is not Home Care or Residential</errorMessage>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Home Care</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Name__c</fullName>
    <description>Name of the Service Provider to be Published</description>
    <label>Alternative Service Provider Name</label>
    <length>130</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Provider_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Regulatory Code Violations</relationshipLabel>
    <relationshipName>Regulatory_Code_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>It determines if a service account relationship is active or not</description>
    <formula>IF( Association_Start_Date__c &lt;= TODAY() &amp;&amp;  (Association_End_Date__c &gt; TODAY() || ISNULL(Association_End_Date__c)), true, false)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_Start_Date__c</fullName>
    <label>Association Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountArchRegDecision__c.field-meta.xml
<CustomField>
    <fullName>CountArchRegDecision__c</fullName>
    <description>This field will take the number value of  how many Archived Regulatory Decision Count for each service - will be updated by a trigger</description>
    <label>Archived Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CurrentNonCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CurrentNonCurrentRegDec__c</fullName>
    <description>Stores count of non-current regulatory decisions which are flagged as relevant to rating. Value is updated when a new Regulatory Decision is created or existing decision is removed.</description>
    <label>Non Current Reg Dec Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_Detail__c/Service_Compliance_Detail__c.object-meta.xml
<CustomObject>
    <label>Service Compliance Detail</label>
    <nameField>
        <displayFormat>SCRD-{000000}</displayFormat>
        <label>SCR Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_Detail__c/fields/Service_Compliance_History__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_History__c</fullName>
    <label>Service Compliance History</label>
    <referenceTo>Service_Compliance_History__c</referenceTo>
    <relationshipLabel>Service Compliance Details</relationshipLabel>
    <relationshipName>Service_Compliance_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/SCR_Rating__c.field-meta.xml
<CustomField>
    <fullName>SCR_Rating__c</fullName>
    <label>SCR Rating</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Service_Compliance_Rating_Effect.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Star</fullName>
    </customValue>
    <customValue>
        <fullName>2 Star</fullName>
    </customValue>
    <customValue>
        <fullName>3 Star</fullName>
    </customValue>
    <customValue>
        <fullName>4  Star</fullName>
    </customValue>
    <customValue>
        <fullName>5 Star</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>STAR Rating effect for SCR</description>
    <masterLabel>Service Compliance Rating Effect</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateSCRBatchTest.cls
/**
 * author: Matthew WAll
 * date: 10/11/2022
 * description: Test class for CreateSCRBatch to process Regulatory Decisions
 **/
/* MODIFICATION LOG
 * Version       Developer                   Date                Description
 *-------------------------------------------------------------------------------------------
 *  1.0     		Matthew Wall               10-11-2022          Initial Creation
 *******************************************************************************************/
@isTest
public class CreateSCRBatchTest {
    public static final String THREE_STARS = '3 Star';
    public static final String TEST_REASON = 'Test Reason';
    public static final String DECISION_DETAILS = 'Decision Details';
    public static final Integer ONE = 1;

    @TestSetup
    static void makeData(){
        User testUser = TestDataFactory.createSystemAdminUser();

		Test.startTest();
		System.runAs(testUser) {
            List<Account> providers = TestDataFactory.createProviderRecords(1);
            
            insert providers;

            List<Care_Type__c> careTypeList = TestDataFactory.createSCRcareType(1, providers);
            insert careTypeList;

            List<BusinessLicense> testService = TestDataFactory.createServiceRecords(1);
            for (BusinessLicense service : testService) {
                service.RecordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName()
                    .get('Approved_Provider_Service')
                    .getRecordTypeId();
            }
            
            insert testService;

            List<Service_Account_Relationship__c> serviceAccounts = TestDataFactory.createServiceAccountRecords(1, testService, providers); 
            serviceAccounts[0].Association_Start_Date__c = Date.today().addDays(-150);
            insert serviceAccounts;

            List<RegulatoryCodeViolation> regDecisionList = new List<RegulatoryCodeViolation>();
            // Create current & published
            regDecisionList.add(new RegulatoryCodeViolation(Service_name_lookup__c = testService[0].Id, Service_Provider_Name__c = providers[0].Id, 
                                                            Service_Account_Relationship__c = serviceAccounts[0].Id, Status = 'Current', 
                                                            DateCreated = Datetime.now(), 
                                                            Published__c = true, Rating_Relevant__c = true, SCR_Rating__c = THREE_STARS, 
                                                            Decision_Details__c = DECISION_DETAILS,
                                                            Reason_for_issuing_Regulatory_Decision__c = TEST_REASON,
                                                            Service_Provider_Name_lookup__c =  providers[0].id,
                                                            Date_Decision_Applied__c = serviceAccounts[0].Association_Start_Date__c.addDays(10)));
            // Create Non-Current
            regDecisionList.add(new RegulatoryCodeViolation(Service_name_lookup__c = testService[0].Id, Service_Provider_Name__c = providers[0].Id, 
                                                            Service_Account_Relationship__c = serviceAccounts[0].Id, Status = 'Non-Current', 
                                                            DateCreated = Datetime.now(), 
                                                            Published__c = true, Rating_Relevant__c = true, SCR_Rating__c = THREE_STARS, 
                                                            Decision_Details__c = DECISION_DETAILS,
                                                            Reason_for_issuing_Regulatory_Decision__c = TEST_REASON,
                                                            Service_Provider_Name_lookup__c =  providers[0].id,
                                                            Date_Decision_Applied__c = serviceAccounts[0].Association_Start_Date__c.addDays(8)));
            // Create Archived
            regDecisionList.add(new RegulatoryCodeViolation(Service_name_lookup__c = testService[0].Id, Service_Provider_Name__c = providers[0].Id, 
                                                            Service_Account_Relationship__c = serviceAccounts[0].Id, Status = 'Non-Current', 
                                                            DateCreated = Datetime.now(), 
                                                            Published__c = true, Archived_Regulatory_Decision__c = true, SCR_Rating__c = THREE_STARS, 
                                                            Decision_Details__c = DECISION_DETAILS,
                                                            Reason_for_issuing_Regulatory_Decision__c = TEST_REASON,
                                                            Service_Provider_Name_lookup__c =  providers[0].id,
                                                            Date_Decision_Applied__c = serviceAccounts[0].Association_Start_Date__c.addDays(5)));
            insert regDecisionList;
        }
        Test.stopTest();
    }

    @IsTest
    static void createSCRTest() {
        User user = createTestUser();
        System.runAs(user) {
            // query records before
            List<Service_Compliance_History__c> schBefore = [SELECT Id FROM Service_Compliance_History__c];
            List<BusinessLicense> serviceListBefore = [SELECT Id, CountCurrentRegDec__c, CountArchRegDecision__c, NoOf_NonCurr_Rating_RegDecision__c
                                                        FROM BusinessLicense];
            // check pre asserts
            System.assertEquals(0, schBefore.size(), 'Expected 0 Compliance History');

            Test.startTest();
            CreateSCRBatch myBatchObject = new CreateSCRBatch(); 
            Database.executeBatch(myBatchObject);
            Test.stopTest();
            // query post batch records
            List<Service_Compliance_History__c> schAfter = [SELECT Id FROM Service_Compliance_History__c];
            List<Service_Compliance_Detail__c> scdAfter = [SELECT Id, Name FROM Service_Compliance_Detail__c];
            List<BusinessLicense> serviceListAfter = [SELECT Id, CountCurrentRegDec__c, CountArchRegDecision__c, NoOf_NonCurr_Rating_RegDecision__c
                                                        FROM BusinessLicense];
            List<Service_Account_Relationship__c> sarAfter = [SELECT Id, CountCurrentRegDec__c, CurrentNonCurrentRegDec__c, CountArchRegDecision__c, Active__c
                                                                FROM Service_Account_Relationship__c];
            // check post asserts
            System.assertEquals(1, schAfter.size(), 'Expected 1 Compliance History');
            System.assertEquals(3, scdAfter.size(), 'Expected 3 Compliance Detail');
            System.assertEquals(1, serviceListAfter[0].CountCurrentRegDec__c, 'Value must be 1');
            System.assertEquals(1, serviceListAfter[0].CountArchRegDecision__c, 'Value must be 1');
            System.assertEquals(1, serviceListAfter[0].NoOf_NonCurr_Rating_RegDecision__c, 'Value must be 1');
            System.assertEquals(1, sarAfter[0].CountCurrentRegDec__c, 'Value must be 1');
            System.assertEquals(1, sarAfter[0].CountArchRegDecision__c, 'Value must be 1');
            System.assertEquals(1, sarAfter[0].CurrentNonCurrentRegDec__c, 'Value must be 1');
        }
    }

    public static User createTestUser() {
        Profile prof = [SELECT Id, Name FROM Profile WHERE Name LIKE 'System Administrator'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.ProfileId = prof.Id;
        user.Username = 'tester1@unittest.com';
        user.email = 'test@test.com';
        user.Alias = 'tst';
        user.TimeZoneSidKey = 'Australia/Sydney';
        user.LocaleSidKey = 'en_AU'; 
        user.EmailEncodingKey = 'UTF-8'; 
        user.LanguageLocaleKey = 'en_US';
        insert user;
        return user;
    }
}