force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/Allotment__c.object-meta.xml
<CustomObject>
    <label>Allotment</label>
    <nameField>
        <displayFormat>ALMT-{00000}</displayFormat>
        <label>Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allotment__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>NATSIFAC</fullName>
            </value>
            <value>
                <fullName>Innovative Pool</fullName>
                <isActive>false</isActive>
                <label>Innovative Pool</label>
            </value>
            <value>
                <fullName>Multiple-Purpose Service</fullName>
                <isActive>false</isActive>
                <label>Multiple-Purpose Service</label>
            </value>
            <value>
                <fullName>Short Term Restorative Care(STRC)</fullName>
                <isActive>false</isActive>
                <label>Short Term Restorative Care(STRC)</label>
            </value>
            <value>
                <fullName>Transition Care</fullName>
                <isActive>false</isActive>
                <label>Transition Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Go_Live_Date__c</fullName>
    <description>Date STAR Rating is live on MAC</description>
    <label>Go-Live Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <description>Date STAR rating is to be published to the provider portal</description>
    <label>Publish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STARRating_Settings__mdt/STARRating_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Use this metadata type to store period of time to Go Live and Publish status for SCR Records</description>
    <label>STARRating Settings</label>
    <pluralLabel>STARRating Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/StarRatingsSettingsCustomMetadataTest.cls
@isTest
private with sharing class StarRatingsSettingsCustomMetadataTest {
	private static Integer RECORD_COUNT = 1;
	private static User testAdminUser1 = TestDataFactory.insertNewSysAdmin();

	@TestSetup
	static void makeData() {
		System.runAs(testAdminUser1) {
			// Insert previous quarter reporting period
			Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod('Quarter');
			rPeriod.Start_Date__c = (System.today() + 12).addMonths(-6);
			rPeriod.End_Date__c = (System.today() + 24).addMonths(-3);
			insert rPeriod;

			// Insert providers
			List<Account> providers = TestDataFactory.createProviderRecords(RECORD_COUNT);
			insert providers;

			// Insert care type
			List<Care_Type__c> careTypeList = TestDataFactory.createSCRcareType(1, providers);
			insert careTypeList;

			// Insert services
			List<BusinessLicense> services = TestDataFactory.createServiceRecords(RECORD_COUNT);
			insert services;

			// As per the new requirements, everytime a service is created, the status will be defaulted to 'Inactive'.
			// The system requires an Allotment to be attached to the Service in order to make the service Operational
			List<Allotment__c> allotments = TestDataFactory.createAllotments(RECORD_COUNT, services);
			insert allotments;

			List<Places_Allotment__c> placesAllotments = TestDataFactory.createPlacesAllotments(
				RECORD_COUNT,
				allotments
			);
			insert placesAllotments;

			// This update will trigger flow Service: Update Service Status Start Date and set service status to operational
			update services;
			Test.getEventBus().deliver();

			// Insert service account relationships
			List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(
				RECORD_COUNT,
				services,
				providers
			);
			insert serviceAccountRecords;
		}
	}

	/**
	 * Test star ratings settings custom metadata config
	 * Expected result: fields should match the values set in test method
	 */
	@isTest
	static void starRatingsSettingsConfigTest() {
		Test.startTest();
		System.runAs(testAdminUser1) {
			StarRatingsSettingsCustomMetadata.daysAfterDateDecisionEndsOne = 500;
			StarRatingsSettingsCustomMetadata.daysAfterDateDecisionEndsTwo = 400;
			StarRatingsSettingsCustomMetadata.goLiveDate = 30;
			StarRatingsSettingsCustomMetadata.publishDate = 20;
		}
		Test.stopTest();

		// Assert Results
		Assert.areEqual(500, StarRatingsSettingsCustomMetadata.daysAfterDateDecisionEndsOne, 'Value should be 500');
		Assert.areEqual(400, StarRatingsSettingsCustomMetadata.daysAfterDateDecisionEndsTwo, 'Value should be 400');
		Assert.areEqual(30, StarRatingsSettingsCustomMetadata.goLiveDate, 'Value should be 30');
		Assert.areEqual(20, StarRatingsSettingsCustomMetadata.publishDate, 'Value should be 20');
	}

	/**
	 * Test SRH creation using the default values of STARRating_Settings__mdt
	 * Expected result: publish date = today, go-live date = today + 14
	 */
	@isTest
	static void defaultCustomMetadataTest() {
		Test.startTest();
		System.runAs(testAdminUser1) {
			RatingsCalculationService.starRatingRecords();
		}
		Test.stopTest();

		// Asserts Result
		List<STAR_Rating_History__c> srhsCreated = [
			SELECT Id, Go_Live_Date__c, Publish_Date__c
			FROM STAR_Rating_History__c
			LIMIT 1
		];
		Assert.areNotEqual(0, srhsCreated.size(), 'SRH should have been created');
		Assert.areEqual(System.today(), srhsCreated.get(0).Publish_Date__c, 'Default publish date is current day');
		Assert.areEqual(
			System.today().addDays(14),
			srhsCreated.get(0).Go_Live_Date__c,
			'Default golive date is today + 14 days'
		);
	}

	/**
	 * Test SRH creation using the CUSTOM values of STARRating_Settings__mdt
	 * Expected result: publish date = today + 5, go-live date = today + 20
	 */
	@isTest
	static void customValuesCustomMetadataTest() {
		// Set custom values in custom metadata
		StarRatingsSettingsCustomMetadata.goLiveDate = 20;
		StarRatingsSettingsCustomMetadata.publishDate = 5;

		Test.startTest();
		System.runAs(testAdminUser1) {
			RatingsCalculationService.starRatingRecords();
		}
		Test.stopTest();

		// Asserts Result
		List<STAR_Rating_History__c> srhsCreated = [
			SELECT Id, Go_Live_Date__c, Publish_Date__c
			FROM STAR_Rating_History__c
			LIMIT 1
		];
		Assert.areNotEqual(0, srhsCreated.size(), 'SRH should have been created');
		Assert.areEqual(
			System.today().addDays(5),
			srhsCreated.get(0).Publish_Date__c,
			'Custom publish date is current day + 5 days'
		);
		Assert.areEqual(
			System.today().addDays(20),
			srhsCreated.get(0).Go_Live_Date__c,
			'Custom golive date is today + 20 days'
		);
	}
}