force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Late Submission</fullName>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <label>Submitted - Updated After Due Date</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/QI_Submission_Due_Dt__c.field-meta.xml
<CustomField>
    <fullName>QI_Submission_Due_Dt__c</fullName>
    <description>capture the QI submission due date</description>
    <label>QI Submission Due Dt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_End_Date__c</fullName>
    <label>Association End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/SRQI_Exemption__c.object-meta.xml
<CustomObject>
    <description>Exemption record for services that have been granted an exemption from either the CER, SCR, QI or CM rating domains</description>
    <label>Exemption</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Exemption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_Exemption__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It indicates which service account relationship record the exemption record is linked to.</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service in Service Account Relationship must match service in Exemption record.</errorMessage>
        <filterItems>
            <field>$Source.Service__c</field>
            <operation>equals</operation>
            <valueField>Service_Account_Relationship__c.Service_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Exemptions</relationshipLabel>
    <relationshipName>ExemptionsSAR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QIRemindersService.cls
/**
* author: Neha Malik
* date: 18/05/2023
* description: This is the service class for the QI notifications which will have all the data regarding Reporting 
* Period and QI summary.
**/
public with sharing class QIRemindersService {
    private static final String BLANK_STRING = '';
    private static final String DUE_REMINDER = 'due';
    private static final String QI_SUBMIT = 'submitQI';
    private static final String OVERDUE_REMINDER = 'overdue';
    private static final String ORG_ROLE = 'QI Role - Org';
    private static final String SERVICE_ROLE = 'QI Role - Service';
    private static final List<String> statusCheck = new List<String> {'Submitted','Late Submission','Submitted - Updated After Due Date','Updated After Due Date'};
    private static final String DUE_TEMPLATE = 'QI_Due_Date';
    private static final String SERVICE_DUE_TEMPLATE = 'QI_Due_Date_Service_User';
    private static final String SUBMIT_TEMPLATE = 'QI_Date_Submission_Reminder';
    private static final String SUBMIT_TEMPLATE_SERVICE = 'QI_Submission_Reminder_Service_User';
    private static final String OVERDUE_TEMPLATE = 'QI_Date_Submission_Overdue_Reminder';
    private static final String OVERDUE_TEMPLATE_SERVICE = 'QI_Submission_Overdue_Reminder_Service_User';
        
    /**
     * This method will return the type of reminder - duedate, QI submission or overdue
     **/
    public String calculateQIReminderDate(List<Reporting_Period__c> prevRepPeriod){
        String reminderType = BLANK_STRING;
        if(prevRepPeriod.size()>0){
           Date todayDt = System.Today();
           Date endDate = prevRepPeriod.get(0).End_Date__c;
           Date dueDate = prevRepPeriod.get(0).QI_Submission_Due_Dt__c;
           if(endDate.daysBetween(todayDt) >= 1 && endDate.daysBetween(todayDt) < 5){
               	reminderType = DUE_REMINDER;
           	} else if(todayDt >= prevRepPeriod.get(0).Start_Date__c && (todayDt.daysBetween(dueDate)<=7 && todayDt.daysBetween(dueDate)>=4)){
               	reminderType = QI_SUBMIT;
           	} else if(todayDt >= prevRepPeriod.get(0).Start_Date__c
           			&& (dueDate.daysBetween(todayDt) >= 1 && dueDate.daysBetween(todayDt) < 5)){
           		reminderType = OVERDUE_REMINDER; 
           	} 
        }
        return reminderType;
    }
    
    /**
     * This method will prepare the list of Providers and send the reminders to the relevant contacts
     * send email reminders to the providers
     **/
    public void sendReminders(List<AccountContactRelation> acrList,EmailTemplate et){
        SendEmailNotificationService notificationService = new SendEmailNotificationService();
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        if(et != null){
        	for (AccountContactRelation acctConRelatn : acrList){
                List<String> toAddress = new List<String>();
                toAddress.add(acctConRelatn.Contact.Email);
                Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                emailMsg = notificationService.prepareEmailList(toAddress,et.Id,acctConRelatn.ContactId,acctConRelatn.AccountId);
                emailList.add(emailMsg);
            }
            notificationService.sendEmailFromList(emailList);
        }
    }
    
    /**
     * This method will prepare the data for Org Roles
     **/
    public void prepareAccountDataForOrgRole(List<AccountContactRelation> acrRelnList,List<Reporting_Period__c> prevRepPeriod,EmailTemplate et){
        List<Service_Account_Relationship__c> serviceRelationList = [select Service_Name__r.Id, Service_Name__r.Name, Provider_Name__r.Id,Provider_Name__r.Name  
                                                                                  from Service_Account_Relationship__c WHERE (Service_Name__r.Status__c = 'Operational' OR Service_Name__r.Status__c = 'Offline') AND Service_Name__r.Care_Type__c = 'Residential' AND 
                                                                                  (Association_End_Date__c = null OR Association_End_Date__c >= TODAY)];
        Set<Id> accountIds = new Set<Id>();
        for(Service_Account_Relationship__c serAccReln : serviceRelationList){
        	accountIds.add(serAccReln.Provider_Name__r.Id);
        }
        
        List<Account> acctList = [SELECT Id, PreviousReportingPeriodDueDt__c, PreviousReportingPeriodName__c, ServiceNames__c FROM Account WHERE Id IN :(accountIds)];
        List<Account> accountUpdateList = new List<Account>();
        for(Account acct:acctList){
        	String serviceName = '';
            for(Service_Account_Relationship__c serAccReln : serviceRelationList){
            	if(acct.Id == serAccReln.Provider_Name__r.Id){
                	if(!serviceName.contains(serAccReln.Service_Name__r.Name)){
                    	serviceName = serAccReln.Service_Name__r.Name +', '+ serviceName;
                    }
                    acct.PreviousReportingPeriodName__c = prevRepPeriod.get(0).Reporting_Period_Short__c;
                    acct.PreviousReportingPeriodDueDt__c = prevRepPeriod.get(0).QI_Submission_Due_Dt__c;
                }
            }
            if (serviceName!=''){
            	serviceName = serviceName.removeEnd(', ');
                acct.ServiceNames__c = serviceName;
                accountUpdateList.add(acct);
            }
        }
        if(accountUpdateList.size()>0){
        	update accountUpdateList;
        }
        sendReminders(acrRelnList,et);
    }
    
    /**
     * This method will prepare the data for Service Roles
     **/
    public void prepareContactDataForServiceRole(List<AccountContactRelation> acrRelnList,List<Reporting_Period__c> prevRepPeriod,EmailTemplate et){
         List<Contact_Relationship__c> contactRelationList = [select Service__r.Name,Service__r.Id,Contact__r.Id,Portal_Service_Roles__c from Contact_Relationship__c WHERE (Service__r.Status__c = 'Operational' OR Service__r.Status__c = 'Offline')
                                                             AND Service__r.Care_Type__c = 'Residential' AND Portal_Service_Roles__c INCLUDES ('QI Role - Service')];
        if(contactRelationList.size()>0){
            Set<ID> contactIds = new Set<ID>();
            for(Contact_Relationship__c contReln:contactRelationList){
                if(contReln.Portal_Service_Roles__c.contains('QI Role - Service') && !contReln.Portal_Service_Roles__c.contains('QI Role - Org')){
                    contactIds.add(contReln.Contact__r.Id);
                }
            }             
            List<Contact> contactList = [SELECT Id,ServiceNames__c,PreviousReportingPeriodDueDt__c,PreviousReportingPeriodName__c FROM Contact Where Id IN :(contactIds)];
            List<Contact> contactsToUpdate = new List<Contact>();
            for(Contact contct:contactList){
                String serviceName = '';
                for(Contact_Relationship__c ctReln:contactRelationList){ 
                    if(contct.Id == ctReln.Contact__r.Id){
                        if(!serviceName.contains(ctReln.Service__r.Name)){
                            serviceName = ctReln.Service__r.Name+', '+serviceName;
                        }
                        contct.PreviousReportingPeriodName__c = prevRepPeriod.get(0).Reporting_Period_Short__c;
                        contct.PreviousReportingPeriodDueDt__c = prevRepPeriod.get(0).QI_Submission_Due_Dt__c;
                    }
                } 
                if (serviceName!=''){
                	serviceName = serviceName.removeEnd(', ');
                    contct.ServiceNames__c = serviceName;
                    contactsToUpdate.add(contct);
                }
            }
            if(contactsToUpdate.size()>0){
                update contactsToUpdate;
            }
            sendReminders(acrRelnList,et);
        }
    }
    
     /**
     * This method will prepare the data for Org Roles for QI submission and Overdue
     **/
    public void prepareAccountData(List<AccountContactRelation> acrRelnList,List<Reporting_Period__c> prevRepPeriod,EmailTemplate et,String reminderType){
        List<Service_Account_Relationship__c> serviceRelationList = [select Service_Name__r.Id, Service_Name__r.Name, Provider_Name__r.Id,Provider_Name__r.Name  
                                                                                  from Service_Account_Relationship__c WHERE (Service_Name__r.Status__c = 'Operational' OR Service_Name__r.Status__c = 'Offline') AND Service_Name__r.Care_Type__c = 'Residential' AND 
                                                                                  (Association_End_Date__c = null OR Association_End_Date__c >= TODAY)];
        Set<Id> accountIds = new Set<Id>();
        Set<Id> serviceIDs = new Set<Id>();
        for(Service_Account_Relationship__c serAccReln : serviceRelationList){
        	accountIds.add(serAccReln.Provider_Name__r.Id);
            serviceIDs.add(serAccReln.Service_Name__r.Id);
        }
        List<Quality_Indicator_Summary__c> qISummaryList = new List<Quality_Indicator_Summary__c>();
        if(reminderType.equals(QI_SUBMIT)){
        	qISummaryList =  [SELECT Id, Status__c, REPORTING_PERIOD__r.Start_Date__c, REPORTING_PERIOD__r.End_Date__c, REPORTING_PERIOD__r.QI_Submission_Due_Dt__c,Service__r.Id,Service__r.Name, Service__r.AccountId FROM Quality_Indicator_Summary__c WHERE Status__c = 'Submitted' AND 
                                                             REPORTING_PERIOD__r.Previous_Reporting_Period__c = true AND Service__r.Id IN :(serviceIDs)];
        }
        else if (reminderType.equals(OVERDUE_REMINDER)){
        	qISummaryList =  [SELECT Id, Status__c, REPORTING_PERIOD__r.Start_Date__c, REPORTING_PERIOD__r.End_Date__c, REPORTING_PERIOD__r.QI_Submission_Due_Dt__c,Service__r.Id,Service__r.Name, Service__r.AccountId FROM Quality_Indicator_Summary__c 
                                                             WHERE Status__c IN :(statusCheck) AND REPORTING_PERIOD__r.Previous_Reporting_Period__c = true AND Service__r.Id IN :(serviceIDs)];
        }
        List<Account> acctList = [SELECT Id, PreviousReportingPeriodDueDt__c, PreviousReportingPeriodName__c, ServiceNames__c FROM Account WHERE Id IN :(accountIds)];
        List<Account> accountUpdateList = new List<Account>();
        for(Account acct:acctList){
        	String serviceName = '';
            for(Service_Account_Relationship__c serAccReln : serviceRelationList){
            	if(acct.Id == serAccReln.Provider_Name__r.Id){
                	if(!serviceName.contains(serAccReln.Service_Name__r.Name)){
                    	serviceName = serAccReln.Service_Name__r.Name +', '+ serviceName;
                    }
                    acct.PreviousReportingPeriodName__c = prevRepPeriod.get(0).Reporting_Period_Short__c;
                    acct.PreviousReportingPeriodDueDt__c = prevRepPeriod.get(0).QI_Submission_Due_Dt__c;
                }
            }
            if (serviceName!=''){
            	serviceName = serviceName.removeEnd(', ');
                acct.ServiceNames__c = serviceName;
                accountUpdateList.add(acct);
            }
        }
        if(accountUpdateList.size()>0){
             //check if the qi data is already submitted then remove that service name from the Account field
        	if(qISummaryList.size()>0){
                for(Account acc:accountUpdateList){
                    String serviceNames = acc.ServiceNames__c;
                    for(Quality_Indicator_Summary__c qis:qISummaryList){
                        if(acc.Id == qis.Service__r.AccountId) {
                             if(serviceNames !=null && serviceNames.contains(qis.Service__r.Name)){
                        		serviceNames = serviceNames.remove(qis.Service__r.Name+',');
                    		}                          
                        }
            		}
                    acc.ServiceNames__c = serviceNames;
                }
        	}
        	update accountUpdateList;
        }
        sendReminders(acrRelnList,et); 
    }
    
    /**
     * This method will prepare the data for Service Roles for QI submission and Overdue
     **/
    public void prepareContactData(List<AccountContactRelation> acrRelnList,List<Reporting_Period__c> prevRepPeriod,EmailTemplate et,String reminderType){
        List<Contact_Relationship__c> contactRelationList = [select Service__r.Name,Service__r.Id,Contact__r.Id,Portal_Service_Roles__c from Contact_Relationship__c WHERE (Service__r.Status__c = 'Operational' OR Service__r.Status__c = 'Offline')
                                                             AND Service__r.Care_Type__c = 'Residential' AND Portal_Service_Roles__c INCLUDES ('QI Role - Service')];
        if(contactRelationList.size()>0){
            Set<ID> contactIds = new Set<ID>();
            Set<Id> serviceIds = new Set<Id>();
            for(Contact_Relationship__c contReln:contactRelationList){
                if(contReln.Portal_Service_Roles__c.contains('QI Role - Service') && !contReln.Portal_Service_Roles__c.contains('QI Role - Org')){
                    contactIds.add(contReln.Contact__r.Id);
                    serviceIds.add(contReln.Service__r.Id);
                }
            }             
            List<Contact> contactList = [SELECT Account.Id,ServiceNames__c,PreviousReportingPeriodDueDt__c,PreviousReportingPeriodName__c FROM Contact Where Id IN :(contactIds)];
            List<Contact> contactsToUpdate = new List<Contact>();
            for(Contact contct:contactList){
                String serviceName = '';
                for(Contact_Relationship__c ctReln:contactRelationList){ 
                    if(contct.Id == ctReln.Contact__r.Id){
                        if(!serviceName.contains(ctReln.Service__r.Name)){
                            serviceName = ctReln.Service__r.Name+', '+serviceName;
                        }
                        contct.PreviousReportingPeriodName__c = prevRepPeriod.get(0).Reporting_Period_Short__c;
                        contct.PreviousReportingPeriodDueDt__c = prevRepPeriod.get(0).QI_Submission_Due_Dt__c;
                    }
                } 
                if (serviceName!=''){
                	serviceName = serviceName.removeEnd(', ');
                    contct.ServiceNames__c = serviceName;
                    contactsToUpdate.add(contct);
                }
            }
             List<Quality_Indicator_Summary__c> qISummaryList = new List<Quality_Indicator_Summary__c>();
            if(reminderType.equals(QI_SUBMIT)){
                qISummaryList =  [SELECT Id, Status__c, REPORTING_PERIOD__r.Start_Date__c, REPORTING_PERIOD__r.End_Date__c, REPORTING_PERIOD__r.QI_Submission_Due_Dt__c,Service__r.Id,Service__r.Name, Service__r.AccountId FROM Quality_Indicator_Summary__c WHERE Status__c = 'Submitted' AND 
                                                                 REPORTING_PERIOD__r.Previous_Reporting_Period__c = true AND Service__r.Id IN :(serviceIDs)];
            }
            else if (reminderType.equals(OVERDUE_REMINDER)){
                qISummaryList =  [SELECT Id, Status__c, REPORTING_PERIOD__r.Start_Date__c, REPORTING_PERIOD__r.End_Date__c, REPORTING_PERIOD__r.QI_Submission_Due_Dt__c,Service__r.Id,Service__r.Name, Service__r.AccountId FROM Quality_Indicator_Summary__c 
                                                                 WHERE Status__c IN :(statusCheck) AND REPORTING_PERIOD__r.Previous_Reporting_Period__c = true AND Service__r.Id IN :(serviceIDs)];
            }
            if(contactsToUpdate.size()>0){
                //check if the qi data is already submitted then remove that service name from the Account field
        		if(qISummaryList.size()>0){
                	for(Contact ct:contactsToUpdate){
                        String serviceNames = ct.ServiceNames__c;
                        for(Quality_Indicator_Summary__c qis:qISummaryList){
                            if(ct.Account.Id == qis.Service__r.AccountId) {
                                 if(serviceNames !=null && serviceNames.contains(qis.Service__r.Name)){
                                    serviceNames = serviceNames.remove(qis.Service__r.Name+',');
                                }                          
                            }
                        }
                        ct.ServiceNames__c = serviceNames;
                    }
                }
            	update contactsToUpdate;  
            }
            sendReminders(acrRelnList,et);
        }
    }

    /**
     * This method will fetch due template
     **/
    public List<EmailTemplate> fetchDueTemplate(){
        List<EmailTemplate> etList = [SELECT Id,HtmlValue,Body,DeveloperName FROM EmailTemplate WHERE (DeveloperName = :DUE_TEMPLATE OR DeveloperName = :SERVICE_DUE_TEMPLATE)];
        return etList;
    }
    
    /**
     * This method will fetch due template
     **/
    public List<EmailTemplate> fetchQISubmitTemplate(){
        List<EmailTemplate> etList = [SELECT Id,HtmlValue,Body,DeveloperName FROM EmailTemplate WHERE (DeveloperName = :SUBMIT_TEMPLATE OR DeveloperName = :SUBMIT_TEMPLATE_SERVICE)];
        return etList;
    }
    
    /**
     * This method will fetch due template
     **/
    public List<EmailTemplate> fetchOverdueTemplate(){
        List<EmailTemplate> etList = [SELECT Id,HtmlValue,Body,DeveloperName FROM EmailTemplate WHERE (DeveloperName = :OVERDUE_TEMPLATE OR DeveloperName = :OVERDUE_TEMPLATE_SERVICE)];
        return etList;
    }
}