force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Party_ID__c.field-meta.xml
<CustomField>
    <fullName>Party_ID__c</fullName>
    <description>Primary key to link the Provider Record to GovGPS Record</description>
    <label>Party ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Commonwealth_Home_Support_Programme.recordType-meta.xml
<RecordType>
    <fullName>Commonwealth_Home_Support_Programme</fullName>
    <active>true</active>
    <description>Commonwealth Home Support Programme</description>
    <label>Commonwealth Home Support Programme</label>
</RecordType>

force-app/main/default/objects/Aged_Care_Planning_Region__c/Aged_Care_Planning_Region__c.object-meta.xml
<CustomObject>
    <label>Aged Care Planning Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aged Care Planning Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Aged_Care_Planning_Region__c/fields/ACPR_State__c.field-meta.xml
<CustomField>
    <fullName>ACPR_State__c</fullName>
    <label>ACPR State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aged_Care_Planning_Region__c/fields/Geospatial_Information_Layer_Version__c.field-meta.xml
<CustomField>
    <fullName>Geospatial_Information_Layer_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Geospatial Information Layer Version</label>
    <referenceTo>GPMS_Geospatial_Information_LayerVersion__c</referenceTo>
    <relationshipLabel>Aged Care Planning Regions</relationshipLabel>
    <relationshipName>Aged_Care_Planning_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <label>Party Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Care Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community and Home Support</fullName>
            </value>
            <value>
                <fullName>Service System Development</fullName>
            </value>
            <value>
                <fullName>Care Relationship and Carer Support</fullName>
            </value>
            <value>
                <fullName>Assistance with Care and Housing</fullName>
            </value>
            <value>
                <fullName>Transition Care</fullName>
            </value>
            <value>
                <fullName>Innovative Pool</fullName>
            </value>
            <value>
                <fullName>Multi-Purpose Service</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Short-Term Restorative Care (STRC)</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>EACH Dementia</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Home Care Packages</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC High Care</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC High Care Dementia</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC Low Care</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retirement Villages Care Pilot</fullName>
            </value>
            <value>
                <fullName>Extended Aged Care at Home</fullName>
            </value>
            <value>
                <fullName>STRC</fullName>
                <isActive>false</isActive>
                <label>STRC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/CHSP_Service.recordType-meta.xml
<RecordType>
    <fullName>CHSP_Service</fullName>
    <active>true</active>
    <label>CHSP Service</label>
</RecordType>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/CHSP_Procurement_Based_AWP_Record__c.object-meta.xml
<CustomObject>
    <label>CHSP Procurement Based AWP Record</label>
    <nameField>
        <displayFormat>CPAWP-{000000000}</displayFormat>
        <label>CHSP Procurement Based AWP Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Procurement Based AWP Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Activity_Work_Plan_ID__c.field-meta.xml
<CustomField>
    <fullName>Activity_Work_Plan_ID__c</fullName>
    <externalId>true</externalId>
    <label>Activity Work Plan ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Aged_Care_Planning_Region__c.field-meta.xml
<CustomField>
    <fullName>Aged_Care_Planning_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aged Care Planning Region</label>
    <referenceTo>Aged_Care_Planning_Region__c</referenceTo>
    <relationshipLabel>CHSP Procurement Based AWP Records</relationshipLabel>
    <relationshipName>CHSP_Procurement_Based_AWP_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Party_ID__c.field-meta.xml
<CustomField>
    <fullName>Party_ID__c</fullName>
    <label>Party ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>CHSP Procurement Based AWP Records</relationshipLabel>
    <relationshipName>CHSP_Procurement_Based_AWP_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Service Care Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Service_Type_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Level__c</fullName>
    <label>Service Type Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Schedule__c/CHSP_Service_Schedule__c.object-meta.xml
<CustomObject>
    <label>CHSP Schedule Detail</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CHSP Schedule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Schedule Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CHSP Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Commonwealth Home Support Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CHSP Schedule Details</relationshipLabel>
    <relationshipName>CHSP_Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <label>Party Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>CHSP Service Schedules</relationshipLabel>
    <relationshipName>CHSP_Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPMS_Geospatial_Information_LayerVersion__c/GPMS_Geospatial_Information_LayerVersion__c.object-meta.xml
<CustomObject>
    <label>Geospatial Information Layer Version</label>
    <nameField>
        <displayFormat>GILV-{00000}</displayFormat>
        <label>Geospatial Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geospatial Information Layer Version</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GPMS_Geospatial_Information_LayerVersion__c/fields/GPMS_Layer__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Layer__c</fullName>
    <description>The layer of the Geospatial layer version table</description>
    <label>Layer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPMS_Geospatial_Information_LayerVersion__c/fields/GPMS_Version__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Version__c</fullName>
    <description>The version of the Geospatial Layer Version table</description>
    <label>Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GPMSCHSPCPAWPLinkServiceHelperTest.cls
@IsTest
public class GPMSCHSPCPAWPLinkServiceHelperTest {

    @TestSetup
    static void setup() {
        TestDataFactory.createSystemAdminUser();
        User adminUser = TestDataFactory.createSystemAdminUser();
        System.runAs(adminUser) {
            GPMS_Geospatial_Information_LayerVersion__c layerVersionRecord = new GPMS_Geospatial_Information_LayerVersion__c();
            layerVersionRecord.GPMS_Layer__c = 'Aged Care Planning Regions';
            layerVersionRecord.GPMS_Version__c = '2023';
            layerVersionRecord.Start_Date__c = Date.today().addDays(-1);
            layerVersionRecord.End_Date__c = null;
            insert layerVersionRecord;
            
            GPMS_Geospatial_Information_LayerVersion__c layerVersionRecordExpired = new GPMS_Geospatial_Information_LayerVersion__c();
            layerVersionRecordExpired.GPMS_Layer__c = 'Aged Care Planning Regions';
            layerVersionRecordExpired.GPMS_Version__c = '2022';
            layerVersionRecordExpired.Start_Date__c = Date.today().addDays(-200);
            layerVersionRecordExpired.End_Date__c = Date.today().addDays(-100);
            insert layerVersionRecordExpired;
            
            Aged_Care_Planning_Region__c acprRecord1 = new Aged_Care_Planning_Region__c();
            acprRecord1.Name = GPMSCHSPConstants.ACPR_REGION_2;
            acprRecord1.ACPR_State__c = 'QLD';
            acprRecord1.Geospatial_Information_Layer_Version__c = layerVersionRecord.Id;
            insert acprRecord1;
            
            Aged_Care_Planning_Region__c acprRecord2 = new Aged_Care_Planning_Region__c();
            acprRecord2.Name = GPMSCHSPConstants.ACPR_REGION_1;
            acprRecord2.ACPR_State__c = 'VIC';
            acprRecord2.Geospatial_Information_Layer_Version__c = layerVersionRecord.Id;
            insert acprRecord2;
            
            Aged_Care_Planning_Region__c acprRecord3 = new Aged_Care_Planning_Region__c();
            acprRecord3.Name = GPMSCHSPConstants.ACPR_REGION_1;
            acprRecord3.ACPR_State__c = 'VIC';
            acprRecord3.Geospatial_Information_Layer_Version__c = layerVersionRecordExpired.Id;
            insert acprRecord3;
            
            Aged_Care_Planning_Region__c acprRecord4 = new Aged_Care_Planning_Region__c();
            acprRecord4.Name = GPMSCHSPConstants.ACPR_REGION_3;
            acprRecord4.ACPR_State__c = 'VIC';
            acprRecord4.Geospatial_Information_Layer_Version__c = layerVersionRecordExpired.Id;
            insert acprRecord4;
            
            Aged_Care_Planning_Region__c acprRecord5 = new Aged_Care_Planning_Region__c();
            acprRecord5.Name = GPMSCHSPConstants.ACPR_REGION_4;
            acprRecord5.ACPR_State__c = null;
            acprRecord5.Geospatial_Information_Layer_Version__c = layerVersionRecord.Id;
            insert acprRecord5;
        }
    }
    
    @IsTest
    static void testServiceCreated() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
            // Create Scope
            Account chspProvider = new Account(Name = 'ProviderA',Incorporation_ID_Type__c='Other');
            chspProvider.Party_ID__c = GPMSCHSPConstants.TEST_PARTYID_2; // Required for populating Organisation_Name__c in CHSP_Service_Schedule__c (trigger another Flow)
            chspProvider.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commonwealth_Home_Support_Programme').getRecordTypeId();
            Insert chspProvider;
            
            List<CHSP_Procurement_Based_AWP_Record__c> chspAWPRecords = new List<CHSP_Procurement_Based_AWP_Record__c>();
            for(Integer i=0; i<2; i++) {
                CHSP_Procurement_Based_AWP_Record__c chspAWPRecord = new CHSP_Procurement_Based_AWP_Record__c();
                chspAWPRecord.Service_Type_Level__c = GPMSCHSPConstants.SERVICE_TYPE_LEVEL_2; // Required for populating Service_Care_Sub_Type__c (trigger another Flow)
                chspAWPRecord.Party_ID__c = chspProvider.Party_ID__c;
                chspAWPRecord.Service_Care_Sub_Type__c = GPMSCHSPConstants.SERVICE_SUB_CARE_TYPE_2;
                chspAWPRecord.Activity_Status__c = 'Approved';
                chspAWPRecord.Service_Area__c = 'Central West (QLD)';
                chspAWPRecord.Activity_Work_Plan_ID__c = '4-XY'+i+'RJKL';
                chspAWPRecords.add(chspAWPRecord);
            }
            insert chspAWPRecords;
            
            // Get scope
            List<CHSP_Procurement_Based_AWP_Record__c> scope = [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c, Activity_Status__c, Service_Area__c
                                                    		FROM CHSP_Procurement_Based_AWP_Record__c
                                                    		WHERE Service__c = null AND Party_Id__c != null AND Service_Care_Sub_Type__c != null];
            
            // Execute GPMSCHSPLinkService
            GPMSCHSPCPAWPLinkServiceHelper chspLinkServiceHelper = new GPMSCHSPCPAWPLinkServiceHelper(scope);
            chspLinkServiceHelper.executeGPMSCHSPCPAWPLinkService();
            
            List<BusinessLicense> services = [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c 
                                              FROM BusinessLicense];
            System.assert(services.size() > 0, 'There should be at least one service created.');
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testServiceCreatedOtherRegion() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
            // Create Scope
            Account chspProvider = new Account(Name = 'ProviderA',Incorporation_ID_Type__c='Other');
            chspProvider.Party_ID__c = GPMSCHSPConstants.TEST_PARTYID_2; // Required for populating Organisation_Name__c in CHSP_Service_Schedule__c (trigger another Flow)
            chspProvider.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commonwealth_Home_Support_Programme').getRecordTypeId();
            Insert chspProvider;
            
            List<CHSP_Procurement_Based_AWP_Record__c> chspAWPRecords = new List<CHSP_Procurement_Based_AWP_Record__c>();
            for(Integer i=0; i<2; i++) {
                CHSP_Procurement_Based_AWP_Record__c chspAWPRecord = new CHSP_Procurement_Based_AWP_Record__c();
                chspAWPRecord.Service_Type_Level__c = GPMSCHSPConstants.SERVICE_TYPE_LEVEL_2; // Required for populating Service_Care_Sub_Type__c (trigger another Flow)
                chspAWPRecord.Party_ID__c = chspProvider.Party_ID__c;
                chspAWPRecord.Service_Care_Sub_Type__c = GPMSCHSPConstants.SERVICE_SUB_CARE_TYPE_2;
                chspAWPRecord.Activity_Status__c = 'Approved';
                chspAWPRecord.Service_Area__c = 'ACT';
                chspAWPRecord.Activity_Work_Plan_ID__c = '4-XY'+i+'RJKL';
                chspAWPRecords.add(chspAWPRecord);
            }
            insert chspAWPRecords;
            
            // Get scope
            List<CHSP_Procurement_Based_AWP_Record__c> scope = [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c, Activity_Status__c, Service_Area__c
                                                    		FROM CHSP_Procurement_Based_AWP_Record__c
                                                    		WHERE Service__c = null AND Party_Id__c != null AND Service_Care_Sub_Type__c != null];
            
            // Execute GPMSCHSPLinkService
            GPMSCHSPCPAWPLinkServiceHelper chspLinkServiceHelper = new GPMSCHSPCPAWPLinkServiceHelper(scope);
            chspLinkServiceHelper.executeGPMSCHSPCPAWPLinkService();
            
            List<BusinessLicense> services = [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c 
                                              FROM BusinessLicense];
            System.assert(services.size() > 0, 'There should be at least one service created.');
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testServiceUpdate() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
            // Create Scope
            Account chspProvider = new Account(Name = 'ProviderA',Incorporation_ID_Type__c='Other');
            chspProvider.Party_ID__c = GPMSCHSPConstants.TEST_PARTYID_2; // Required for populating Organisation_Name__c in CHSP_Service_Schedule__c (trigger another Flow)
            chspProvider.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commonwealth_Home_Support_Programme').getRecordTypeId();
            Insert chspProvider;
            
            List<CHSP_Procurement_Based_AWP_Record__c> chspAWPRecords = new List<CHSP_Procurement_Based_AWP_Record__c>();
            for(Integer i=0; i<2; i++) {
                CHSP_Procurement_Based_AWP_Record__c chspAWPRecord = new CHSP_Procurement_Based_AWP_Record__c();
                chspAWPRecord.Service_Type_Level__c = GPMSCHSPConstants.SERVICE_TYPE_LEVEL_2; // Required for populating Service_Care_Sub_Type__c (trigger another Flow)
                chspAWPRecord.Party_ID__c = chspProvider.Party_ID__c;
                chspAWPRecord.Service_Care_Sub_Type__c = GPMSCHSPConstants.SERVICE_SUB_CARE_TYPE_2;
                chspAWPRecord.Activity_Status__c = 'Approved';
                chspAWPRecord.Service_Area__c = GPMSCHSPConstants.ACPR_REGION_1;
                chspAWPRecord.Activity_Work_Plan_ID__c = '4-XY'+i+'RJKL';
                chspAWPRecords.add(chspAWPRecord);
            }
            insert chspAWPRecords;
            
            // Create existing service
            BusinessLicense existingService = new BusinessLicense();
            existingService.RecordTypeId = Schema.SObjectType.BusinessLicense
        		.getRecordTypeInfosByDeveloperName()
                .get('CHSP_Service').getRecordTypeId();
            existingService.Care_Type__c = 'Commonwealth Home Support Programme';
            existingService.Party_Id__c = GPMSCHSPConstants.TEST_PARTYID_2;
            existingService.Service_Name_Effective_Date__c = Date.today();
            existingService.Status_Date__c = Date.today();
            existingService.Service_Care_Sub_Type__c = GPMSCHSPConstants.SERVICE_SUB_CARE_TYPE_2;
            existingService.Status__c = 'Inactive';
            existingService.Name = 'Test Service Name';
            insert existingService;
            
            // Get scope
            List<CHSP_Procurement_Based_AWP_Record__c> scope = [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c, Activity_Status__c, Service_Area__c
                                                    		FROM CHSP_Procurement_Based_AWP_Record__c
                                                    		WHERE Service__c = null AND Party_Id__c != null AND Service_Care_Sub_Type__c != null];
            
            // Execute GPMSCHSPLinkService
            GPMSCHSPCPAWPLinkServiceHelper chspLinkServiceHelper = new GPMSCHSPCPAWPLinkServiceHelper(scope);
            chspLinkServiceHelper.executeGPMSCHSPCPAWPLinkService();
            
            List<BusinessLicense> services = [SELECT Id, Party_Id__c, Service_Care_Sub_Type__c, Status__c 
                                              FROM BusinessLicense];
            System.assertEquals('Operational', services[0].Status__c, 'Existing service status should be operational.');
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testServiceUpdateToInactive() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
            // Create Scope
            Account chspProvider = new Account(Name = 'ProviderA',Incorporation_ID_Type__c='Other');
            chspProvider.Party_ID__c = GPMSCHSPConstants.TEST_PARTYID_2; // Required for populating Organisation_Name__c in CHSP_Service_Schedule__c (trigger another Flow)
            chspProvider.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commonwealth_Home_Support_Programme').getRecordTypeId();
            Insert chspProvider;
            
            List<CHSP_Procurement_Based_AWP_Record__c> chspAWPRecords = new List<CHSP_Procurement_Based_AWP_Record__c>();
            for(Integer i=0; i<2; i++) {
                CHSP_Procurement_Based_AWP_Record__c chspAWPRecord = new CHSP_Procurement_Based_AWP_Record__c();
                chspAWPRecord.Service_Type_Level__c = GPMSCHSPConstants.SERVICE_TYPE_LEVEL_2; // Required for populating Service_Care_Sub_Type__c (trigger another Flow)
                chspAWPRecord.Party_ID__c = chspProvider.Party_ID__c;
                chspAWPRecord.Service_Care_Sub_Type__c = GPMSCHSPConstants.SERVICE_SUB_CARE_TYPE_2;
                chspAWPRecord.Activity_Status__c = 'Inactive';
                chspAWPRecord.Service_Area__c = GPMSCHSPConstants.ACPR_REGION_1;
                chspAWPRecord.Activity_Work_Plan_ID__c = '4-XY'+i+'RJKL';
                chspAWPRecords.add(chspAWPRecord);
            }
            insert chspAWPRecords;
            
            // Create existing service
            BusinessLicense existingService = new BusinessLicense();
            existingService.RecordTypeId = Schema.SObjectType.BusinessLicense
        		.getRecordTypeInfosByDeveloperName()
                .get('CHSP_Service').getRecordTypeId();
            existingService.Care_Type__c = 'Commonwealth Home Support Programme';
            existingService.Party_Id__c = GPMSCHSPConstants.TEST_PARTYID_2;
            existingService.Service_Name_Effective_Date__c = Date.today();
            existingService.Status_Date__c = Date.today();
            existingService.Service_Care_Sub_Type__c = GPMSCHSPConstants.SERVICE_SUB_CARE_TYPE_2;
            existingService.Status__c = 'Operational';
            existingService.Name = 'Test Service Name';
            insert existingService;
            
            // Get scope
            List<CHSP_Procurement_Based_AWP_Record__c> scope = [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c, Activity_Status__c, Service_Area__c
                                                    		FROM CHSP_Procurement_Based_AWP_Record__c
                                                    		WHERE Service__c = null AND Party_Id__c != null AND Service_Care_Sub_Type__c != null];
            
            // Execute GPMSCHSPLinkService
            GPMSCHSPCPAWPLinkServiceHelper chspLinkServiceHelper = new GPMSCHSPCPAWPLinkServiceHelper(scope);
            chspLinkServiceHelper.executeGPMSCHSPCPAWPLinkService();
            
            List<BusinessLicense> services = [SELECT Id, Party_Id__c, Service_Care_Sub_Type__c, Status__c 
                                              FROM BusinessLicense];
            System.assertEquals('Inactive', services[0].Status__c, 'Existing service status should be inactive.');
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testNoProvider() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
            
            List<CHSP_Procurement_Based_AWP_Record__c> chspAWPRecords = new List<CHSP_Procurement_Based_AWP_Record__c>();
            for(Integer i=0; i<2; i++) {
                CHSP_Procurement_Based_AWP_Record__c chspAWPRecord = new CHSP_Procurement_Based_AWP_Record__c();
                chspAWPRecord.Service_Type_Level__c = GPMSCHSPConstants.SERVICE_TYPE_LEVEL_2; // Required for populating Service_Care_Sub_Type__c (trigger another Flow)
                chspAWPRecord.Party_ID__c = GPMSCHSPConstants.TEST_PARTYID_2;
                chspAWPRecord.Service_Care_Sub_Type__c = GPMSCHSPConstants.SERVICE_SUB_CARE_TYPE_2;
                chspAWPRecord.Activity_Status__c = 'Approved';
                chspAWPRecord.Service_Area__c = GPMSCHSPConstants.ACPR_REGION_1;
                chspAWPRecord.Activity_Work_Plan_ID__c = '4-XY'+i+'RJKL';
                chspAWPRecords.add(chspAWPRecord);
            }
            insert chspAWPRecords;
            
            
			// Get scope
            List<CHSP_Procurement_Based_AWP_Record__c> scope = [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c, Activity_Status__c, Service_Area__c
                                                    		FROM CHSP_Procurement_Based_AWP_Record__c
                                                    		WHERE Service__c = null AND Party_Id__c != null AND Service_Care_Sub_Type__c != null];
            
            // Execute GPMSCHSPLinkService
            GPMSCHSPCPAWPLinkServiceHelper chspLinkServiceHelper = new GPMSCHSPCPAWPLinkServiceHelper(scope);
            chspLinkServiceHelper.executeGPMSCHSPCPAWPLinkService();
            
            List<BusinessLicense> services = [SELECT Id, Party_Id__c, Service_Care_Sub_Type__c, Status__c 
                                              FROM BusinessLicense];
            
            System.assert(services.size() == 1, 'A service should be created.');
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testNoWorkPlan() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
            
			// Get scope
            List<CHSP_Procurement_Based_AWP_Record__c> scope = [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c, Activity_Status__c, Service_Area__c
                                                    		FROM CHSP_Procurement_Based_AWP_Record__c
                                                    		WHERE Service__c = null AND Party_Id__c != null AND Service_Care_Sub_Type__c != null];
            
            // Execute GPMSCHSPLinkService
            GPMSCHSPCPAWPLinkServiceHelper chspLinkServiceHelper = new GPMSCHSPCPAWPLinkServiceHelper(scope);
            chspLinkServiceHelper.executeGPMSCHSPCPAWPLinkService();
            
            List<BusinessLicense> services = [SELECT Id, Party_Id__c, Service_Care_Sub_Type__c, Status__c 
                                              FROM BusinessLicense];
            
            System.assert(services.size() == 0, 'No service should be created.');
        }
        Test.stopTest();
    }
}