force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Oracle_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_ID__c</fullName>
    <description>Oracle ID used for migration only. Read-only thereafter.</description>
    <externalId>true</externalId>
    <label>Oracle ID</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/Allotment__c/Allotment__c.object-meta.xml
<CustomObject>
    <label>Allotment</label>
    <nameField>
        <displayFormat>ALMT-{00000}</displayFormat>
        <label>Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allotment__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>NATSIFAC</fullName>
            </value>
            <value>
                <fullName>Innovative Pool</fullName>
                <isActive>false</isActive>
                <label>Innovative Pool</label>
            </value>
            <value>
                <fullName>Multiple-Purpose Service</fullName>
                <isActive>false</isActive>
                <label>Multiple-Purpose Service</label>
            </value>
            <value>
                <fullName>Short Term Restorative Care(STRC)</fullName>
                <isActive>false</isActive>
                <label>Short Term Restorative Care(STRC)</label>
            </value>
            <value>
                <fullName>Transition Care</fullName>
                <isActive>false</isActive>
                <label>Transition Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Oracle_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_ID__c</fullName>
    <description>Oracle ID used for migration only. Read-only thereafter.</description>
    <externalId>true</externalId>
    <label>Oracle ID</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Oracle_Service_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Service_ID__c</fullName>
    <description>Migration value for APPROVAL_ID</description>
    <externalId>true</externalId>
    <label>Oracle Service ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Oracle_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_ID__c</fullName>
    <description>Oracle ID used for migration only. Read-only thereafter.</description>
    <externalId>true</externalId>
    <label>Oracle ID</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BusinessLicenseHandlerTest.cls
@isTest
private class BusinessLicenseHandlerTest {
    private static final User testAdminUser1 = TestDataFactory.insertNewSysAdmin();
    private static final String APPROVED_PROVIDER_REC_TYPE = 'Approved_Provider';
    private static final Integer RECORD_COUNT = 1;
    private static final String SERVICE_GROUP_NAME_PREFIX = 'SRV_';

    @TestSetup
    static void makeData() {
        System.runAs(testAdminUser1) {
            // Insert providers
            List<Account> providers = TestDataFactory.createProviderRecords(RECORD_COUNT);
            insert providers;

            // Insert care type
            List<Care_Type__c> careTypeList = TestDataFactory.createSCRcareType(1, providers);
            insert careTypeList;

            // Insert services
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(RECORD_COUNT);
            insert services;

            // As per the new requirements, everytime a service is created, the status will be defaulted to 'Inactive'.
            // The system requires an Allotment to be attached to the Service in order to make the service Operational
            List<Allotment__c> allotments = TestDataFactory.createAllotments(RECORD_COUNT, services);
            insert allotments;

            List<Places_Allotment__c> placesAllotments = TestDataFactory.createPlacesAllotments(RECORD_COUNT, allotments);
            insert placesAllotments;

            // This update will trigger flow Service: Update Service Status Start Date and set service status to operational
            update services;
            Test.getEventBus().deliver();

            // Insert service account relationships and the flow, 'SACR : Update Service', will assign account to service
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(
                RECORD_COUNT,
                services,
                providers
            );
            insert serviceAccountRecords;
        }
    }

    @isTest
    public static void testOwnershipChangeBusinessLicenseUpdate() {
        System.runAs(testAdminUser1) {
            // Given
            Test.startTest();
            Account accountToInsert = GPMSTestUtility.getACOAccount();
            insert accountToInsert;

            Contact contactToInsert = GPMSTestUtility.getContact();
            insert contactToInsert;

            BusinessLicense service = [SELECT Id, Status__c FROM BusinessLicense LIMIT 1].get(0);
            String groupName = SERVICE_GROUP_NAME_PREFIX + service.Id;
            Integer recordCount = Database.countQuery('SELECT Count() FROM Group WHERE DeveloperName = \'' + groupName + '\'');
            Assert.areEqual(1, recordCount, 'Expected public group to be created');

            User adminUser2 = TestDataFactory.createSystemAdminUser();
            adminUser2.IsActive = true;
            update adminUser2;

            // When
            service.OwnerId = adminUser2.Id;
            update service;
            Test.getEventBus().deliver();
            Test.stopTest();

            // Then
            Integer count = Database.countQuery('SELECT Count() FROM BusinessLicenseShare WHERE ParentId = \'' + service.Id + '\' AND RowCause = \'Manual\'');
            Assert.areEqual(1, count, 'Expected BusinessLicenseShare record to be created');
        }
    }

    @isTest
    public static void testCreateDeletePublicGroupAfterBusinessLicenseInsertDelete() {
        System.runAs(testAdminUser1) {
            // Given
            Test.startTest();
            BusinessLicense service = [SELECT Id, Status__c FROM BusinessLicense LIMIT 1].get(0);
            String groupName = SERVICE_GROUP_NAME_PREFIX + service.Id;
            Integer recordCount = Database.countQuery('SELECT Count() FROM Group WHERE DeveloperName = \'' + groupName + '\'');
            Assert.areEqual(1, recordCount, 'Expected public group to exist');

            // When
            delete service;
            Test.getEventBus().deliver();
            Test.stopTest();

            // Then
            recordCount = Database.countQuery('SELECT Count() FROM Group WHERE DeveloperName = \'' + groupName + '\'');
            Assert.areEqual(0, recordCount, 'Expected public group to be deleted');
        }
    }

    @isTest
    public static void testCreateGroupAfterSAR() {
        System.runAs(testAdminUser1) {
            // Given
            Id approvedProviderRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                .get(APPROVED_PROVIDER_REC_TYPE)
                .getRecordTypeId();
            List<Account> providers = [SELECT Id FROM Account WHERE RecordTypeId = :approvedProviderRecordTypeId];

            List<Contact> providerContacts = TestDataFactory.createContact(
                RECORD_COUNT,
                providers
            );
            insert providerContacts;

            List<AccountContactRelation> acrs = [
                SELECT Id
                FROM AccountContactRelation
                WHERE ContactId IN :new Map<Id, Contact>(providerContacts).keySet()
            ];
            for (AccountContactRelation acr : acrs) {
                acr.Roles = AccountContactRelationshipTriggerService.ROLE_STAR_RATING_REVIEWER;
            }
            update acrs;

            List<User> providerPortalUsers = TestDataFactory.createProviderPortalUser(
                RECORD_COUNT,
                providerContacts
            );


            // Test situation that groups are created 'AFTER' SAR imported so we need to
            // again create new services and make them operational after inserting SARs
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(RECORD_COUNT);
            setServiceUniqueOracleId(services);
            insert services;

            // Insert service account relationships and the flow will assign account to service
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(
                RECORD_COUNT,
                services,
                providers
            );
            insert serviceAccountRecords;

            // When
            Test.startTest();
            // As per the new requirements, everytime a service is created, the status will be defaulted to 'Inactive'.
            // The system requires an Allotment to be attached to the Service in order to make the service Operational
            List<Allotment__c> allotments = TestDataFactory.createAllotments(RECORD_COUNT, services);
            insert allotments;

            List<Places_Allotment__c> placesAllotments = TestDataFactory.createPlacesAllotments(RECORD_COUNT, allotments);
            setPlacesAllotmentUniqueOracleId(placesAllotments);
            insert placesAllotments;

            // This update will trigger flow Service: Update Service Status Start Date and set service status to operational
            update services;
            Test.getEventBus().deliver();
            Test.stopTest();

            // Then
            String groupName = SERVICE_GROUP_NAME_PREFIX + services[0].Id;
            Group publicGroup = [SELECT Id FROM Group WHERE DeveloperName = :groupName LIMIT 1];
            List<GroupMember> publicGroupMembers = [
                SELECT Id
                FROM GroupMember
                WHERE GroupId = :publicGroup.Id
                AND UserOrGroupId = :providerPortalUsers[0].Id
            ];
            Assert.areEqual(
                RECORD_COUNT, publicGroupMembers.size(),
                'Expected existing community user to be added to public group when SAR is imported AFTER group creation');
        }
    }

    @isTest
    public static void testCreateGroupBeforeSAR() {
        System.runAs(testAdminUser1) {
            // Given
            Id approvedProviderRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                .get(APPROVED_PROVIDER_REC_TYPE)
                .getRecordTypeId();
            List<Account> providers = [SELECT Id FROM Account WHERE RecordTypeId = :approvedProviderRecordTypeId];

            List<Contact> providerContacts = TestDataFactory.createContact(
                RECORD_COUNT,
                providers
            );
            insert providerContacts;

            List<AccountContactRelation> acrs = [
                SELECT Id
                FROM AccountContactRelation
                WHERE ContactId IN :new Map<Id, Contact>(providerContacts).keySet()
            ];
            for (AccountContactRelation acr : acrs) {
                acr.Roles = AccountContactRelationshipTriggerService.ROLE_STAR_RATING_REVIEWER;
            }
            update acrs;

            List<User> providerPortalUsers = TestDataFactory.createProviderPortalUser(
                RECORD_COUNT,
                providerContacts
            );

            // Test situation that groups are created 'BEFORE' SAR imported so we need to
            // again create new services and make them operational after inserting SARs
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(RECORD_COUNT);
            setServiceUniqueOracleId(services);
            insert services;

            // When
            // As per the new requirements, everytime a service is created, the status will be defaulted to 'Inactive'.
            // The system requires an Allotment to be attached to the Service in order to make the service Operational
            List<Allotment__c> allotments = TestDataFactory.createAllotments(RECORD_COUNT, services);
            insert allotments;

            List<Places_Allotment__c> placesAllotments = TestDataFactory.createPlacesAllotments(RECORD_COUNT, allotments);
            setPlacesAllotmentUniqueOracleId(placesAllotments);
            insert placesAllotments;

            // This update will trigger flow Service: Update Service Status Start Date and set service status to operational
            update services;
            Test.getEventBus().deliver();

            // Insert service account relationships and the flow will assign account to service
            Test.startTest();
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(
                RECORD_COUNT,
                services,
                providers
            );
            insert serviceAccountRecords;
            Test.stopTest();

            // Then
            String groupName = SERVICE_GROUP_NAME_PREFIX + services[0].Id;
            Group publicGroup = [SELECT Id FROM Group WHERE DeveloperName = :groupName LIMIT 1];
            List<GroupMember> publicGroupMembers = [
                SELECT Id
                FROM GroupMember
                WHERE GroupId = :publicGroup.Id
                AND UserOrGroupId = :providerPortalUsers[0].Id
            ];
            Assert.areEqual(
                RECORD_COUNT, publicGroupMembers.size(),
                'Expected existing community user to be added to public group when SAR is imported BEFORE group creation');
        }
    }


    // When calling TestDataFactory.createServiceRecords more than once, we need to assign unique Oracle_Service_ID__c
    private static void setServiceUniqueOracleId(List<BusinessLicense> services) {
        List<BusinessLicense> serviceWithLastOracleId = [
            SELECT Oracle_Service_ID__c
            FROM BusinessLicense
            ORDER BY Oracle_Service_ID__c DESC
            LIMIT 1
        ];
        if (!serviceWithLastOracleId.isEmpty()) {
            for (Integer i = 0; i < services.size(); i++) {
                services[i].Oracle_Service_ID__c = serviceWithLastOracleId.get(0).Oracle_Service_ID__c + (i + 1);
            }
        }
    }

    // When calling TestDataFactory.createPlacesAllotments more than once, we need to assign unique Oracle_ID__c
    private static void setPlacesAllotmentUniqueOracleId(List<Places_Allotment__c> placesAllotments) {
        List<Places_Allotment__c> placesAllotmentWithLastOracleId = [
            SELECT Oracle_ID__c
            FROM Places_Allotment__c
            ORDER BY Oracle_ID__c DESC
            LIMIT 1
        ];
        if (!placesAllotmentWithLastOracleId.isEmpty()) {
            for (Integer i = 0; i < placesAllotments.size(); i++) {
                placesAllotments[i].Oracle_ID__c = Integer.valueOf(placesAllotmentWithLastOracleId.get(0).Oracle_ID__c) + (i + 1);
            }
        }
    }
}