force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accreditation_Certification__c/Accreditation_Certification__c.object-meta.xml
<CustomObject>
    <label>Accreditation/Certification</label>
    <nameField>
        <displayFormat>AC-{0000000}</displayFormat>
        <label>Accreditation/Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accreditation/Certifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Accreditation_Certification__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Details the end date of the accreditation period.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Accreditation_Certification__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Details the start date of the accreditation period.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Accreditation_Certification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Accredited</fullName>
            </value>
            <value>
                <fullName>Not Accredited</fullName>
            </value>
            <value>
                <fullName>Compliant</fullName>
            </value>
            <value>
                <fullName>Non-compliant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accreditation_Certification__c/recordTypes/Accreditation.recordType-meta.xml
<RecordType>
    <fullName>Accreditation</fullName>
    <active>true</active>
    <description>Accreditation</description>
    <label>Accreditation</label>

</RecordType>

force-app/main/default/objects/Accreditation_Certification__c/recordTypes/Certification.recordType-meta.xml
<RecordType>
    <fullName>Certification</fullName>
    <active>true</active>
    <description>Certification</description>
    <label>Certification</label>
</RecordType>

force-app/main/default/objects/Allotment__c/Allotment__c.object-meta.xml
<CustomObject>
    <label>Allotment</label>
    <nameField>
        <displayFormat>ALMT-{00000}</displayFormat>
        <label>Allotment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allotments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allotment__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>NATSIFAC</fullName>
            </value>
            <value>
                <fullName>Innovative Pool</fullName>
                <isActive>false</isActive>
                <label>Innovative Pool</label>
            </value>
            <value>
                <fullName>Multiple-Purpose Service</fullName>
                <isActive>false</isActive>
                <label>Multiple-Purpose Service</label>
            </value>
            <value>
                <fullName>Short Term Restorative Care(STRC)</fullName>
                <isActive>false</isActive>
                <label>Short Term Restorative Care(STRC)</label>
            </value>
            <value>
                <fullName>Transition Care</fullName>
                <isActive>false</isActive>
                <label>Transition Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <description>The name of the related Service.</description>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Allotments</relationshipLabel>
    <relationshipName>Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allotment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Provisional</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Ceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/Approved_Provider_Service.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Service</fullName>
    <active>true</active>
    <label>Approved Provider Service</label>
</RecordType>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Allotment__c.field-meta.xml
<CustomField>
    <fullName>Allotment__c</fullName>
    <label>Allotment</label>
    <referenceTo>Allotment__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Places_Allotment__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateExemptionsBatchTest.cls
@isTest
public with sharing class CreateExemptionsBatchTest {
	static final String SERVICE_STATUS = 'Operational';
	static final String SERVICE_CARE_TYPE = 'Residential';
	static final String SERVICE_REC_TYPE = 'Approved_Provider_Service';

	@TestSetup
	static void makeData() {
		User testUser = TestDataFactory.createSystemAdminUser();
		Test.startTest();
		System.runAs(testUser){
			Integer recordCount = 10;

			// create report period type year
			Reporting_Period__c yearRP = TestDataFactory.createReportingPeriod('Year');
			Integer yearDate = System.today().Year() - 1;
			yearRP.Start_Date__c = date.newInstance(yearDate, 7, 1);
			yearRP.End_Date__c = date.newInstance(yearDate, 12, 31);
			insert yearRP;

			// // Create service
			List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
			for (Integer i = 0; i < recordCount; i++) {
				services[i].Status__c = SERVICE_STATUS;
				services[i].Care_Type__c = SERVICE_CARE_TYPE;
				services[i].RecordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName()
					.get(SERVICE_REC_TYPE)
					.getRecordTypeId();
			}

			insert services;
             
            // create allotment
            List<Allotment__c> allAlots = new List<Allotment__c>();
            for(Integer i = 0; i < recordCount; i++){
                Allotment__c allot = new Allotment__c();
            	allot.Service_Name__c = services[i].Id;
                allAlots.add(allot);
            }
            insert allAlots;
            
            // create Places Allotment
            List<Places_Allotment__c> placeAllot = new List<Places_Allotment__c>();
            for(Integer i = 0; i < recordCount; i++){
                Places_Allotment__c pallot = new Places_Allotment__c();
            	pallot.Number_of_Places__c = 4;
                pallot.Status_of_Places__c = 'Operational';
                pallot.Current__c = 'Yes';
            	pallot.Allotment__c = allAlots[i].Id;
                placeAllot.add(pallot);
            }
                       
            insert placeAllot;
            // This update will trigger flow Service: Update Service Status Start Date and set service status to operational
            update services;

			// create providers
			List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
			insert providers;

			// create sar
			List<Service_Account_Relationship__c> sar = TestDataFactory.createServiceAccountRecords(
				recordCount,
				services,
				providers
			);

			// update association start date in sar
			for (Service_Account_Relationship__c sarRec : sar) {
				sarRec.Association_Start_Date__c = System.today().addMonths(-3);
			}
			insert sar;

			// Insert Accreditation/Certification records
			List<Accreditation_Certification__c> accredCertRecords = TestDataFactory.createAccreditationCertification(
				recordCount,
				services
			);
			for (Integer i = 0; i < recordCount; i++) {
				accredCertRecords[i].Start_Date__c = System.today().addMonths(-6);
				accredCertRecords[i].End_Date__c = accredCertRecords[i].Start_Date__c.addMonths(36);
			}
			insert accredCertRecords;
		}
		Test.stopTest();
	}

	@isTest
	public static void testCreateExemptionsBatchGoLive() {
		Map<Id, BusinessLicense> servicesMap = new Map<Id, BusinessLicense>([SELECT Id FROM BusinessLicense]);
		User testUser = TestDataFactory.createSystemAdminUser();

		// Initialise required maps in star rating util class
		StarRatingUtil.cacheServiceAccRelationship(servicesMap.keySet());
		StarRatingUtil.cacheAccredCertification(servicesMap.keySet());

		// Update custom metadata
		StarRatingExemptionCustomMetadata.goLiveSetting = true;

		Test.startTest();
		System.runAs(testUser){
			Database.executeBatch(new CreateExemptionsBatch());
		}
		Test.stopTest();

		Map<Id, BusinessLicense> updatedServices = new Map<Id, BusinessLicense>(
			[SELECT Id, CER_Exempt__c, CM_Exempt__c, QI_Exempt__c, SCR_Exempt__c FROM BusinessLicense]
		);

		for (BusinessLicense service : updatedServices.values()) {
			System.assertEquals(true, service.CER_Exempt__c, 'CER service flag should be checked');
			System.assertEquals(true, service.CM_Exempt__c, 'CM service flag should be checked');
			System.assertEquals(true, service.QI_Exempt__c, 'QI service flag should be checked');
			System.assertEquals(true, service.SCR_Exempt__c, 'SCR service flag should be checked');
		}
	}

	@isTest
	public static void testCreateExemptionsBatch() {
		Map<Id, BusinessLicense> servicesMap = new Map<Id, BusinessLicense>([SELECT Id FROM BusinessLicense]);
		User testUser = TestDataFactory.createSystemAdminUser();

		// Update status date to today
		for (BusinessLicense service : servicesMap.values()) {
			service.Status_Date__c = Date.today();
		}

		update servicesMap.values();

		// Initialise required maps in star rating util class
		StarRatingUtil.cacheServiceAccRelationship(servicesMap.keySet());
		StarRatingUtil.cacheAccredCertification(servicesMap.keySet());

		// Update custom metadata
		StarRatingExemptionCustomMetadata.goLiveSetting = false;

		Test.startTest();
		System.runAs(testUser){
			Database.executeBatch(new CreateExemptionsBatch());
		}
		Test.stopTest();

		Map<Id, BusinessLicense> updatedServices = new Map<Id, BusinessLicense>(
			[SELECT Id, CER_Exempt__c, CM_Exempt__c, QI_Exempt__c, SCR_Exempt__c FROM BusinessLicense]
		);

		for (BusinessLicense service : updatedServices.values()) {
			System.assertEquals(true, service.CER_Exempt__c, 'CER service flag should be checked');
			System.assertEquals(true, service.CM_Exempt__c, 'CM service flag should be checked');
			System.assertEquals(true, service.QI_Exempt__c, 'QI service flag should be checked');
			System.assertEquals(true, service.SCR_Exempt__c, 'SCR service flag should be checked');
		}
	}
}