force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Approved_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Care Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community and Home Support</fullName>
            </value>
            <value>
                <fullName>Service System Development</fullName>
            </value>
            <value>
                <fullName>Care Relationship and Carer Support</fullName>
            </value>
            <value>
                <fullName>Assistance with Care and Housing</fullName>
            </value>
            <value>
                <fullName>Transition Care</fullName>
            </value>
            <value>
                <fullName>Innovative Pool</fullName>
            </value>
            <value>
                <fullName>Multi-Purpose Service</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Short-Term Restorative Care (STRC)</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>EACH Dementia</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Home Care Packages</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC High Care</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC High Care Dementia</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC Low Care</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retirement Villages Care Pilot</fullName>
            </value>
            <value>
                <fullName>Extended Aged Care at Home</fullName>
            </value>
            <value>
                <fullName>STRC</fullName>
                <isActive>false</isActive>
                <label>STRC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/Approved_Provider_Service.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Service</fullName>
    <active>true</active>
    <label>Approved Provider Service</label>
</RecordType>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Removed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Removed_Reason__c</fullName>
    <description>Reason for Removing the Regulatory Decision</description>
    <label>Removed Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test only</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Account_Relationship__c.Provider_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Service care type is not Home Care or Residential</errorMessage>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Home Care</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_Start_Date__c</fullName>
    <label>Association Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Service Compliance Histories</relationshipLabel>
    <relationshipName>Service_Compliance_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Publish</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
                <isActive>false</isActive>
                <label>Archive</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RegulatoryDecisionTriggerTest.cls
@IsTest
public with sharing class RegulatoryDecisionTriggerTest {
	@TestSetup
	static void makeData() {
		User u = TestDataFactory.createTestUser();
		u.Alias = 'TestUser';
		insert u;
	}

	@isTest
	static void testUpdate() {
		User adminUser = TestDataFactory.createSystemAdminUser();
		adminUser.isActive = true;

		update adminUser;

		System.runAs(adminUser) {
			List<Account> providerList = TestDataFactory.createProviderRecords(
				1
			);
			insert providerList;

			List<Care_Type__c> careTypeListRecords = TestDataFactory.createSCRcareType(
				1,
				providerList
			);
			insert careTypeListRecords;

			List<BusinessLicense> testService = TestDataFactory.createSCRServiceRecords(
				1,
				'TestService1',
				providerList,
				0,
				0,
				0
			);

			testService.get(0)
				.RecordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName()
				.get('Approved_Provider_Service')
				.getRecordTypeId();
			testService.get(0).Name = 'Test JC';
			testService.get(0).Care_Type__c = 'Home Care';
			testService.get(0).Status__c = 'Operational';
			testService.get(0).AccountId = providerList[0].Id;
			testService.get(0).Service_Care_Sub_Type__c = 'Home Care';
			insert testService;

			Test.getEventBus().deliver();

			List<ViolationType> violationTypeList = TestDataFactory.createQIViolationType(
				1
			);
			insert violationTypeList;

			List<Service_Account_Relationship__c> sarList = TestDataFactory.createServiceAccountRecords(
				1,
				testService,
				providerList
			);
			for (Service_Account_Relationship__c rec : sarList) {
				rec.Association_Start_Date__c = Date.today().addDays(-10);
			}
			insert sarList;

			List<Service_Compliance_History__c> servCompHistory = TestDataFactory.createServiceComplianceHistory(
				1
			);
			for (Service_Compliance_History__c rec : servCompHistory) {
				rec.Service_Account__c = sarList[0].Id;
				rec.Service__c = testService[0].Id;
				rec.Provider__c = providerList[0].Id;
			}
			insert servCompHistory;

			List<RegulatoryCodeViolation> regDecisionList = TestDataFactory.createQIRegulatoryCodeViolation(
				1,
				testService,
				providerList,
				violationTypeList,
				sarList
			);
			regDecisionList[0].published__c = false;
			regDecisionList[0].Status = 'Current';
			insert regDecisionList;

			Test.startTest();
			regDecisionList[0].published__c = true;
			update regDecisionList;
			regDecisionList[0].Status = 'Removed';
			regDecisionList[0].Removed_Reason__c = 'testtesttesttest';
			update regDecisionList;
			Test.stopTest();
			System.assertEquals(
				regDecisionList[0].published__c,
				true,
				'Error occured on update'
			);
		}
	}

	@isTest
	public static void testShareAfterRegulatoryCodeViolationInsert() {
		User adminUser = TestDataFactory.createSystemAdminUser();
		adminUser.isActive = true;

		update adminUser;

		System.runAs(adminUser) {
			List<Account> providerList = TestDataFactory.createProviderRecords(
				1
			);
			insert providerList;

			List<Care_Type__c> careTypeListRecords = TestDataFactory.createSCRcareType(
				1,
				providerList
			);
			insert careTypeListRecords;

			List<BusinessLicense> testService = TestDataFactory.createSCRServiceRecords(
				1,
				'TestService1',
				providerList,
				0,
				0,
				0
			);

			testService.get(0)
				.RecordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName()
				.get('Approved_Provider_Service')
				.getRecordTypeId();
			testService.get(0).Name = 'Test JC';
			testService.get(0).Care_Type__c = 'Home Care';
			testService.get(0).Status__c = 'Operational';
			testService.get(0).AccountId = providerList[0].Id;
			testService.get(0).Service_Care_Sub_Type__c = 'Home Care';
			insert testService;

			Test.getEventBus().deliver();
			// Create public groups
			BusinessLicenseTriggerService.createPublicGroupAndShare(
				new Map<Id, BusinessLicense>(testService)
			);
			List<ViolationType> violationTypeList = TestDataFactory.createQIViolationType(
				1
			);
			insert violationTypeList;

			List<Service_Account_Relationship__c> sarList = TestDataFactory.createServiceAccountRecords(
				1,
				testService,
				providerList
			);
			insert sarList;

			Test.startTest();
			List<RegulatoryCodeViolation> regDecisionList = TestDataFactory.createQIRegulatoryCodeViolation(
				1,
				testService,
				providerList,
				violationTypeList,
				sarList
			);
			regDecisionList[0].published__c = false;
			regDecisionList[0].Status = 'Current';
			regDecisionList[0].Service_Name_lookup__c = testService[0].Id;

			insert regDecisionList;
			regDecisionList[0].published__c = true;
			update regDecisionList;
			Test.stopTest();

			Integer count = Database.countQuery(
				'SELECT Count() FROM RegulatoryCodeViolationShare WHERE ParentId = \'' +
					regDecisionList[0].Id +
					'\' AND RowCause = \'Manual\''
			);
			System.assertEquals(1, count);
		}
	}

	@isTest
	public static void testOwnershipChangeRegulatoryCodeViolationUpdate() {
		User adminUser = TestDataFactory.createSystemAdminUser();
		adminUser.isActive = true;

		update adminUser;

		System.runAs(adminUser) {
			User u = [SELECT Id, Alias FROM User WHERE Alias = 'TestUser'];

			List<Account> providerList = TestDataFactory.createProviderRecords(
				1
			);
			insert providerList;

			List<Care_Type__c> careTypeListRecords = TestDataFactory.createSCRcareType(
				1,
				providerList
			);
			insert careTypeListRecords;

			List<BusinessLicense> testService = TestDataFactory.createSCRServiceRecords(
				1,
				'TestService1',
				providerList,
				0,
				0,
				0
			);

			testService.get(0)
				.RecordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName()
				.get('Approved_Provider_Service')
				.getRecordTypeId();
			testService.get(0).Name = 'Test JC';
			testService.get(0).Care_Type__c = 'Home Care';
			testService.get(0).Status__c = 'Operational';
			testService.get(0).AccountId = providerList[0].Id;
			testService.get(0).Service_Care_Sub_Type__c = 'Home Care';
			insert testService;

			Test.getEventBus().deliver();
			// Create public groups
			BusinessLicenseTriggerService.createPublicGroupAndShare(
				new Map<Id, BusinessLicense>(testService)
			);
			List<ViolationType> violationTypeList = TestDataFactory.createQIViolationType(
				1
			);
			insert violationTypeList;

			List<Service_Account_Relationship__c> sarList = TestDataFactory.createServiceAccountRecords(
				1,
				testService,
				providerList
			);
			insert sarList;

			List<RegulatoryCodeViolation> regDecisionList = TestDataFactory.createQIRegulatoryCodeViolation(
				1,
				testService,
				providerList,
				violationTypeList,
				sarList
			);
			regDecisionList[0].published__c = false;
			regDecisionList[0].Status = 'Current';
			regDecisionList[0].Service_Name_lookup__c = testService[0].Id;

			insert regDecisionList;

			Test.startTest();

			regDecisionList[0].OwnerId = u.Id;

			update regDecisionList;
			Test.stopTest();

			Integer count = Database.countQuery(
				'SELECT Count() FROM RegulatoryCodeViolationShare WHERE ParentId = \'' +
					regDecisionList[0].Id +
					'\' AND RowCause = \'Manual\''
			);
			System.assertEquals(1, count);
		}
	}
}