force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Decision_Details__c.field-meta.xml
<CustomField>
    <fullName>Decision_Details__c</fullName>
    <label>Decision Details</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Rating_Relevant__c.field-meta.xml
<CustomField>
    <fullName>Rating_Relevant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rating Relevant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Reason_for_issuing_Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_issuing_Regulatory_Decision__c</fullName>
    <label>Reason for issuing Regulatory Decision</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Removed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Removed_Reason__c</fullName>
    <description>Reason for Removing the Regulatory Decision</description>
    <label>Removed Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/SCR_Rating__c.field-meta.xml
<CustomField>
    <fullName>SCR_Rating__c</fullName>
    <description>calculated SCR rating for the record</description>
    <label>SCR Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Compliance_Rating_Effect</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test only</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Account_Relationship__c.Provider_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Compliance_Rating__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating__c</fullName>
    <description>Service Compliance Rating for an individual Reg Dec</description>
    <label>Service Compliance Rating</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Service care type is not Home Care or Residential</errorMessage>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Home Care</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Name__c</fullName>
    <description>Name of the Service Provider to be Published</description>
    <label>Alternative Service Provider Name</label>
    <length>130</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Provider_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Regulatory Code Violations</relationshipLabel>
    <relationshipName>Regulatory_Code_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_Start_Date__c</fullName>
    <label>Association Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_Detail__c/Service_Compliance_Detail__c.object-meta.xml
<CustomObject>
    <label>Service Compliance Detail</label>
    <nameField>
        <displayFormat>SCRD-{000000}</displayFormat>
        <label>SCR Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_Detail__c/fields/Service_Compliance_History__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_History__c</fullName>
    <label>Service Compliance History</label>
    <referenceTo>Service_Compliance_History__c</referenceTo>
    <relationshipLabel>Service Compliance Details</relationshipLabel>
    <relationshipName>Service_Compliance_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/SCR_Rating__c.field-meta.xml
<CustomField>
    <fullName>SCR_Rating__c</fullName>
    <label>SCR Rating</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service_Compliance_Rating__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating__c</fullName>
    <description>Service Compliance number rating, out of 5</description>
    <label>Service Compliance Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Service_Compliance_Rating_Effect.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Star</fullName>
    </customValue>
    <customValue>
        <fullName>2 Star</fullName>
    </customValue>
    <customValue>
        <fullName>3 Star</fullName>
    </customValue>
    <customValue>
        <fullName>4  Star</fullName>
    </customValue>
    <customValue>
        <fullName>5 Star</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>STAR Rating effect for SCR</description>
    <masterLabel>Service Compliance Rating Effect</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestRegulatoryDecisionEventTrigger.cls
@IsTest
public class TestRegulatoryDecisionEventTrigger {
	private static User currentUser = TestDataFactory.createSystemAdminUser();

	@TestSetup
	static void makeData() {
		System.runAs(currentUser) {
			Test.startTest();
			List<Account> providerList = TestDataFactory.createProviderRecords(
				1
			);
			insert providerList;

			List<BusinessLicense> testService = TestDataFactory.createServiceRecords(
				1
			);
			testService[0].Care_Type__c = 'Residential';
			testService[0].AccountId = providerList[0].Id;
			insert testService;

			List<ViolationType> violationTypeList = TestDataFactory.createQIViolationType(
				1
			);
			insert violationTypeList;

			List<Service_Account_Relationship__c> sarList = TestDataFactory.createServiceAccountRecords(
				1,
				testService,
				providerList
			);
			for (Service_Account_Relationship__c rec : sarList) {
				rec.Association_Start_Date__c = Date.today().addDays(-10);
			}
			insert sarList;
			Test.stopTest();
		}

	}

	/**
	 * This method creates a regulatory decision and publishes it.
	 * Expected result: 1 SCRH and 1 SCD records created
	 */
	@isTest
	static void testPublishEvent() {
		System.runAs(currentUser) {
			Test.startTest();

			List<Account> providers = [SELECT Id FROM Account];
			List<Service_Account_Relationship__c> sarList = [
				SELECT Id
				FROM Service_Account_Relationship__c
			];

			BusinessLicense service = [
				SELECT Id, Name
				FROM BusinessLicense
				WHERE Name = 'Service Test 0'
			];

			List<ViolationType> violationTypeList = [
				SELECT Id
				FROM ViolationType
			];

			List<RegulatoryCodeViolation> regDecisionList = new List<RegulatoryCodeViolation>{
				new RegulatoryCodeViolation(
					Service_name_lookup__c = service.Id,
					Service_Provider_Name__c = null,
					ViolationTypeId = violationTypeList.get(0).Id,
					Status = 'Current',
					Service_Provider_Name_lookup__c = providers[0].Id,
					Service_Account_Relationship__c = sarList[0].Id,
					DateCreated = Datetime.now(),
					Published__c = false,
					Rating_Relevant__c = true,
					SCR_Rating__c = '2 Star',
					Decision_Details__c = 'Decision Details',
					Reason_for_issuing_Regulatory_Decision__c = 'Test Reason'
				)
			};

			insert regDecisionList;

			List<RegulatoryCodeViolation> regForPublishing = [
				SELECT Id, Published__c
				FROM RegulatoryCodeViolation
				WHERE Published__c = FALSE
			];

			regForPublishing.get(0).Published__c = true;
			update regForPublishing;

			Test.getEventBus().deliver();
			Test.stopTest();

			List<Service_Compliance_History__c> schList = [
				SELECT Id, Name
				FROM Service_Compliance_History__c
			];

			List<Service_Compliance_Detail__c> scdList = [
				SELECT Id, Name, Service_Compliance_History__c
				FROM Service_Compliance_Detail__c
			];

			Assert.areEqual(1, schList.size(), '1 history should exist');
			Assert.areEqual(1, scdList.size(), '1 detail should exist');
		}
	}

	/**
	 * This method creates a regulatory decision which is published and non current. Status is then updated to removed.
	 * Expected result: 1 SCRH and 1 SCD records created
	 */
	@isTest
	static void testRemoveDecisionDecision() {
		System.runAs(currentUser) {
			Test.startTest();
			List<Account> providers = [SELECT Id FROM Account];
			List<Service_Account_Relationship__c> sarList = [
				SELECT Id
				FROM Service_Account_Relationship__c
			];

			List<BusinessLicense> service = [
				SELECT Id, Name
				FROM BusinessLicense
				WHERE Name = 'Service Test 0'
			];

			List<ViolationType> violationTypeList = [
				SELECT Id
				FROM ViolationType
			];

			List<RegulatoryCodeViolation> regDecisionList = new List<RegulatoryCodeViolation>{
				new RegulatoryCodeViolation(
					Service_name_lookup__c = service.get(0).Id,
					Service_Provider_Name__c = null,
					ViolationTypeId = violationTypeList.get(0).Id,
					Status = 'Non-Current',
					Service_Provider_Name_lookup__c = providers[0].Id,
					Service_Account_Relationship__c = sarList[0].Id,
					DateCreated = Datetime.now(),
					Published__c = true,
					Rating_Relevant__c = true,
					SCR_Rating__c = '2 Star',
					Decision_Details__c = 'Decision Details',
					Reason_for_issuing_Regulatory_Decision__c = 'Test Reason'
				)
			};

			insert regDecisionList;

			List<RegulatoryCodeViolation> regToUpdate = [
				SELECT Id, Status, Removed_Reason__c
				FROM RegulatoryCodeViolation
			];
			regToUpdate.get(0).Status = 'Removed';
			regToUpdate.get(0).Removed_Reason__c = 'Test';
			update regToUpdate;

			Test.getEventBus().deliver();
			Test.stopTest();

			List<Service_Compliance_History__c> schList = [
				SELECT Id, Name, Service_Compliance_Rating__c
				FROM Service_Compliance_History__c
			];

			List<Service_Compliance_Detail__c> scdList = [
				SELECT Id
				FROM Service_Compliance_Detail__c
			];

			Assert.areEqual(1, schList.size(), 'Expected 1');
			Assert.areEqual(1, scdList.size(), 'Expected 1');
		}
	}
}