force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporated_Under__c.field-meta.xml
<CustomField>
    <fullName>Incorporated_Under__c</fullName>
    <description>INCORP_SPECIFIC_CODE, INCORP_SPECIFIC_CODE. ACO Incorporated Under list</description>
    <label>Incorporated Under</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Aboriginal Communities Act 1979 (WA)</fullName>
            </value>
            <value>
                <fullName>Aboriginal Land Act 1991 (QLD)</fullName>
            </value>
            <value>
                <fullName>Aboriginal Land Rights (Northern Territory) Act 1976</fullName>
            </value>
            <value>
                <fullName>Aboriginal Land Rights Act 1983 (NSW)</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia (Bodies Corporate) Act 1938 (NSW)</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia Act 1895 (Queensland)</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia Trust Property Act 1917</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia Trust Property Act 1917 (NSW)</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia Trust Property Act 1928 (ACT)</fullName>
            </value>
            <value>
                <fullName>Anglican Trusts Corporations Act 1884 (VIC)</fullName>
            </value>
            <value>
                <fullName>Anglican Welfare Agency Act 1997 (VIC)</fullName>
            </value>
            <value>
                <fullName>Associations Act 2008 (NT)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1964 (TAS)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1981 (QLD)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1981 (VIC)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1984 (NSW)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1985 (SA)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1987 (WA)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1991 (ACT)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 2009 (NSW)</fullName>
            </value>
            <value>
                <fullName>Benevolent Society (Reconstitution) Act 1998 (NSW)</fullName>
            </value>
            <value>
                <fullName>Brotherhood of St. Laurence (Incorporation) Act 1971</fullName>
            </value>
            <value>
                <fullName>Canberra Institute of Technology Act 1987 ACT</fullName>
            </value>
            <value>
                <fullName>Charitable Collections Act (1934)</fullName>
            </value>
            <value>
                <fullName>Churches of Christ, Scientist, Incorporation Act 1964 (QLD)</fullName>
            </value>
            <value>
                <fullName>Community Services (Aborigines) Act 1984 (QLD)</fullName>
            </value>
            <value>
                <fullName>Companies Act 1899</fullName>
            </value>
            <value>
                <fullName>Companies Act 1961</fullName>
            </value>
            <value>
                <fullName>Co-operatives Act 1992 (NSW)</fullName>
            </value>
            <value>
                <fullName>Co-operatives Act 1997 (QLD)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_ID__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID__c</fullName>
    <description>CORPORATE_IDENTIFIER ACO Incorporation ID</description>
    <label>Incorporation ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_Status__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_Status__c</fullName>
    <description>ACO Incorporation Status</description>
    <label>Incorporation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Strike Off Status</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>External Administration</fullName>
            </value>
            <value>
                <fullName>Non-Active</fullName>
            </value>
            <value>
                <fullName>Not available</fullName>
            </value>
            <value>
                <fullName>Not registered</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Strike-off action in progress</fullName>
            </value>
            <value>
                <fullName>To be advised</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prospective_Provider__c.field-meta.xml
<CustomField>
    <fullName>Prospective_Provider__c</fullName>
    <description>Likely to become a provider in the future</description>
    <label>Prospective Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Types</relationshipLabel>
    <relationshipName>Care_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Code</description>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Line_Item__c/Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI-{00000}</displayFormat>
        <label>Service Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Line_Item__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField> 

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FinancialReportingRulesControllerTest.cls
/*****************************************
 *@Author        :Jhosua Arda
 *@Company       :Accenture
 *@Description   : this class will test the functionality of FinancialReportingRulesController
 *@Test Class    :
 *@Date:N/A
 *@Revision:
 *When                 Who               What
 *11-Jan-2023          Developer Name    Created
 *15-Feb-2023		  Cla Capagas		Modified
 *****************************************/
@isTest
private class FinancialReportingRulesControllerTest {
	@TestSetup
	static void setup() {
		User testUser = TestDataFactory.createSystemAdminUser();
		System.runAs(testUser) {
			Profile adminProfile = [
				SELECT Id
				FROM Profile
				WHERE Name = 'System Administrator'
				LIMIT 1
			];

			User record = new User(
				Alias = 'testUser',
				Email = 'testUser@admin.com',
				FirstName = 'Test',
				LastName = 'User',
				TimeZoneSidKey = 'America/Los_Angeles',
				LanguageLocaleKey = 'en_US',
				EmailEncodingKey = 'UTF-8',
				LocaleSidKey = 'en_US',
				ProfileId = adminProfile.Id,
				UserName = 'testUser01@admin.com'
			);
			insert record;

			List<PermissionSet> permissionSets = [
				SELECT Id
				FROM PermissionSet
				WHERE
					Name IN (
						'QFR_Create_Update_View',
						'System_Admin',
						'QFR_Create_Update_View_Submit',
						'QFR_Dev_Permission_Set'
					)
			];

			List<PermissionSetAssignment> permissionSetAssignments = new List<PermissionSetAssignment>();
			for (PermissionSet permissionSet : permissionSets) {
				PermissionSetAssignment psa = new PermissionSetAssignment(
					PermissionSetId = permissionSet.Id,
					AssigneeId = record.Id
				);
				permissionSetAssignments.add(psa);
			}
			insert permissionSetAssignments;

			//Account
			Account acc = new Account(
				Name = 'Test Account Company',
				Purpose__c = 'Government',
				Incorporated_Under__c = 'Associations Act 2008 (NT)',
				Incorporation_Status__c = 'Registered',
				Incorporation_ID_Type__c = 'Other',
				Prospective_Provider__c = 'No',
				Incorporation_ID__c = '1222211111',
				RecordTypeId = [
					SELECT Id
					FROM RecordType
					WHERE
						SobjectType = 'Account'
						AND IsActive = TRUE
						AND Name = 'Approved Provider'
					LIMIT 1
				]
				.Id
			);
			insert acc;

			//Case
			Case caseData = new Case(
				AccountId = acc.id,
				Status = 'Not Required'
			);
			insert caseData;

			//Form
			Form__c formData = new Form__c(
				Account__c = acc.id,
				Case__c = caseData.Id,
				Type__c = 'Residential Food and Nutrition Reporting',
				RecordTypeId = Schema.SObjectType.Form__c.getRecordTypeInfosByDeveloperName()
					.get('QFR')
					.getRecordTypeId()
			);
			insert formData;

			// Business License
			BusinessLicense businessLicense = new BusinessLicense();
			businessLicense.Care_Type__c = 'Residential';
			businessLicense.Name = 'Home care Melbourne City - North West Region';
			businessLicense.Effective_Date__c = Date.today();
			businessLicense.Status = 'Operational';
			insert businessLicense;

			// Service Line item 1
			Service_Line_Item__c serviceLineItem1 = new Service_Line_Item__c(
				Form__c = formData.Id,
				active__c = true,
				Service_Category__c = 'Home Care',
				Service__c = businessLicense.Id
			);
			insert serviceLineItem1;

			// Service Line item 2
			Service_Line_Item__c serviceLineItem2 = new Service_Line_Item__c(
				Form__c = formData.Id,
				active__c = true,
				Service_Category__c = 'Residential',
				Service__c = businessLicense.Id
			);
			insert serviceLineItem2;

			// Service Line item 2
			Service_Line_Item__c serviceLineItemTotal = new Service_Line_Item__c(
				Form__c = formData.Id,
				active__c = true,
				Service_Category__c = 'Total'
			);
			insert serviceLineItemTotal;

			//GL Code Residential
			GL_Code__c gLCodeResi = new GL_Code__c(
				External_Name__c = 'Dietetic Care',
				Name = 'Dietetic Care',
				run_rules__c = true,
				Business_ID__c = 'Q00001',
				Type__c = 'Residential Food and Nutrition Reporting',
				Line_Item_Value_Type__c = 'Hrs'
			);
			insert gLCodeResi;

			//GL Code Residential Labour Cost and Hours
			GL_Code_Line_Item__c gLCodeLineItemResi = new GL_Code_Line_Item__c(
				Line_Item_Value__c = '15',
				GL_Code__c = gLCodeResi.Id,
				Service_Line_Item__c = ServiceLineItem1.Id
			);
			insert gLCodeLineItemResi;

			//GL Code Labour
			GL_Code__c gLCodeLabour = new GL_Code__c(
				External_Name__c = 'Dietetic Care - Labour',
				Name = 'Dietetic Care - Labour',
				run_rules__c = true,
				Business_ID__c = 'Q00002',
				Type__c = 'Home Care Labour Costs and Hours',
				Line_Item_Value_Type__c = 'Hrs'
			);
			insert gLCodeLabour;

			//GL Code Residential Food and Nutrition Reporting
			GL_Code_Line_Item__c gLCodeLineItemLabour = new GL_Code_Line_Item__c(
				Line_Item_Value__c = '25',
				GL_Code__c = gLCodeLabour.Id,
				Service_Line_Item__c = ServiceLineItem2.Id
			);
			insert gLCodeLineItemLabour;

			//GL Code Residential Food and Nutrition Reporting Total
			GL_Code_Line_Item__c gLCodeLineItemLabourTotal = new GL_Code_Line_Item__c(
				Line_Item_Value__c = '0',
				GL_Code__c = GLCodeLabour.Id,
				Service_Line_Item__c = ServiceLineItemTotal.Id
			);
			insert gLCodeLineItemLabourTotal;

			//Get RecordType
			Id financialRepRuleDuplicateTypeId = Schema.SObjectType.Financial_Reporting_Rule_Details__c.getRecordTypeInfosByDeveloperName()
				.get('Duplicate_Value_Reference')
				.getRecordTypeId();

			// Financial reporting for Residential
			Financial_Reporting_Rule_Details__c financialReportingResi = new Financial_Reporting_Rule_Details__c(
				Active__c = true,
				GL_Code__c = GLCodeResi.Id,
				GL_Code_Target__c = GLCodeLabour.Id,
				RecordTypeId = financialRepRuleDuplicateTypeId
			);
			insert financialReportingResi;

			// Financial reporting for Labour
			Financial_Reporting_Rule_Details__c financialReportingLabour = new Financial_Reporting_Rule_Details__c(
				Active__c = true,
				GL_Code__c = GLCodeLabour.Id,
				GL_Code_Target__c = GLCodeResi.Id,
				RecordTypeId = financialRepRuleDuplicateTypeId
			);
			insert financialReportingLabour;
		}

	}

	@isTest
	static void updateGLCodeLineItemVal() {
		String itemValue = '100';
		User adminUser = [
			SELECT Id
			FROM User
			WHERE UserName = 'testUser01@admin.com'
			LIMIT 1
		];
		GL_Code_Line_Item__c glliCode = [
			SELECT Id, Line_Item_Value__c
			FROM GL_Code_Line_Item__c
			WHERE GL_Code__r.Business_ID__c = 'Q00001'
			LIMIT 1
		];

		Test.startTest();
		System.runAs(adminUser) {
			glliCode.Line_Item_Value__c = itemValue;
			update glliCode;
		}
		Test.stopTest();
		//check if glcodetarget values are getting updated
		GL_Code_Line_Item__c glliCodeTarget = [
			SELECT Id, Line_Item_Value__c
			FROM GL_Code_Line_Item__c
			WHERE GL_Code__r.Business_ID__c = 'Q00002'
			LIMIT 1
		];
		system.assertEquals(itemValue, glliCodeTarget.Line_Item_Value__c);
	}

	@isTest
	static void updateGLCodeLineItemValWithDecimal() {
		String itemValue = '45.01';
		User adminUser = [
			SELECT Id
			FROM User
			WHERE UserName = 'testUser01@admin.com'
			LIMIT 1
		];
		GL_Code_Line_Item__c glliCode = [
			SELECT Id, Line_Item_Value__c
			FROM GL_Code_Line_Item__c
			WHERE GL_Code__r.Business_ID__c = 'Q00001'
			LIMIT 1
		];

		Test.startTest();
		System.runAs(adminUser) {
			glliCode.Line_Item_Value__c = itemValue;
			update glliCode;
		}
		Test.stopTest();
		//check if glcodetarget values are getting updated
		GL_Code_Line_Item__c glliCodeTarget = [
			SELECT Id, Line_Item_Value__c
			FROM GL_Code_Line_Item__c
			WHERE GL_Code__r.Business_ID__c = 'Q00002'
			LIMIT 1
		];
		system.assertEquals(itemValue, glliCodeTarget.Line_Item_Value__c);
	}

	@isTest
	static void updateGLCodeLineItemValString() {
		String itemValue = 'Cook Chill';
		User adminUser = [
			SELECT Id
			FROM User
			WHERE UserName = 'testUser01@admin.com'
			LIMIT 1
		];
		GL_Code_Line_Item__c glliCode = [
			SELECT Id, Line_Item_Value__c
			FROM GL_Code_Line_Item__c
			WHERE GL_Code__r.Business_ID__c = 'Q00001'
			LIMIT 1
		];

		Test.startTest();
		System.runAs(adminUser) {
			glliCode.Line_Item_Value__c = itemValue;
			update glliCode;
		}
		Test.stopTest();
		//check if glcodetarget values are not updated since duplicate rules applicable for numeric only
		GL_Code_Line_Item__c glliCodeTarget = [
			SELECT Id, Line_Item_Value__c
			FROM GL_Code_Line_Item__c
			WHERE GL_Code__r.Business_ID__c = 'Q00002'
			LIMIT 1
		];
		system.assertEquals('25', glliCodeTarget.Line_Item_Value__c);
	}

	@isTest
	static void updateGLCodeLineItemValNull() {
		String itemValue = null;
		User adminUser = [
			SELECT Id
			FROM User
			WHERE UserName = 'testUser01@admin.com'
			LIMIT 1
		];
		GL_Code_Line_Item__c glliCode = [
			SELECT Id, Line_Item_Value__c
			FROM GL_Code_Line_Item__c
			WHERE GL_Code__r.Business_ID__c = 'Q00001'
			LIMIT 1
		];

		Test.startTest();
		System.runAs(adminUser) {
			glliCode.Line_Item_Value__c = itemValue;
			update glliCode;
		}
		Test.stopTest();
		//check if glcodetarget values are getting updated
		GL_Code_Line_Item__c glliCodeTarget = [
			SELECT Id, Line_Item_Value__c
			FROM GL_Code_Line_Item__c
			WHERE GL_Code__r.Business_ID__c = 'Q00002'
			LIMIT 1
		];
		system.assertEquals(null, glliCodeTarget.Line_Item_Value__c);
	}
}