force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Party_ID__c.field-meta.xml
<CustomField>
    <fullName>Party_ID__c</fullName>
    <description>Primary key to link the Provider Record to GovGPS Record</description>
    <label>Party ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aged_Care_Planning_Region__c/Aged_Care_Planning_Region__c.object-meta.xml
<CustomObject>
    <label>Aged Care Planning Region</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aged Care Planning Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Aged_Care_Planning_Region__c/fields/ACPR_State__c.field-meta.xml
<CustomField>
    <fullName>ACPR_State__c</fullName>
    <label>ACPR State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aged_Care_Planning_Region__c/fields/Geospatial_Information_Layer_Version__c.field-meta.xml
<CustomField>
    <fullName>Geospatial_Information_Layer_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Geospatial Information Layer Version</label>
    <referenceTo>GPMS_Geospatial_Information_LayerVersion__c</referenceTo>
    <relationshipLabel>Aged Care Planning Regions</relationshipLabel>
    <relationshipName>Aged_Care_Planning_Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <label>Party Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Care Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community and Home Support</fullName>
            </value>
            <value>
                <fullName>Service System Development</fullName>
            </value>
            <value>
                <fullName>Care Relationship and Carer Support</fullName>
            </value>
            <value>
                <fullName>Assistance with Care and Housing</fullName>
            </value>
            <value>
                <fullName>Transition Care</fullName>
            </value>
            <value>
                <fullName>Innovative Pool</fullName>
            </value>
            <value>
                <fullName>Multi-Purpose Service</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Short-Term Restorative Care (STRC)</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>EACH Dementia</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Home Care Packages</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC High Care</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC High Care Dementia</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC Low Care</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retirement Villages Care Pilot</fullName>
            </value>
            <value>
                <fullName>Extended Aged Care at Home</fullName>
            </value>
            <value>
                <fullName>STRC</fullName>
                <isActive>false</isActive>
                <label>STRC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Service_Name_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_Effective_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Service Name Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/CHSP_Service.recordType-meta.xml
<RecordType>
    <fullName>CHSP_Service</fullName>
    <active>true</active>
    <label>CHSP Service</label>
</RecordType>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/CHSP_Procurement_Based_AWP_Record__c.object-meta.xml
<CustomObject>
    <label>CHSP Procurement Based AWP Record</label>
    <nameField>
        <displayFormat>CPAWP-{000000000}</displayFormat>
        <label>CHSP Procurement Based AWP Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Procurement Based AWP Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Aged_Care_Planning_Region__c.field-meta.xml
<CustomField>
    <fullName>Aged_Care_Planning_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aged Care Planning Region</label>
    <referenceTo>Aged_Care_Planning_Region__c</referenceTo>
    <relationshipLabel>CHSP Procurement Based AWP Records</relationshipLabel>
    <relationshipName>CHSP_Procurement_Based_AWP_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Party_ID__c.field-meta.xml
<CustomField>
    <fullName>Party_ID__c</fullName>
    <label>Party ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>CHSP Procurement Based AWP Records</relationshipLabel>
    <relationshipName>CHSP_Procurement_Based_AWP_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Service Care Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPMS_Geospatial_Information_LayerVersion__c/GPMS_Geospatial_Information_LayerVersion__c.object-meta.xml
<CustomObject>
    <label>Geospatial Information Layer Version</label>
    <nameField>
        <displayFormat>GILV-{00000}</displayFormat>
        <label>Geospatial Run ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geospatial Information Layer Version</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_Start_Date__c</fullName>
    <label>Association Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/recordTypes/Provider_to_Service.recordType-meta.xml
<RecordType>
    <fullName>Provider_to_Service</fullName>
    <active>true</active>
    <label>Provider to Service</label>
</RecordType>

force-app/main/default/classes/GPMSCHSPCPAWPLinkServiceHelper.cls
public with sharing class GPMSCHSPCPAWPLinkServiceHelper {
    
    private List<CHSP_Procurement_Based_AWP_Record__c> scope;
    private static final String ServiceRT = Schema.SObjectType.BusinessLicense
        .getRecordTypeInfosByDeveloperName()
        .get('CHSP_Service').getRecordTypeId();
    private static final String ServiceProviderRT = Schema.SObjectType.Service_Account_Relationship__c
        .getRecordTypeInfosByDeveloperName()
        .get('Provider_to_Service').getRecordTypeId();
    
    private List<String> partyIds = new List<String>();
    private Set<String> setServiceCareSubTypes_all = new set<String>();
    private Map<String,BusinessLicense> serviceMap = new Map<String,BusinessLicense>();
    private Map<String,Account> accountMap = new Map<String,Account>();
    private Set<String> awpStatusIsApproved = new Set<String>();
    private Map<String,BusinessLicense> serviceToInsertMap = new Map<String,BusinessLicense>();
    private Map<String,BusinessLicense> serviceToUpdateMap = new Map<String,BusinessLicense>();
    private Map<String, Id> agedCarePlanningRegionRecords = new Map<String, Id>();
    
    public GPMSCHSPCPAWPLinkServiceHelper(List<CHSP_Procurement_Based_AWP_Record__c> scope) {
        this.scope = scope;
    }
    
    public void executeGPMSCHSPCPAWPLinkService() {
        getPartyIdsAndServiceCareSubTypes();
        
        //No Service SubCareType
        if(setServiceCareSubTypes_all.isEmpty() || partyIds.isEmpty()){
            return;
        }
        
        getExistingServiceMap();
        getRelatedProviderAccounts();
        getApprovedProcurementBasedAWPRecords();
        
        // get ACPR data
        getAgedCarePlanningRegionRecords();
        
        processCHSPWorkPlans();
    }
    
    private void getPartyIdsAndServiceCareSubTypes() {
        for(CHSP_Procurement_Based_AWP_Record__c chspserviceschedule : scope){
            partyIds.add(chspserviceschedule.Party_Id__c);
            setServiceCareSubTypes_all.add(chspserviceschedule.Service_Care_Sub_Type__c);
        }
    }
    
    private void getExistingServiceMap() {
        for(BusinessLicense service : [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c, Status__c
                                          FROM BusinessLicense WHERE Party_Id__c in :partyIds 
                                          AND Service_Care_Sub_Type__c in :setServiceCareSubTypes_all]){
            serviceMap.put(service.Party_Id__c + service.Service_Care_Sub_Type__c,service);
        }
    }
    
    private void getRelatedProviderAccounts() {
        for(Account acc : [SELECT Id,Party_Id__c, Name 
                           FROM Account 
                           WHERE Party_Id__c in :partyIds]){
            accountMap.put(acc.Party_Id__c, acc);
        }
    }
    
    private void getApprovedProcurementBasedAWPRecords() {
        for(CHSP_Procurement_Based_AWP_Record__c chspserviceschedule : scope) {
            String serviceKey = chspserviceschedule.Party_Id__c+chspserviceschedule.Service_Care_Sub_Type__c;
            if(chspserviceschedule.Activity_Status__c == 'Approved') {
                awpStatusIsApproved.add(serviceKey);
            }
        }
    }
    
    private void processCHSPWorkPlans() {
        try {
            processCHSPServiceSchedule();
            
            if(!serviceToUpdateMap.values().isEmpty()) {
                update serviceToUpdateMap.values();
            }
            
            if(!serviceToInsertMap.values().isEmpty()){
                insert serviceToInsertMap.Values();
                
                List<Service_Account_Relationship__c> serviceaccountToInsert = getServiceAccountRelationships();
                if(!serviceaccountToInsert.isEmpty()){
                    insert serviceaccountToInsert;
                }
            }
            
            for(CHSP_Procurement_Based_AWP_Record__c chspserviceschedule : scope){
                chspserviceschedule.Service__c = serviceMap.get(chspserviceschedule.Party_Id__c+chspserviceschedule.Service_Care_Sub_Type__c).Id;
                chspserviceschedule.Aged_Care_Planning_Region__c = getAgedCarePlanningRegionRecordId(chspserviceschedule);
            }
            
            update scope;
        } catch (Exception ex) {
            dohagedcare.Logger.error(ex.getMessage(),ex,'GPMS').Log();
        }
    }
    
    private void processCHSPServiceSchedule() {
        for(CHSP_Procurement_Based_AWP_Record__c chspserviceschedule : scope){
            String serviceKey = chspserviceschedule.Party_Id__c+chspserviceschedule.Service_Care_Sub_Type__c;
            if(serviceMap.get(serviceKey) == null){
                BusinessLicense service = new BusinessLicense();
                service.RecordTypeId = ServiceRT;
                service.Care_Type__c = 'Commonwealth Home Support Programme';
                service.Service_Name_Effective_Date__c = Date.today();
                service.Status_Date__c = Date.today();
                service.Party_Id__c = chspserviceschedule.Party_Id__c;
                service.Service_Care_Sub_Type__c = chspserviceschedule.Service_Care_Sub_Type__c;
                service.Status__c = awpStatusIsApproved.contains(serviceKey) ? 'Operational':'Inactive';
                service.Name = getServiceName(chspserviceschedule);
                serviceToInsertMap.put(service.Party_Id__c + service.Service_Care_Sub_Type__c,service);
            } else {
                BusinessLicense serviceRecord = serviceMap.get(serviceKey);
                if(awpStatusIsApproved.contains(serviceKey) && serviceRecord.Status__c != 'Operational') {
                    serviceRecord.Status__c = 'Operational';
                    serviceToUpdateMap.put(serviceKey, serviceRecord);
                } else if(!awpStatusIsApproved.contains(serviceKey) && serviceRecord.Status__c == 'Operational') {
                    serviceRecord.Status__c = 'Inactive';
                    serviceToUpdateMap.put(serviceKey, serviceRecord);
                } else {
                    continue;
                }
            }
        }
    }
    
    private List<Service_Account_Relationship__c> getServiceAccountRelationships() {
        List<Service_Account_Relationship__c> serviceaccountToInsert = new List<Service_Account_Relationship__c>();
        for(BusinessLicense service : serviceToInsertMap.Values()){
            serviceMap.put(service.Party_Id__c + service.Service_Care_Sub_Type__c,service);
            if(accountMap.get(service.Party_Id__c) != null){
                Service_Account_Relationship__c accountservice = new Service_Account_Relationship__c();
                accountservice.Provider_Name__c = accountMap.get(service.Party_Id__c).Id;
                accountservice.RecordTypeId = ServiceProviderRT;
                accountservice.Service_Name__c = service.Id;
                accountservice.Association_Start_Date__c = Date.today();
                serviceaccountToInsert.add(accountservice);
            }
        }
        
        return serviceaccountToInsert;
    }
    
   	private void getAgedCarePlanningRegionRecords() {
        for(Aged_Care_Planning_Region__c acpr: [SELECT Id, Name, ACPR_State__c, 
                                                Geospatial_Information_Layer_Version__r.Start_Date__c,
                                                Geospatial_Information_Layer_Version__r.End_Date__c 
                                                FROM Aged_Care_Planning_Region__c
                                               	WHERE Geospatial_Information_Layer_Version__r.Start_Date__c <= TODAY
												AND (Geospatial_Information_Layer_Version__r.End_Date__c >= TODAY
                                                OR Geospatial_Information_Layer_Version__r.End_Date__c = null)]) {
			String searchKey = acpr.Name + ';' + acpr.ACPR_State__c;
			agedCarePlanningRegionRecords.put(searchKey, acpr.Id);
        }
    }
    
    private String getServiceName(CHSP_Procurement_Based_AWP_Record__c record) {
        String serviceName = record.Service_Care_Sub_Type__c;
         if(accountMap != null && accountMap.size() >0)
         {
            Account acc_tmp = accountMap.get(record.Party_ID__c);
            if(null != acc_tmp){
                serviceName = acc_tmp.Name + ' - ' + record.Service_Care_Sub_Type__c;
                if(String.isNotBlank(serviceName)){
                    serviceName = serviceName.left(80);
                }
            } 
      }
        return serviceName;
    }
    
    private Id getAgedCarePlanningRegionRecordId(CHSP_Procurement_Based_AWP_Record__c workPlanRecord) {
        String region;
        String state;
        String acprKey;
        
        // Extract region and state
        Pattern serviceAreaPattern = Pattern.compile('(.*?)\\((.*?)\\)');
        Matcher serviceAreaMatcher = serviceAreaPattern.matcher(workPlanRecord.Service_Area__c);
        if(serviceAreaMatcher.find()) { 
            region = serviceAreaMatcher.group(1).trim();
            state = serviceAreaMatcher.group(2);
        } else {
            region = workPlanRecord.Service_Area__c;
        }

        // Locate ACPR Id
        if(region == 'ACT') {
            acprKey = region + ';' + 'ACT';
        } else if(state == null) {
            for(String searchKey : agedCarePlanningRegionRecords.keySet()) {
                if(searchKey.contains(region)) {
                    acprKey = searchKey;
                    break;
                }
            }    
        } else {
            acprKey = region + ';' + state;
        }

        return agedCarePlanningRegionRecords.get(acprKey);

    }
}