force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <label>Additional Information</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Types</relationshipLabel>
    <relationshipName>Care_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <description>Care Type field pulled in from Account Object</description>
    <formula>TEXT(Account.Care_Type__c)</formula>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact, Record Id of the related Contact record.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>Administrator/Liquidator effective date</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>(Generic NAPS Position Name) The role of this contact</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Assessment Service Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Assessor</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Financial Management</fullName>
            </value>
            <value>
                <fullName>Funding Agreement Variations</fullName>
            </value>
            <value>
                <fullName>Funding Submissions</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Aged Care Program Contact</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Key Personnel</fullName>
            </value>
            <value>
                <fullName>General Staff</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>Applicant Representative</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Leader</fullName>
            </value>
            <value>
                <fullName>Activity Contact</fullName>
            </value>
            <value>
                <fullName>Acquittal/Financial Reporting</fullName>
            </value>
            <value>
                <fullName>Assessment Service Administrator</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate Support</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate</fullName>
            </value>
            <value>
                <fullName>Choice Attributes</fullName>
            </value>
            <value>
                <fullName>Care Services Management</fullName>
            </value>
            <value>
                <fullName>Remittance/RCTI</fullName>
            </value>
            <value>
                <fullName>High level contact</fullName>
                <label>High Level Contact</label>
            </value>
            <value>
                <fullName>Service Monitoring &amp; Reports</fullName>
            </value>
            <value>
                <fullName>Centre Management</fullName>
            </value>
            <value>
                <fullName>Aged Care Service Manager</fullName>
            </value>
            <value>
                <fullName>QFR Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/QA_Comments__c.field-meta.xml
<CustomField>
    <fullName>QA_Comments__c</fullName>
    <inlineHelpText>Please note the provider will see your comment if the QFR is reissued.</inlineHelpText>
    <label>External QA Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Code</description>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <description>QFR Viability Responses</description>
    <label>Response</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to be deprecated</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <description>The Form that the response was given in. </description>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/QA_Comments__c.field-meta.xml
<CustomField>
    <fullName>QA_Comments__c</fullName>
    <label>QA External Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Response_Options__c.field-meta.xml
<CustomField>
    <fullName>Response_Options__c</fullName>
    <label>Response Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>x</fullName>
                <isActive>false</isActive>
                <label>x</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Line_Item__c/Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI-{00000}</displayFormat>
        <label>Service Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Line_Item__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField> 

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QFRLWCDownloadControllerTest.cls
@isTest
public class QFRLWCDownloadControllerTest {
	@TestSetup
	static void setup() {
		User testUser = TestDataFactory.createSystemAdminUser();
		System.runAs(testUser) {
			List<BusinessLicense> services = new List<BusinessLicense>();
			for (Integer i = 0; i < 5; i++) {
				services.add(
					new BusinessLicense(
						Name = 'Test Service ' + i,
						Effective_Date__c = Date.today(),
						Status_Date__c = Date.today(),
						Care_Type__c = 'Residential',
						Status = 'Approved'
					)
				);
			}

			services.add(
				new BusinessLicense(
					Name = 'Total',
					Effective_Date__c = Date.today(),
					Status_Date__c = Date.today(),
					Care_Type__c = 'Residential',
					Status = 'Approved'
				)
			);
			insert services;

			Account acc = TestDataFactory.createProviderRecords(1)[0]; // create one, get first entry
			insert acc;

			Contact con1 = new Contact(
				FirstName = '2',
				LastName = 'Test',
				Salutation = 'Ms',
				Email = 'test@gmail.com'
			);
			insert con1;

			Contact_Relationship__c cr1 = new Contact_Relationship__c(
				Account__c = acc.Id,
				Contact__c = con1.Id,
				Role__c = 'QFR Primary Contact'
			);
			insert cr1;

			Case tc = new Case(
				AccountId = acc.Id,
				Status = 'Submitted',
				RecordTypeId = [
					SELECT Id
					FROM RecordType
					WHERE SObjectType = 'Case' AND DeveloperName = 'QFR'
					LIMIT 1
				]
				.Id
			);
			insert tc;

			Form__c viability = new Form__c(
				Type__c = 'Residential Viability and Prudential Reporting',
				Account__c = acc.Id,
				Case__c = tc.Id,
				QA_Comments__c = 'None',
				RecordTypeId = Schema.SObjectType.Form__c.getRecordTypeInfosByDeveloperName()
					.get('QFR')
					.getRecordTypeId()
			);
			insert viability;

			Response__c response = new Response__c(
				Response_Options__c = 'Yes',
				Additional_Information__c = 'Test class response',
				Form__c = viability.Id
			);
			insert response;

			Form__c form = new Form__c(
				Type__c = 'Home Care Labour Costs and Hours',
				Account__c = acc.Id,
				Case__c = tc.Id,
				QA_Comments__c = 'None',
				RecordTypeId = Schema.SObjectType.Form__c.getRecordTypeInfosByDeveloperName()
					.get('QFR')
					.getRecordTypeId()
			);
			insert form;

			List<GL_Code__c> testGLCodes = new List<GL_Code__c>();
			testGLCodes.add(
				new GL_Code__c(
					Name = 'Test GL',
					Type__c = 'Home Care Labour Costs and Hours',
					Display_Order__c = 0,
					Line_Item_Value_Type__c = 'Numeric'
				)
			);
			testGLCodes.add(
				new GL_Code__c(
					Name = 'Test GL 2',
					Type__c = 'Residential Labour Costs and Hours',
					Display_Order__c = 0,
					Line_Item_Value_Type__c = 'Numeric'
				)
			);
			insert testGLCodes;
			insert new List<Service_Line_Item__c>{
				new Service_Line_Item__c(
					Service__c = services[0].Id,
					Form__c = form.Id
				),
				new Service_Line_Item__c(
					Service__c = services[services.size() - 1].Id, // add Total Service Line Item
					Form__c = form.Id
				)
			};
		}
	}

	@isTest
	static void it_get_forms_for_case() {
		Id caseId = [SELECT Id FROM Case WHERE Status = 'Submitted' LIMIT 1].Id;

		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();
		List<Form__c> forms = [SELECT Id FROM Form__c];
		for (Form__c form : forms) {
			form.OwnerId = healthUser.Id;
		}
		update forms;

		List<QFRLWCDownloadController.FormDownloadDetail> result = new List<QFRLWCDownloadController.FormDownloadDetail>();

		Test.startTest();
		System.runAs(healthUser) {
			result = QFRLWCDownloadController.getFormIdsForCase(caseId);
		}
		Test.stopTest();

		System.assertEquals(2, result.size());
	}

	@isTest
	static void it_get_response_for_viability() {
		Id formId = [
			SELECT Id
			FROM Form__c
			WHERE Type__c = 'Residential Viability and Prudential Reporting'
		]
		.Id;

		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();
		List<Form__c> forms = [SELECT Id FROM Form__c];
		for (Form__c form : forms) {
			form.OwnerId = healthUser.Id;
		}
		update forms;

		List<QFRLWCDownloadController.ViabilityResponse> result = new List<QFRLWCDownloadController.ViabilityResponse>();

		Test.startTest();
		System.runAs(healthUser) {
			result = QFRLWCDownloadController.getViabilityResponses(formId);
		}
		Test.stopTest();

		System.assertEquals(
			'Test class response',
			result[0].additionalInformation
		);
		System.assertEquals('Yes', result[0].response);
	}

	@isTest
	static void it_save_a_file() {
		Id caseId = [SELECT Id FROM Case WHERE Status = 'Submitted' LIMIT 1].Id;
		String fileName = 'UploadExcel.xlsx';
		String fileData = 'String to convert to base64 encoding.';
		String base64File = EncodingUtil.base64Encode(Blob.valueOf(fileData));

		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();

		Test.startTest();
		System.runAs(healthUser) {
			QFRLWCDownloadController.saveExcelFile(
				caseId,
				base64File,
				fileName
			);
		}
		Test.stopTest();

		String contentDocTitle = [
			SELECT ContentDocument.Title
			FROM ContentDocumentLink
			WHERE
				LinkedEntityId = :caseId
				AND ContentDocument.FileExtension = 'xlsx'
			ORDER BY ContentDocument.LastModifiedDate DESC
			LIMIT 1
		]
		.ContentDocument.Title;

		String contentDocType = [
			SELECT ContentDocument.FileType
			FROM ContentDocumentLink
			WHERE
				LinkedEntityId = :caseId
				AND ContentDocument.FileExtension = 'xlsx'
			ORDER BY ContentDocument.LastModifiedDate DESC
			LIMIT 1
		]
		.ContentDocument.FileType;

		System.assertEquals('UploadExcel', contentDocTitle);
		System.assertEquals('EXCEL_X', contentDocType);
	}

	@isTest
	static void it_load_a_file() {
		Id caseId = [SELECT Id FROM Case WHERE Status = 'Submitted' LIMIT 1].Id;

		String fileName = 'UploadExcel.xlsx';
		String fileData = 'String to convert to base64 encoding.';
		String base64File = EncodingUtil.base64Encode(Blob.valueOf(fileData));
		Blob contentBody = EncodingUtil.base64Decode(base64File);
		ContentVersion cv = new ContentVersion(
			ContentLocation = 'S',
			FirstPublishLocationId = caseId,
			PathOnClient = fileName,
			VersionData = contentBody
		);

		DMLImpl dmlinsert = new DMLImpl();
		dmlinsert.InsertRecord(cv);

		Id contentDocId = [
			SELECT ContentDocumentId
			FROM ContentVersion
			WHERE id = :cv.id
		]
		.ContentDocumentId;

		TestUserBuilder healthUserBuilder = QFRTestDataFactory.getHealthProviderBuilder();
		User healthUser = healthUserBuilder.createUser();

		dohagedcare.FilePreviewUtility.PreviewResponseWrapper result = new dohagedcare.FilePreviewUtility.PreviewResponseWrapper();

		Test.startTest();
		System.runAs(healthUser) {
			result = QFRLWCDownloadController.loadExcelFile(caseId);
		}
		Test.stopTest();

		System.assertEquals(contentDocId, result.ContentDocumentId);
	}
}