force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Party_ID__c.field-meta.xml
<CustomField>
    <fullName>Party_ID__c</fullName>
    <description>Primary key to link the Provider Record to GovGPS Record</description>
    <label>Party ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <label>Party Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Care Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community and Home Support</fullName>
            </value>
            <value>
                <fullName>Service System Development</fullName>
            </value>
            <value>
                <fullName>Care Relationship and Carer Support</fullName>
            </value>
            <value>
                <fullName>Assistance with Care and Housing</fullName>
            </value>
            <value>
                <fullName>Transition Care</fullName>
            </value>
            <value>
                <fullName>Innovative Pool</fullName>
            </value>
            <value>
                <fullName>Multi-Purpose Service</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Short-Term Restorative Care (STRC)</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>EACH Dementia</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Home Care Packages</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC High Care</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC High Care Dementia</fullName>
            </value>
            <value>
                <fullName>Innovative Pool - CDC Low Care</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retirement Villages Care Pilot</fullName>
            </value>
            <value>
                <fullName>Extended Aged Care at Home</fullName>
            </value>
            <value>
                <fullName>STRC</fullName>
                <isActive>false</isActive>
                <label>STRC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Service_Name_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_Effective_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Service Name Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/CHSP_Service.recordType-meta.xml
<RecordType>
    <fullName>CHSP_Service</fullName>
    <active>true</active>
    <label>CHSP Service</label>
</RecordType>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/CHSP_Service_Activity_Work_Plan_Record__c.object-meta.xml
<CustomObject>
    <label>CHSP Service Activity Work Plan Record</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>CHSP Service AWP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Service Activity Work Plan Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/fields/CHSP_Service_Schedule__c.field-meta.xml
<CustomField>
    <fullName>CHSP_Service_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CHSP Service Schedule</label>
    <referenceTo>CHSP_Service_Schedule__c</referenceTo>
    <relationshipName>CHSP_Service_Activity_Work_Plan_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <label>Service Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Service Care Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Schedule__c/CHSP_Service_Schedule__c.object-meta.xml
<CustomObject>
    <label>CHSP Schedule Detail</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CHSP Schedule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Schedule Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <label>Party Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>CHSP Service Schedules</relationshipLabel>
    <relationshipName>CHSP_Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/recordTypes/Provider_to_Service.recordType-meta.xml
<RecordType>
    <fullName>Provider_to_Service</fullName>
    <active>true</active>
    <label>Provider to Service</label>
</RecordType>

force-app/main/default/objects/Service_with_CHSP_Schedule_Detail__c/Service_with_CHSP_Schedule_Detail__c.object-meta.xml
<CustomObject>
    <label>Service with CHSP Schedule Detail</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Service with CHSP Schedule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service with CHSP Schedule Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_with_CHSP_Schedule_Detail__c/fields/CHSP_Schedule_Detail__c.field-meta.xml
<CustomField>
    <fullName>CHSP_Schedule_Detail__c</fullName>
    <label>CHSP Schedule Detail</label>
    <referenceTo>CHSP_Service_Schedule__c</referenceTo>
    <relationshipLabel>Service with CHSP Schedule Details</relationshipLabel>
    <relationshipName>Service_with_CHSP_Schedule_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_with_CHSP_Schedule_Detail__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service with CHSP Schedule Details</relationshipLabel>
    <relationshipName>Service_with_CHSP_Schedule_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GPMSCHSPLinkServiceHelper.cls
public with sharing class GPMSCHSPLinkServiceHelper {

    private List<CHSP_Service_Schedule__c> scope;
    private static final String ServiceRT = Schema.SObjectType.BusinessLicense
        .getRecordTypeInfosByDeveloperName()
        .get('CHSP_Service').getRecordTypeId();
    private static final String ServiceProviderRT = Schema.SObjectType.Service_Account_Relationship__c
        .getRecordTypeInfosByDeveloperName()
        .get('Provider_to_Service').getRecordTypeId();
    
    private List<String> partyIds = new List<String>();
    private List<String> recordIds = new List<String>();
    private Set<String> setServiceCareSubTypes_all = new set<String>();
    private Map<String, Set<String>> awpCareSubTypeAndActivityStatusMap = new Map<String, Set<String>>();
    private Map<id, List<String>> mapDetailWithSubtype = new Map<id, List<String>>();
    private Map<String,BusinessLicense> serviceMap = new Map<String,BusinessLicense>();
    private Map<String,Account> accountMap = new Map<String,Account>();
    private Map<String,Service_with_CHSP_Schedule_Detail__c> serviceDetailMap = new Map<String,Service_with_CHSP_Schedule_Detail__c>();
    private Map<String,BusinessLicense> serviceToInsertMap = new Map<String,BusinessLicense>();
    private Map<String,BusinessLicense> serviceToUpdateMap = new Map<String,BusinessLicense>();
    private Map<String, Id> agedCarePlanningRegionRecords = new Map<String, Id>();
    private Map<Id, List<CHSP_Service_Activity_Work_Plan_Record__c>> scheduleIdToWorkPlanMap = new Map<Id, List<CHSP_Service_Activity_Work_Plan_Record__c>>();
    
    public GPMSCHSPLinkServiceHelper(List<CHSP_Service_Schedule__c> scope) {
        this.scope = scope;
    }
    
    public void executeGPMSCHSPLinkService() {
        getRelatedWorkPlanRecords();
        getCareSubtypeAndStatus();
        
        //No Service SubCareType
        if(setServiceCareSubTypes_all.isEmpty() || partyIds.isEmpty()){
            return;
        }
        
        getExistingServiceMap();
        getRelatedProviderAccounts();
        getServiceAndScheduleDetailRelations();
        processCHSPWorkPlans();
        
        // De-duplicate
        processServiceWithScheduleDetails();
        
        // get ACPR data
        getAgedCarePlanningRegionRecords();
        
        // Update ACPR field
        updateACPRFieldOnWorkPlan();
    }

    private void getRelatedWorkPlanRecords() {
        for (CHSP_Service_Activity_Work_Plan_Record__c workPlan : [
            SELECT Id, Name, Service_Care_Sub_Type__c, Activity_Status__c, Service_Area__c, CHSP_Service_Schedule__c 
            FROM CHSP_Service_Activity_Work_Plan_Record__c 
            WHERE Service_Care_Sub_Type__c != null AND CHSP_Service_Schedule__c IN : scope
        ]) {
            List<CHSP_Service_Activity_Work_Plan_Record__c> workPlanList = scheduleIdToWorkPlanMap.get(workPlan.CHSP_Service_Schedule__c);
            if (workPlanList == null) {
                workPlanList = new List<CHSP_Service_Activity_Work_Plan_Record__c>{ workPlan };
            } else {
                workPlanList.add(workPlan);
            }
            scheduleIdToWorkPlanMap.put(workPlan.CHSP_Service_Schedule__c, workPlanList);
        }
    }
    
    private void getCareSubtypeAndStatus() {
        for(CHSP_Service_Schedule__c chspserviceschedule : scope){
            partyIds.add(chspserviceschedule.Party_Id__c);
            recordIds.add(chspserviceschedule.Id);
            set<String> setServiceCareSubTypes = new set<String>();
            Set<String> awpStatusIsApproved = new Set<String>();
            if (scheduleIdToWorkPlanMap.get(chspserviceschedule.Id) != null) {
                for(CHSP_Service_Activity_Work_Plan_Record__c AWP : scheduleIdToWorkPlanMap.get(chspserviceschedule.Id)){
                    if(AWP.Activity_Status__c == 'Approved') {
                        awpStatusIsApproved.add(chspserviceschedule.Party_Id__c+AWP.Service_Care_Sub_Type__c);
                    }
                    setServiceCareSubTypes.add(AWP.Service_Care_Sub_Type__c);
                    setServiceCareSubTypes_all.add(AWP.Service_Care_Sub_Type__c);
                }
            }
            awpCareSubTypeAndActivityStatusMap.put(chspserviceschedule.Id, awpStatusIsApproved);
            List<String> tmp = new List<string>(setServiceCareSubTypes);
            mapDetailWithSubtype.put(chspserviceschedule.id, tmp);
        }
    }
    
    private void getExistingServiceMap() {
        for(BusinessLicense service : [SELECT Id,Party_Id__c,Service_Care_Sub_Type__c, Status__c 
                                       FROM BusinessLicense 
                                       WHERE Party_Id__c in :partyIds 
                                       AND Service_Care_Sub_Type__c in :setServiceCareSubTypes_all]){
            serviceMap.put(service.Party_Id__c + service.Service_Care_Sub_Type__c,service);
        }
    }
    
    private void getRelatedProviderAccounts() {
        for(Account acc : [SELECT Id,Party_Id__c, Name 
                           FROM Account 
                           WHERE Party_Id__c in :partyIds]){
            accountMap.put(acc.Party_Id__c, acc);
        }
    }
    
    private void getServiceAndScheduleDetailRelations() {
        for(Service_with_CHSP_Schedule_Detail__c swsc : [SELECT Id,CHSP_Schedule_Detail__c,Service__c 
                                                         FROM Service_with_CHSP_Schedule_Detail__c 
                                                         WHERE CHSP_Schedule_Detail__c in :recordIds]){
            serviceDetailMap.put(String.valueof(swsc.Service__c) + String.valueOf(swsc.CHSP_Schedule_Detail__c), swsc);
        }
    }
    
    private void processCHSPWorkPlans() {
        for(CHSP_Service_Schedule__c chspserviceschedule : scope){
			processServicesForCreateOrUpdate(chspserviceschedule);
        }
        
        try {
            if(!serviceToUpdateMap.values().isEmpty()) {
                update serviceToUpdateMap.values();
            }
            
            if(!serviceToInsertMap.values().isEmpty()){
                insert serviceToInsertMap.Values();
                
                List<Service_Account_Relationship__c> serviceaccountToInsert = getServiceAccountRelationships();
                if(!serviceaccountToInsert.isEmpty()){
                    insert serviceaccountToInsert;
                }
            }
        } catch(Exception exp){
            dohagedcare.Logger.error(exp.getMessage(),exp,'GPMS').Log(); 
        }
    }
    
    private void processServicesForCreateOrUpdate(CHSP_Service_Schedule__c chspserviceschedule) {
        Set<String> awpStatusIsApproved = awpCareSubTypeAndActivityStatusMap.get(chspserviceschedule.Id);
        for(String subtype : mapDetailWithSubtype.get(chspserviceschedule.id)){
            if(serviceMap.get(chspserviceschedule.Party_Id__c+subtype) == null){
                BusinessLicense service = new BusinessLicense();
                service.RecordTypeId = ServiceRT;
                service.Care_Type__c = 'Commonwealth Home Support Programme';
                service.Party_Id__c = chspserviceschedule.Party_Id__c;
                service.Service_Name_Effective_Date__c = Date.today();
                service.Status_Date__c = Date.today();
                service.Service_Care_Sub_Type__c = subtype;
                service.Status__c = awpStatusIsApproved.contains(chspserviceschedule.Party_Id__c+subtype) ? 
                    'Operational':'Inactive';
                service.Name = getServiceName(chspserviceschedule.Party_Id__c, subtype);
                serviceToInsertMap.put(service.Party_Id__c + service.Service_Care_Sub_Type__c,service);
            } else {
                BusinessLicense serviceRecord = serviceMap.get(chspserviceschedule.Party_Id__c+subtype);
                if(awpStatusIsApproved.contains(chspserviceschedule.Party_Id__c+subtype) && serviceRecord.Status__c != 'Operational') {
                    serviceRecord.Status__c = 'Operational';
                    serviceToUpdateMap.put(chspserviceschedule.Party_Id__c+subtype, serviceRecord);
                } else if (!awpStatusIsApproved.contains(chspserviceschedule.Party_Id__c+subtype) && serviceRecord.Status__c == 'Operational') {
                    serviceRecord.Status__c = 'Inactive';
                    serviceToUpdateMap.put(chspserviceschedule.Party_Id__c+subtype, serviceRecord);
                } else {
                    continue;
                }
            }
        }
    }
    
    @TestVisible
    private String getServiceName(String partyId, String subtype) {
        String servName;
        Account acc_tmp = accountMap.get(partyId);
        if(null != acc_tmp){
            String serviceName = acc_tmp.Name + ' - ' + subtype;
            if(String.isNotBlank(serviceName)){
                servName = serviceName.left(80);
            }
        }else{
            servName = subtype;
        }
        
        return servName;
    }
    
    private List<Service_Account_Relationship__c> getServiceAccountRelationships() {
        List<Service_Account_Relationship__c> serviceaccountToInsert = new List<Service_Account_Relationship__c>();
        for(BusinessLicense service : serviceToInsertMap.Values()){
            serviceMap.put(service.Party_Id__c + service.Service_Care_Sub_Type__c,service);
            if(accountMap.get(service.Party_Id__c) != null){
                Service_Account_Relationship__c accountservice = new Service_Account_Relationship__c();
                accountservice.Provider_Name__c = accountMap.get(service.Party_Id__c).Id;
                accountservice.RecordTypeId = ServiceProviderRT;
                accountservice.Service_Name__c = service.Id;
                accountservice.Association_Start_Date__c = Date.today();
                serviceaccountToInsert.add(accountservice);
            }
        }
        
        return serviceaccountToInsert;
    }
    
    private void processServiceWithScheduleDetails() {
        List<Service_with_CHSP_Schedule_Detail__c> listJunctionInsert = new List<Service_with_CHSP_Schedule_Detail__c>();
        for(CHSP_Service_Schedule__c chspserviceschedule : scope){
            for(String subtype : mapDetailWithSubtype.get(chspserviceschedule.id)){
                String serviceRelationship = String.valueof(serviceMap.get(chspserviceschedule.Party_Id__c+subtype).id) + chspserviceschedule.Id;
                if(serviceDetailMap.get(serviceRelationship) == null){
                    Service_with_CHSP_Schedule_Detail__c juction = new Service_with_CHSP_Schedule_Detail__c();
                    juction.CHSP_Schedule_Detail__c = chspserviceschedule.id;
                    juction.Service__c = serviceMap.get(chspserviceschedule.Party_Id__c+subtype).id;
                    listJunctionInsert.add(juction);
                }
            }
        }
        
        if(!listJunctionInsert.isEmpty()){
            insert listJunctionInsert;
        }
    }
    
    private void getAgedCarePlanningRegionRecords() {
        for(Aged_Care_Planning_Region__c acpr: [SELECT Id, Name, ACPR_State__c, 
                                                Geospatial_Information_Layer_Version__r.Start_Date__c,
                                                Geospatial_Information_Layer_Version__r.End_Date__c 
                                                FROM Aged_Care_Planning_Region__c
                                               	WHERE Geospatial_Information_Layer_Version__r.Start_Date__c <= TODAY
												AND (Geospatial_Information_Layer_Version__r.End_Date__c >= TODAY
                                                OR Geospatial_Information_Layer_Version__r.End_Date__c = null)]) {
			String searchKey = acpr.Name + ';' + acpr.ACPR_State__c;
			agedCarePlanningRegionRecords.put(searchKey, acpr.Id);
        }
    }
    
    private void updateACPRFieldOnWorkPlan() {
        List<CHSP_Service_Activity_Work_Plan_Record__c> workPlanRecords = new List<CHSP_Service_Activity_Work_Plan_Record__c>();
        for(CHSP_Service_Schedule__c chspserviceschedule : scope){
            if (scheduleIdToWorkPlanMap.get(chspserviceschedule.Id) != null) {
                for(CHSP_Service_Activity_Work_Plan_Record__c AWP : scheduleIdToWorkPlanMap.get(chspserviceschedule.Id)){
                    AWP.Aged_Care_Planning_Region__c = getAgedCarePlanningRegionRecordId(AWP);
                    workPlanRecords.add(AWP);
                }
            }
        }
        
        try {
			update workPlanRecords;    
        } catch(Exception ex) {
            dohagedcare.Logger.error(ex.getMessage(),ex,'GPMS').Log();
        }
    }
    
    private Id getAgedCarePlanningRegionRecordId(CHSP_Service_Activity_Work_Plan_Record__c workPlanRecord) {
        String region;
        String state;
        String acprKey;
        
        // Extract region and state
        Pattern serviceAreaPattern = Pattern.compile('(.*?)\\((.*?)\\)');
        Matcher serviceAreaMatcher = serviceAreaPattern.matcher(workPlanRecord.Service_Area__c);
        if(serviceAreaMatcher.find()) { 
            region = serviceAreaMatcher.group(1).trim();
            state = serviceAreaMatcher.group(2);
        } else {
            region = workPlanRecord.Service_Area__c;
        }

        // Locate ACPR Id
        if(region == 'ACT') {
            acprKey = region + ';' + 'ACT';    
        } else if(state == null) {
            for(String searchKey : agedCarePlanningRegionRecords.keySet()) {
                if(searchKey.contains(region)) {
                    acprKey = searchKey;
                    break;
                }
            }    
        } else {
            acprKey = region + ';' + state;
        }

        return agedCarePlanningRegionRecords.get(acprKey);

    }
}