force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Approved_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CountArchRegDecision__c.field-meta.xml
<CustomField>
    <fullName>CountArchRegDecision__c</fullName>
    <description>This field will take the number value of  how many Archived Regulatory Decisions Count for each service - will be updated by a trigger</description>
    <label>Archived Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/NoOf_NonCurr_Rating_RegDecision__c.field-meta.xml
<CustomField>
    <fullName>NoOf_NonCurr_Rating_RegDecision__c</fullName>
    <description>Field updated by SCR Handler with no of non current Regulatory decisions relevant for SCR Rating i.e Non Current that count towards SCR</description>
    <label>NoOf NonCurr Rating RegDecision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Archived_Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Archived_Regulatory_Decision__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the regulatory decision has been archived</description>
    <label>Archived Regulatory Decision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Date_Decision_Applied__c.field-meta.xml
<CustomField>
    <fullName>Date_Decision_Applied__c</fullName>
    <label>Date Decision Applied</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Rating_Relevant__c.field-meta.xml
<CustomField>
    <fullName>Rating_Relevant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rating Relevant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test only</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Account_Relationship__c.Provider_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Compliance_Rating__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating__c</fullName>
    <description>Service Compliance Rating for an individual Reg Dec</description>
    <label>Service Compliance Rating</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Compliance_Rating_Effect__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating_Effect__c</fullName>
    <label>Service Compliance Rating Effect</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Compliance_Rating_Effect</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <description>Name of the Service to be Published</description>
    <label>Alternative Service Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Service care type is not Home Care or Residential</errorMessage>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Home Care</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Provider_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Regulatory Code Violations</relationshipLabel>
    <relationshipName>Regulatory_Code_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_Start_Date__c</fullName>
    <label>Association Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountArchRegDecision__c.field-meta.xml
<CustomField>
    <fullName>CountArchRegDecision__c</fullName>
    <description>This field will take the number value of  how many Archived Regulatory Decision Count for each service - will be updated by a trigger</description>
    <label>Archived Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CurrentNonCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CurrentNonCurrentRegDec__c</fullName>
    <description>Stores count of non-current regulatory decisions which are flagged as relevant to rating. Value is updated when a new Regulatory Decision is created or existing decision is removed.</description>
    <label>Non Current Reg Dec Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_Detail__c/Service_Compliance_Detail__c.object-meta.xml
<CustomObject>
    <label>Service Compliance Detail</label>
    <nameField>
        <displayFormat>SCRD-{000000}</displayFormat>
        <label>SCR Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_Detail__c/fields/Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Decision__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regulatory Decision</label>
    <referenceTo>RegulatoryCodeViolation</referenceTo>
    <relationshipLabel>Service Compliance Details</relationshipLabel>
    <relationshipName>Service_Compliance_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_Detail__c/fields/Regulatory_Decision_Status__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Decision_Status__c</fullName>
    <description>Captures Regulatory Decision Status at time of Publishing</description>
    <label>Regulatory Decision Status</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_Detail__c/fields/Service_Compliance_History__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_History__c</fullName>
    <label>Service Compliance History</label>
    <referenceTo>Service_Compliance_History__c</referenceTo>
    <relationshipLabel>Service Compliance Details</relationshipLabel>
    <relationshipName>Service_Compliance_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Calc_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Calc_Date__c</fullName>
    <description>Date time rating calculation occurred</description>
    <label>SCR Rating Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Decision__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>connection to regulatory Decision</description>
    <label>Regulatory Decision</label>
    <referenceTo>RegulatoryCodeViolation</referenceTo>
    <relationshipLabel>Service Compliance Histories</relationshipLabel>
    <relationshipName>Service_Compliance_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service_Account__c.field-meta.xml
<CustomField>
    <fullName>Service_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Service Compliance Histories</relationshipLabel>
    <relationshipName>Service_Compliance_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service_Compliance_Rating__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating__c</fullName>
    <description>Service Compliance number rating, out of 5</description>
    <label>Service Compliance Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Service_Compliance_Rating_Effect.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Star</fullName>
    </customValue>
    <customValue>
        <fullName>2 Star</fullName>
    </customValue>
    <customValue>
        <fullName>3 Star</fullName>
    </customValue>
    <customValue>
        <fullName>4  Star</fullName>
    </customValue>
    <customValue>
        <fullName>5 Star</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>STAR Rating effect for SCR</description>
    <masterLabel>Service Compliance Rating Effect</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateSCRBatchHelper.cls
/**
 * author: Matthew WAll
 * date: 10/11/2022
 * description: Helper Class used by CreateSCRBatch to process Regulatory Decisions
 **/
/* MODIFICATION LOG
 * Version       Developer                   Date                Description
 *-------------------------------------------------------------------------------------------
 *  1.0     		Matthew Wall               10-11-2022          Initial Creation
 *******************************************************************************************/
public with sharing class CreateSCRBatchHelper {
    static final String NEW_RATING = 'New Rating';

    public void processSCRBatch(List<Service_Account_Relationship__c> sarList) { 

        Map<Id,Service_Account_Relationship__c> serviceAccountMap = new Map<Id,Service_Account_Relationship__c>(sarList);
        Map<Id,List< RegulatoryCodeViolation>> regDecMap = getRegulatoryDecisionMap(sarList);
        List<Service_Compliance_History__c> schList = new List<Service_Compliance_History__c>(); 

        Map<Id, BusinessLicense> serviceAccountIdToServiceMap = getServiceAccountIdToServiceMap(sarList);

        // loop Service Account Relationship from RegDec
        for (Id key : regDecMap.keySet()) {
            // get counts
            Integer currentCount = 0;
            Integer nonCurrentCount = 0;
            Integer archivedCount = 0;
            for (RegulatoryCodeViolation current : regDecMap.get(key)) {
                if (current.published__c == true && current.Status == 'Current') {
                    currentCount++;
                    continue;
                }
                if (current.Status == 'Non-Current' && current.Rating_Relevant__c == true) {
                    nonCurrentCount++;
                    continue;
                }
                if (current.Status == 'Non-Current' && current.Archived_Regulatory_Decision__c == true) {
                    archivedCount++;
                    continue;
                }
            }
            
            BusinessLicense service = serviceAccountIdToServiceMap.get(key);
            service.CountCurrentRegDec__c = currentCount;
            service.NoOf_NonCurr_Rating_RegDecision__c = nonCurrentCount;
            service.CountArchRegDecision__c = archivedCount;
            Service_Account_Relationship__c sar = serviceAccountMap.get(key);
            sar.CountCurrentRegDec__c = currentCount;
            sar.CurrentNonCurrentRegDec__c = nonCurrentCount;
            sar.CountArchRegDecision__c = archivedCount;

            // create SCH
            RegulatoryCodeViolation latestRegDec = getLatestRegDec(regDecMap.get(key));
            if(latestRegDec != null && currentCount > 0 && latestRegDec.Date_Decision_Applied__c >= sar.Association_Start_Date__c) {
                Service_Compliance_History__c sch = new Service_Compliance_History__c();
                sch.Rating_Type__c = NEW_Rating;
                sch.Regulatory_Decision__c = latestRegDec.Id;
                sch.Service__c = latestRegDec.Service_Name_lookup__c;
                sch.Provider__c = latestRegDec.Service_Provider_Name_lookup__c;
                sch.Rating_Calc_Date__c = datetime.now();
                sch.Publication_Date__c=datetime.now();
                sch.Rating_Type__c = 'Current Rating';
                sch.Availability_Status__c = 'LIVE';
                sch.Service_Account__c = latestRegDec.Service_Account_Relationship__c;
                sch.Service_Compliance_Rating__c = RegulatoryDecisionEventTriggerHelper.getLeastStarRating(regDecMap.get(key));
                schList.add(sch);
            } 
        }
        insert schList;
        
        // loop SCH to create SCD
        List<Service_Compliance_Detail__c> scdList = new List<Service_Compliance_Detail__c>();
        for (Service_Compliance_History__c sch : schList) {
            for (RegulatoryCodeViolation current : regDecMap.get(sch.Service_Account__c)) {
                Service_Compliance_Detail__c scd = new Service_Compliance_Detail__c(Regulatory_Decision__c=current.Id, 
                                                                                Regulatory_Decision_Status__c=current.status, 
                                                                                Service_Compliance_History__c=sch.Id);
                scdList.add(scd);
            }
        }

        if (Schema.sObjectType.Service_Account_Relationship__c.isCreateable()) {
            insert scdList;
        }
        
        update serviceAccountMap.values();

        update serviceAccountIdToServiceMap.values();
    }

    // Map of sarId to RegDec
    private Map<Id,List<RegulatoryCodeViolation>> getRegulatoryDecisionMap(List<Service_Account_Relationship__c> sarList) { 
        Set<Id> sarIds = new Set<Id>();
        for (Service_Account_Relationship__c sar : sarList) {
            sarIds.add(sar.Id);
        }

        List<RegulatoryCodeViolation> regDecList =  [SELECT Id, Service_Name_lookup__c, published__c, Status, 
                                                    Rating_Relevant__c, Archived_Regulatory_Decision__c, 
                                                    Date_Decision_Applied__c, Service_Provider_Name_lookup__c,
                                                    Service_Account_Relationship__c, Service_Compliance_Rating__c,
                                                    Service_Compliance_Rating_Effect__c 
                                                    FROM RegulatoryCodeViolation 
                                                    WHERE Service_Account_Relationship__c IN: sarIds];

        Map<id,List< RegulatoryCodeViolation>> serviceAccountRegDecMap = new Map<id,List<RegulatoryCodeViolation>>();

        for (RegulatoryCodeViolation currentRegDec : regDecList) {
            if (!serviceAccountRegDecMap.containsKey(currentRegDec.Service_Account_Relationship__c)) {
                serviceAccountRegDecMap.put(currentRegDec.Service_Account_Relationship__c, new List<RegulatoryCodeViolation>());
            }
            serviceAccountRegDecMap.get(currentRegDec.Service_Account_Relationship__c).add(currentRegDec);
        }

        return serviceAccountRegDecMap;
    }
    
    private Map<Id,BusinessLicense> getServiceAccountIdToServiceMap(List<Service_Account_Relationship__c> sarList) {
        Map<Id,BusinessLicense> serviceAccountIdToServiceMap = new Map<Id,BusinessLicense>();
        Set<Id> serviceIds = new Set<Id>();
        for (Service_Account_Relationship__c sar : sarList) {
            serviceIds.add(sar.Service_Name__c);
        }
        Map<Id,BusinessLicense> serviceMap = new Map<Id,BusinessLicense>([Select Id, Name, Care_Type__c, CountCurrentRegDec__c, CountArchRegDecision__c, 
                                                                            NoOf_NonCurr_Rating_RegDecision__c 
                                                                            FROM BusinessLicense WHERE Id IN: serviceIds]);
        for (Service_Account_Relationship__c sar : sarList) {
            serviceAccountIdToServiceMap.put(sar.Id,serviceMap.get(sar.Service_Name__c));
        }
        return serviceAccountIdToServiceMap;
    }

    private RegulatoryCodeViolation getLatestRegDec(List<RegulatoryCodeViolation> regDecList) {
        RegulatoryCodeViolation current = null;
        for (RegulatoryCodeViolation regDec : regDecList) {
            if (regDec.Status == 'Current' && regDec.Date_Decision_Applied__c != null && current == null ) {
                current = regDec;
            }
            else if ( regDec.Status == 'Current' && regDec.Date_Decision_Applied__c != null && current != null && 
                    regDec.Date_Decision_Applied__c > current.Date_Decision_Applied__c ) {
                current = regDec;
            }
            else {
                continue;
            }
        }
        return current;
    }
}