force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/Approved_Provider_Service.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Service</fullName>
    <active>true</active>
    <label>Approved Provider Service</label>
</RecordType>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Archived_Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Archived_Regulatory_Decision__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the regulatory decision has been archived</description>
    <label>Archived Regulatory Decision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Date_Decision_Ends__c.field-meta.xml
<CustomField>
    <fullName>Date_Decision_Ends__c</fullName>
    <label>Date Decision Ends</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Decision_Details__c.field-meta.xml
<CustomField>
    <fullName>Decision_Details__c</fullName>
    <label>Decision Details</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Rating_Relevant__c.field-meta.xml
<CustomField>
    <fullName>Rating_Relevant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rating Relevant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Reason_for_issuing_Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_issuing_Regulatory_Decision__c</fullName>
    <label>Reason for issuing Regulatory Decision</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/SCR_Rating__c.field-meta.xml
<CustomField>
    <fullName>SCR_Rating__c</fullName>
    <description>calculated SCR rating for the record</description>
    <label>SCR Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Compliance_Rating_Effect</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test only</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Account_Relationship__c.Provider_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Compliance_Rating__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating__c</fullName>
    <description>Service Compliance Rating for an individual Reg Dec</description>
    <label>Service Compliance Rating</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Compliance_Rating_Effect__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Rating_Effect__c</fullName>
    <label>Service Compliance Rating Effect</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Compliance_Rating_Effect</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Service care type is not Home Care or Residential</errorMessage>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Home Care</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Name__c</fullName>
    <description>Name of the Service Provider to be Published</description>
    <label>Alternative Service Provider Name</label>
    <length>130</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Provider_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Regulatory Code Violations</relationshipLabel>
    <relationshipName>Regulatory_Code_Violations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CountCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CountCurrentRegDec__c</fullName>
    <description>Count of current regulatory decisions</description>
    <label>Current Regulatory Decision Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/CurrentNonCurrentRegDec__c.field-meta.xml
<CustomField>
    <fullName>CurrentNonCurrentRegDec__c</fullName>
    <description>Stores count of non-current regulatory decisions which are flagged as relevant to rating. Value is updated when a new Regulatory Decision is created or existing decision is removed.</description>
    <label>Non Current Reg Dec Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Service_Compliance_Rating_Effect.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 Star</fullName>
    </customValue>
    <customValue>
        <fullName>2 Star</fullName>
    </customValue>
    <customValue>
        <fullName>3 Star</fullName>
    </customValue>
    <customValue>
        <fullName>4  Star</fullName>
    </customValue>
    <customValue>
        <fullName>5 Star</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>STAR Rating effect for SCR</description>
    <masterLabel>Service Compliance Rating Effect</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RegulatoryDecisionUtilityTest.cls
/* 
    * Regulatory Decision Utility Test
    * Tests for RegulatoryDecisionUtility
    * Author: Matthew Wall
    * Date: 5/10/22
*/
@IsTest
public with sharing class RegulatoryDecisionUtilityTest {
    @TestSetup
    static void makeData() {
        User testUser = TestDataFactory.createSystemAdminUser();

		Test.startTest();
		System.runAs(testUser){
            List<Account> providers = TestDataFactory.createProviderRecords(1);
            insert providers;
            List<BusinessLicense> testService = TestDataFactory.createServiceRecords(1);
            testService[0].Care_Type__c = 'Residential';
            testService[0].RecordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName()
                    .get('Approved_Provider_Service')
                    .getRecordTypeId();
            insert testService;
            List<Service_Account_Relationship__c> serviceAccounts = TestDataFactory.createServiceAccountRecords(1, testService, providers);
            insert serviceAccounts;
            List<RegulatoryCodeViolation> regDecisionList = new List<RegulatoryCodeViolation>();
            regDecisionList.add(new RegulatoryCodeViolation(Service_name_lookup__c = testService[0].Id, Service_Provider_Name__c = providers[0].Id, 
                                                            Service_Account_Relationship__c = serviceAccounts[0].Id, Status = 'Current', 
                                                            DateCreated = Datetime.now(), 
                                                            Published__c = true, Rating_Relevant__c = true, SCR_Rating__c = '3 Star', 
                                                            Decision_Details__c = 'Decision Details',
                                                        Reason_for_issuing_Regulatory_Decision__c = 'Test Reason',
                                                        Service_Provider_Name_lookup__c =  providers[0].id));
            insert regDecisionList;
        }
        Test.stopTest();
    }
    @isTest
    static void testRegDecCount() {
        User user = createTestUser();
        System.runAs(user) {
            List<RegulatoryCodeViolation> regDecisionList = [SELECT Id, Name, Status, Service_Name_lookup__c,  
                                                            Service_Provider_Name_lookup__c, 
                                                            Published__c, SCR_Rating__c, Rating_Relevant__c,
                                                            Service_Compliance_Rating__c, Archived_Regulatory_Decision__c,
                                                            Service_Account_Relationship__c, Service_Compliance_Rating_Effect__c
                                                            FROM RegulatoryCodeViolation];
            Test.startTest();
            RegulatoryDecisionUtility.getCurrentDecisionCount(regDecisionList);
            Test.stopTest();

        }
    }
    @isTest
    static void testSetRegDecCount() {
        User user = createTestUser();
        System.runAs(user) {
            Set<Id> serviceAccountIds = new Set<Id>();
            List<Service_Account_Relationship__c> serviceAccountRelationship = [SELECT Id FROM Service_Account_Relationship__c];
            for (Service_Account_Relationship__c sar : serviceAccountRelationship) {
                serviceAccountIds.add(sar.Id);
            }
            
            Map<Id,RegulatoryCodeViolation> regDecMap = new Map<Id,RegulatoryCodeViolation>([SELECT Id, Name, Status, Service_Name_lookup__c,  
                                                                                            Service_Provider_Name_lookup__c, 
                                                                                            Published__c, SCR_Rating__c, Rating_Relevant__c,
                                                                                            Service_Compliance_Rating__c, Archived_Regulatory_Decision__c,
                                                                                            Service_Account_Relationship__c, Service_Compliance_Rating_Effect__c
                                                                                            FROM RegulatoryCodeViolation]);
            Test.startTest();
            RegulatoryDecisionUtility.setRegDecCount(serviceAccountIds, regDecMap);
            Test.stopTest();
            List<BusinessLicense> services = [SELECT Id, CountCurrentRegDec__c FROM BusinessLicense];
            System.assertEquals(1, services[0].CountCurrentRegDec__c, 'Count on service must be one');
            List<Service_Account_Relationship__c> sarList = [SELECT Id, CountCurrentRegDec__c FROM Service_Account_Relationship__c];
            System.assertEquals(1, sarList[0].CountCurrentRegDec__c, 'Count on Serivce Account Rel must be one');
        }
    }
    @isTest
    static void testUpdateNonCurrentCount() {
        User user = createTestUser();
        System.runAs(user) {
            Set<Id> serviceAccountIds = new Set<Id>();
            List<Service_Account_Relationship__c> serviceAccountRelationship = [SELECT Id FROM Service_Account_Relationship__c];
            for (Service_Account_Relationship__c sar : serviceAccountRelationship) {
                serviceAccountIds.add(sar.Id);
            }
            
            Map<Id,RegulatoryCodeViolation> regDecMap = new Map<Id,RegulatoryCodeViolation>([SELECT Id, Name, Status, Service_Name_lookup__c,  
                                                                                            Service_Provider_Name_lookup__c, 
                                                                                            Published__c, SCR_Rating__c, Rating_Relevant__c,
                                                                                            Service_Compliance_Rating__c, Archived_Regulatory_Decision__c,
                                                                                            Service_Account_Relationship__c, Service_Compliance_Rating_Effect__c
                                                                                            FROM RegulatoryCodeViolation]);
            regDecMap.values()[0].Rating_Relevant__c = true;
            regDecMap.values()[0].Status = RegulatoryDecisionUtility.NON_CURRENT_STATUS;
            regDecMap.values()[0].Date_Decision_Ends__c = Date.today();
            update regDecMap.values();
            Test.startTest();
            RegulatoryDecisionUtility.updateNonCurrentCount(serviceAccountIds, regDecMap);
            Test.stopTest();
            List<Service_Account_Relationship__c> sarList = [SELECT Id, CurrentNonCurrentRegDec__c FROM Service_Account_Relationship__c];
            System.assertEquals(1, sarList[0].CurrentNonCurrentRegDec__c, 'Expected count of 1 ');
        }
    }
    @isTest
    static void testConvertDate(){
        Test.startTest();
        Date d = RegulatoryDecisionUtility.convertDate(System.today());
        Test.stopTest();
        System.assertNotEquals(null, d, 'Date expected');

    }
    public static User createTestUser() {
        Profile prof = [SELECT Id, Name FROM Profile WHERE Name LIKE 'System Administrator'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.ProfileId = prof.Id;
        user.Username = 'tester1@unittest.com';
        user.email = 'test@test.com';
        user.Alias = 'tst';
        user.TimeZoneSidKey = 'Australia/Sydney';
        user.LocaleSidKey = 'en_AU'; 
        user.EmailEncodingKey = 'UTF-8'; 
        user.LanguageLocaleKey = 'en_US';
        insert user;
        return user;
    }
}