force-app/main/default/objects/Account/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Aboriginal and Torres Strait Island Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_ID__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID__c</fullName>
    <description>CORPORATE_IDENTIFIER ACO Incorporation ID</description>
    <label>Incorporation ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prospective_Provider__c.field-meta.xml
<CustomField>
    <fullName>Prospective_Provider__c</fullName>
    <description>Likely to become a provider in the future</description>
    <label>Prospective Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <description>Care Type field pulled in from Account Object</description>
    <formula>TEXT(Account.Care_Type__c)</formula>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provider Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull from Reporting Perion Object.</description>
    <label>Reporting Period ID</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account Relationship</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <description>GL Code</description>
    <label>GL Code</label>
    <nameField>
        <label>GL Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Category__c/Question_Category__c.object-meta.xml
<CustomObject>
    <description>Parent object - Master object</description>
    <label>Question Category</label>
    <nameField>
        <label>Question Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions Category</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quality Indicator</fullName>
            </value>
            <value>
                <fullName>Consumer Experience Interview</fullName>
            </value>
            <value>
                <fullName>Quality Standard</fullName>
            </value>
            <value>
                <fullName>Care Minutes</fullName>
            </value>
            <value>
                <fullName>Residential Viability and Prudential Reporting</fullName>
            </value>
            <value>
                <fullName>Home Care Viability and Prudential Reporting</fullName>
            </value>
            <value>
                <fullName>Quality Indicator Targets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Association_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_Start_Date__c</fullName>
    <label>Association Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ACFRGetViabilityResponseTest.cls
/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 11-24-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/

@IsTest
public with sharing class ACFRGetViabilityResponseTest {
	@TestSetup
	static void setup() {
		User testUser = TestDataFactory.createSystemAdminUser(); //Added by CJJOYA 20012023

		System.runAs(testUser) {
			Profile adminProfile = [
				SELECT Id
				FROM Profile
				WHERE Name = 'System Administrator'
				LIMIT 1
			];

			User record = new User(
				Alias = 'testUser',
				Email = 'testUser@admin.com',
				FirstName = 'Test',
				LastName = 'User',
				TimeZoneSidKey = 'America/Los_Angeles',
				LanguageLocaleKey = 'en_US',
				EmailEncodingKey = 'UTF-8',
				LocaleSidKey = 'en_US',
				ProfileId = adminProfile.Id,
				UserName = 'testUser01@admin.com'
			);
			insert record;

			Account acc = new Account(
				Name = 'Test Provider',
				Purpose__c = 'Government',
				//Incorporation_ID_Type__c = 'Not Incorporated',
				Incorporation_ID_Type__c = 'ACN',
				Prospective_Provider__c = 'No',
				Incorporation_ID__c = '852147963',
				RecordTypeId = [
					SELECT Id
					FROM RecordType
					WHERE
						SobjectType = 'Account'
						AND IsActive = TRUE
						AND Name = 'Approved Provider'
					LIMIT 1
				]
				.Id
			);
			insert acc;

			BusinessLicense serviceHome = new BusinessLicense(
				Name = 'Total',
				Effective_Date__c = Date.today(),
				Care_Type__c = 'Home Care',
				Status = 'Operational',
				Status_Date__c = Date.today()
			);
			insert serviceHome;

			Service_Account_Relationship__c servHomeCare = new Service_Account_Relationship__c(
				Association_Start_Date__c = System.today(),
				Service_Name__c = serviceHome.id,
				Provider_Name__c = acc.id
			);
			insert servHomeCare;
			Reporting_Period__c currentRP = new Reporting_Period__c(
				Start_Date__c = date.today().toStartOfMonth(),
				End_Date__c = date.today().addDays(32)
			);
			insert currentRP;

			GL_Code__c testGLCode = new GL_Code__c(
				Name = 'Test GL',
				Type__c = 'Home Care Viability and Prudential Reporting',
				Display_Order__c = 0,
				Line_Item_Value_Type__c = 'Numeric'
			);
			insert testGLCode;

			Case c = new Case();
			c.Status = 'New';
			c.accountid = acc.id;
			c.Priority = 'Medium';
			c.Reporting_Period__c = currentRP.id;
			insert c;

			Form__c form = new Form__c();
			form.Account__c = acc.id;
			form.Case__c = c.Id;
			form.Reporting_Period__c = currentRP.Id;
			form.Type__c = 'Home Care Viability and Prudential Reporting';
			form.QA_Comments__c = 'None';
			form.RecordTypeId = Schema.SObjectType.Form__c.getRecordTypeInfosByDeveloperName()
				.get('QFR')
				.getRecordTypeId();
			insert form;

			Question_Category__c qc = new Question_Category__c(
				name = 'Cat1',
				External_Id__c = 'qc001' //, //qfr to fix
				//Type__c = 'Home Care Viability and Prudential Reporting' //qfr to fix
			);
			insert qc;

			List<Question_Library__c> qls = new List<Question_Library__c>();
			qls.add(
				new Question_Library__c(
					Question_Category__c = qc.id,
					QL_DM_Key__c = 'Q.HV.A.BSS.OTH001',
					Question__c = 'Business Improvement Fund?'
				)
			);
			qls.add(
				new Question_Library__c(
					Question_Category__c = qc.id,
					QL_DM_Key__c = 'Q.HV.A.SOL002',
					Question__c = 'solvecy next six months'
				)
			);
			insert qls;

			List<Response__c> responseList = new List<Response__c>();
			responseList.add(
				new Response__c(
					Form__c = form.id,
					Question_Library__c = qls[0].id,
					Care_or_Services__c = 'Clinical Care;Personal Care',
					Response_options__c = 'Yes',
					Additional_information__c = 'Test Only'
				)
			);
			responseList.add(
				new Response__c(
					Form__c = form.id,
					Question_Library__c = qls[1].id,
					Care_or_Services__c = 'Clinical Care;Personal Care;Allied Health;Diversional Therapy;Lifestyle/Recreation/Activities Officer;Other',
					Response_options__c = 'Yes',
					Additional_information__c = 'Test Only'
				)
			);
			insert responseList;
		}
	}

	@IsTest
	private static void Test_getViabilityResponse() {
		User testUser = TestDataFactory.createSystemAdminUser(); //Added by CJJOYA
		System.runAs(testUser) {
			User adminUser = [
				SELECT Id
				FROM User
				WHERE UserName = 'testUser01@admin.com'
				LIMIT 1
			];
			Form__c form = [
				SELECT id
				FROM Form__c
				WHERE Type__c = 'Home Care Viability and Prudential Reporting'
			];
			Boolean result;
			Map<String, Map<String, Object>> args = new Map<String, Map<String, Object>>{
				'output' => new Map<String, Object>(),
				'input' => new Map<String, Object>{ 'FormId' => form.Id }
			};

			if (form != null) {
				Test.startTest();
				//System.runAs(adminUser) { //Modified by CJJOYA 20012023
				Callable extension = (Callable) Type.forName(
						'ACFRGetViabilityResponse'
					)
					.newInstance();
				result = (Boolean) extension.call('getResponse', args);

				//}
				Test.stopTest();
				List<Case> newcases = [SELECT Id FROM Case];

				//Ensure records were created
				System.assertNotEquals(
					newcases.size(),
					0,
					'List should not be empty'
				);
			}
		}
	}
}