force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prospective_Provider__c.field-meta.xml
<CustomField>
    <fullName>Prospective_Provider__c</fullName>
    <description>Likely to become a provider in the future</description>
    <label>Prospective Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Received_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/GPMSRelatedDocumentControllerTest.cls
@IsTest
public class GPMSRelatedDocumentControllerTest {
    
    static void setup() {
        Account acc = new Account(Name = 'TestAcct0',Incorporation_ID_Type__c='Taken to be Incorporated',Prospective_Provider__c='');
        acc.Purpose__c = 'Government';
        acc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Approved_Provider').getRecordTypeId();
        insert acc;

        ContentVersion cv = new ContentVersion();
        cv.Description  = 'test description';
        cv.PathOnClient ='test_file.txt';
        cv.Title = 'test file '+DateTime.now();
        cv.versiondata=Blob.valueOf('test file body');
        cv.Received_Date__c = System.today().addDays(-1);
        insert cv;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        cdl.LinkedEntityId =acc.Id;
        cdl.ShareType = 'V';
        insert cdl;

    }

    @isTest static void testGetRelatedDocuments() {
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        System.runAs(gpmsUser)
        {
            Test.startTest();
            setup();
        Account acct = [SELECT Id FROM Account WHERE Name='TestAcct0' LIMIT 1];
        GPMSRelatedDocumentController.RelatedDocument documents =  GPMSRelatedDocumentController.getRelatedDocuments(acct.Id);
        System.assertEquals(documents.documentsSize, 1);
            Test.stopTest();
        }
    }

    @isTest static void testUpdateRelatedDocument() {
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        System.runAs(gpmsUser)
        {
            Test.startTest();
            setup();
        Account acct = [SELECT Id FROM Account WHERE Name='TestAcct0' LIMIT 1];
        GPMSRelatedDocumentController.RelatedDocument documentResult =  GPMSRelatedDocumentController.getRelatedDocuments(acct.Id);
        List<ContentVersion> docs = documentResult.documents;
        for (ContentVersion doc : docs) {
            doc.Received_Date__c = System.today();
        }
        GPMSRelatedDocumentController.updateRelatedDocument((Object)docs);
        documentResult =  GPMSRelatedDocumentController.getRelatedDocuments(acct.Id);
        System.assertEquals(documentResult.documentsSize, 1);
        System.assertEquals(documentResult.documents[0].Received_Date__c, System.today());
            Test.stopTest();
        }
    }

    @isTest static void testDeleteRelatedDocument() {
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        System.runAs(gpmsUser)
        {
            Test.startTest();
            setup();
        Account acct = [SELECT Id FROM Account WHERE Name='TestAcct0' LIMIT 1];
        GPMSRelatedDocumentController.RelatedDocument documentResult =  GPMSRelatedDocumentController.getRelatedDocuments(acct.Id);
        System.assertEquals(documentResult.documentsSize, 1);
        String a = GPMSRelatedDocumentController.deleteRelatedDocument(documentResult.documents[0].ContentDocumentId);
        documentResult =  GPMSRelatedDocumentController.getRelatedDocuments(acct.Id);
        System.assertEquals(documentResult.documentsSize, 0);
            Test.stopTest();
        }
    }

}