force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Party_ID__c.field-meta.xml
<CustomField>
    <fullName>Party_ID__c</fullName>
    <description>Primary key to link the Provider Record to GovGPS Record</description>
    <label>Party ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prospective_Provider__c.field-meta.xml
<CustomField>
    <fullName>Prospective_Provider__c</fullName>
    <description>Likely to become a provider in the future</description>
    <label>Prospective Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Commonwealth_Home_Support_Programme.recordType-meta.xml
<RecordType>
    <fullName>Commonwealth_Home_Support_Programme</fullName>
    <active>true</active>
    <description>Commonwealth Home Support Programme</description>
    <label>Commonwealth Home Support Programme</label>
</RecordType>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/CHSP_Procurement_Based_AWP_Record__c.object-meta.xml
<CustomObject>
    <label>CHSP Procurement Based AWP Record</label>
    <nameField>
        <displayFormat>CPAWP-{000000000}</displayFormat>
        <label>CHSP Procurement Based AWP Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Procurement Based AWP Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Party_ID__c.field-meta.xml
<CustomField>
    <fullName>Party_ID__c</fullName>
    <label>Party ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Service Care Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Procurement_Based_AWP_Record__c/fields/Service_Type_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Level__c</fullName>
    <label>Service Type Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GPMSCHSPCPAWPLinkServiceScheduleTest.cls
@IsTest
public class GPMSCHSPCPAWPLinkServiceScheduleTest {
    
    private static User currentUser = [SELECT Id From User WHERE Id = :UserInfo.getUserId()];
    
    @IsTest
    static void testPositive(){
        
        System.runAs(currentUser){
            Test.startTest();
            
            GPMSCHSPCPAWPLinkServiceSchedule s = new GPMSCHSPCPAWPLinkServiceSchedule();
            String sch = '00 40 09 ? * *';
            String jobId = System.schedule('Test GPMSCHSPCPAWPLinkServiceSchedule', sch, s);
            
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                              NextFireTime
                              FROM CronTrigger WHERE id = :jobId];
            
            System.assertEquals(sch, ct.CronExpression);
            
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testErrorCatch(){
        
        System.runAs(currentUser){
            Test.startTest();
            
            GPMSCHSPCPAWPLinkServiceBatch awpLinkServiceBatch;
            
            GPMSCHSPCPAWPLinkServiceSchedule s = new GPMSCHSPCPAWPLinkServiceSchedule(awpLinkServiceBatch);
            String sch = '00 40 09 ? * *';
            String jobId = System.schedule('Test GPMSCHSPCPAWPLinkServiceSchedule', sch, s);
            
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                              NextFireTime
                              FROM CronTrigger WHERE id = :jobId];
            
            System.assertEquals(sch, ct.CronExpression);
            
            Test.stopTest();
        }
    }
    
    //@IsTest
    static void setup(){
        //account
        
        Account aco = new Account(Name = 'ACO',Incorporation_ID_Type__c='Not Incorporated',Prospective_Provider__c='');
        aco.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commonwealth_Home_Support_Programme').getRecordTypeId();
        insert aco;
        
        //service detail
        List<CHSP_Procurement_Based_AWP_Record__c> chsp_List = new List<CHSP_Procurement_Based_AWP_Record__c>();
        for(integer i=0;i<10;i++){
            CHSP_Procurement_Based_AWP_Record__c chsp1 = new CHSP_Procurement_Based_AWP_Record__c();
            chsp1.Party_Id__c = '111';
            chsp1.Activity_Status__c = 'Approved';
            chsp1.Service_Type_Level__c = 'Allied Health and Therapy Services';
            chsp1.Service_Care_Sub_Type__c = 'xxx' + i;
            chsp_List.add(chsp1);
        }
        insert chsp_List;
    }
    
    static void test(){
        List<CHSP_Procurement_Based_AWP_Record__c> chsp_List = new List<CHSP_Procurement_Based_AWP_Record__c>();
        for(integer i=0;i<10;i++){
            CHSP_Procurement_Based_AWP_Record__c chsp1 = new CHSP_Procurement_Based_AWP_Record__c();
            chsp1.Party_Id__c = '6956';
            chsp1.Service_Type_Level__c = 'Allied Health and Therapy Services';
            chsp1.Activity_Status__c = 'Approved';
            chsp1.Service_Care_Sub_Type__c = 'xxx' + i;
            chsp_List.add(chsp1);
        }
        insert chsp_List;
    }
}