force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prospective_Provider__c.field-meta.xml
<CustomField>
    <fullName>Prospective_Provider__c</fullName>
    <description>Likely to become a provider in the future</description>
    <label>Prospective Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Aged_Care_Organisation.recordType-meta.xml
<RecordType>
    <fullName>Aged_Care_Organisation</fullName>
    <active>true</active>
    <description>Aged Care Organisation</description>
    <label>Aged Care Organisation</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Accounts</label>
    <nameField>
        <displayFormat>ARL-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/Account_From_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_From_Id__c</fullName>
    <description>Parent account record to link another account record.</description>
    <label>Account From</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 AND 4) OR (1 AND 2)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account, Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation, Provider to Management Company, Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account From)</relationshipLabel>
    <relationshipName>Account_Relationship_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Account_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_To_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account To</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Management Company, Administrative Organisation, Service Delivery Organisation, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Management Company</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Management Company</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Delivery Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account To)</relationshipLabel>
    <relationshipName>Account_Relationship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/recordTypes/ACO_to_Account.recordType-meta.xml
<RecordType>
    <fullName>ACO_to_Account</fullName>
    <active>true</active>
    <label>ACO to Account</label>
</RecordType>

force-app/main/default/objects/ACO_Group__c/ACO_Group__c.object-meta.xml
<CustomObject>
    <label>ACO Group</label>
    <nameField>
        <label>ACO Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACO Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ACO_Group_Member__c/ACO_Group_Member__c.object-meta.xml
<CustomObject>
    <description>Acts as a junction between ACO Group and Account</description>
    <label>ACO Group Member</label>
    <nameField>
        <displayFormat>ACGM-{00000}</displayFormat>
        <label>ACO Group Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACO Group Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ACO_Group_Member__c/fields/ACO_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>ACO_Group_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACO Group Name</label>
    <referenceTo>ACO_Group__c</referenceTo>
    <relationshipLabel>ACO Group Members (ACO Group Name)</relationshipLabel>
    <relationshipName>ACO_Group_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ACO_Group_Member__c/fields/ACOs_to_link__c.field-meta.xml
<CustomField>
    <fullName>ACOs_to_link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Allows users to select from existing ACOs</description>
    <label>ACO to link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ACO Group Members (ACOs to link)</relationshipLabel>
    <relationshipName>ACO_Group_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GPMSRelatedProviderControllerTest.cls
@isTest
public class GPMSRelatedProviderControllerTest {
    
    private static User currentUser = TestDataFactory.createGPMSTestUser();
    
    @testSetup static void setup() {
        
        System.runAs(currentUser){
            
            List<Account> accToInsert = new List<Account>();
            Account aco = new Account(Name = 'ACO',Incorporation_ID_Type__c='Not Incorporated',Prospective_Provider__c='');
            aco.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Aged_Care_Organisation').getRecordTypeId();
            accToInsert.add(aco);
            Account provider = new Account(Name = 'Provider',Incorporation_ID_Type__c='Taken to be Incorporated',Prospective_Provider__c='');
            provider.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Approved_Provider').getRecordTypeId();
            provider.Purpose__c = 'Government';
            accToInsert.add(provider);
            insert accToInsert;
            
            provider = [SELECT Id FROM Account WHERE Name = 'Provider' limit 1];
            aco = [SELECT Id FROM Account WHERE Name = 'ACO' limit 1];
            
            Account_Relationship__c ar = new Account_Relationship__c();
            ar.Account_From_Id__c = aco.Id;
            ar.Account_To_Id__c = provider.Id;
            ar.recordTypeId = Schema.SObjectType.Account_Relationship__c.getRecordTypeInfosByDeveloperName().get('ACO_to_Account').getRecordTypeId();
            insert ar;
            
            ACO_Group__c acogroup = new ACO_Group__c();
            acogroup.Name = 'Test';
            insert acogroup;
            
            ACO_Group_Member__c member = new ACO_Group_Member__c();
            member.ACO_Group_Name__c = acogroup.Id;
            member.ACOs_to_link__c = aco.Id;
            insert member;
        }
        
    }
    
    @isTest static void testGPMSFetchAcoGrpMember() {
        
        Account_Relationship__c ar = [SELECT Id,Account_From_Id__c,Account_To_Id__c FROM Account_Relationship__c  limit 1];
        System.debug(ar);
        
        Map<String,Object> inputMap = new Map<String,Object>();
        Map<String,Object> outMap = new Map<String,Object>();
        Map<String,Object> options = new Map<String,Object>();
        
        inputMap.put('AccountId',ar.Account_To_Id__c);
        
        GPMSRelatedProviderController getGroupList = new GPMSRelatedProviderController();
        Boolean result = getGroupList.invokeMethod('fetchAcoGrpMember',inputMap,outMap,options);
        
        System.assertEquals(true, result);
        
    }
    
    @isTest static void testGPMSFetchSingleAcoGrpMember() {
        
        ACO_Group__c acoGroup = [SELECT Id FROM ACO_Group__c limit 1];
        
        Map<String,Object> inputMap = new Map<String,Object>();
        Map<String,Object> outMap = new Map<String,Object>();
        Map<String,Object> options = new Map<String,Object>();
        
        inputMap.put('AccountId',acoGroup.Id);
        
        GPMSRelatedProviderController getGroupList = new GPMSRelatedProviderController();
        Boolean result = getGroupList.invokeMethod('fetchSingleAcoGrpMember',inputMap,outMap,options);
        
        System.assertEquals(true, result);
        
    }
    
    @isTest static void testGPMSFetchAcoGrp() {
        
        Account_Relationship__c ar = [SELECT Id,Account_From_Id__c,Account_To_Id__c FROM Account_Relationship__c  limit 1];
        System.debug(ar);
        
        Map<String,Object> inputMap = new Map<String,Object>();
        Map<String,Object> outMap = new Map<String,Object>();
        Map<String,Object> options = new Map<String,Object>();
        
        inputMap.put('AccountId',ar.Account_To_Id__c);
        
        GPMSRelatedProviderController getGroupList = new GPMSRelatedProviderController();
        Boolean result = getGroupList.invokeMethod('fetchAcoGrp',inputMap,outMap,options);
        
        System.assertEquals(true, result);
        
    }
    
}