force-app/main/default/objects/Account/fields/Incorporated_Under__c.field-meta.xml
<CustomField>
    <fullName>Incorporated_Under__c</fullName>
    <description>INCORP_SPECIFIC_CODE, INCORP_SPECIFIC_CODE. ACO Incorporated Under list</description>
    <label>Incorporated Under</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Aboriginal Communities Act 1979 (WA)</fullName>
            </value>
            <value>
                <fullName>Aboriginal Land Act 1991 (QLD)</fullName>
            </value>
            <value>
                <fullName>Aboriginal Land Rights (Northern Territory) Act 1976</fullName>
            </value>
            <value>
                <fullName>Aboriginal Land Rights Act 1983 (NSW)</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia (Bodies Corporate) Act 1938 (NSW)</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia Act 1895 (Queensland)</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia Trust Property Act 1917</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia Trust Property Act 1917 (NSW)</fullName>
            </value>
            <value>
                <fullName>Anglican Church of Australia Trust Property Act 1928 (ACT)</fullName>
            </value>
            <value>
                <fullName>Anglican Trusts Corporations Act 1884 (VIC)</fullName>
            </value>
            <value>
                <fullName>Anglican Welfare Agency Act 1997 (VIC)</fullName>
            </value>
            <value>
                <fullName>Associations Act 2008 (NT)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1964 (TAS)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1981 (QLD)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1981 (VIC)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1984 (NSW)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1985 (SA)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1987 (WA)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 1991 (ACT)</fullName>
            </value>
            <value>
                <fullName>Associations Incorporation Act 2009 (NSW)</fullName>
            </value>
            <value>
                <fullName>Benevolent Society (Reconstitution) Act 1998 (NSW)</fullName>
            </value>
            <value>
                <fullName>Brotherhood of St. Laurence (Incorporation) Act 1971</fullName>
            </value>
            <value>
                <fullName>Canberra Institute of Technology Act 1987 ACT</fullName>
            </value>
            <value>
                <fullName>Charitable Collections Act (1934)</fullName>
            </value>
            <value>
                <fullName>Churches of Christ, Scientist, Incorporation Act 1964 (QLD)</fullName>
            </value>
            <value>
                <fullName>Community Services (Aborigines) Act 1984 (QLD)</fullName>
            </value>
            <value>
                <fullName>Companies Act 1899</fullName>
            </value>
            <value>
                <fullName>Companies Act 1961</fullName>
            </value>
            <value>
                <fullName>Co-operatives Act 1992 (NSW)</fullName>
            </value>
            <value>
                <fullName>Co-operatives Act 1997 (QLD)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_ID__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID__c</fullName>
    <description>CORPORATE_IDENTIFIER ACO Incorporation ID</description>
    <label>Incorporation ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_Status__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_Status__c</fullName>
    <description>ACO Incorporation Status</description>
    <label>Incorporation Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Association Strike Off Status</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>External Administration</fullName>
            </value>
            <value>
                <fullName>Non-Active</fullName>
            </value>
            <value>
                <fullName>Not available</fullName>
            </value>
            <value>
                <fullName>Not registered</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Strike-off action in progress</fullName>
            </value>
            <value>
                <fullName>To be advised</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prospective_Provider__c.field-meta.xml
<CustomField>
    <fullName>Prospective_Provider__c</fullName>
    <description>Likely to become a provider in the future</description>
    <label>Prospective Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/classes/AcfrInboundEmailServiceTest.cls
/****************************************************************************************************
 * @Description : Test Class for AcfrInboundEmailService
 *****************************************************************************************************/
@IsTest
public with sharing class AcfrInboundEmailServiceTest {
    
	
    @testSetup static void setup() {
        User testUser = TestDataFactory.createSystemAdminUser(); 
		System.runAs(testUser) {
        
            Account acc = new Account(
				Name = 'Test Account Company',
				Purpose__c = 'Government',
				Incorporated_Under__c = 'Associations Act 2008 (NT)',
				Incorporation_Status__c = 'Registered',
				Incorporation_ID_Type__c = 'Other',
				Prospective_Provider__c = 'No',
				Incorporation_ID__c = String.valueOf(
					(Integer) (Math.random() * 1000000000)
				),
				RecordTypeId = [
					SELECT Id
					FROM RecordType
					WHERE
						SobjectType = 'Account'
						AND IsActive = TRUE
						AND Name = 'Approved Provider'
					LIMIT 1
				]
				.Id
			);
			insert acc;
        
        Contact c=new Contact();
        c.firstName='Test';
        c.lastName='Last';
        c.email='test@test.com.au';
        c.AccountId=acc.id;
        c.Salutation='Mr';
        insert c;
            
        Case defaultCase=new Case();
        defaultCase.RecordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('QFR').getRecordTypeId();
    	defaultCase.Subject='QFR Unresolved Items';
        insert defaultCase;
        
        }

    }
   
    @IsTest
    static void TestEmailCreatedAndLinked() {
       
       Messaging.InboundEmail email = new Messaging.InboundEmail() ;
       Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
       List<string> emails = new List<string>{'testbandi@gmail.com','testbandi123@gmail.com'};
      
       email.subject = 'Create case';
       email.fromAddress = 'someaddress@email.com';
       email.toAddresses = emails;
       email.plainTextBody = 'email body Sender:(test@test.com.au<)';
       Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
       attachment.body = blob.valueOf('my attachment text');
       attachment.fileName = 'textfileone.txt';
       attachment.mimeTypeSubType = 'text/plain';
       email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
     
       AcfrInboundEmailService  testInbound=new AcfrInboundEmailService ();
       Test.startTest();
       testInbound.handleInboundEmail(email, env); 
       Test.stopTest();
        
        Case c=[select id from case where subject='QFR Unresolved Items' LIMIT 1];
        Task t=[select id,whatId from task where whatId=:c.id];
        
        
        System.assertEquals(t.WhatId, c.Id);
        
   		}
    
 

}