force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prospective_Provider__c.field-meta.xml
<CustomField>
    <fullName>Prospective_Provider__c</fullName>
    <description>Likely to become a provider in the future</description>
    <label>Prospective Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Aged_Care_Organisation.recordType-meta.xml
<RecordType>
    <fullName>Aged_Care_Organisation</fullName>
    <active>true</active>
    <description>Aged Care Organisation</description>
    <label>Aged Care Organisation</label>
</RecordType>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Accounts</label>
    <nameField>
        <displayFormat>ARL-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/Account_From_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_From_Id__c</fullName>
    <description>Parent account record to link another account record.</description>
    <label>Account From</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 AND 4) OR (1 AND 2)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account, Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation, Provider to Management Company, Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account From)</relationshipLabel>
    <relationshipName>Account_Relationship_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Account_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_To_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account To</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Management Company, Administrative Organisation, Service Delivery Organisation, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Management Company</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Management Company</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Delivery Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account To)</relationshipLabel>
    <relationshipName>Account_Relationship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/Address_Location__c.object-meta.xml
<CustomObject>
    <label>Address Location</label>
    <nameField>
        <displayFormat>ALN-{00000}</displayFormat>
        <label>Address Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Address Locations</relationshipLabel>
    <relationshipName>Address_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/fields/Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Relationship</label>
    <referenceTo>Contact_Relationship__c</referenceTo>
    <relationshipLabel>Address Locations</relationshipLabel>
    <relationshipName>Address_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipName>Service_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/recordTypes/AccountAddress.recordType-meta.xml
<RecordType>
    <fullName>AccountAddress</fullName>
    <active>true</active>
    <label>Account Address</label>
</RecordType>

force-app/main/default/objects/Address_Location__c/recordTypes/Physical.recordType-meta.xml
<RecordType>
    <fullName>Physical</fullName>
    <active>false</active>
    <label>Physical (dont use)</label>
</RecordType>

force-app/main/default/objects/Address_Location__c/recordTypes/ServiceAddress.recordType-meta.xml
<RecordType>
    <fullName>ServiceAddress</fullName>
    <active>true</active>
    <label>Service Address</label>
</RecordType>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Types</relationshipLabel>
    <relationshipName>Care_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact, Record Id of the related Contact record.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Contact Relationships</relationshipLabel>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{00000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Places Tracker</description>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/fields/Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Relationship</label>
    <referenceTo>Contact_Relationship__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/GPMSTestUtility.cls
public with sharing class GPMSTestUtility {
    
    public static Account getAccountByRecordType(String recordTypeName){
        
        Account provider = new Account(Name = 'Provider',Incorporation_ID_Type__c='Taken to be Incorporated',Prospective_Provider__c='');
        provider.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
        provider.Purpose__c = 'Government';
        return provider;
        
    }
    
    public static Account getACOAccount(){
        
        Account aco = new Account(Name = 'ACO',Incorporation_ID_Type__c='Not Incorporated',Prospective_Provider__c='');
        aco.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Aged_Care_Organisation').getRecordTypeId();
        return aco;
        
    }
    
    public static Contact getContact(){
        
        String recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('GPMS Contact').getRecordTypeId();
        Contact contact = new Contact();
        contact.salutation = 'Miss';
        contact.RecordTypeId = recordTypeId;
        contact.FirstName = 'First';
        contact.LastName = 'Last';
        contact.Birthdate = System.today().addYears(-20);        
        return contact;
        
    }
    
    public static Account_Relationship__c getAccountRelationship(String recordTypeName,Id accountFrom, Id accountTo){
        
        Account_Relationship__c accountRelationship = new Account_Relationship__c();
        accountRelationship.recordTypeId = Schema.SObjectType.Account_Relationship__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
        accountRelationship.Account_From_Id__c = accountFrom;
        accountRelationship.Account_To_Id__c = accountTo;
        
        return accountRelationship;
        
    }
    
    public static Contact_Relationship__c getContactRelationship(String recordTypeName, Id accountId, Id contactId){
        
        Contact_Relationship__c contactRelationship = new Contact_Relationship__c();
        contactRelationship.recordTypeId = Schema.SObjectType.Contact_Relationship__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
        contactRelationship.Account__c = accountId;
        contactRelationship.Contact__c = contactId;
        contactRelationship.Start_Date__c = System.today();
        
        return contactRelationship;
        
    }
    
    public static Contact_Relationship__c getServiceContactRelationship(String recordTypeName, Id serviceId, Id contactId){
        
        Contact_Relationship__c contactRelationship = new Contact_Relationship__c();
        contactRelationship.recordTypeId = Schema.SObjectType.Contact_Relationship__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
        contactRelationship.Service__c = serviceId;
        contactRelationship.Contact__c = contactId;
        contactRelationship.Start_Date__c = System.today();
        
        return contactRelationship;
        
    }

    public static Address__c getAddress(){
        
        Address__c address = new Address__c();
        return address;
        
    }

    public static Address_Location__c getAccountAddress(Id addressId, Id accountId){
        
        Address_Location__c location = new Address_Location__c();
        location.Address__c = addressId;
        location.Account__c = accountId;
        location.Location_Type__c = 'Physical';
        location.recordTypeId = Schema.SObjectType.Address_Location__c.getRecordTypeInfosByDeveloperName().get('AccountAddress').getRecordTypeId();
        return location;
        
    }
    
    public static Address_Location__c getServiceAddress(Id addressId, Id serviceId){
        
        Address_Location__c location = new Address_Location__c();
        location.Address__c = addressId;
        location.Service__c = serviceId;
        location.Location_Type__c = 'Physical';
        location.recordTypeId = Schema.SObjectType.Address_Location__c.getRecordTypeInfosByDeveloperName().get('ServiceAddress').getRecordTypeId();
        return location;
        
    }
    
    public static BusinessLicense getServiceByRecordType(String recordType){
        
        BusinessLicense service = new BusinessLicense();
        service.Name = 'Test' + String.valueOf(System.now());
        service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get(recordType).getRecordTypeId();
        service.Care_Type__c = 'Home Care';
        service.Status__c = 'Inactive';
        service.Status_Date__c = Date.today();
        return service;
        
    }
    
    public static Allotment__c getAllotment(String recordType, String serviceId){
        
        Allotment__c Allotment = new Allotment__c(Service_Name__c = serviceId);
        Allotment.recordTypeId = Schema.SObjectType.Allotment__c.getRecordTypeInfosByDeveloperName().get(recordType).getRecordTypeId();
        return Allotment;
        
    }
    
    public static List<Places_Allotment__c> getPlaces(Integer recordCount, String allotmentId){
        List<Places_Allotment__c> places = new List<Places_Allotment__c>();
        for(Integer i = 0; i< recordCount; i++){
            Places_Allotment__c place = new Places_Allotment__c(Allotment__c = allotmentId);
            place.Care_Level__c = '';
            place.Care_Type__c = '';
            place.Number_of_Places__c = 10;
            place.Current__c = 'Yes';
            places.add(place);
        }
        return places;
    }
    
    public static Event__c getPlaceEvent(String recordType){
        
        Event__c evt = new Event__c();
        evt.recordTypeId = Schema.SObjectType.Event__c.getRecordTypeInfosByDeveloperName().get(recordType).getRecordTypeId();
        return evt;
        
    }

}