force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incorporation_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_Type__c</fullName>
    <description>INCORP_TYPE_CODE ACO Incorporation Type list</description>
    <label>Incorporation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Australian Proprietary Company</fullName>
            </value>
            <value>
                <fullName>Australian Public Company</fullName>
            </value>
            <value>
                <fullName>Australian Registered Body</fullName>
            </value>
            <value>
                <fullName>Foreign Company (Overseas)</fullName>
            </value>
            <value>
                <fullName>Own Legislation</fullName>
            </value>
            <value>
                <fullName>BLANK</fullName>
            </value>
            <value>
                <fullName>Incorporated Association</fullName>
            </value>
            <value>
                <fullName>Indigenous Corporation</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Local Government</fullName>
            </value>
            <value>
                <fullName>State Government</fullName>
            </value>
            <value>
                <fullName>State Government Statutory Authority</fullName>
            </value>
            <value>
                <fullName>Territory Government</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Aged_Care_Organisation.recordType-meta.xml
<RecordType>
    <fullName>Aged_Care_Organisation</fullName>
    <active>true</active>
    <description>Aged Care Organisation</description>
    <label>Aged Care Organisation</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Management_Company.recordType-meta.xml
<RecordType>
    <fullName>Management_Company</fullName>
    <active>true</active>
    <description>Management Company</description>
    <label>Management Company</label>
</RecordType>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Accounts</label>
    <nameField>
        <displayFormat>ARL-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/recordTypes/ACO_to_Account.recordType-meta.xml
<RecordType>
    <fullName>ACO_to_Account</fullName>
    <active>true</active>
    <label>ACO to Account</label>
</RecordType>

force-app/main/default/objects/Account_Relationship__c/recordTypes/Provider_to_Management_Company.recordType-meta.xml
<RecordType>
    <fullName>Provider_to_Management_Company</fullName>
    <active>true</active>
    <label>Provider to Management Company</label>
</RecordType>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{00000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Location__c/Address_Location__c.object-meta.xml
<CustomObject>
    <label>Address Location</label>
    <nameField>
        <displayFormat>ALN-{00000}</displayFormat>
        <label>Address Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/fields/Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Relationship</label>
    <referenceTo>Contact_Relationship__c</referenceTo>
    <relationshipLabel>Address Locations</relationshipLabel>
    <relationshipName>Address_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/recordTypes/Key_Personnel_CR.recordType-meta.xml
<RecordType>
    <fullName>Key_Personnel_CR</fullName>
    <active>true</active>
    <label>Key Personnel</label>
</RecordType>

force-app/main/default/classes/GPMSAccountPayloadResponseTest.cls
@IsTest
public class GPMSAccountPayloadResponseTest {
    
    private static User currentUser = TestDataFactory.createGPMSTestUser();
    
    @testSetup static void setup() {
        
        System.runAs(currentUser){
        
            List<Account> accountToInsert = new List<Account>();
            
            Account apaccount = new Account();
            apaccount = GPMSTestUtility.getAccountByRecordType('Approved_Provider');
            apaccount.Incorporation_ID_Type__c = 'IAN';
            
            Account tpoaccount = new Account();
            tpoaccount = GPMSTestUtility.getAccountByRecordType('Management_Company');
            tpoaccount.Incorporation_ID_Type__c = 'IAN';
            tpoaccount.Incorporation_Type__c = 'Incorporated Association';
            
            accountToInsert.add(GPMSTestUtility.getACOAccount());
            accountToInsert.add(apaccount);
            accountToInsert.add(tpoaccount);
            insert accountToInsert;
            
            Contact contactToInsert = GPMSTestUtility.getContact();
            insert contactToInsert;
            
            Account aco = [SELECT Id FROM Account Where RecordType.DeveloperName = 'Aged_Care_Organisation' limit 1];
            Account ap = [SELECT Id FROM Account Where RecordType.DeveloperName = 'Approved_Provider' limit 1];
            Account tpo = [SELECT Id FROM Account Where RecordType.DeveloperName = 'Management_Company' limit 1];
            
            List<Account_Relationship__c> accountRelationshipToInsert = new List<Account_Relationship__c>();
            accountRelationshipToInsert.add(GPMSTestUtility.getAccountRelationship('ACO_to_Account',aco.Id,ap.Id));
            accountRelationshipToInsert.add(GPMSTestUtility.getAccountRelationship('Provider_to_Management_Company',ap.Id,tpo.Id));
            insert accountRelationshipToInsert;
            
            ap.Name = 'Name Update';
            update ap;
            
            contactToInsert.LastName = 'Update';
            update contactToInsert;
            
            Contact_Relationship__c contactRelationshipToInsert = GPMSTestUtility.getContactRelationship('Key_Personnel_CR',ap.Id,contactToInsert.Id);
            insert contactRelationshipToInsert;
            
            Address__c address = GPMSTestUtility.getAddress();
            insert address;
            
            Address_Location__c accountLocation = GPMSTestUtility.getAccountAddress(address.Id,ap.Id);
            insert accountLocation;
            
        }
        
    }
    
    @isTest static void testGPMSAccountPayload() {

        Account ap = [SELECT Id FROM Account Where RecordType.DeveloperName = 'Approved_Provider' limit 1];

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GPMS/Account/' + ap.Id ;  //Request URL
        req.httpMethod = 'GET';//HTTP Request Type
        
        System.runAs(currentUser){
            Test.startTest();
        	
            RestContext.request = req;
            RestContext.response= res;
            GPMSAccountPayload payload = GPMSAccountPayloadResponse.getAccountPayload();
            
            System.assertEquals(payload.accountId, ap.Id, 'Did not get expected Account by Id');
            
            Test.stopTest();
        }

    }

}