force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Aged_Care_Organisation.recordType-meta.xml
<RecordType>
    <fullName>Aged_Care_Organisation</fullName>
    <active>true</active>
    <description>Aged Care Organisation</description>
    <label>Aged Care Organisation</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Commonwealth_Home_Support_Programme.recordType-meta.xml
<RecordType>
    <fullName>Commonwealth_Home_Support_Programme</fullName>
    <active>true</active>
    <description>Commonwealth Home Support Programme</description>
    <label>Commonwealth Home Support Programme</label>
</RecordType>

force-app/main/default/objects/Account_Relationship__c/Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Accounts</label>
    <nameField>
        <displayFormat>ARL-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Relationship__c/fields/Account_From_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_From_Id__c</fullName>
    <description>Parent account record to link another account record.</description>
    <label>Account From</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 AND 4) OR (1 AND 2)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account, Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation, Provider to Management Company, Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account From)</relationshipLabel>
    <relationshipName>Account_Relationship_From</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Account_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_To_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account To</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ACO to Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Management Company, Administrative Organisation, Service Delivery Organisation, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation Owner and Owned</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aged Care Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Administrative Organisation</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Management Company</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Management Company</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Provider to Service Delivery Organisation</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service Delivery Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Relationships (Account To)</relationshipLabel>
    <relationshipName>Account_Relationship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Association_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Association_End_Date__c</fullName>
    <label>Association End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Relationship__c/recordTypes/ACO_to_Account.recordType-meta.xml
<RecordType>
    <fullName>ACO_to_Account</fullName>
    <active>true</active>
    <label>ACO to Account</label>
</RecordType>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/CHSP_Service.recordType-meta.xml
<RecordType>
    <fullName>CHSP_Service</fullName>
    <active>true</active>
    <label>CHSP Service</label>
</RecordType>

force-app/main/default/objects/CHSP_Service_Schedule__c/CHSP_Service_Schedule__c.object-meta.xml
<CustomObject>
    <label>CHSP Schedule Detail</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CHSP Schedule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Schedule Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CHSP Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Commonwealth Home Support Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CHSP Schedule Details</relationshipLabel>
    <relationshipName>CHSP_Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>CHSP Service Schedules</relationshipLabel>
    <relationshipName>CHSP_Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_with_CHSP_Schedule_Detail__c/Service_with_CHSP_Schedule_Detail__c.object-meta.xml
<CustomObject>
    <label>Service with CHSP Schedule Detail</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Service with CHSP Schedule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service with CHSP Schedule Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_with_CHSP_Schedule_Detail__c/fields/CHSP_Schedule_Detail__c.field-meta.xml
<CustomField>
    <fullName>CHSP_Schedule_Detail__c</fullName>
    <label>CHSP Schedule Detail</label>
    <referenceTo>CHSP_Service_Schedule__c</referenceTo>
    <relationshipLabel>Service with CHSP Schedule Details</relationshipLabel>
    <relationshipName>Service_with_CHSP_Schedule_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_with_CHSP_Schedule_Detail__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service with CHSP Schedule Details</relationshipLabel>
    <relationshipName>Service_with_CHSP_Schedule_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GPMSScheduledUpdateCHSPServiceBatchTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-14-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class GPMSScheduledUpdateCHSPServiceBatchTest {
    @testSetup static void setup() 
    {             
       User gpmsUser = TestDataFactory.createGPMSTestUser();
       System.runAs(gpmsUser)
       {
           Test.startTest();
           Account chspProvider = new Account(Name = 'ProviderA',Incorporation_ID_Type__c='Other');
           chspProvider.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commonwealth_Home_Support_Programme').getRecordTypeId();
           Insert chspProvider;
           
           CHSP_Service_Schedule__c chspSchDetA = new CHSP_Service_Schedule__c(Organisation_Name__c = chspProvider.Id,Contract_End_Date__c = System.today());
           insert chspSchDetA;
           CHSP_Service_Schedule__c chspSchDetB = new CHSP_Service_Schedule__c(Organisation_Name__c = chspProvider.Id,Contract_End_Date__c = System.today());
           insert chspSchDetB;
           
           Account aco = new Account(Name = 'ACO',Incorporation_ID_Type__c='Not Incorporated');
           aco.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Aged_Care_Organisation').getRecordTypeId();
           Insert aco;
            
           Account_Relationship__c acoRole = new Account_Relationship__c(Account_From_Id__c = aco.Id,Account_To_Id__c = chspProvider.Id,Association_End_Date__c = System.today() + 1);
           acoRole.recordTypeId = Schema.SObjectType.Account_Relationship__c.getRecordTypeInfosByDeveloperName().get('ACO_to_Account').getRecordTypeId();
           insert acoRole;  
                   
           BusinessLicense service = new BusinessLicense(Name = 'CHSP Service',AccountId = chspProvider.Id);
           service.recordTypeId = Schema.SObjectType.BusinessLicense.getRecordTypeInfosByDeveloperName().get('CHSP_Service').getRecordTypeId();
           service.Status_Date__c =  Date.today();
           insert service;
                    
           Service_with_CHSP_Schedule_Detail__c serviceCHSPSchDetA = new Service_with_CHSP_Schedule_Detail__c(Service__c = service.Id,CHSP_Schedule_Detail__c = chspSchDetA.Id);
           insert serviceCHSPSchDetA;
           Service_with_CHSP_Schedule_Detail__c serviceCHSPSchDetB = new Service_with_CHSP_Schedule_Detail__c(Service__c = service.Id,CHSP_Schedule_Detail__c = chspSchDetB.Id);
           insert serviceCHSPSchDetB;
           Test.stopTest();
       }
    }
    static testmethod void testGPMSScheduledBatch_UpdateCHSPService()
    {
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        System.runAs(gpmsUser)
        {
            Test.startTest();
            GPMSScheduledUpdateCHSPServiceBatch serviceStatusUpdateBatch =  new GPMSScheduledUpdateCHSPServiceBatch();
            Database.executeBatch(serviceStatusUpdateBatch,2);   
            Test.stopTest();
        }
        
        BusinessLicense serviceAfterUpdate = [SELECT Id,Status__c FROM BusinessLicense limit 1]; 
        
        system.assertEquals('Inactive',serviceAfterUpdate.Status__c);        
    }
    static testmethod void testGPMSScheduledBatch_UpdateCHSPServiceManualExecution()
    {
        List<CHSP_Service_Schedule__c> chspSchDetList = [SELECT Id,Contract_End_Date__c FROM CHSP_Service_Schedule__c limit 2];
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        System.runAs(gpmsUser)
        {
            Test.startTest();
            Set<Id> recIdSet = new Set<Id>{chspSchDetList[0].Id,chspSchDetList[1].Id};
            GPMSScheduledUpdateCHSPServiceBatch.executeByIds(recIdSet,2); 
            Test.stopTest();
        }
        
        BusinessLicense serviceAfterUpdate = [SELECT Id,Status__c FROM BusinessLicense limit 1]; 
                
        system.assertEquals('Inactive',serviceAfterUpdate.Status__c);        
    }

}