force-app/main/default/objects/Account/fields/Incorporation_ID_Type__c.field-meta.xml
<CustomField>
    <fullName>Incorporation_ID_Type__c</fullName>
    <description>IDENTIFIER_TYPE ACO Incorporation ID Type</description>
    <inlineHelpText>Taken to be Incorporated should only be selected if you are a Government Organisation</inlineHelpText>
    <label>Incorporation ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACN</fullName>
            </value>
            <value>
                <fullName>ARBN</fullName>
            </value>
            <value>
                <fullName>IAN</fullName>
            </value>
            <value>
                <fullName>ICN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Incorporated</fullName>
            </value>
            <value>
                <fullName>Taken to be Incorporated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Party_ID__c.field-meta.xml
<CustomField>
    <fullName>Party_ID__c</fullName>
    <description>Primary key to link the Provider Record to GovGPS Record</description>
    <label>Party ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prospective_Provider__c.field-meta.xml
<CustomField>
    <fullName>Prospective_Provider__c</fullName>
    <description>Likely to become a provider in the future</description>
    <label>Prospective Provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Commonwealth_Home_Support_Programme.recordType-meta.xml
<RecordType>
    <fullName>Commonwealth_Home_Support_Programme</fullName>
    <active>true</active>
    <description>Commonwealth Home Support Programme</description>
    <label>Commonwealth Home Support Programme</label>
</RecordType>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/CHSP_Service_Activity_Work_Plan_Record__c.object-meta.xml
<CustomObject>
    <label>CHSP Service Activity Work Plan Record</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>CHSP Service AWP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Service Activity Work Plan Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/fields/CHSP_Service_Schedule__c.field-meta.xml
<CustomField>
    <fullName>CHSP_Service_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CHSP Service Schedule</label>
    <referenceTo>CHSP_Service_Schedule__c</referenceTo>
    <relationshipName>CHSP_Service_Activity_Work_Plan_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/fields/Service_Care_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Care_Sub_Type__c</fullName>
    <label>Service Care Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Activity_Work_Plan_Record__c/fields/Service_Type_Level__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Level__c</fullName>
    <label>Service Type Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Schedule__c/CHSP_Service_Schedule__c.object-meta.xml
<CustomObject>
    <label>CHSP Schedule Detail</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CHSP Schedule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Schedule Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <label>Party Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GPMSCHSPLinkServiceScheduleTest.cls
@IsTest
public class GPMSCHSPLinkServiceScheduleTest {
    
    private static User currentUser = [SELECT Id From User WHERE Id = :UserInfo.getUserId()];
    
    @IsTest
    static void testPositive(){
        
        System.runAs(currentUser){
            Test.startTest();
            
            GPMSCHSPLinkServiceSchedule s = new GPMSCHSPLinkServiceSchedule();
            String sch = '00 40 09 ? * *';
            String jobId = System.schedule('Test GPMSCHSPLinkServiceSchedule', sch, s);
            
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                              NextFireTime
                              FROM CronTrigger WHERE id = :jobId];
            
            System.assertEquals(sch, ct.CronExpression);
            
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testException(){
        
        System.runAs(currentUser){
            Test.startTest();
            
            GPMSCHSPLinkServiceBatch linkServicebatch;
            
            GPMSCHSPLinkServiceSchedule s = new GPMSCHSPLinkServiceSchedule(linkServicebatch);
            String sch = '00 40 09 ? * *';
            
            String jobId = System.schedule('Test GPMSCHSPLinkServiceSchedule', sch, s);
            
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                              NextFireTime
                              FROM CronTrigger WHERE id = :jobId];
            
            System.assertEquals(sch, ct.CronExpression);
            
            Test.stopTest();
        }
    }
    //@IsTest
    static void setup(){
        //account
        
        Account aco = new Account(Name = 'ACO Service',Incorporation_ID_Type__c='Not Incorporated',Prospective_Provider__c='');
        aco.Party_Id__c = '1112';
        aco.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commonwealth_Home_Support_Programme').getRecordTypeId();
        insert aco;
        
        //service detail
        CHSP_Service_Schedule__c scheduleDetail = new CHSP_Service_Schedule__c();
        scheduleDetail.Party_Id__c = '1112';
        scheduleDetail.Service_Type_Level__c = 'Allied Health and Therapy Services';
        insert scheduleDetail;
        
        //service activity work plan
        CHSP_Service_Activity_Work_Plan_Record__c awp = new CHSP_Service_Activity_Work_Plan_Record__c();
        awp.Service_Type_Level__c = 'Allied Health and Therapy Services';
        awp.Service_Care_Sub_Type__c = 'Community and Home Support';
        awp.CHSP_Service_Schedule__c = scheduleDetail.Id;
        awp.Activity_Status__c = 'Approved';
        awp.Service_Care_Sub_Type__c = 'Community and Home Support';
        insert awp;
    }
}