force-app/main/default/objects/Account/fields/Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Integration_ID__c</fullName>
    <externalId>true</externalId>
    <label>Integration ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/Case/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provider Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AcfrCreateQuaterlyCasesAndFormsScheduler.cls
/*------------------------------------------------------------------------------------------------
Author:         Pinali Patel
Description:    This class will be the Batch class and Scheduler class for bulk case and form creation functionality.
************************************************************************************************
History
************************************************************************************************
 * @TestClass AcfrCreateQuaterlyCasesAndFormsTest
--------------------------------------------------------------------------------------------------*/
public with sharing class AcfrCreateQuaterlyCasesAndFormsScheduler implements Schedulable, Database.Batchable<sObject> {
	List<Account> accountList = new List<Account>();
	public AcfrCreateQuaterlyCasesAndFormsScheduler(List<Account> accounts) {
		this.accountList = accounts;
	}

	public AcfrCreateQuaterlyCasesAndFormsScheduler() {
	}
	public void execute(SchedulableContext context) {
		Database.executebatch(this, 30);
	}
	public Database.QueryLocator start(Database.BatchableContext bc) {
		Id approvedProvider = Schema.Account.getSObjectType()
			.getDescribe()
			.getRecordTypeInfosByDeveloperName()
			.get('Approved_Provider')
			.getRecordTypeId();

		if (this.accountList.isEmpty()) {
			return Database.getQueryLocator(
				[
					SELECT
						Id,
						Purpose__c,
						RecordType.Name,
						Name,
						Integration_ID__c,
						RecordType.SobjectType
					FROM Account
					WHERE
						RecordType.Name = 'Approved Provider'
						AND RecordType.SobjectType = 'Account'
						AND Id IN (
							SELECT Provider_name__c
							FROM Service_Account_Relationship__c
						)
				]
			);
		} else {
			return Database.getQueryLocator(
				[
					SELECT
						Id,
						Purpose__c,
						RecordType.Name,
						Name,
						Integration_ID__c,
						RecordType.SobjectType
					FROM Account
					WHERE Id IN :this.accountList
				]
			);
		}
	}

	public void execute(
		Database.BatchableContext bc,
		List<Account> accountList
	) {
		AcfrCreateQuaterlyCasesAndFormsService createCasesAndForms = new AcfrCreateQuaterlyCasesAndFormsService(
			accountList
		);
		createCasesAndForms.performAction();
	}

	public void finish(Database.BatchableContext bc) {
		List<String> jobStatus = new List<String>{
			'Aborted',
			'Completed',
			'Failed'
		};

		List<AsyncApexJob> glCodeLineItemBatchInProgress = [
			SELECT Id, ApexClass.Name, Status
			FROM AsyncApexJob
			WHERE
				ApexClass.Name = 'AcfrCreateQuaterlyGLCLineItemScheduler'
				AND Status NOT IN :jobStatus
		];
		if (glCodeLineItemBatchInProgress.size() == 0) {
			AcfrCreateQuaterlyGLCLineItemScheduler glCodeLineItemBatch = new AcfrCreateQuaterlyGLCLineItemScheduler();
			Database.executeBatch(
				glCodeLineItemBatch,
				AcfrCreateQuaterlyGLCLineItemScheduler.DEFAULT_BATCH_SIZE
			);
		}
	}
}