force-app/main/default/objects/Account/fields/Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Integration_ID__c</fullName>
    <externalId>true</externalId>
    <label>Integration ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Case_DM_Key__c.field-meta.xml
<CustomField>
    <fullName>Case_DM_Key__c</fullName>
    <externalId>true</externalId>
    <label>Case_DM_Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Assessment_Status__c.field-meta.xml
<CustomField>
    <fullName>QA_Assessment_Status__c</fullName>
    <label>QA Assessment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finalised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull from Reporting Perion Object.</description>
    <label>Reporting Period ID</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FA2SFCreateCases.cls
// This class is for the data migration of QFR data from Forms Admin.   The class creates Case records for each provider 
// for a specific Reporting Period.   Before execution you should change the Reporting Period Name (Line 20)
public with sharing class FA2SFCreateCases implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'select Id, Name, Integration_ID__c ' +
            'from Account ' +
            'where RecordType.Name = \'Approved Provider\'' +
             + ' or RecordType.Name = \'National Aboriginal and Torres Strait Islander Flexible Aged Care Program\'' +
             + ' or RecordType.Name = \'Commonwealth Home Support Programme\''
        );
    }
    public void execute(Database.BatchableContext bc, List<Account> lAccts){
    
      Id caseQFRRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('QFR').getRecordTypeId();
      
      //You will only ever get one single record in the Reporting_Period__c list due to the 'WHERE' clause
      ID sRPId;
      string sRPName;
      List<Reporting_Period__c> lRP = [SELECT Id, Name FROM Reporting_Period__c where Name = 'RP-162'];
      for(Reporting_Period__c thisRP: lRP)
      {
         sRPId = thisRP.Id;
         sRPName = thisRP.Name;
      }
          
    
        List<Case> newCases = new List<Case>();
        string sSubject;
    
            for(Account a : lAccts) {        
            // add a Case for each Provider Account for the Reporting Period
            sSubject = 'Migrated Case for Provider ' + a.Integration_ID__c + ' QFR Period : ' + sRPName;
            Case c = new Case(AccountId = a.Id, 
                              Subject=sSubject, 
                              RecordTypeId=caseQFRRecTypeId, 
                              Reporting_Period__c = sRPId, 
                              Status = 'Submitted', 
                              QA_Assessment_Status__c = 'Finalised',
                              Case_DM_Key__c = a.Integration_ID__c + sRPName,
                              Priority = 'Medium');

            newCases.add(c);
        }
    
        if(newCases != null && !newCases.isEmpty()){
          try{
              Database.insert(newCases, false);}
          catch(DmlException e) {
               dohagedcare.logger.error(e.getMessage(),e,'QFR').log();}
        }
  
        // process each batch of records
    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}