force-app/main/default/objects/Account/fields/Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Integration_ID__c</fullName>
    <externalId>true</externalId>
    <label>Integration ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Integration_ID__c</fullName>
    <formula>&apos;SRV-&apos;+IF(ISBLANK(Oracle_Service_ID__c),Service_Number__c,Oracle_Service_ID__c)</formula>
    <label>Integration ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Integration_ID__c.field-meta.xml
<CustomField>
    <fullName>Integration_ID__c</fullName>
    <formula>&apos;CON&apos;+&apos;-&apos;+if(ISBLANK(TEXT( Oracle_ID__c )),Contact_ID__c,TEXT( Oracle_ID__c ))</formula>
    <label>Integration ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test only</description>
    <label>Service Account Relationship</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Account_Relationship__c.Provider_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Short__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Short__c</fullName>
    <description>Shortened version or Reporting Period to match Siebel</description>
    <formula>IF( ISPICKVAL(Reporting_Period_Type__c, &apos;Quarter&apos;),
&apos;Quarter &apos; &amp;
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3 ,&apos;3&apos;,
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6 ,&apos;4&apos;,
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9 ,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12 ,&apos;2&apos;,null) ) ) ) &amp;
&apos; FY &apos; &amp;
IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1), 2),
RIGHT( TEXT(YEAR(Start_Date__c)), 2)) &amp; &apos; - &apos; &amp;
IF(MONTH(End_Date__c) &gt;= 7, RIGHT( TEXT(YEAR(End_Date__c) +1), 2),
RIGHT( TEXT(YEAR(End_Date__c)), 2)),

TEXT(YEAR(Start_Date__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporting Period Short</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Publish</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
                <isActive>false</isActive>
                <label>Archive</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/SRQI_CER__c.object-meta.xml
<CustomObject>
    <label>Consumer Experience Report</label>
    <nameField>
        <displayFormat>CER-{000000}</displayFormat>
        <label>Consumer Experience Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Experience Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_CER__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Consumer_Experience_Id__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Experience_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer Experience Report</label>
    <referenceTo>SRQI_CER__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Service_Compliance_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Compliance_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Compliance</label>
    <referenceTo>Service_Compliance_History__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/STAR_Rating_Calculation__c.field-meta.xml
<CustomField>
    <fullName>STAR_Rating_Calculation__c</fullName>
    <label>STAR Rating Calculation</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of Star Rating calculation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availability_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Availability_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Published</fullName>
    </customValue>
    <customValue>
        <fullName>LIVE</fullName>
    </customValue>
    <customValue>
        <fullName>Removed</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review/On Hold</fullName>
        <isActive>false</isActive>
        <label>Under Review/On Hold</label>
    </customValue>
    <description>Status for Overall &amp; subcategory StarRatings</description>
    <masterLabel>Availability Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SrqiSearchStarRatingTest.cls
/**
 * @auther Rami Zuhairi
 * @date 30-09-2022
 * @description Test class to cover srqiSearchStarRating apex class
 */
@isTest
private class SrqiSearchStarRatingTest {
    @TestSetup private static void setupData() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
            Integer recordCount = 10;
            // get reporting period
            Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod(
                'Quarter'
            );
            insert rPeriod;
            // get providers
            List<Account> providers = TestDataFactory.createProviderRecords(
                recordCount
            );
            insert providers;
            // get services
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(
                recordCount
            );
            for (Integer i = 0; i < recordCount; i++) {
                services[i].AccountId = providers[i].Id;
            }
            insert services;
            Test.getEventBus().deliver();
            // get provide contacts
            List<Contact> providerContacts = TestDataFactory.createContact(
                recordCount,
                providers
            );
            insert providerContacts;
            List<User> providerPortalUsers = TestDataFactory.createProviderPortalUser(
                recordCount,
                providerContacts
            );
            // get service account relationships
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(
                recordCount,
                services,
                providers
            );
            insert serviceAccountRecords;
            // get consumer experience reports
            List<SRQI_CER__c> cerRecords = TestDataFactory.createCERRecords(
                recordCount,
                serviceAccountRecords,
                providers,
                services,
                rPeriod
            );
            insert cerRecords;
            // get ViolationTypes records
            List<ViolationType> violationTypeRecords = TestDataFactory.createQIViolationType(
                recordCount
            );
            insert violationTypeRecords;

            // get RegulatoryCodeViolation records
            List<RegulatoryCodeViolation> regulatoryCodeViolationRecords = TestDataFactory.createQIRegulatoryCodeViolation(
                recordCount,
                services,
                providers,
                violationTypeRecords,
                serviceAccountRecords
            );
            insert regulatoryCodeViolationRecords;
            // get service compliance history
            List<Service_Compliance_History__c> schRecords = TestDataFactory.createServiceComplianceHistory(
                recordCount
            );
            insert schRecords;
            // get star rating history records
            List<STAR_Rating_History__c> srhRecords = TestDataFactory.createStarRatingHistoryRecords(
                recordCount,
                services,
                providers,
                rPeriod
            );
            for (Integer i = 0; i < srhRecords.size(); i++) {
                srhRecords[i].Service_Account_Relationship__c = serviceAccountRecords[i].Id;
                srhRecords[i].Consumer_Experience_Id__c = cerRecords[i].Id;
                srhRecords[i].Service_Compliance_Id__c = schRecords[i].Id;
                srhRecords[i].Rating_Type__c = Math.mod(i, 2) == 0
                    ? 'New Rating'
                    : 'Current Rating';
                srhRecords[i].Status__c = Math.mod(i, 2) == 0
                    ? 'Published'
                    : 'Live';
                srhRecords[i].STAR_Rating_Calculation__c = Math.mod(i, 2) == 0
                    ? 2
                    : 5;

            }
            insert srhRecords;
            // Create public groups
            List<Group> serviceGroups = new List<Group>();
            for (BusinessLicense rec : services) {
                Group grp = new Group(Name = 'SRV_' + rec.Id, DoesIncludeBosses = false);
                serviceGroups.add(grp);
            }
            insert serviceGroups;
            Map<Id, String> accountToGroupName = new Map<Id, String>();
            Map<Id, Account> accountMap = new Map<Id, Account>(providers);
            for (BusinessLicense service : [

                SELECT Id, AccountId
                FROM BusinessLicense
                WHERE AccountId IN :accountMap.keySet()
            ]) {
                accountToGroupName.put(service.AccountId, 'SRV_' + service.Id);
            }
            Map<String, Id> groupNameToGroupIdMap = new Map<String, Id>();
            for (Group g : [
                SELECT Id, DeveloperName
                FROM Group
                WHERE DeveloperName IN :accountToGroupName.values()
            ]) {
                groupNameToGroupIdMap.put(g.DeveloperName, g.Id);
            }
            List<GroupMember> groupMembers = new List<GroupMember>();
            for (Integer i = 0; i < recordCount; i++) {
                GroupMember gm = new GroupMember(
                    GroupId = groupNameToGroupIdMap.get(
                        accountToGroupName.get(providers[i].Id)
                    ),
                    UserOrGroupId = providerPortalUsers[i].Id
                );
                groupMembers.add(gm);
            }
            insert groupMembers;


        }
        Test.stopTest();
    }

    @isTest
    private static void testGetFilterValuesAndDefaultSearchResults() {
        Test.startTest();
        // When
        System.runAs(getProviderPortalUser()) {
            Map<String, Object> results = SrqiSearchStarRating.getFilterValuesAndDefaultSearchResults();
            // Then
            System.assertEquals(1, ((Set<String>) results.get('reportingPeriods')).size(), 'Expected reportingPeriods size to match');
            System.assertEquals(1, ((Set<String>) results.get('statuses')).size(), 'Expected statuses size to match');
            System.assertEquals(1, ((Set<String>) results.get('ratingTypes')).size(), 'Expected ratingTypes size to match');
            System.assertEquals(1, ((List<String>) results.get('ratings')).size(), 'Expected ratings size to match');
            System.assertEquals(1, ((List<STAR_Rating_History__c>) results.get('defaultSearchResults')).size(), 'Expected defaultSearchResults size to match');
        }
        Test.stopTest();
    }

    @isTest
    private static void testSearchStarRatingHistoriesByReportingPeriod() {
        //Given
        String reportingPeriod = [SELECT Reporting_Period_Short__c FROM Reporting_Period__c LIMIT 1].Reporting_Period_Short__c;
        SrqiSearchStarRating.SearchConfig searchConfig = new SrqiSearchStarRating.SearchConfig();
        searchConfig.reportingPeriods.add(reportingPeriod);
        searchConfig.ratingTypes.add('New');
        Test.startTest();
        // When
        System.runAs(getProviderPortalUser()) {
            List<STAR_Rating_History__c> results = SrqiSearchStarRating.searchStarRatingHistories(searchConfig);
            // Then
            Assert.areEqual(1, results.size(), 'Expected results size to match');
        }
        Test.stopTest();
    }

    @isTest
    private static void testSearchStarRatingHistoriesByRatingType() {
        //Given
        SrqiSearchStarRating.SearchConfig searchConfig = new SrqiSearchStarRating.SearchConfig();
        searchConfig.ratingTypes.add('New');
        Test.startTest();
        // When
        System.runAs(getProviderPortalUser()) {
            List<STAR_Rating_History__c> results = SrqiSearchStarRating.searchStarRatingHistories(searchConfig);
            // Then
            Assert.areEqual(1, results.size(), 'Expected results size to match');
        }
        Test.stopTest();
    }

    @isTest
    private static void testSearchStarRatingHistoriesByStatus() {
        //Given
        SrqiSearchStarRating.SearchConfig searchConfig = new SrqiSearchStarRating.SearchConfig();
        searchConfig.statuses.add('Preview');
        Test.startTest();
        // When
        System.runAs(getProviderPortalUser()) {
            List<STAR_Rating_History__c> results = SrqiSearchStarRating.searchStarRatingHistories(searchConfig);
            // Then
            Assert.areEqual(1, results.size(), 'Expected results size to match');
        }
        Test.stopTest();
    }

    @isTest
    private static void testSearchStarRatingHistoriesByOverallRating() {
        //Given
        SrqiSearchStarRating.SearchConfig searchConfig = new SrqiSearchStarRating.SearchConfig();
        searchConfig.ratings.add('2');
        Test.startTest();
        // When
        System.runAs(getProviderPortalUser()) {
            List<STAR_Rating_History__c> results = SrqiSearchStarRating.searchStarRatingHistories(searchConfig);
            // Then
            Assert.areEqual(1, results.size(), 'Expected results size to match');
        }
        Test.stopTest();
    }

    @isTest
    private static void testSearchStarRatingHistoriesByServiceName() {
        //Given
        SrqiSearchStarRating.SearchConfig searchConfig = new SrqiSearchStarRating.SearchConfig();
        searchConfig.serviceNamesOrIds = 'Service Test 0';
        Test.startTest();
        // When
        System.runAs(getProviderPortalUser()) {
            List<STAR_Rating_History__c> results = SrqiSearchStarRating.searchStarRatingHistories(searchConfig);
            // Then
            Assert.areEqual(1, results.size(), 'Expected results size to match');
        }
        Test.stopTest();
    }


    @isTest
    private static void testSearchStarRatingHistoriesByServiceId() {
        //Given
        String serviceId = [SELECT Integration_ID__c FROM BusinessLicense WHERE Name = 'Service Test 0'].Integration_ID__c;
        SrqiSearchStarRating.SearchConfig searchConfig = new SrqiSearchStarRating.SearchConfig();
        searchConfig.serviceNamesOrIds = serviceId;
        Test.startTest();
        // When
        System.runAs(getProviderPortalUser()) {
            List<STAR_Rating_History__c> results = SrqiSearchStarRating.searchStarRatingHistories(searchConfig);
            // Then
            Assert.areEqual(1, results.size(), 'Expected results size to match');
        }
        Test.stopTest();
    }

    @isTest
    private static void testSearchStarRatingHistoriesNegative() {
        //Given
        SrqiSearchStarRating.SearchConfig searchConfig = new SrqiSearchStarRating.SearchConfig();
        searchConfig.serviceNamesOrIds = 'Test non-extsting';
        Test.startTest();
        // When
        System.runAs(getProviderPortalUser()) {
            List<STAR_Rating_History__c> results = SrqiSearchStarRating.searchStarRatingHistories(searchConfig);
            // Then
            Assert.areEqual(0, results.size(), 'Expected results size to match');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetServiceNameRecords() {
        Test.startTest();
        System.runAs(getProviderPortalUser()) {
            List<BusinessLicense> results = srqiSearchStarRating.getServiceNameRecords();
            System.assertEquals(1, results.size(), 'Expected results size to match');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetServiceNameIDRecord() {
        Test.startTest();
        System.runAs(getProviderPortalUser()) {
            String integrationID = [SELECT Id FROM BusinessLicense WHERE Name = 'Service Test 0'].Id;
            String returnedIntegrationID = srqiSearchStarRating.getServiceNameIDRecord('Service Test 0');
            System.assertEquals(integrationID, returnedIntegrationID, 'Expected integrationID to match');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetServiceNameIDRecordNegative() {
        Boolean hasError = false;
        Test.startTest();
        System.runAs(getProviderPortalUser()) {
            try {
                String returnedIntegrationID = srqiSearchStarRating.getServiceNameIDRecord('Test non-existence');
            } catch (AuraHandledException ex) {
                hasError = true;
            }
            System.assert(hasError, 'Expected error to occur');
        }
        Test.stopTest();
    }

    private static User getProviderPortalUser() {
        return [SELECT Id FROM User WHERE Username LIKE 'ProviderPortalTestClassUser0%' LIMIT 1];
    }
}