force-app/main/default/objects/Account/fields/NAPS_Service_Id__c.field-meta.xml
<CustomField>
    <fullName>NAPS_Service_Id__c</fullName>
    <description>This field is displayed in QI email template when the QI is submitted.</description>
    <label>NAPS Service Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PreviousReportingPeriodDueDt__c.field-meta.xml
<CustomField>
    <fullName>PreviousReportingPeriodDueDt__c</fullName>
    <description>This field is referenced in Classic Email Templates for sending QI Submission Reminders to the Providers</description>
    <label>PreviousReportingPeriodDueDt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PreviousReportingPeriodName__c.field-meta.xml
<CustomField>
    <fullName>PreviousReportingPeriodName__c</fullName>
    <description>This field is referenced in Classic Email Templates for sending QI Submission Reminders to the Providers</description>
    <label>PreviousReportingPeriodName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/QISubmissionDetails__c.field-meta.xml
<CustomField>
    <fullName>QISubmissionDetails__c</fullName>
    <description>This field is used to display the date on which QI is submitted,</description>
    <label>QISubmissionDetails</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ServiceNames__c.field-meta.xml
<CustomField>
    <fullName>ServiceNames__c</fullName>
    <description>This field is referenced in Classic Email Templates for sending QI Submission Reminders to the Providers. This field consists name of all the services linked to a Provider</description>
    <label>ServiceNames</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Oracle_Service_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Service_ID__c</fullName>
    <description>Migration value for APPROVAL_ID</description>
    <externalId>true</externalId>
    <label>Oracle Service ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/PreviousReportingPeriodDueDt__c.field-meta.xml
<CustomField>
    <fullName>PreviousReportingPeriodDueDt__c</fullName>
    <label>PreviousReportingPeriodDueDt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/PreviousReportingPeriodName__c.field-meta.xml
<CustomField>
    <fullName>PreviousReportingPeriodName__c</fullName>
    <description>It will store the reporting period name for QI notifications</description>
    <label>PreviousReportingPeriodName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PreviousReportingPeriodDueDt__c.field-meta.xml
<CustomField>
    <fullName>PreviousReportingPeriodDueDt__c</fullName>
    <description>This field is displayed in email template for QI Service Role Users</description>
    <label>PreviousReportingPeriodDueDt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PreviousReportingPeriodName__c.field-meta.xml
<CustomField>
    <fullName>PreviousReportingPeriodName__c</fullName>
    <description>This field is used for displaying the Reporting Period Name to QI Service users in Email Reminders</description>
    <label>PreviousReportingPeriodName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ServiceNames__c.field-meta.xml
<CustomField>
    <fullName>ServiceNames__c</fullName>
    <description>This field is used for displaying the Services names to QI Service users in Email Reminders</description>
    <label>ServiceNames</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EmailNotificationSetting__mdt/EmailNotificationSetting__mdt.object-meta.xml
<CustomObject>
    <label>RatingPublishNotification</label>
    <pluralLabel>RatingPublishNotifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/NAPS_SERVICE_ID__c.field-meta.xml
<CustomField>
    <fullName>NAPS_SERVICE_ID__c</fullName>
    <label>NAPS Service Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/PROVIDER_ID__c.field-meta.xml
<CustomField>
    <fullName>PROVIDER_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Provider Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Submission_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Submission_Date_Time__c</fullName>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reporting Period</relationshipLabel>
    <relationshipName>Reporting_Period</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/QI_Submission_Due_Dt__c.field-meta.xml
<CustomField>
    <fullName>QI_Submission_Due_Dt__c</fullName>
    <description>capture the QI submission due date</description>
    <label>QI Submission Due Dt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Short__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Short__c</fullName>
    <description>Shortened version or Reporting Period to match Siebel</description>
    <formula>IF( ISPICKVAL(Reporting_Period_Type__c, &apos;Quarter&apos;),
&apos;Quarter &apos; &amp;
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3 ,&apos;3&apos;,
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6 ,&apos;4&apos;,
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9 ,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12 ,&apos;2&apos;,null) ) ) ) &amp;
&apos; FY &apos; &amp;
IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1), 2),
RIGHT( TEXT(YEAR(Start_Date__c)), 2)) &amp; &apos; - &apos; &amp;
IF(MONTH(End_Date__c) &gt;= 7, RIGHT( TEXT(YEAR(End_Date__c) +1), 2),
RIGHT( TEXT(YEAR(End_Date__c)), 2)),

TEXT(YEAR(Start_Date__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporting Period Short</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/SRQI_Exemption__c.object-meta.xml
<CustomObject>
    <description>Exemption record for services that have been granted an exemption from either the CER, SCR, QI or CM rating domains</description>
    <label>Exemption</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Exemption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_Exemption__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Exemptions</relationshipLabel>
    <relationshipName>Service</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendEmailNotificationService.cls
/**
* author: Neha Malik
* date: 23/03/2023
* description: This is the Service class to send the email notifications
* @testClass SendEmailNotificationServiceTest
**/
public with sharing class SendEmailNotificationService {
    OrgWideEmailAddress[] owea ;
    private Map<String, EmailNotificationSetting__mdt> mapEmailNotf;
    private static final String SEND_EML_MDT = 'Send_Email';
    private static final List<String> ROLES = new List<String>{ 'QI Role - Service', 'QI Role - Org' };
    private static final String SUBMIT_TEMPLATE = 'QI_Submission_Template';


    public SendEmailNotificationService(){
        mapEmailNotf = EmailNotificationSetting__mdt.getAll();
        String emailAdr = mapEmailNotf.get(SEND_EML_MDT).OWEA__c;
        owea = [SELECT Id, IsAllowAllProfiles, DisplayName, Address FROM OrgWideEmailAddress WHERE Address = :emailAdr LIMIT 1];
    }

    public Messaging.SingleEmailMessage prepareEmailList2(List<String> toAddress, String emailTemplateId, Id targetObjectId, Id whatId){
        Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
       // List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();


        Messaging.SingleEmailMessage msg = Messaging.renderStoredEmailTemplate(emailTemplateId, targetObjectId, whatId);
        String emailSubject = msg.getSubject();
        String emailTextBody = msg.getPlainTextBody();
        msg.setSubject(emailSubject);
        msg.setPlainTextBody(emailTextBody);
        msg.setToAddresses(toAddress);
        msg.setUseSignature(false);
        msg.setBccSender(false);
        msg.setSaveAsActivity(false);
        msg.setSenderDisplayName('Government Provider Management System');
        return msg;
    }

    public Messaging.SingleEmailMessage prepareEmailList(List<String> toAddress, String emailTemplateId, Id targetObjectId, Id whatId){
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        if ( owea?.size() > 0 ) {
            msg.setOrgWideEmailAddressId(owea[0].id);
        }
        msg.setTemplateId(emailTemplateId);
        msg.setToAddresses(toAddress);
        msg.setWhatId(whatId);
        msg.setUseSignature(false);
        msg.setBccSender(false);
        msg.setSaveAsActivity(true);
        msg.setTargetObjectId(targetObjectId);
        return msg;
    }


    public void sendEmailFromList(List<Messaging.SingleEmailMessage> lstMsgsToSend){
        if(!lstMsgsToSend.isempty()){
            List<Messaging.SendEmailResult> results = new List<Messaging.SendEmailResult>();
            try{
                results = Messaging.sendEmail(lstMsgsToSend,false);
                List<dohagedcare__Application_Log__c> logsList = new List<dohagedcare__Application_Log__c>();
                for(Messaging.SendEmailResult result:results) {
                    boolean isSuccess = result.isSuccess();
                    if(!isSuccess){
                        dohagedcare__Application_Log__c appLog = new dohagedcare__Application_Log__c();
                        appLog.dohagedcare__Exception_Type__c = 'SendEmailNotificationService error';
                        appLog.dohagedcare__Logging_Date_Time__c = System.now();
                        appLog.dohagedcare__Logging_Level__c = 'ERROR';
                        appLog.dohagedcare__Logging_User_Id__c = UserInfo.getUserId();
                        appLog.dohagedcare__Message__c = result.getErrors().get(0).getMessage();
                        appLog.dohagedcare__Source_Application__c = 'Star Rating';
                        logsList.add(appLog);
                    }
                }
                Database.insert(logsList);
            } catch (System.EmailException emlEx) {
                dohagedcare.Logger.error(emlEx.getMessage(),emlEx,'SendEmailNotificationService').Log();
            } catch(Exception exp) {
                dohagedcare.Logger.error(exp.getMessage(),exp,'SendEmailNotificationService').Log();
            }
        }
    }


    /**
    * @description : Send emails
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 05-26-2023
    * @param qiSummaries
    **/
    public void sendEmailForQISubmission(List<Quality_Indicator_Summary__c> qiSummaries){
        try{
            map<id, List<Quality_Indicator_Summary__c>> mapAccQIS= new map<id, List<Quality_Indicator_Summary__c>>();
            List<Quality_Indicator_Summary__c> qisList=[SELECT PROVIDER_ID__c, Reporting_Period__r.Reporting_Period_Short__c, Reporting_Period__r.QI_Submission_Due_Dt__c, Submission_Date_Time__c,
                                                        Service__r.Oracle_Service_ID__c,Service__r.Name FROM Quality_Indicator_Summary__c
                                                        WHERE Id IN : qiSummaries];
            for(Quality_Indicator_Summary__c qis:qisList){
                    if(mapAccQIS.containskey(qis.PROVIDER_ID__c)){
                        List<Quality_Indicator_Summary__c> qisSummaries=new List<Quality_Indicator_Summary__c>();
                        qisSummaries=mapAccQIS.get(qis.PROVIDER_ID__c);
                        qisSummaries.add(qis);
                        mapAccQIS.put(qis.PROVIDER_ID__c, qisSummaries);
                    }
                    else{
                        List<Quality_Indicator_Summary__c> qisSummaries=new List<Quality_Indicator_Summary__c>();
                        qisSummaries.add(qis);
                        mapAccQIS.put(qis.PROVIDER_ID__c, qisSummaries);
                    }
            }
            System.debug('Account Ids FROM QIS:'+ mapAccQIS.keyset());
            AccountUpdation updateAct =new AccountUpdation();
        	updateAct.updateAccountData(mapAccQIS);

            if (!mapAccQIS.isEmpty()) {
                List<AccountContactRelation> acctRelatnList = [
                    SELECT Id, ContactId, AccountId, Roles, Contact.Email
                    FROM AccountContactRelation
                    WHERE Roles INCLUDES('QI Role - Service', 'QI Role - Org') AND AccountId IN :mapAccQIS.keyset() AND Contact.Email != NULL];
                System.debug('acctRelatnList:'+ acctRelatnList);
                List<EmailTemplate> et = [  SELECT Id, HtmlValue, Body
                                            FROM EmailTemplate
                                            WHERE DeveloperName = :SUBMIT_TEMPLATE];
                if(!et.isEmpty()){
                    List<String> toAddress;
                    List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
                    for (AccountContactRelation acctConRelatn : acctRelatnList) {
                        Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                        toAddress = new List<String>();
                        toAddress.add(acctConRelatn.Contact.Email);
                        emailMsg = prepareEmailList(toAddress, et[0].Id, acctConRelatn.ContactId, acctConRelatn.AccountId);
                        emailList.add(emailMsg);
                    }
                    sendEmailFromList(emailList);
                }
            }
        }
        catch(Exception exp) {
            dohagedcare.Logger.error(exp.getMessage(),exp,'SendEmailNotificationService').Log();
        }
    }

    //need to update account fields by portal users for sending emails
    // because of that need to run this in without sharing context
    private without sharing class AccountUpdation{

        /**
        * @description : Update Account fields
        * @author Neha | 29-05-2023
        * @param newMap
        **/
        public void updateAccountData(map<id, List<Quality_Indicator_Summary__c>> mapAccQIS) {
            List<Account> accountToUpdate = new List<Account>();
            for(Account acc: [SELECT Id, PreviousReportingPeriodName__c, PreviousReportingPeriodDueDt__c, QISubmissionDetails__c,ServiceNames__c,NAPS_Service_Id__c FROM Account WHERE Id IN :mapAccQIS.keyset()]){
                acc.PreviousReportingPeriodName__c=mapAccQIS.get(acc.id)[0].Reporting_Period__r.Reporting_Period_Short__c;
                acc.PreviousReportingPeriodDueDt__c=mapAccQIS.get(acc.id)[0].Reporting_Period__r.QI_Submission_Due_Dt__c;
                acc.ServiceNames__c = mapAccQIS.get(acc.id)[0].Service__r.Name;
                acc.NAPS_Service_Id__c = mapAccQIS.get(acc.id)[0].Service__r.Oracle_Service_ID__c;
                DateTime submittedDate = mapAccQIS.get(acc.id)[0].Submission_Date_Time__c;
                if(submittedDate != null) {
                    acc.QISubmissionDetails__c= date.newinstance(submittedDate.year(), submittedDate.month(), submittedDate.day());
                }
                accountToUpdate.add(acc);
            }
            if(accountToUpdate.size()>0){
                update accountToUpdate;
            }
        }
    }
}