force-app/main/default/objects/Account/fields/Oracle_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_ID__c</fullName>
    <description>Oracle ID used for migration only. Read-only thereafter.</description>
    <externalId>true</externalId>
    <label>Oracle ID</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Oracle_Service_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Service_ID__c</fullName>
    <description>Migration value for APPROVAL_ID</description>
    <externalId>true</externalId>
    <label>Oracle Service ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/Quality_Indicator_Details__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Details</label>
    <nameField>
        <label>Quality Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quality Indicator Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/PROVIDER_ID__c.field-meta.xml
<CustomField>
    <fullName>PROVIDER_ID__c</fullName>
    <formula>QI_Summary_Id__r.PROVIDER_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SF Provider Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/SERVICE_ACCOUNT_ID__c.field-meta.xml
<CustomField>
    <fullName>SERVICE_ACCOUNT_ID__c</fullName>
    <formula>QI_Summary_Id__r.SERVICE_ACCOUNT_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Late Completion</fullName>
                <isActive>false</isActive>
                <label>Late Completion</label>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <isActive>false</isActive>
                <label>Updated After Due Date</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/PROVIDER_ID__c.field-meta.xml
<CustomField>
    <fullName>PROVIDER_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Provider Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/SERVICE_ACCOUNT_ID__c.field-meta.xml
<CustomField>
    <fullName>SERVICE_ACCOUNT_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Service Account</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField> 

force-app/main/default/objects/Quality_Indicator_Targets__c/Quality_Indicator_Targets__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Targets</label>
    <nameField>
        <displayFormat>QIT-{000000}</displayFormat>
        <label>Quality Indicator Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Targets__c/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <description>Parent-Child relationship to Quality Indicator Summary</description>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Quality Indicator Targets</relationshipLabel>
    <relationshipName>Quality_Indicator_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Targets__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Targets</relationshipLabel>
    <relationshipName>Quality_Indicator_Targets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Targets__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup relationship to Business License</description>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Quality Indicator Targets</relationshipLabel>
    <relationshipName>Quality_Indicator_Targets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QIDynamicManagementController.cls
/****************************************************************************************************
 * @CreatedBy   : Yifei Pei
 * @CreatedDate : 23-02-2023
 * @Description : Controller Class for LWC qiDynamicManagement
 *                LWC is put on Service record Accordion side panel
 * @Test Class  : QIDynamicManagementControllerTest
 *****************************************************************************************************/

public with sharing class QIDynamicManagementController {
    private final static String STATUS_IP = 'In Progress';
    /**
     * Method getCurrentQISList to query on existing Quality Indicator Summary
     * If there is, return to the record page of the newest created record
     * If there isn't, the button on LWC will create a new record
     * @parameter serviceId is the recordId retrieved from service record
     */
    @AuraEnabled(cacheable=true)
    public static String getCurrentQISList(String serviceId) {
        QISResponse response = new QISResponse();
        try {
            List<Quality_Indicator_Summary__c> qisList = getQISList(serviceId);
            if (qisList?.size() > 0) {
                response.isEmpty = false;
                response.Id = qisList[0].Id;
            } else {
                response.isEmpty = true;
            }
        } catch (Exception e) {
            dohagedcare.Logger.error(e.getMessage(), e, 'QIDynamicManagementController.getCurrentQISList failed').Log();
            throw new AuraHandledException(e.getMessage());
        }
        return JSON.serialize(response);
    }
    /**
     * Method createNewQI to create new Quality Indicator Summary
     * with 11 QID records (one record for each record type)
     * after creation, the LWC will return the newly created QIS record page
     * @parameter serviceId is the recordId retrieved from service record
     */
    @AuraEnabled
    public static String createNewQI(String serviceId) {
        QISResponse response = new QISResponse();
        try {
            Quality_Indicator_Summary__c newQIS = new Quality_Indicator_Summary__c();
            List<Service_Account_Relationship__c> relatedSAR = getServAcctRelp(serviceId);
            List<Reporting_Period__c> currentRP = getCurrentRP();

            //Validations
            String errorMessage = '';
            if (!(relatedSAR?.size() > 0)) {
                errorMessage += 'No related Service Account Relationship to be added into Quality Indicator Summary.' + '\r\n';
            } else {
                if (relatedSAR[0].Provider_Name__r.Oracle_ID__c == null) {
                    errorMessage += 'Account does not have external ID.' + '\r\n';
                }
                if (String.isBlank(relatedSAR[0].Service_Name__r.Oracle_Service_ID__c)) {
                    errorMessage += 'Service does not have external ID.' + '\r\n';
                }
            }
            if (!(currentRP?.size() > 0)) {
                errorMessage += 'No related Reporting Period to be added into Quality Indicator Summary.' + '\r\n';
            }
            if (!String.isBlank(errorMessage)) {
                throw qiMessageException(errorMessage);
            }

            // if the lists contain more than one records, we still only pick up the first one
            newQIS.Service__c = relatedSAR[0].Service_Name__c;
            newQIS.SERVICE_ACCOUNT_ID__c = relatedSAR[0].Id;
            newQIS.PROVIDER_ID__c = relatedSAR[0].Provider_Name__c;
            newQIS.REPORTING_PERIOD__c = currentRP[0].Id;
            newQIS.External_ID__c =
                String.valueOf(relatedSAR[0].Provider_Name__r.Oracle_ID__c) +
                '-' +
                String.valueOf(relatedSAR[0].Service_Name__r.Oracle_Service_ID__c) +
                '-' +
                String.valueOf(currentRP[0].Id);
            // Here the status fields value is hard coded
            // can creat helper class to handle it without hard code if required
            newQIS.Availability_Status__c = 'Draft';
            newQIS.Status__c = STATUS_IP;
            newQIS.Rating_Type__c = 'Draft Rating';
            // only one Quality Indicator Summary record needs to be inserted
            insert newQIS;
            List<Quality_Indicator_Details__c> allQIDList = new List<Quality_Indicator_Details__c>();
            Set<Id> allQIDRTIds = getQIDRecordTypes();
            for (Id rtId : allQIDRTIds) {
                allQIDList.add(
                    new Quality_Indicator_Details__c(
                        QI_Summary_Id__c = newQIS.Id,
                        RecordTypeId = rtId,
                        // this is hardcoded, a helper class can be created to handle it if required
                        Status__c = STATUS_IP
                    )
                );
            }
            insert allQIDList;

            Quality_Indicator_Targets__c newQIT = new Quality_Indicator_Targets__c();
            newQIT.Quality_Indicator_Summary__c = newQIS.Id;
            newQIT.Reporting_Period__c = currentRP[0].Id;
            newQIT.Service__c = relatedSAR[0].Service_Name__c;
            // only one Quality Indicator Target record needs to be inserted
            insert newQIT;
            response.isEmpty = false;
            response.Id = newQIS.Id;
        } catch (Exception e) {
            dohagedcare.Logger.error(e.getMessage(), e, 'QIDynamicManagementController.createNewQI failed').Log();
            throw new AuraHandledException(e.getMessage());
        }
        return JSON.serialize(response);
    }

    public static Set<Id> getQIDRecordTypes() {
        Set<Id> allRecordTypeIds = new Set<Id>();
        List<Schema.RecordTypeInfo> rtInfo = Quality_Indicator_Details__c.SObjectType.getDescribe().getRecordTypeInfos();
        for (Schema.RecordTypeInfo rtRecord : rtInfo) {
            if (!rtRecord.isMaster() && rtRecord.isActive()) {
                allRecordTypeIds.add(rtRecord.getRecordTypeId());
            }
        }
        return allRecordTypeIds;
    }

    public static AuraHandledException qiMessageException(String message) {
        AuraHandledException e = new AuraHandledException(message);
        e.setMessage(message);
        return e;
    }

    private static List<Quality_Indicator_Summary__c> getQISList(String serviceId) {
        return [
            SELECT Id
            FROM Quality_Indicator_Summary__c
            WHERE Service__c = :serviceId AND Reporting_Period__r.Current_Reporting_Period__c = TRUE
            ORDER BY CreatedDate DESC
        ];
    }

    private static List<Service_Account_Relationship__c> getServAcctRelp(String serviceId) {
        return [
            SELECT Id, Provider_Name__c, Service_Name__c, Provider_Name__r.Oracle_ID__c, Service_Name__r.Oracle_Service_ID__c
            FROM Service_Account_Relationship__c
            WHERE Service_Name__c = :serviceId AND Active__c = TRUE
            ORDER BY CreatedDate DESC
        ];
    }

    private static List<Reporting_Period__c> getCurrentRP() {
        return [
            SELECT Id
            FROM Reporting_Period__c
            WHERE Start_Date__c <= TODAY AND End_Date__c >= TODAY AND Current_Reporting_Period__c = TRUE AND Reporting_Period_Type__c = 'Quarter'
            ORDER BY CreatedDate DESC
        ];
    }

    @JsonAccess(serializable='always')
    public class QISResponse {
        @AuraEnabled
        public String id;

        @AuraEnabled
        public Boolean isEmpty;
    }
}