force-app/main/default/objects/Account/fields/Oracle_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_ID__c</fullName>
    <description>Oracle ID used for migration only. Read-only thereafter.</description>
    <externalId>true</externalId>
    <label>Oracle ID</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Oracle_Service_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Service_ID__c</fullName>
    <description>Migration value for APPROVAL_ID</description>
    <externalId>true</externalId>
    <label>Oracle Service ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Details__c/Quality_Indicator_Details__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Details</label>
    <nameField>
        <label>Quality Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quality Indicator Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Quality_Indicator_Details__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Details</label>
    <referenceTo>Quality_Indicator_Details__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QIDynamicManagementControllerTest.cls
/**
 * author: Yifei Pei
 * date: 28/02/2023
 * description: Test Class for QIDynamicManagementController
 **/
@isTest
private with sharing class QIDynamicManagementControllerTest {
    @TestSetup
    static void dataSetup() {
        Integer recordCount = 2;
        User testUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(testUser) {
            Reporting_Period__c rPeriod = TestDataFactory.createReportingPeriod('Quarter');
            insert rPeriod;

            List<Account> providersWithQIS = new List<Account>();
            List<BusinessLicense> servicesWithQIS = new List<BusinessLicense>();
            List<Service_Account_Relationship__c> serviceAccountRecordsWithQIS = new List<Service_Account_Relationship__c>();

            List<Account> providers = TestDataFactory.createProviderRecords(recordCount);
            insert providers;
            providersWithQIS.add(providers[1]);
            List<BusinessLicense> services = TestDataFactory.createServiceRecords(recordCount);
            insert services;
            servicesWithQIS.add(services[1]);
            List<Service_Account_Relationship__c> serviceAccountRecords = TestDataFactory.createServiceAccountRecords(
                recordCount,
                services,
                providers
            );
            insert serviceAccountRecords;
            serviceAccountRecordsWithQIS.add(serviceAccountRecords[1]);

            List<Quality_Indicator_Summary__c> qisRecords = TestDataFactory.createQISummaryRecords(
                1,
                providersWithQIS,
                rPeriod,
                servicesWithQIS,
                serviceAccountRecordsWithQIS
            );
            insert qisRecords;
            List<Quality_Indicator_Details__c> qidRecords = TestDataFactory.createQIDetailRecords(11, qisRecords);
            // assuming there are totally 11 record types
            Set<Id> allQIDRTIds = QIDynamicManagementController.getQIDRecordTypes();
            List<Id> allQIDRTIdList = new List<Id>();
            allQIDRTIdList.addAll(allQIDRTIds);
            for (Integer i = 0; i < qidRecords.size(); i++) {
                qidRecords[i].RecordTypeId = allQIDRTIdList[i];
            }
            insert qidRecords;
        }
        Test.stopTest();
    }
    @isTest
    public static void testQIMgmtCtrl() {
        List<BusinessLicense> allServices = [
            SELECT Id, Oracle_Service_ID__c
            FROM BusinessLicense
        ];
        List<Account> allProviders = [SELECT Id, Oracle_ID__c FROM Account];
        List<Quality_Indicator_Summary__c> allQISList = [
            SELECT Id, Service__c
            FROM Quality_Indicator_Summary__c
        ];
        List<Service_Account_Relationship__c> allServiceAccountRelationships = [
            SELECT Id
            FROM Service_Account_Relationship__c
        ];
        List<Reporting_Period__c> allReportingPeriods = [
            SELECT Id, Start_Date__c, End_Date__c
            FROM Reporting_Period__c
        ];
        Id serviceWithQISId = allQISList[0].Service__c;
        BusinessLicense serviceWithQIS;
        BusinessLicense serviceWithoutQIS;
        for (BusinessLicense serviceRecord : allServices) {
            if (serviceRecord.Id == serviceWithQISId) {
                serviceWithQIS = serviceRecord;
            } else {
                serviceWithoutQIS = serviceRecord;
            }
        }

        String getExistingQIS = '';
        String getEmptyQIS = '';
        String successCreation = '';

        Test.startTest();
        // Test the successful path
        getExistingQIS = QIDynamicManagementController.getCurrentQISList(serviceWithQIS.Id);
        getEmptyQIS = QIDynamicManagementController.getCurrentQISList(serviceWithoutQIS.Id);
        successCreation = QIDynamicManagementController.createNewQI(serviceWithoutQIS.Id);
        // Test the exceptions
        Exception capturedException;
        for (Account provider : allProviders) {
            provider.Oracle_ID__c = null;
        }
        for (BusinessLicense service : allServices) {
            service.Oracle_Service_ID__c = null;
        }
        update allProviders;
        update allServices;
        try {
            QIDynamicManagementController.createNewQI(serviceWithoutQIS.Id);
        } catch (Exception e) {
            capturedException = e;
        }
        delete allServiceAccountRelationships;
        for (Reporting_Period__c reportingPeriod : allReportingPeriods) {
            reportingPeriod.Start_Date__c = (System.today() + 12).addMonths(-6);
            reportingPeriod.End_Date__c = (System.today() + 24).addMonths(-3);
        }
        update allReportingPeriods;
        try {
            QIDynamicManagementController.createNewQI(serviceWithoutQIS.Id);
        } catch (Exception e) {
            capturedException = e;
        }
        Test.stopTest();

        Quality_Indicator_Summary__c newlyCreatedQIS = [
            SELECT Id
            FROM Quality_Indicator_Summary__c
            WHERE Service__c = :serviceWithoutQIS.Id
            LIMIT 1
        ];

        String assetedExistingQIS = '{\"isEmpty\":false,\"id\":\"' + allQISList[0].Id + '\"}';
        String assetedEmptyQIS = '{\"isEmpty\":true,\"id\":null}';
        String assetedSsuccessCreation = '{\"isEmpty\":false,\"id\":\"' + newlyCreatedQIS.Id + '\"}';

        System.assertEquals(assetedExistingQIS, getExistingQIS, 'Existing QIS assertion failed');
        System.assertEquals(assetedEmptyQIS, getEmptyQIS, 'Empty QIS assertion failed');
        System.assertEquals(assetedSsuccessCreation, successCreation, 'Newly Created QIS assertion failed');
    }
}