force-app/main/default/objects/Account/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Approved_Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Providers</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Approved_Provider.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider</fullName>
    <active>true</active>
    <description>Approved Provider</description>
    <label>Approved Provider</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Benchmarking_Organisation.recordType-meta.xml
<RecordType>
    <fullName>Benchmarking_Organisation</fullName>
    <active>true</active>
    <description>Benchmarking Organisation</description>
    <label>Benchmarking Organisation</label>
</RecordType>

force-app/main/default/objects/File_Staging__c/File_Staging__c.object-meta.xml
<CustomObject>
    <description>This is the object for File Staging</description>
    <label>File Upload</label>
    <nameField>
        <label>File Upload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Uploads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Staging__c/fields/File_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>File_CreatedDate__c</fullName>
    <description>This field will hold the CreatedDate of the csv file that inserted from LWC custom comp to content document object. Also used to record the date/time in which a bulk upload file was submitted.</description>
    <label>File_CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/File_Id__c.field-meta.xml
<CustomField>
    <fullName>File_Id__c</fullName>
    <description>this filed will hold the ContnetDocumentId after the file insertion</description>
    <label>File_Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Approved_Provider,Benchmarking_Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>File Stagings</relationshipLabel>
    <relationshipName>File_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Reporting_Category__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Category__c</fullName>
    <label>Reporting Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Sources</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>File Stagings</relationshipLabel>
    <relationshipName>File_Stagings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Request_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Received_Date__c</fullName>
    <description>The date in which the request to do a bulk upload (on behalf of an external user) was received by Health staff user</description>
    <label>Request Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Ready To Publish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Submission_Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Submission_Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to capture the contact of the user who requested the bulk upload submission (if applicable).</description>
    <inlineHelpText>User who requested the bulk upload submission (if applicable).</inlineHelpText>
    <label>Submission Requested By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>File Stagings</relationshipLabel>
    <relationshipName>File_Stagings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/recordTypes/QI.recordType-meta.xml
<RecordType>
    <fullName>QI</fullName>
    <active>true</active>
    <label>QI</label>
</RecordType>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reporting Period</relationshipLabel>
    <relationshipName>Reporting_Period</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Current_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Current_Reporting_Period__c</fullName>
    <description>Displays true if current reporting period.</description>
    <formula>IF( TODAY( ) &gt;= Start_Date__c &amp;&amp; TODAY( ) &lt;= End_Date__c, True, False )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Data_Sources.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CEI</fullName>
    </customValue>
    <customValue>
        <fullName>QI</fullName>
    </customValue>
    <masterLabel>Data Sources</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QIBulkUploadUtility.cls
/**
 * author: Sharevreet Singh
 * date: 29/04/2023
 * description: Utility class for QI Bulk Upload
 */
public with sharing class QIBulkUploadUtility {
    private static String STATUS_NEW = 'New';
    private static String QI_RT = 'QI';

    /**
     * @description Create file staging record if doesnot exist already, invocable from flow
     * @params List<FileStagingWrapper> fileStagingWrapper
     * @return List<File_Staging__c> record
     */
    @InvocableMethod(label='Create File Staging Record' description='Returns the file staging records')
    public static List<File_Staging__c> createFileStagingRecord(List<FileStagingWrapper> fileStagingWrapper) {
        return (new List<File_Staging__c>{ createFileStagingRecord(fileStagingWrapper[0]) });
    }

    /**
     * @description Create file staging record if doesnot exist already
     * @params FileStagingWrapper
     * @return File_Staging__c record
     */
    @AuraEnabled
    public static File_Staging__c createFileStagingRecord(FileStagingWrapper fileStagingWrapper) {
        //initialize variables for flow
        Id userId = fileStagingWrapper.userId;
        Id fileStagingRecordId = fileStagingWrapper.fileStagingRecordId;
        String fileName = fileStagingWrapper.fileName;
        Id providerId = null;
        Id subReqById = null;
        Date reqReceivedDate = null;
        final Id QT_RT = Schema.SObjectType.File_Staging__c.getRecordTypeInfosByDeveloperName().get(QI_RT).getRecordTypeId();
        final String FILE_NAME_DEFAULT = 'Pending';

        //initialize variables for lwc
        if (fileStagingWrapper.userId == null) {
            userId = fileStagingWrapper.userIdAura;
            fileStagingRecordId = fileStagingWrapper.fileStagingRecordIdAura;
            fileName = fileStagingWrapper.fileNameAura;
            providerId = fileStagingWrapper.providerIdAura;
            subReqById = fileStagingWrapper.subReqByIdAura;
            reqReceivedDate = fileStagingWrapper.reqReceivedDateAura;
        }

        File_Staging__c fileStaging = new File_Staging__c();
        User user = getUser(userId);
        Id accId = providerId != null ? providerId : getAccountIdFromContactId(user.Contact.Id);

        File_Staging__c fileStagingRecord = retrieveFileStagingRecord(userId, accId);

        if (fileStagingRecord != null && ((fileStagingRecordId == null && subReqById == null) || providerId != null)) {
            //return existing user if no update is required
            return fileStagingRecord;
        } else if (fileStagingRecord == null && (fileStagingRecordId == null || providerId != null)) {
            //create record when file staging record is not provided
            fileStaging = new File_Staging__c(
                RecordTypeId = QT_RT,
                Name = user.Alias + ' ' + Datetime.now().format(),
                Status__c = STATUS_NEW,
                Reporting_Period__c = [
                    SELECT Id
                    FROM Reporting_Period__c
                    WHERE Current_Reporting_Period__c = TRUE AND Reporting_Period_Type__c = 'Quarter'
                    LIMIT 1
                ]
                .Id,
                Provider__c = providerId != null ? providerId : accId,
                Submission_Requested_By__c = subReqById != null ? subReqById : user.Contact.Id,
                File_Name__c = fileName != null ? fileName : FILE_NAME_DEFAULT,
                Request_Received_Date__c = reqReceivedDate,
                Reporting_Category__c = QI_RT
            );
        } else if (fileStagingRecordId != null) {
            //create record based on existing file staging record
            File_Staging__c fileStagingRec = retrieveFileStagingRecord(fileStagingRecordId);
            fileStaging = new File_Staging__c(
                RecordTypeId = QT_RT,
                Name = user.Alias + ' ' + Datetime.now().format(),
                Status__c = STATUS_NEW,
                Reporting_Period__c = fileStagingRec.Reporting_Period__c,
                Provider__c = fileStagingRec.Provider__c != null ? fileStagingRec.Provider__c : accId,
                Submission_Requested_By__c = fileStagingRec.Submission_Requested_By__c != null
                    ? fileStagingRec.Submission_Requested_By__c
                    : user.Contact.Id,
                File_Name__c = fileName != null ? fileName : fileStagingRec.File_Name__c,
                Reporting_Category__c = QI_RT
            );
        }

        try {
            Database.insert(fileStaging, false);
        } catch (Exception ex) {
            dohagedcare.Logger.error(ex.getMessage(), ex, 'QIBulkUploadUtility.cls').log();
        }

        return fileStaging;
    }

    private static User getUser(Id userId) {
        return [SELECT Alias, Contact.Id, Contact.AccountId FROM USER WHERE Id = :userId LIMIT 1];
    }

    // Assumption: Contact will be related to either an Approved Provider or Benchmarking Organisation, not both.
    private static Id getAccountIdFromContactId(Id contactId) {
        final String AP_RT = 'Approved_Provider';
        final String BO_RT = 'Benchmarking_Organisation';

        return [
            SELECT AccountId
            FROM AccountContactRelation
            WHERE ContactId = :contactId 
            AND IsActive = TRUE 
            AND (
                Account.RecordType.DeveloperName = :AP_RT
                OR Account.RecordType.DeveloperName = :BO_RT
            )
            LIMIT 1
        ]
        .AccountId;
    }
    /**
     * @description Retrieve file staging record if exist
     * @params User user
     * @return File_Staging__c record
     */
    public static File_Staging__c retrieveFileStagingRecord(Id userId, Id accId) {
        List<File_Staging__c> fileStaging = [
            SELECT Id, Reporting_Period__c, Reporting_Period__r.Name, File_Id__c
            FROM File_Staging__c
            WHERE Provider__c = :accId AND Status__c = :STATUS_NEW AND CreatedById = :userId AND File_Id__c = NULL
        ];
        if (fileStaging.size() > 0) {
            return fileStaging[0];
        }
        return null;
    }

    /**
     * @description Retrieve file staging record if exists
     * @params Id of File Staging Record
     * @return File_Staging__c record
     */
    public static File_Staging__c retrieveFileStagingRecord(Id fileStagingRecordId) {
        List<File_Staging__c> fileStaging = [
            SELECT
                Id,
                Reporting_Period__c,
                Reporting_Period__r.Name,
                Name,
                File_Id__c,
                File_Name__c,
                File_CreatedDate__c,
                Provider__c,
                Submission_Requested_By__c
            FROM File_Staging__c
            WHERE Id = :fileStagingRecordId
        ];
        if (fileStaging.size() > 0) {
            return fileStaging[0];
        }
        return null;
    }

    public class FileStagingWrapper {
        //used with Flow
        @InvocableVariable
        public Id userId;
        @InvocableVariable
        public Id fileStagingRecordId;
        @InvocableVariable
        public String fileName;

        //used with lwc
        @AuraEnabled
        public Id userIdAura { get; set; }
        @AuraEnabled
        public Id fileStagingRecordIdAura { get; set; }
        @AuraEnabled
        public String fileNameAura { get; set; }
        @AuraEnabled
        public Id providerIdAura { get; set; }
        @AuraEnabled
        public Id subReqByIdAura { get; set; }
        @AuraEnabled
        public Date reqReceivedDateAura { get; set; }
    }
}