force-app/main/default/objects/Account/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Organisation Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Incorporation_ID_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Private for Profit</fullName>
            </value>
            <value>
                <fullName>Not for Profit</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <formula>TEXT(Form__r.QA_Outcome__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QA Outcome</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact, Record Id of the related Contact record.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>(Generic NAPS Position Name) The role of this contact</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Assessment Service Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Assessor</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Financial Management</fullName>
            </value>
            <value>
                <fullName>Funding Agreement Variations</fullName>
            </value>
            <value>
                <fullName>Funding Submissions</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Aged Care Program Contact</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Key Personnel</fullName>
            </value>
            <value>
                <fullName>General Staff</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>Applicant Representative</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Leader</fullName>
            </value>
            <value>
                <fullName>Activity Contact</fullName>
            </value>
            <value>
                <fullName>Acquittal/Financial Reporting</fullName>
            </value>
            <value>
                <fullName>Assessment Service Administrator</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate Support</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate</fullName>
            </value>
            <value>
                <fullName>Choice Attributes</fullName>
            </value>
            <value>
                <fullName>Care Services Management</fullName>
            </value>
            <value>
                <fullName>Remittance/RCTI</fullName>
            </value>
            <value>
                <fullName>High level contact</fullName>
                <label>High Level Contact</label>
            </value>
            <value>
                <fullName>Service Monitoring &amp; Reports</fullName>
            </value>
            <value>
                <fullName>Centre Management</fullName>
            </value>
            <value>
                <fullName>Aged Care Service Manager</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>QFR Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Declaration_Complete__c.field-meta.xml
<CustomField>
    <fullName>Declaration_Complete__c</fullName>
    <label>Is the declaration complete?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/fields/Declaration_Incomplete_Reason__c.field-meta.xml
<CustomField>
    <fullName>Declaration_Incomplete_Reason__c</fullName>
    <description>Reason Declaration was incomplete</description>
    <label>Declaration Incomplete Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Declaration is a blank document</fullName>
            </value>
            <value>
                <fullName>You must submit an approved Declaration</fullName>
            </value>
            <value>
                <fullName>Declaration is for a prior quarter</fullName>
            </value>
            <value>
                <fullName>A new declaration must be submitted</fullName>
            </value>
            <value>
                <fullName>Signatory is not an authorised person</fullName>
            </value>
            <value>
                <fullName>Signature is missing</fullName>
            </value>
            <value>
                <fullName>Name is missing</fullName>
            </value>
            <value>
                <fullName>Position is missing</fullName>
            </value>
            <value>
                <fullName>Date is missing</fullName>
            </value>
            <value>
                <fullName>Declaration is dated into the future</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/fields/Name_of_Signer__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Signer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the declaration signatory</description>
    <label>Name of Signatory</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/QA_Outcome__c.field-meta.xml
<CustomField>
    <fullName>QA_Outcome__c</fullName>
    <label>QA Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Re-Issue</fullName>
                <label>Reissue</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>More information required</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>ReIssued</fullName>
                <isActive>false</isActive>
                <label>ReIssued</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AcfrEmailTemplateBuilderController.cls
public with sharing class AcfrEmailTemplateBuilderController {
  static final String declartionFrmName = 'Declaration and Submission';
  static final String residentialViabilityFrmName = 'Residential Viability and Prudential Reporting';
  static final String homeCareViabilityFrmName = 'Home Care Viability and Prudential Reporting';
  static final String approvedProviderFrmName = 'Approved Provider Quarterly Financial Statements';
  static final String homeCareLabourCostFrmName = 'Home Care Labour Costs and Hours';
  static final String resiLabourCostFrmName = 'Residential Labour Costs and Hours';
  static final String mpsFoodFrmName = 'MPS Food and Nutrition Reporting';
  static final String resiFoodFrmName = 'Residential Food and Nutrition Reporting';
  static final String natsifacpFrmName = 'NATSIFACP Food and Nutrition Reporting';

  @AuraEnabled
  public static String getEmailSubject(String recordId) {
    String emailSubject = AcfrEmailService.getEmailSubject(
      recordId,
      'Case',
      'QFR_Reissue_Email'
    );
    return emailSubject;
  }

  @AuraEnabled
  public static String getEmailContent(String recordId) {
    String emailBody = AcfrEmailService.getEmailContent(
      recordId,
      'Case',
      'QFR_Reissue_Email'
    );
    List<Case> caseRec = [
      SELECT Id, AccountId, Account.Purpose__c
      FROM Case
      WHERE Id = :recordId AND AccountId != NULL
    ];
    List<Contact_Relationship__c> conRel = [
      SELECT id, Contact__c
      FROM Contact_Relationship__c
      WHERE
        Account__c = :caseRec[0].AccountId
        AND Role__c = 'QFR Primary Contact'
      LIMIT 1
    ];

    Set<String> notExistingTypes = new Set<String>();
    notExistingTypes.add(declartionFrmName);
    notExistingTypes.add(residentialViabilityFrmName);
    notExistingTypes.add(homeCareViabilityFrmName);
    notExistingTypes.add(approvedProviderFrmName);
    notExistingTypes.add(homeCareLabourCostFrmName);
    notExistingTypes.add(resiLabourCostFrmName);
    notExistingTypes.add(mpsFoodFrmName);
    notExistingTypes.add(resiFoodFrmName);
    notExistingTypes.add(natsifacpFrmName);
    for (Form__c rec : [
      SELECT
        id,
        Name,
        Type__c,
        QA_Outcome__c,
        Declaration_Complete__c,
        Declaration_Incomplete_Reason__c,
        Name_of_Signer__c,
        Case__c,
        Case__r.Account.Purpose__c
      FROM Form__c
      WHERE QA_Outcome__c != 'Accepted' AND Case__c = :recordId
      ORDER BY QA_Outcome__c DESC
    ]) {
        if(conRel != null){
      emailBody = getEmailBody(emailBody, rec, conRel[0]);
      notExistingTypes.remove(rec.Type__c);
        }
    }

    if (!notExistingTypes.isEmpty()) {
      emailBody = getEmailBodyNotExistingtype(emailBody, notExistingTypes);
    }
      emailBody = emailBody.substringAfter('<p').substringBeforeLast('</td>');
      emailBody = '<p'+emailBody;
      return emailBody;
  }

  public static String getEmailBody(
    String emailBody,
    Form__c rec,
    Contact_Relationship__c conRel
  ) {
    if (rec.Type__c == declartionFrmName) {
      emailBody = emailBody.replace('DECLARATION_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'DECLARATION',
        rec.Declaration_Complete__c != 'Yes'
      );

      DeclarationReasonWrapper resultwrap = checkDeclarationReason(
        rec,
        conRel,
        rec.Declaration_Incomplete_Reason__c
      );
      Boolean signatoryNonPrimary = resultwrap.signatoryNonPrimary;
      Boolean signatoryPrimary = resultwrap.signatoryPrimary;
      Boolean signatory = resultwrap.signatory;
      Boolean other = resultwrap.other;

      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'SIGNATORY2A_NONPRIMARY',
        signatoryNonPrimary
      );
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'SIGNATORY2A_PRIMARY',
        signatoryPrimary
      );
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'SIGNATORY2B',
        signatory
      );
      emailBody = AcfrEmailService.hideConditions(emailBody, 'OTHER2C', other);

      emailBody = emailBody.replace(
        'DECLARATION_LIST',
        resultwrap.declationList
      );
      emailBody = AcfrEmailService.mergeFields(emailBody, rec.Id, 'Form__c');
    } else if (rec.Type__c == residentialViabilityFrmName) {
      emailBody = emailBody.replace('RESI_VIABILITY_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'RESIVIABILITY',
        rec.QA_Outcome__c != 'Accepted'
      );
    } else if (rec.Type__c == homeCareViabilityFrmName) {
      emailBody = emailBody.replace('HOME_VIABILITY_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'HOMEVIABILITY',
        rec.QA_Outcome__c != 'Accepted'
      );
    } else if (rec.Type__c == approvedProviderFrmName) {
      emailBody = emailBody.replace('QUARTERLY_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'QUARTERLY',
        rec.QA_Outcome__c != 'Accepted'
      );
    } else if (rec.Type__c == homeCareLabourCostFrmName) {
      emailBody = emailBody.replace('HOME_LABOUR_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'HOMELABOUR',
        rec.QA_Outcome__c != 'Accepted'
      );
    } else if (rec.Type__c == resiLabourCostFrmName) {
      emailBody = emailBody.replace('RESI_LABOUR_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'RESILABOUR',
        rec.QA_Outcome__c != 'Accepted'
      );
    } else if (rec.Type__c == resiFoodFrmName) {
      emailBody = emailBody.replace('RESIFOOD_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'RESIFOOD',
        rec.QA_Outcome__c != 'Accepted'
      );
    } else if (rec.Type__c == mpsFoodFrmName) {
      emailBody = emailBody.replace('MPS_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'MPS',
        rec.QA_Outcome__c != 'Accepted'
      );
    } else if (rec.Type__c == natsifacpFrmName) {
      emailBody = emailBody.replace('NATSI_FORM_NAME', rec.Type__c);
      emailBody = AcfrEmailService.hideConditions(
        emailBody,
        'NATSI',
        rec.QA_Outcome__c != 'Accepted'
      );
    } else {
      //Do nothing
    }

    return emailBody;
  }

  public static String getEmailBodyNotExistingtype(
    String emailBody,
    Set<String> notExistingTypes
  ) {
    for (String rec : notExistingTypes) {
      if (rec == declartionFrmName) {
        emailBody = AcfrEmailService.hideConditions(
          emailBody,
          'DECLARATION',
          false
        );
      } else if (rec == residentialViabilityFrmName) {
        emailBody = AcfrEmailService.hideConditions(
          emailBody,
          'RESIVIABILITY',
          false
        );
      } else if (rec == homeCareViabilityFrmName) {
        emailBody = AcfrEmailService.hideConditions(
          emailBody,
          'HOMEVIABILITY',
          false
        );
      } else if (rec == approvedProviderFrmName) {
        emailBody = AcfrEmailService.hideConditions(
          emailBody,
          'QUARTERLY',
          false
        );
      } else if (rec == homeCareLabourCostFrmName) {
        emailBody = AcfrEmailService.hideConditions(
          emailBody,
          'HOMELABOUR',
          false
        );
      } else if (rec == resiLabourCostFrmName) {
        emailBody = AcfrEmailService.hideConditions(
          emailBody,
          'RESILABOUR',
          false
        );
      } else if (rec == resiFoodFrmName) {
        emailBody = AcfrEmailService.hideConditions(
          emailBody,
          'RESIFOOD',
          false
        );
      } else if (rec == mpsFoodFrmName) {
        emailBody = AcfrEmailService.hideConditions(emailBody, 'MPS', false);
      } else if (rec == natsifacpFrmName) {
        emailBody = AcfrEmailService.hideConditions(emailBody, 'NATSI', false);
      } else {
        //Do nothing
      }
    }

    return emailBody;
  }

  private static DeclarationReasonWrapper checkDeclarationReason(
    Form__c rec,
    Contact_Relationship__c conRel,
    String declarationIncReason
  ) {
    DeclarationReasonWrapper res = new DeclarationReasonWrapper();
    res.signatoryNonPrimary = false;
    res.signatoryPrimary = false;
    res.signatory = false;
    res.other = false;
    String declationList = '<ul>';
      if(declarationIncReason != null ){
          for (String val : declarationIncReason.split(';')) {
              declationList = declationList + '<li>' + val + '</li>';
              
              switch on val {
                  when 'Signatory is not an authorised person' {
                      res = clauseSignatoryIsNotAuthorizedPerson(conRel, res, rec);
                  }
                  when 'Other' {
                      res.other = true;
                  }
                  when else {
                      //Do nothing
                  }
              }
          }
      }
    declationList = declationList + '</ul>';
    res.declationList = declationList;

    return res;
  }

  public static DeclarationReasonWrapper clauseSignatoryIsNotAuthorizedPerson(Contact_Relationship__c conRel, DeclarationReasonWrapper res, Form__c rec){
    if (conRel != null) {
      res.signatoryPrimary = (conRel.Contact__c == rec.Name_of_Signer__c);
      res.signatoryNonPrimary = (conRel.Contact__c !=
      rec.Name_of_Signer__c);
    } else {
      res.signatoryNonPrimary = true;
    }

    if (rec.Case__r?.Account?.Purpose__c == 'Government') {
      res.signatory = true;
    }
    return res;
  }


  @AuraEnabled
  public static String getEmailAddress(String recordId) {
    String emailAdd = AcfrEmailService.getPrimaryEmailAddress(recordId);
    return emailAdd;
  }

  @AuraEnabled
  public static String getEmailAddressCC(String recordId) {
    String emailAdd = AcfrEmailService.getNonPrimaryEmailAddress(recordId);
    return emailAdd;
  }

  @AuraEnabled
  public static void sendSingleEmailMethod(
    String recordId,
    String emailBody,
    String emailAddress,
    String emailAddressCC,
    String emailSubject
  ) {
    AcfrEmailService.sendCustomSingleEmailMethod(
      recordId,
      emailBody,
      emailAddress,
      emailAddressCC,
      emailSubject
    );
  }

  public class DeclarationReasonWrapper {
    public Boolean signatoryNonPrimary;
    public Boolean signatoryPrimary;
    public Boolean signatory;
    public Boolean other;
    public String declationList;
  }
}