force-app/main/default/objects/Address_Location__c/Address_Location__c.object-meta.xml
<CustomObject>
    <label>Address Location</label>
    <nameField>
        <displayFormat>ALN-{00000}</displayFormat>
        <label>Address Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Location__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address_Location__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipName>Service_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Type__c/Care_Type__c.object-meta.xml
<CustomObject>
    <label>Care Type</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Care Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Type__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <description>Care Type field pulled in from Account Object</description>
    <formula>TEXT(Account.Care_Type__c)</formula>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull from Reporting Perion Object.</description>
    <label>Reporting Period ID</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <businessProcess>QFR</businessProcess>
    <description>This is for Quarterly Financial Reports</description>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <description>Form</description>
    <label>Form</label>
    <nameField>
        <displayFormat>FRM#{00000}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Service_Account_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Service_Account_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Account Relationship</label>
    <referenceTo>Service_Account_Relationship__c</referenceTo>
    <relationshipLabel>Forms</relationshipLabel>
    <relationshipName>QFR_Reports_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form__c/recordTypes/QFR.recordType-meta.xml
<RecordType>
    <fullName>QFR</fullName>
    <active>true</active>
    <label>QFR</label>
</RecordType>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <formula>Text(Service_Name__r.Care_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Line_Item__c/Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI-{00000}</displayFormat>
        <label>Service Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Line_Item__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField> 

force-app/main/default/objects/Service_Line_Item__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Line_Item__c/fields/Service_Region__c.field-meta.xml
<CustomField>
    <fullName>Service_Region__c</fullName>
    <label>Service_Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/SRQI_Exemption__c.object-meta.xml
<CustomObject>
    <description>Exemption record for services that have been granted an exemption from either the CER, SCR, QI or CM rating domains</description>
    <label>Exemption</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Exemption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_Exemption__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Exemptions</relationshipLabel>
    <relationshipName>Service</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Describes the type of exemption. System is generated by a process and business is generated by a staff</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Residential Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Viability and Prudential Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Provider Quarterly Financial Statements</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Home Care Labour Costs and Hours</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Declaration and Submission</fullName>
    </customValue>
    <customValue>
        <fullName>NATSIFACP Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>MPS Food and Nutrition Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Food and Nutrition Reporting</fullName>
        <isActive>false</isActive>
        <label>Food and Nutrition Reporting</label>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AcfrApexClassFromOmnistudio.cls
/*------------------------------------------------------------------------------------------------
Author:         Varun Sood
Description:    This class is a proof of concept to dyanmically invoke Apex Class from Omnistudio for User Story# 233681.
************************************************************************************************
History 
************************************************************************************************
Updated code for following 
For disply missing serivce section 
    added code to get the missing services and collate a list and provide it to user
    For service of care type - Home care, implemented logic for getting the region from missing service and display the same
For Add missing service 
    Called method for adding service not of care type home care
    For service of type home care 
    - Added logic for getting region for service getting added
    - checked if the region is not already present for current services then add the service
--------------------------------------------------------------------------------------------------*/

global with sharing class AcfrApexClassFromOmnistudio implements omnistudio.VlocityOpenInterface 
{
    global Static string HC ='Home Care';
    global Static String HC_FORM='Home Care Labour Costs and Hours';
    global Static Boolean invokeMethod(String methodName, Map<String,Object> InputMap, Map<String,Object> OutputMap, Map<String,Object> OptionsMap)
    {
        Boolean result=true; 
        
        try{
            //To display Service Records Name in OmniLookup
            if(methodName.equalsIgnoreCase('displayMissingService')){			 
                List<Map<String, String>>  lookupValues =new List<Map<String, String>>();
                String CaseId =(String)InputMap.get('ContextId');
                List<Id> servicesAlreadyAdded= new List<id>();  
                List<id>  listSA =new List<id>(); 
                List<Id> listRA =new List<Id>();
                List<Case>  ListCase =new List<Case>();
                List<id> formids= new List<id>();
                String AccountId; 
                date ReportingPeriodEndDate;  
                List<String> regionsPresent= new List<String>();

                Case c =[Select id, Status, AccountId, Reporting_Period__c, Reporting_Period__r.Start_Date__c, Reporting_Period__r.End_Date__c from Case where id =:CaseId];
                if (c != null && c.Status != 'New' && c.Status != 'Draft') return false;
                AccountId = c?.AccountId;
                ReportingPeriodEndDate = c?.Reporting_Period__r.End_Date__c;
                    
                for(Form__c fm:[Select id, Case__c from Form__c where Case__c=: CaseId]) {
                formids.add(fm.id); 
                } 
                for(Service_Line_Item__c slis:[Select id, Service__c, Form__c, Service_Region__c,Form__r.Type__c, Service__r.Care_Type__c from Service_Line_Item__c 
                    where Service__r.Care_Type__c != :HC and Form__c IN:formids]){
                        if (slis.Service__r.Care_Type__c != null){
                                servicesAlreadyAdded.add(slis.Service__c);
                        } 
                }
                for(Service_Line_Item__c sli:[Select id, Service__c, Form__c, Service_Region__c,Form__r.Type__c,Form__r.Case__r.Service__c from Service_Line_Item__c 
                    where Form__r.Type__c = :HC_FORM and Form__c IN:formids]){                  
                        if (sli.Form__r.Type__c != null && sli.Service_Region__c != null && !regionsPresent.contains(sli.Service_Region__c)){
                                regionsPresent.add(sli.Service_Region__c); // regions already added for HC
                        }
                }
                for(Service_Account_Relationship__c sar:[Select id, Service_Name__c, Care_Type__c from Service_Account_Relationship__c 
                    where Provider_Name__c= :AccountId 
                    AND Association_Start_Date__c <= :c.Reporting_Period__r.End_Date__c
                    AND Service_Name__c NOT IN : servicesAlreadyAdded 
                    AND Care_Type__c != :HC AND (Association_End_Date__c = NULL
                        OR (Association_End_Date__c >= :c.Reporting_Period__r.Start_Date__c AND Association_End_Date__c <= :c.Reporting_Period__r.End_Date__c))]){
                                                        
                                listSA.add(sar.Service_Name__c);
                        
                } 
                for(Service_Account_Relationship__c sar:[Select id, Service_Name__c, Care_Type__c from Service_Account_Relationship__c 
                    where Provider_Name__c= :AccountId 
                    AND Association_Start_Date__c <= :c.Reporting_Period__r.End_Date__c
                    AND Care_Type__c = :HC 
                                                        AND (Association_End_Date__c = NULL
                        OR (Association_End_Date__c >= :c.Reporting_Period__r.Start_Date__c AND Association_End_Date__c <= :c.Reporting_Period__r.End_Date__c))
                    
                                                        ]){
                                                        
                            listRA.add(sar.Service_Name__c);
                } 
                for(BusinessLicense bl:[Select id, Name from BusinessLicense where Id IN:listSA])  
                {
                    if (bl != null){
                        Map<String, String> tempMap =new Map<String, String>();
                        tempMap.put('name', bl.Id);
                        tempMap.put('value', bl.Name);
                        lookupValues.add(tempMap);
                    }
                }
                OutputMap.put('options', lookupValues); 
                Set<Id> addressIds=new Set<Id>();
                Map<Id,Id> mapOfServiceAddress=new Map<Id,Id>();
                for (Address_Location__c recType:[SELECT Id, Address__c, Service__c FROM Address_Location__c 
                    WHERE Service__c IN :listRA]){ 
                
                    addressIds.add(recType.address__c);
                    mapOfServiceAddress.put(recType.address__c,recType.Service__c); 
                }
                for(Geospatial_Information__c geoInfo: [SELECT Address__c, Address__r.State_Province__c, Description__c,Layer__c FROM Geospatial_Information__c 
                    WHERE Address__c IN :addressIds AND Layer__c = 'Aged Care Planning Regions']){
                
                    if (geoInfo != null){
                        Map<String, String> tempMap =new Map<String, String>();
                        String region = geoInfo.Address__r.State_Province__c +'-'+geoInfo.Description__c;
                        if (!regionsPresent.contains(region)){
                            tempMap.put('name', mapOfServiceAddress.get(geoInfo.address__c));
                            tempMap.put('value', region);
                            lookupValues.add(tempMap);
                        }            
                                    
                    }
                OutputMap.put('Options', lookupValues);  
                }
                                
            }
         
            if(methodName.equalsIgnoreCase('addMissingService')){
                AcfrCreateQuaterlyCasesAndFormsService ac=new AcfrCreateQuaterlyCasesAndFormsService();
                Id caseIdVar;
                Id serviceIdVar;
                List<Id> listRAs =new List<Id>();
                List<id> formids= new List<id>();
                List<String> regionNameList = new List<String>();
                caseIdVar =(String)InputMap.get('CaseId');
                serviceIdVar =(String)InputMap.get('ServiceId');
                BusinessLicense bl=[Select id, Name,Care_Type__c from BusinessLicense where Id=:serviceIdVar];
                If (bl.Care_Type__c != HC) {
                    ac.generateRecordsForAdditionalServices(caseIdVar, serviceIdVar,null);
                } else{
                    Case c =[Select id, Status, AccountId, Reporting_Period__c, Reporting_Period__r.Start_Date__c, Reporting_Period__r.End_Date__c from Case where id =:caseIdVar];
                    System.Debug('Case===='+c);
                    for(Form__c fm:[Select id, Case__c from Form__c where Case__c=: caseIdVar]) {
                        formids.add(fm.id); 
                       } 
                        for(Service_Line_Item__c sli:[Select id, Service__c, Form__c, Service_Region__c,Form__r.Type__c, Service__r.Care_Type__c from Service_Line_Item__c 
                            where Form__r.Type__c =:HC_FORM
                            AND Form__c IN:formids]){
                                if (sli.Form__r.Type__c != null && sli.Service_Region__c != null && !regionNameList.contains(sli.Service_region__c)){
                                    regionNameList.add(sli.Service_region__c);
                                }
                        }
                    for (Service_Account_Relationship__c sarr:[Select id, Service_Name__c, Care_Type__c from Service_Account_Relationship__c 
                        where Service_Name__c= :serviceIdVar 
                        AND Association_Start_Date__c <= :c.Reporting_Period__r.End_Date__c
                        AND Care_Type__c = :HC 
                        AND (Association_End_Date__c = NULL
                        OR (Association_End_Date__c >= :c.Reporting_Period__r.Start_Date__c AND Association_End_Date__c <= :c.Reporting_Period__r.End_Date__c))]){
                            listRAs.add(sarr.Service_Name__c);
                    } 
                    Set<Id> addressIds=new Set<Id>();
                    for (Address_Location__c recType:[SELECT Id, Address__c, Service__c FROM Address_Location__c 
                        WHERE Service__c IN :listRAs]){ 
                            addressIds.add(recType.address__c);
                    }
                    for(Geospatial_Information__c geoInfo: [SELECT Address__c, Address__r.State_Province__c, Description__c,Layer__c FROM Geospatial_Information__c 
                        WHERE Address__c IN :addressIds AND Layer__c = 'Aged Care Planning Regions']){
                            String region = geoInfo.Address__r.State_Province__c +'-'+geoInfo.Description__c;
                            if (geoInfo != null && !regionNameList.contains(region)){
                                ac.generateRecordsForAdditionalServices(caseIdVar, serviceIdVar, region);
                            }
                    }
                }
                OutputMap.put('Apexoutput', InputMap);
            }
        }Catch(Exception e){
            dohagedcare.logger.error(e.getMessage(),e,'QFR').log();
           return false; 
        }
        return result;
    }
}