force-app/main/default/objects/CHSP_Service_Schedule__c/CHSP_Service_Schedule__c.object-meta.xml
<CustomObject>
    <label>CHSP Schedule Detail</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>CHSP Schedule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHSP Schedule Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CHSP Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Commonwealth Home Support Programme</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CHSP Schedule Details</relationshipLabel>
    <relationshipName>CHSP_Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CHSP_Service_Schedule__c/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <label>Party Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GPMSCHSPLinkServiceBatch.cls
/****************************************************************************************************
* @CreatedBy   : Accenture Developer Team
* @CreatedDate : 18-Sep-2022
* @Description : Handles the logic to link service with service schedule
* @Test Class  : GPMSCHSPLinkServiceScheduleTest
*****************************************************************************************************/
public with sharing class GPMSCHSPLinkServiceBatch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        String query = 'SELECT Id,Party_Id__c,Service_Care_Sub_Type__c '+
            +'FROM CHSP_Service_Schedule__c '
            +'WHERE Organisation_Name__c != null AND Party_Id__c != null';
        return Database.getQueryLocator(query);
        
    }
    
    public void execute(Database.BatchableContext BC, List<CHSP_Service_Schedule__c> scope){
        GPMSCHSPLinkServiceHelper chspLinkServiceHelper = new GPMSCHSPLinkServiceHelper(scope);
        chspLinkServiceHelper.executeGPMSCHSPLinkService();
    }
    
    public void finish(Database.BatchableContext BC){
        
    }
}