force-app/main/default/objects/Care_Minutes_Summary__c/Care_Minutes_Summary__c.object-meta.xml
<CustomObject>
    <label>Care Minutes Summary</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Care Minutes Summary Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Minutes Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/RequiresSRH__c.field-meta.xml
<CustomField>
    <fullName>RequiresSRH__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Back end field for query after insert of records</description>
    <label>RequiresSRH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/SRHQueryId__c.field-meta.xml
<CustomField>
    <fullName>SRHQueryId__c</fullName>
    <description>Back end field for query after insert of records</description>
    <label>SRHQueryId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/SRQI_CER__c.object-meta.xml
<CustomObject>
    <label>Consumer Experience Report</label>
    <nameField>
        <displayFormat>CER-{000000}</displayFormat>
        <label>Consumer Experience Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Experience Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_CER__c/fields/RequiresSRH__c.field-meta.xml
<CustomField>
    <fullName>RequiresSRH__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Back end field for query after insert of records</description>
    <label>RequiresSRH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/SRHQueryId__c.field-meta.xml
<CustomField>
    <fullName>SRHQueryId__c</fullName>
    <description>Back end field for query after insert of records</description>
    <label>SRHQueryId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/Care_Minutes_Id__c.field-meta.xml
<CustomField>
    <fullName>Care_Minutes_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Minutes</label>
    <referenceTo>Care_Minutes_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Consumer_Experience_Id__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Experience_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumer Experience Report</label>
    <referenceTo>SRQI_CER__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Quality_Indicator_Id__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SRHRatingsLinkHelper.cls
/**
 * author: Daniel Clift
 * date: 30/09/2022
 * description: Links inserted subrating records to satar rating history records
 **/
public with sharing class SRHRatingsLinkHelper {
	private static Map<String, Map<String, String>> srhUpdate = new Map<String, Map<String, String>>();

	private static void updateCM(List<Care_Minutes_Summary__c> cmList) {
		for (Care_Minutes_Summary__c cm : cmList) {
			srhUpdate.put(cm.SRHQueryId__c, new Map<String, String>{ 'CM' => cm.Id });
			cm.RequiresSRH__c = false;
		}
	}

	private static void updateCER(List<SRQI_CER__c> cerList) {
		for (SRQI_CER__c cer : cerList) {
			if (srhUpdate.get(cer.SRHQueryId__c) != null) {
				srhUpdate.get(cer.SRHQueryId__c).put('CER', cer.Id);
			} else {
				srhUpdate.put(cer.SRHQueryId__c, new Map<String, String>{ 'CER' => cer.Id });
				cer.RequiresSRH__c = false;
			}
		}
	}

	private static void updateQI(List<Quality_Indicator_Summary__c> qiList) {
		for (Quality_Indicator_Summary__c qi : qiList) {
			if (srhUpdate.get(qi.SRHQueryId__c) != null) {
				srhUpdate.get(qi.SRHQueryId__c).put('QI', qi.Id);
			} else {
				srhUpdate.put(qi.SRHQueryId__c, new Map<String, String>{ 'QI' => qi.Id });
				qi.RequiresSRH__c = false;
			}
		}
	}

	public static void updateSubDomains() {
		// For CM
		Map<Id, Care_Minutes_Summary__c> cmMap = new Map<Id, Care_Minutes_Summary__c>(
			[SELECT Id, SRHQueryId__c FROM Care_Minutes_Summary__c WHERE RequiresSRH__c = TRUE]
		);

		if (!cmMap.isEmpty()) {
			updateCM(cmMap.values());
			update cmMap.values();
		}

		// For CER
		Map<Id, SRQI_CER__c> cerMap = new Map<Id, SRQI_CER__c>(
			[SELECT Id, SRHQueryId__c FROM SRQI_CER__c WHERE RequiresSRH__c = TRUE]
		);
		if (!cerMap.isEmpty()) {
			updateCER(cerMap.values());
			update cerMap.values();
		}

		// for QI
		Map<Id, Quality_Indicator_Summary__c> qiMap = new Map<Id, Quality_Indicator_Summary__c>(
			[SELECT Id, SRHQueryId__c FROM Quality_Indicator_Summary__c WHERE RequiresSRH__c = TRUE]
		);
		if (!qiMap.isEmpty()) {
			updateQI(qiMap.values());
			update qiMap.values();
		}

		if (!srhUpdate.isEmpty()) {
			linkRecords(srhUpdate);
		}
	}

	public static void linkRecords(Map<String, Map<String, String>> srhRecords) {
		Map<Id, STAR_Rating_History__c> srhList = new Map<Id, STAR_Rating_History__c>(
			[SELECT Id FROM STAR_Rating_History__c WHERE Id IN :srhRecords.keySet()]
		);

		for (String srhId : srhRecords.keySet()) {
			Map<String, String> recordTypes = srhRecords.get(srhId);
			for (String recordType : recordTypes.keySet()) {
				if (recordType == 'CER' && srhList.get(srhId) != null) {
					srhList.get(srhId).Consumer_Experience_Id__c = recordTypes.get('CER');
				} else if (recordType == 'QI' && srhList.get(srhId) != null) {
					srhList.get(srhId).Quality_Indicator_Id__c = recordTypes.get('QI');
				} else if (recordType == 'CM' && srhList.get(srhId) != null) {
					srhList.get(srhId).Care_Minutes_Id__c = recordTypes.get('CM');
				} else {
					continue;
				}
			}
		}
		update srhList.values();
	}
}