force-app/main/default/objects/Care_Minutes_Summary__c/Care_Minutes_Summary__c.object-meta.xml
<CustomObject>
    <label>Care Minutes Summary</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Care Minutes Summary Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Minutes Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availability_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Publication_Date__c.field-meta.xml
<CustomField>
    <fullName>Publication_Date__c</fullName>
    <description>Date/Time record was published to provider portal</description>
    <label>Publication Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Care Minutes Summary</relationshipLabel>
    <relationshipName>Care_Minutes_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Availability_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Published</fullName>
    </customValue>
    <customValue>
        <fullName>LIVE</fullName>
    </customValue>
    <customValue>
        <fullName>Removed</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review/On Hold</fullName>
        <isActive>false</isActive>
        <label>Under Review/On Hold</label>
    </customValue>
    <description>Status for Overall &amp; subcategory StarRatings</description>
    <masterLabel>Availability Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CareMinutesSummaryTriggerHandler.cls
/**
* author: Daniel Clift
* date: 09/09/2022
* description: trigger handler for Care Minites Summary
**/

public with sharing class CareMinutesSummaryTriggerHandler implements afterInsert, beforeUpdate {
    // Care_Minutes_Summary__c
    public static final String DRAFT_STATUS = 'Draft';
    public static final String PUBLISHED_STATUS = 'Published';
    public static final String LIVE_STATUS = 'Live';
    public static final String REMOVED_STATUS = 'Removed';

    public void beforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        
        List<Care_Minutes_Summary__c> cmList = (List<Care_Minutes_Summary__c>) newMap.values();
        // store service Ids
        Map<Id, Id> liveCMRecords = new Map<Id, Id>();
        
        for(Care_Minutes_Summary__c cm : cmList) {
            
            Care_Minutes_Summary__c cmOld = (Care_Minutes_Summary__c) oldMap.get(cm.Id);

            if(cm.Availability_Status__c == PUBLISHED_STATUS && cmOld.Availability_Status__c != PUBLISHED_STATUS) {
                cm.Rating_Type__c = 'New Rating';
                cm.Publication_Date__c = Datetime.now();
            }
            if(cm.Availability_Status__c == LIVE_STATUS && cmOld.Availability_Status__c != LIVE_STATUS) {
                cm.Rating_Type__c = 'Current Rating';
                liveCMRecords.put(cm.Id, cm.Service__c);
            }
        }
        if(!liveCMRecords.isEmpty()) {
            RatingsStatusHelper.UpdateCMRatingType(liveCMRecords);
        }
    }

    public void afterInsert(Map<Id, SObject> newMap) {
        CareMinuteSummaryTriggerService.shareCareMinuteSummaryRecords((Map<Id, Care_Minutes_Summary__c>)newMap);
    }
}