force-app/main/default/objects/Care_Minutes_Summary__c/Care_Minutes_Summary__c.object-meta.xml
<CustomObject>
    <label>Care Minutes Summary</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Care Minutes Summary Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Minutes Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availability_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Care_Minutes_Summary__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Care Minutes Summary</relationshipLabel>
    <relationshipName>Care_Minutes_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Late Submission</fullName>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <label>Submitted - Updated After Due Date</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Publish</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
                <isActive>false</isActive>
                <label>Archive</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/SRQI_CER__c.object-meta.xml
<CustomObject>
    <label>Consumer Experience Report</label>
    <nameField>
        <displayFormat>CER-{000000}</displayFormat>
        <label>Consumer Experience Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Experience Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_CER__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availability_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Rating_Type__c.field-meta.xml
<CustomField>
    <fullName>Rating_Type__c</fullName>
    <label>Rating Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rating_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/STAR_Rating_History__c.object-meta.xml
<CustomObject>
    <label>STAR Rating History</label>
    <nameField>
        <displayFormat>STAR-{000000}</displayFormat>
        <label>STAR Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STAR Rating History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/STAR_Rating_History__c/fields/SF_Service_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Service_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>STAR Rating History</relationshipLabel>
    <relationshipName>STAR_Rating_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/STAR_Rating_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of Star Rating calculation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Availability_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Availability_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Published</fullName>
    </customValue>
    <customValue>
        <fullName>LIVE</fullName>
    </customValue>
    <customValue>
        <fullName>Removed</fullName>
    </customValue>
    <customValue>
        <fullName>Under Review/On Hold</fullName>
        <isActive>false</isActive>
        <label>Under Review/On Hold</label>
    </customValue>
    <description>Status for Overall &amp; subcategory StarRatings</description>
    <masterLabel>Availability Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Rating_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Current Rating</fullName>
    </customValue>
    <customValue>
        <fullName>New Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Previous Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Draft Rating</fullName>
    </customValue>
    <masterLabel>Rating Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RatingsStatusHelper.cls
/**
* author: Daniel Clift
* date: 06/09/2022
* description: handles status changes for StarRating History, QI, SCR, CER, CM 
**/
public with sharing class RatingsStatusHelper {

    public static Map<String, String> serviceIds = new Map<String, String>();

    public static void UpdateSubRatingRecords(Map<String, Map<Id, String>> ratingsMap) {
        
        Map<Id, String> cerIds = ratingsMap.get('CER');
        Map<Id, String> cmIds = ratingsMap.get('CM');
        Map<Id, String> qiIds = ratingsMap.get('QI');
        
        if(!cerIds.isEmpty()) {
            //serviceIds.clear();
            List<SRQI_CER__c> cerRecords = [Select Id, Availability_Status__c, Rating_Type__c, Service__c FROM SRQI_CER__c WHERE Id IN :cerIds.keySet()]; // OR (Availability_Status__c = 'Current Rating' OR Availability_Status__c = 'New Rating')];
            List<SRQI_CER__c> cerUpdate = UpdateSubRatingStatus(cerRecords, cerIds);
            update cerUpdate;
        }

        if(!cmIds.isEmpty()) {
            //serviceIds.clear();
            List<Care_Minutes_Summary__c> cmRecords = [Select Id, Availability_Status__c, Rating_Type__c, Service__c FROM Care_Minutes_Summary__c WHERE Id IN :cmIds.keySet()]; // OR (Availability_Status__c = 'Current Rating' OR Availability_Status__c = 'New Rating')];
            List<Care_Minutes_Summary__c> cmUpdate = UpdateSubRatingStatus(cmRecords, cmIds);
            //UpdateCMRatingType();
            update cmUpdate;
        }

        if(!qiIds.isEmpty()) {
            //serviceIds.clear();
            List<Quality_Indicator_Summary__c> qiRecords = [Select Id, Availability_Status__c, Rating_Type__c, Service__c FROM Quality_Indicator_Summary__c WHERE Id IN :qiIds.keySet()]; // OR (Availability_Status__c = 'Current Rating' OR Availability_Status__c = 'New Rating')];
            List<Quality_Indicator_Summary__c> qiUpdate = UpdateSubRatingStatus(qiRecords, qiIds);
            //UpdateQIRatingType();
            update qiUpdate;
        }
    }

    public static List<sObject> UpdateSubRatingStatus(List<sObject> subRatingRecords, Map<Id, String> sObjectIds) {
        for(sObject subRatingRecord : subRatingRecords) {
            if(sObjectIds.get(subRatingRecord.Id) == 'Published' && subRatingRecord.get('Availability_Status__c') != 'LIVE') {
                subRatingRecord.put('Availability_Status__c', 'Published');
            }
            else if(sObjectIds.get(subRatingRecord.Id) == 'LIVE') {
                subRatingRecord.put('Availability_Status__c', 'LIVE');
            }
            else{
                continue;
            }
            
        }
        return subRatingRecords;
    }

    public static void UpdateCERRatingType(Map<Id, Id> cerMap) {
        List<SRQI_CER__c> cerRecords = [Select Id, Availability_Status__c, Rating_Type__c, Service__c FROM SRQI_CER__c WHERE Service__c IN :cerMap.values() AND Id NOT IN :cerMap.keySet() AND Rating_Type__c = 'Current Rating'];
        if(!cerRecords.isEmpty()){
            for(SRQI_CER__c cerRecord : cerRecords) {
                cerRecord.Rating_Type__c = 'Previous Rating';
            }
            update cerRecords;
        }
    }

    public static void UpdateCMRatingType(Map<Id, Id> cmMap) {
        List<Care_Minutes_Summary__c> cmRecords = [Select Id, Availability_Status__c, Rating_Type__c, Service__c FROM Care_Minutes_Summary__c WHERE Service__c IN :cmMap.values() AND Id NOT IN :cmMap.keySet() AND Rating_Type__c = 'Current Rating'];
        if(!cmRecords.isEmpty()) {
            for(Care_Minutes_Summary__c cmRecord : cmRecords) {
                cmRecord.Rating_Type__c = 'Previous Rating';
            }
            update cmRecords;
        }
    }

    public static void UpdateQIRatingType(Map<Id, Id> qiMap) {
        List<Quality_Indicator_Summary__c> qiRecords = [Select Id, Availability_Status__c, Rating_Type__c, Service__c FROM Quality_Indicator_Summary__c WHERE Service__c IN :qiMap.values() AND Id NOT IN :qiMap.keySet() AND Rating_Type__c = 'Current Rating'];
        if(!qiRecords.isEmpty()) {
            for(Quality_Indicator_Summary__c qiRecord : qiRecords) {
                qiRecord.Rating_Type__c = 'Previous Rating';
            }
            update qiRecords;
        }
    }

    public static void UpdateSCRRatingType(Map<Id, Id> scrMap) {
        List<Service_Compliance_History__c> scrRecords = [Select Id, Availability_Status__c, Rating_Type__c, Service__c FROM Service_Compliance_History__c WHERE Service__c IN :scrMap.values() AND Id NOT IN :scrMap.keySet() AND Rating_Type__c = 'Current Rating'];
        if(!scrRecords.isEmpty()) {
            for(Service_Compliance_History__c scrRecord : scrRecords) {
                scrRecord.Rating_Type__c = 'Previous Rating';
            }
            update scrRecords;
        }
    }

    public static void UpdateSRHRatingType(Map<Id, Id> shrMap) {
        List<STAR_Rating_History__c> shrRecords = [Select Id, Status__c, Rating_Type__c, SF_Service_Id__c FROM STAR_Rating_History__c WHERE SF_Service_Id__c IN :shrMap.values() AND Id NOT IN :shrMap.keySet() AND Rating_Type__c = 'Current Rating'];
        if(!shrRecords.isEmpty()) {
            for (STAR_Rating_History__c shr : shrRecords) {
                shr.Rating_Type__c = 'Previous Rating';
            }
            update shrRecords;
        }
    }
}