force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{00000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <description>Unit Number</description>
    <label>Unit Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UniqueAddressTest.cls
@isTest
public class UniqueAddressTest {    
    @isTest
    static void testCall (){
        Map<String, Object> args = new Map<String, Object>();
        Map<String, Object> input = new Map<String, Object> {
            'poBoxType'=>'',
            'postOfficeBox'=>'',
            'unitNumber'=>'',
            'LevelNumber'=>'',
            'buildingName'=>'',
            'lotNumber'=>'',
            'streetNumber1'=>'',
            'streetNumber2'=>'',
            'street1'=>'',
            'street2'=>'',
            'streetTypeDescription'=>'',
            'streetSuffixTypeDescription'=>'',
            'city'=>'',
            'stateProvince'=>'',
            'zipPostalCode'=>'',
            'country'=>'',
            'latitude'=>145.67512,
            'longitude'=>-37.328421
        };
            
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        args.put('input',input);
        UniqueAddressesController checkAddress = new UniqueAddressesController();
        System.runAs(gpmsUser){
            Test.StartTest();
            checkAddress.call('', args);
            Test.StopTest();
        }    
            
            
    }
    @isTest
    static void testCallNull (){
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        Map<String, Object> args = new Map<String, Object>();
        Map<String, Object> input = new Map<String, Object>();
            args.put('input',input);
            UniqueAddressesController checkAddress = new UniqueAddressesController();
        System.runAs(gpmsUser){
            Test.StartTest();
            checkAddress.call('', args);
            Test.StopTest();
        } 
    }
    @isTest
    static void testTrigger (){
        User gpmsUser = TestDataFactory.createGPMSTestUser();
        Address__c addressToInsert = new Address__c();
        System.runAs(gpmsUser){
            Test.StartTest();
            insert addressToInsert;
        	addressToInsert.Unit_Number__c = '3';
        	update addressToInsert;
            Test.StopTest();
        } 
        
        
    }

}