force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{00000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Location__c/Address_Location__c.object-meta.xml
<CustomObject>
    <label>Address Location</label>
    <nameField>
        <displayFormat>ALN-{00000}</displayFormat>
        <label>Address Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/recordTypes/Approved_Provider_Service.recordType-meta.xml
<RecordType>
    <fullName>Approved_Provider_Service</fullName>
    <active>true</active>
    <label>Approved Provider Service</label>
</RecordType>

force-app/main/default/classes/GPMSAddressPayloadResponseTest.cls
@IsTest
public class GPMSAddressPayloadResponseTest {
    
    private static User currentUser = TestDataFactory.createGPMSTestUser();
    
    @testSetup static void setup() {
        
        System.runAs(currentUser){
            
            BusinessLicense serviceToInsert = GPMSTestUtility.getServiceByRecordType('Approved_Provider_Service');
            insert serviceToInsert;
            
            Address__c address = GPMSTestUtility.getAddress();
            insert address;
            
            Address_Location__c accountLocation = GPMSTestUtility.getServiceAddress(address.Id,serviceToInsert.Id);
            insert accountLocation;
            
        }
        
    }
    
    @isTest static void testGPMSAddressPayload() {
        
        System.runAs(currentUser){
            
            Address__c address = [SELECT Id FROM Address__c limit 1];
            
            RestRequest req = new RestRequest();
            RestResponse res = new RestResponse();
            req.requestURI = '/services/apexrest/GPMS/Address/' + address.Id ;  //Request URL
            req.httpMethod = 'GET';//HTTP Request Type
            
            
            Test.startTest();
            
            RestContext.request = req;
            RestContext.response= res;
            GPMSAddressPayload payload = GPMSAddressPayloadResponse.getAddressPayload();
            
            System.assertEquals(payload.addressId, address.Id, 'Query Address Informaiton Unsucessfully');
            
            Test.stopTest();
        }
        
    }
    
}