force-app/common/utils/fls-override/objects/GPMS_Backup_Config__mdt/GPMS_Backup_Config__mdt.object-meta.xml
<CustomObject>
    <description>277032: Used by PermissionSetsManager for Providing Read FLS on a given Permission Set</description>
    <label>GPMS Backup Config</label>
    <pluralLabel>GPMS Backup Config</pluralLabel>
</CustomObject>

force-app/common/utils/fls-override/objects/GPMS_Backup_Config__mdt/fields/IsCDCRequired__c.field-meta.xml
<CustomField>
    <fullName>IsCDCRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable CDC, if TRUE</description>
    <label>IsCDCRequired</label>
    <type>Checkbox</type>
</CustomField>

force-app/common/utils/fls-override/objects/GPMS_Backup_Config__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Indicates the Name of the object as the MasterLabel field length can accommodate only 40 chars. This allows for __c or __mdt to be included</description>
    <label>Object Name</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/common/utils/fls-override/classes/GPMSPermissionSetsScheduler.cls
/**
 * @description       : Schedules the PermissionSetManager
 **/
public without sharing class GPMSPermissionSetsScheduler implements Schedulable {
	private String permissionSetApiName { get; set; }
	private DML dml = new DMLImpl();
	/**
	 * @description
	 * @param permissionSetApiName
	 **/
	public GPMSPermissionSetsScheduler(
		String permissionSetApiName,
		DML dmlImpl
	) {
		this.permissionSetApiName = permissionSetApiName;
		this.dml = dmlImpl;
	}
	/**
	 * @description
	 * @param permissionSetApiName
	 **/
	public GPMSPermissionSetsScheduler(String permissionSetApiName) {
		this.permissionSetApiName = permissionSetApiName;
	}
	/**
	 * @description
	 * @param SC
	 **/
	public void execute(SchedulableContext SC) {
		List<GPMS_Backup_Config__mdt> backupConfigs = GPMS_Backup_Config__mdt.getAll()
			.values();
		List<FieldPermissions> fieldPermissionToUpdate = new List<FieldPermissions>();
		GPMSPermissionSetsManager pm = new GPMSPermissionSetsManager(
			permissionSetApiName
		);
		for (GPMS_Backup_Config__mdt backupConfig : backupConfigs) {
			if (
				String.isNotBlank(backupConfig.Object_Name__c) &&
				backupConfig.IsCDCRequired__c
			) {
				fieldPermissionToUpdate.addAll(
					pm.setAllFieldsRead(backupConfig.Object_Name__c)
				);
			}
		}
		try {
			dml.insertRecords(fieldPermissionToUpdate, false);
		} catch (DmlException exp) {
			dohagedcare.Logger.error(
					exp.getMessage(),
					exp,
					'GPMSPermissionSetsScheduler'
				)
				.Log();
		}
	}
}