force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <description>Generic Platform Event which minics the structure for CDC</description>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/changedFields__c.field-meta.xml
<CustomField>
    <fullName>changedFields__c</fullName>
    <label>changedFields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/changeOrigin__c.field-meta.xml
<CustomField>
    <fullName>changeOrigin__c</fullName>
    <label>changeOrigin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/changeType__c.field-meta.xml
<CustomField>
    <fullName>changeType__c</fullName>
    <label>changeType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/commitNumber__c.field-meta.xml
<CustomField>
    <fullName>commitNumber__c</fullName>
    <label>commitNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/commitTimestamp__c.field-meta.xml
<CustomField>
    <fullName>commitTimestamp__c</fullName>
    <label>commitTimestamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/commitUser__c.field-meta.xml
<CustomField>
    <fullName>commitUser__c</fullName>
    <label>commitUser</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/entityName__c.field-meta.xml
<CustomField>
    <fullName>entityName__c</fullName>
    <label>entityName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/recordIds__c.field-meta.xml
<CustomField>
    <fullName>recordIds__c</fullName>
    <label>recordIds</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/sequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>sequenceNumber__c</fullName>
    <label>sequenceNumber</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/transactionKey__c.field-meta.xml
<CustomField>
    <fullName>transactionKey__c</fullName>
    <label>transactionKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PlatformEventHelper.cls
public with sharing class PlatformEventHelper {
    public static Generic_Event__e createGenericEvent(sObject newRecord, sObject oldRecord, String operation) {
        return new Generic_Event__e(commitNumber__c = '', commitUser__c = UserInfo.getUserId(), 
                                    sequenceNumber__c = '1', entityName__c = newRecord.Id.getSObjectType().getDescribe().getName(),
                                   changeType__c = operation, changedFields__c = getChangeFieldValues(oldRecord, newRecord, operation),
                                   changeOrigin__c = '', transactionKey__c = '', commitTimestamp__c = String.valueOf(datetime.now().getTime()),
                                   recordIds__c = newRecord.Id);
    }
    
    public static Set<String> getChangedFields(SObject oldRecord, SObject newRecord) {
        Set<String> fields = new Set<String>();
        Set<String> systemFields = new Set<String>{
          'CreatedDate','LastModifiedById','LastModifiedDate','SystemModstamp'
        };
        for (String key : newRecord.getPopulatedFieldsAsMap().keySet()) {
            if(systemFields.contains(key)) {
                continue;
            }
            if(oldRecord.get(key) != newRecord.get(key)){
                fields.add(key);
            }
        }
        return fields;
    }

    public static String getChangeFieldValues(SObject oldRecord, SObject newRecord, String operation) {
        String changedFields = null;
        Set<String> fieldSet;
        if (operation == 'UPDATE') {
            fieldSet = getChangedFields(oldRecord, newRecord);
        }
        if (fieldSet.size() == 0) {
            return '[]';
        }
        for (String field : fieldSet) {
            if (changedFields == null) {
                changedFields = field;
            }
            else {
                changedFields += ', ' + field;
            }
        }
        return changedFields;
    }
}