force-app/main/default/objects/SRQI_CER__c/SRQI_CER__c.object-meta.xml
<CustomObject>
    <label>Consumer Experience Report</label>
    <nameField>
        <displayFormat>CER-{000000}</displayFormat>
        <label>Consumer Experience Report</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumer Experience Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_CER__c/fields/Care_Need_Always__c.field-meta.xml
<CustomField>
    <fullName>Care_Need_Always__c</fullName>
    <label>Care Need - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Care_Need_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Care_Need_Most_of_the_time__c</fullName>
    <label>Care Need - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Care_Need_Never__c.field-meta.xml
<CustomField>
    <fullName>Care_Need_Never__c</fullName>
    <label>Care Need - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Care_Need_Score__c.field-meta.xml
<CustomField>
    <fullName>Care_Need_Score__c</fullName>
    <label>Care Need Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Care_Need_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Care_Need_Some_of_the_time__c</fullName>
    <label>Care Need - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Caring_Always__c.field-meta.xml
<CustomField>
    <fullName>Caring_Always__c</fullName>
    <label>Caring - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Caring_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Caring_Most_of_the_time__c</fullName>
    <label>Caring - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Caring_Never__c.field-meta.xml
<CustomField>
    <fullName>Caring_Never__c</fullName>
    <label>Caring - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Caring_Score__c.field-meta.xml
<CustomField>
    <fullName>Caring_Score__c</fullName>
    <label>Caring Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Caring_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Caring_Some_of_the_time__c</fullName>
    <label>Caring - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Consumer_Experience_Rating__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Experience_Rating__c</fullName>
    <description>Consumer Experience number rating, out of 5</description>
    <label>Consumer Experience Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Explain_Always__c.field-meta.xml
<CustomField>
    <fullName>Explain_Always__c</fullName>
    <label>Explain - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Explain_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Explain_Most_of_the_time__c</fullName>
    <label>Explain - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Explain_Never__c.field-meta.xml
<CustomField>
    <fullName>Explain_Never__c</fullName>
    <label>Explain - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Explain_Score__c.field-meta.xml
<CustomField>
    <fullName>Explain_Score__c</fullName>
    <label>Explain Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Explain_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Explain_Some_of_the_time__c</fullName>
    <label>Explain - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Follow_Up_Always__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Always__c</fullName>
    <label>Follow Up - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Follow_Up_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Most_of_the_time__c</fullName>
    <label>Follow Up - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Follow_Up_Never__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Never__c</fullName>
    <label>Follow Up - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Follow_Up_Score__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Score__c</fullName>
    <label>Follow Up Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Follow_Up_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Some_of_the_time__c</fullName>
    <label>Follow Up - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Food_Always__c.field-meta.xml
<CustomField>
    <fullName>Food_Always__c</fullName>
    <label>Food - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Food_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Food_Most_of_the_time__c</fullName>
    <label>Food - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Food_Never__c.field-meta.xml
<CustomField>
    <fullName>Food_Never__c</fullName>
    <label>Food - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Food_Score__c.field-meta.xml
<CustomField>
    <fullName>Food_Score__c</fullName>
    <label>Food Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Food_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Food_Some_of_the_time__c</fullName>
    <label>Food - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Independent_Always__c.field-meta.xml
<CustomField>
    <fullName>Independent_Always__c</fullName>
    <label>Independent - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Independent_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Independent_Most_of_the_time__c</fullName>
    <label>Independent - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Independent_Never__c.field-meta.xml
<CustomField>
    <fullName>Independent_Never__c</fullName>
    <label>Independent - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Independent_Score__c.field-meta.xml
<CustomField>
    <fullName>Independent_Score__c</fullName>
    <label>Independent Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Independent_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Independent_Some_of_the_time__c</fullName>
    <label>Independent - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Operation_Always__c.field-meta.xml
<CustomField>
    <fullName>Operation_Always__c</fullName>
    <label>Operation - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Operation_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Operation_Most_of_the_time__c</fullName>
    <label>Operation - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Operation_Never__c.field-meta.xml
<CustomField>
    <fullName>Operation_Never__c</fullName>
    <label>Operation - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Operation_Score__c.field-meta.xml
<CustomField>
    <fullName>Operation_Score__c</fullName>
    <label>Operation Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Operation_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Operation_Some_of_the_time__c</fullName>
    <label>Operation - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Respect_Always__c.field-meta.xml
<CustomField>
    <fullName>Respect_Always__c</fullName>
    <label>Respect - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Respect_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Respect_Most_of_the_time__c</fullName>
    <label>Respect - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Respect_Never__c.field-meta.xml
<CustomField>
    <fullName>Respect_Never__c</fullName>
    <label>Respect - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Respect_Score__c.field-meta.xml
<CustomField>
    <fullName>Respect_Score__c</fullName>
    <label>Respect Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Respect_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Respect_Some_of_the_time__c</fullName>
    <label>Respect - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Safety_Always__c.field-meta.xml
<CustomField>
    <fullName>Safety_Always__c</fullName>
    <label>Safety - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Safety_Most_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Safety_Most_of_the_time__c</fullName>
    <label>Safety - Most of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Safety_Never__c.field-meta.xml
<CustomField>
    <fullName>Safety_Never__c</fullName>
    <label>Safety - Never</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Safety_Score__c.field-meta.xml
<CustomField>
    <fullName>Safety_Score__c</fullName>
    <label>Safety Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Safety_Some_of_the_time__c.field-meta.xml
<CustomField>
    <fullName>Safety_Some_of_the_time__c</fullName>
    <label>Safety - Some of the time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Consumer Experience Reports</relationshipLabel>
    <relationshipName>Consumer_Experience_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SRQI_CER__c/fields/Voice_Always__c.field-meta.xml
<CustomField>
    <fullName>Voice_Always__c</fullName>
    <label>Voice - Always</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SRQI_Exemption__c/SRQI_Exemption__c.object-meta.xml
<CustomObject>
    <description>Exemption record for services that have been granted an exemption from either the CER, SCR, QI or CM rating domains</description>
    <label>Exemption</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Exemption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exemptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SRQI_Exemption__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Exemptions</relationshipLabel>
    <relationshipName>Service</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CEIAlgorithmBatch.cls
/**
* author: Daniel Clift
* date: 25/08/2022
* description: To count and calculate CEI data, passing to respective CER
* @testClass CEIAlgorithmTest
**/

public with sharing class CEIAlgorithmBatch implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator(getQuery());
    }

    public void execute(Database.BatchableContext bc, List<SRQI_CER__c> scope)
    {
        try {
            CEIAlgorithmHelper.calcCEI(scope);
        } catch(Exception exp) {
            dohagedcare.Logger.error(exp.getMessage(),exp,'Rating Calc').Log(); 
        }
    }

    public static String getQuery()
    {
        String retQuery = '';
        retQuery = retQuery + 'SELECT Id,Consumer_Experience_Rating__c,Respect_Always__c,Respect_Most_of_the_time__c,Respect_Never__c,Respect_Some_of_the_time__c,Respect_Score__c,Food_Always__c,Food_Most_of_the_time__c,Food_Never__c,Food_Some_of_the_time__c,Food_Score__c,';
        retQuery = retQuery + 'Safety_Always__c,Safety_Most_of_the_time__c,Safety_Never__c,Safety_Some_of_the_time__c,Safety_Score__c,';
        retQuery = retQuery + 'Operation_Always__c,Operation_Most_of_the_time__c,Operation_Never__c,Operation_Some_of_the_time__c,Operation_Score__c,';
        retQuery = retQuery + 'Care_Need_Always__c,Care_Need_Most_of_the_time__c,Care_Need_Never__c,Care_Need_Some_of_the_time__c,Care_Need_Score__c,';
        retQuery = retQuery + 'Independent_Always__c,Independent_Most_of_the_time__c,Independent_Never__c,Independent_Some_of_the_time__c,Independent_Score__c,Explain_Always__c,';
        retQuery = retQuery + 'Explain_Most_of_the_time__c,Explain_Never__c,Explain_Some_of_the_time__c,Explain_Score__c,';
        retQuery = retQuery + 'Follow_Up_Always__c,Follow_Up_Most_of_the_time__c,Follow_Up_Never__c,Follow_Up_Some_of_the_time__c,Follow_Up_Score__c,';
        retQuery = retQuery + 'Caring_Always__c, Caring_Most_of_the_time__c, Caring_Never__c, Caring_Some_of_the_time__c, Caring_Score__c,Service__c,';
        retQuery = retQuery + 'Voice_Always__c,Voice_Most_of_the_time__c,Voice_Never__c,Voice_Some_of_the_time__c,Voice_Score__c,Home_Always__c,Home_Most_of_the_time__c,Home_Never__c,Home_Some_of_the_time__c,Home_Score__c ';
        retQuery = retQuery + 'FROM SRQI_CER__c WHERE Quarterly_RP__r.Previous_Reporting_Period__c = true ';
        retQuery = retQuery + 'AND Service_Account__r.Active__c = TRUE AND Extant__c = TRUE ';
        retQuery = retQuery + 'AND Service__r.Status__c NOT IN (\'Closed\', \'Pre-operational\') ';
        return (retQuery);

    }

    public void finish(Database.BatchableContext bc)
    {
        Database.executeBatch(new CerHybridBatch(true), 90);
    }
}