force-app/main/default/objects/GPMS_Emergency_Situation__c/GPMS_Emergency_Situation__c.object-meta.xml
<CustomObject>
    <label>Emergency Situation</label>
    <nameField>
        <displayFormat>EMG-{0000000}</displayFormat>
        <label>Emergency Situation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emergency Situations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GPMS_Emergency_Situation__c/fields/Emergency_Situation_Status__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Situation_Status__c</fullName>
    <description>Details whether an emergency is currently occurring</description>
    <label>Emergency Situation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Declared</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPMS_Emergency_Situation__c/fields/Emergency_Situation_Type__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Situation_Type__c</fullName>
    <description>Details what emergency has occured</description>
    <label>Emergency Situation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>Pandemic</fullName>
            </value>
            <value>
                <fullName>Epidemic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPMS_Emergency_Situation__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Details end date of emergency situation</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GPMS_Emergency_Situation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Details start date of emergency situation</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EmergencySituationMessageControllerTest.cls
@IsTest
public class EmergencySituationMessageControllerTest {

    @IsTest
    static void testEmergencySituationMessageController() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
        	GPMS_Emergency_Situation__c esRecord = new GPMS_Emergency_Situation__c();
            esRecord.Emergency_Situation_Status__c = 'Declared';
            esRecord.Emergency_Situation_Type__c = 'Disaster';
            esRecord.Start_Date__c = Date.newInstance(2022, 11, 01);
            esRecord.End_Date__c = Date.newInstance(2022, 11, 07);
            insert esRecord;
            ApexPages.StandardController sc = new ApexPages.StandardController(esRecord);
            
            EmergencySituationMessageController controller = new EmergencySituationMessageController(sc);
            System.assertNotEquals(null, controller.customDelete(), 'PageReference should not be null.');
            
            Integer numRecords = (Integer) [SELECT COUNT(Id) num
                                  FROM GPMS_Emergency_Situation__c
                                  WHERE Id = :esRecord.Id][0].get('num');
            System.assertEquals(0, numRecords, 'Record should be deleted.');    
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testDMLException() {
        User adminUser = TestDataFactory.createSystemAdminUser();
        Test.startTest();
        System.runAs(adminUser) {
            GPMS_Emergency_Situation__c esRecord = new GPMS_Emergency_Situation__c();
            esRecord.Emergency_Situation_Status__c = 'Declared';
            esRecord.Emergency_Situation_Type__c = 'Disaster';
            esRecord.Start_Date__c = Date.newInstance(2022, 11, 01);
            esRecord.End_Date__c = Date.newInstance(2022, 11, 07);
            
            // Record not inserted
            ApexPages.StandardController sc = new ApexPages.StandardController(esRecord);
            
            EmergencySituationMessageController controller = new EmergencySituationMessageController(sc);
            System.assertEquals(null, controller.customDelete(), 'PageReference should be null due to exception thrown.'); 
        }
        Test.stopTest();
    }
}