force-app/main/default/objects/Contact/fields/Contact_type__c.field-meta.xml
<CustomField>
    <fullName>Contact_type__c</fullName>
    <label>Contact type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QFR Primary Contact</fullName>
            </value>
            <value>
                <fullName>Food and Nutrition Contact</fullName>
            </value>
            <value>
                <fullName>Home Care Contact</fullName>
            </value>
            <value>
                <fullName>Residential Care Contact</fullName>
            </value>
            <value>
                <fullName>Financial Reporting Contacts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Financial_Contact_QFR_ACFR.recordType-meta.xml
<RecordType>
    <fullName>Financial_Contact_QFR_ACFR</fullName>
    <active>true</active>
    <label>Financial Contact QFR ACFR</label>
</RecordType>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Associated Contacts</label>
    <nameField>
        <displayFormat>CRL-{00000}</displayFormat>
        <label>Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact, Record Id of the related Contact record.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contact_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address of contact</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <inlineHelpText>Please enter a valid mobile number or phone number with area code.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>(Generic NAPS Position Name) The role of this contact</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Contact</fullName>
            </value>
            <value>
                <fullName>Assessment Service Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Assessor</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Financial Management</fullName>
            </value>
            <value>
                <fullName>Funding Agreement Variations</fullName>
            </value>
            <value>
                <fullName>Funding Submissions</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Aged Care Program Contact</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Key Personnel</fullName>
            </value>
            <value>
                <fullName>General Staff</fullName>
            </value>
            <value>
                <fullName>Authorised Person</fullName>
            </value>
            <value>
                <fullName>Applicant Representative</fullName>
            </value>
            <value>
                <fullName>Liaison</fullName>
            </value>
            <value>
                <fullName>Assessment Service Leader</fullName>
            </value>
            <value>
                <fullName>Activity Contact</fullName>
            </value>
            <value>
                <fullName>Acquittal/Financial Reporting</fullName>
            </value>
            <value>
                <fullName>Assessment Service Administrator</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate Support</fullName>
            </value>
            <value>
                <fullName>Assessment Service Delegate</fullName>
            </value>
            <value>
                <fullName>Choice Attributes</fullName>
            </value>
            <value>
                <fullName>Care Services Management</fullName>
            </value>
            <value>
                <fullName>Remittance/RCTI</fullName>
            </value>
            <value>
                <fullName>High level contact</fullName>
                <label>High Level Contact</label>
            </value>
            <value>
                <fullName>Service Monitoring &amp; Reports</fullName>
            </value>
            <value>
                <fullName>Centre Management</fullName>
            </value>
            <value>
                <fullName>Aged Care Service Manager</fullName>
            </value>
            <value>
                <fullName>QFR Primary Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/recordTypes/FinancialContactQFRACFR.recordType-meta.xml
<RecordType>
    <fullName>FinancialContactQFRACFR</fullName>
    <active>true</active>
    <label>FinancialContactQFRACFR</label>
</RecordType>

force-app/main/default/classes/AcfrContactManagment.cls
public without sharing class AcfrContactManagment implements Callable {
  public Object call(String action, Map<String, Object> args) {
    Map<String, Object> input = (Map<String, Object>) args.get('input');
    Map<String, Object> output = (Map<String, Object>) args.get('output');
    Map<String, Object> options = (Map<String, Object>) args.get('options');

    switch on action {
      when 'updateContactAndContactRelationShip' {
        Boolean isUpdated = updateContactAndContactRelationShip(
          (String) input.get('cRelationId'),
          (String) input.get('firstName'),
          (String) input.get('lastName'),
          (String) input.get('position'),
          (String) input.get('email'),
          (String) input.get('phone')
        );
        output.put(
          'updateContactAndContactRelationShip',
          JSON.serialize(isUpdated)
        );
        return true;
      }
      when 'addContactAndContactRelationShip' {
        Boolean isAddMethod = addContactAndContactRelationShip(
          (String) input.get('accountId'),
          (String) input.get('firstName'),
          (String) input.get('lastName'),
          (String) input.get('position'),
          (String) input.get('email'),
          (String) input.get('phone'),
          (String) input.get('role')
        );
        output.put(
          'addContactAndContactRelationShip',
          JSON.serialize(isAddMethod)
        );
        return true;
      }
      when else {
        throw new ExtensionMalformedCallException('Method not implemented');
      }
    }
  }

  public static Boolean updateContactAndContactRelationShip(
    String cRelationId,
    String firstName,
    String lastName,
    String position,
    String email,
    string phone
  ) {
    try {
      Contact_Relationship__c crelation = [
        SELECT id, contact__r.Id
        FROM Contact_Relationship__c
        WHERE id = :cRelationId
        LIMIT 1
      ];
      Contact c = [SELECT id FROM Contact WHERE id = :crelation.contact__r.Id];
      c.FirstName = firstName;
      c.LastName = lastName;
      c.phone = phone;
      c.Email = email;
      crelation.Email__c = email;
      crelation.Primary_Contact__c = phone;
      crelation.Position_Title__c = position;
      update crelation;
      update c;
    } catch (Exception e) {
      dohagedcare.logger.error(e.getMessage(), e, 'QFR').log();
    }
    return true;
  }

  public static Boolean addContactAndContactRelationShip(
    String accountId,
    String firstName,
    String lastName,
    String position,
    String email,
    string phone,
    String role
  ) {
     try {
      Contact c = new Contact();
      c.FirstName = firstName;
      c.LastName = lastName;
      c.phone = phone;
      c.Email = email;
      c.accountId = accountId;
      c.Contact_type__c = 'QFR Primary Contact';
         c.Salutation = 'Ms';
      c.recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
        .get('Financial_Contact_QFR_ACFR')
        .getRecordTypeId();
      if (c != null)
        insert c;

      Contact_Relationship__c cr = new Contact_Relationship__c();
      cr.Email__c = email;
      cr.Primary_Contact__c = phone;
      cr.Position_Title__c = position;
      cr.recordTypeId = Schema.SObjectType.Contact_Relationship__c.getRecordTypeInfosByDeveloperName()
        .get('FinancialContactQFRACFR')
        .getRecordTypeId();
      cr.account__c = accountId;
      cr.role__c = role;
      cr.Start_date__c = System.today();
      cr.Contact__c = c.id;

      insert cr;
    } catch (Exception e) {
      dohagedcare.logger.error(e.getMessage(), e, 'QFR').log();
    }
    return true;
  }
  public class ExtensionMalformedCallException extends Exception {
  }
}