force-app/main/default/objects/RegulatoryCodeViolation/fields/Date_Decision_Applied__c.field-meta.xml
<CustomField>
    <fullName>Date_Decision_Applied__c</fullName>
    <label>Date Decision Applied</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Date_Decision_Ends__c.field-meta.xml
<CustomField>
    <fullName>Date_Decision_Ends__c</fullName>
    <label>Date Decision Ends</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Service_Name_lookup__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Service care type is not Home Care or Residential</errorMessage>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Home Care</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.Care_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>BusinessLicense.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Service_Provider_Name_lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Regulatory Decisions</relationshipLabel>
    <relationshipName>Regulatory_Decisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegulatoryCodeViolationSelector.cls
/**
 * @author      Rami Zuhairi
 * @date        23-02-2023
 * @description Selector class to get data from RegulatoryCodeViolation
 */
public with sharing class RegulatoryCodeViolationSelector {
    public static RegulatoryCodeViolationSelector singletonInstance {
        get {
            if (singletonInstance == null) {
                singletonInstance = new RegulatoryCodeViolationSelector();
            }
            return singletonInstance;
        }
        private set;
    }

    public List<RegulatoryCodeViolation> getRDListBySFServiceIds(
        Id sfServiceAccountRelationshipId
    ) {
        return [
            SELECT
                Id,
                Service_Name_lookup__c,
                Service_Name_lookup__r.name,
                Status,
                ViolationType.name,
                Date_Decision_Ends__c,
                Date_Decision_Applied__c
            FROM RegulatoryCodeViolation
            WHERE
                Service_Name_lookup__c = :sfServiceAccountRelationshipId
                AND (Status = 'Current'
                OR (Status = 'Non-Current'
                AND Date_Decision_Ends__c >= LAST_N_DAYS:1095))
            ORDER BY Status, Date_Decision_Applied__c DESC
        ];
    }
}