force-app/main/default/objects/RegulatoryCodeViolation/fields/Decision_Details__c.field-meta.xml
<CustomField>
    <fullName>Decision_Details__c</fullName>
    <label>Decision Details</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <label>Progress</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RegulatoryCodeViolation/fields/Reason_for_issuing_Regulatory_Decision__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_issuing_Regulatory_Decision__c</fullName>
    <label>Reason for issuing Regulatory Decision</label>
    <length>8000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/srqiOmniscriptLWCRichText.cls
@SuppressWarnings('apex:AvoidGlobalModifier')
global with Sharing class srqiOmniscriptLWCRichText implements omnistudio.VlocityOpenInterface2 {
    global Object call(String action, Map<String, Object> args) {
       
       Map<String, Object> input = (Map<String, Object>)args.get('input');
       Map<String, Object> output = (Map<String, Object>)args.get('output');
       Map<String, Object> options = (Map<String, Object>)args.get('options');

       return invokeMethod(action, input, output, options);
   }
  global Boolean invokeMethod(
    String methodName,
    Map<String, Object> input,
    Map<String, Object> output,
    Map<String, Object> options
  ) {
    switch on methodName {
      when 'getResponseforIssue' {
        string datatableDef = getResponseforIssue(
          (String) input.get('recordid')
        );
        output.put(
          'getResponseforIssue',
          JSON.deserializeUntyped(JSON.serialize(datatableDef))
        );
        return true;
      }
        when 'getDecisionDetails' {
        string DecisionDetails = getDecisionDetails(
          (String) input.get('recordid')
        );
        output.put(
          'getDecisionDetails',
          JSON.deserializeUntyped(JSON.serialize(DecisionDetails))
        );
        return true;
      }
        when 'getProgressDetails' {
        string ProgressDetails = getProgressDetails(
          (String) input.get('recordid')
        );
        output.put(
          'getProgressDetails',
          JSON.deserializeUntyped(JSON.serialize(ProgressDetails))
        );
        return true;
      }
        when else {
        throw new QiSrCustomDatatableException(
          'Specified action not supported'
        );
      }

    }
  }
public class QiSrCustomDatatableException extends Exception {
  }
    public static string getResponseforIssue( string Id) {
        
          String returnParam='';
          List<RegulatoryCodeViolation> ResponseforIssue =[select Reason_for_issuing_Regulatory_Decision__c from RegulatoryCodeViolation where Id =: Id LIMIT 1 ];
 			returnParam= ResponseforIssue[0].Reason_for_issuing_Regulatory_Decision__c;
        
            return returnParam;
       
    }
     public static string getDecisionDetails( string Id) {
        
          String returnParam='';
          List<RegulatoryCodeViolation> DecisionDetails =[select Decision_Details__c from RegulatoryCodeViolation where Id =: Id LIMIT 1 ];
 			returnParam= DecisionDetails[0].Decision_Details__c;
        
            return returnParam;
       
    }
     public static string getProgressDetails( string Id) {
        
          String returnParam='';
         List<RegulatoryCodeViolation> ProgressDetails =[select Progress__c  from RegulatoryCodeViolation where Id =: Id LIMIT 1 ];
        returnParam = ProgressDetails[0].Progress__c;
            return returnParam;
       
    }

}