force-app/main/default/objects/File_Staging__c/File_Staging__c.object-meta.xml
<CustomObject>
    <description>This is the object for File Staging</description>
    <label>File Upload</label>
    <nameField>
        <label>File Upload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Uploads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Staging__c/fields/Reporting_Category__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Category__c</fullName>
    <label>Reporting Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Sources</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Staging__c/recordTypes/CEI.recordType-meta.xml
<RecordType>
    <fullName>CEI</fullName>
    <active>true</active>
    <label>CEI</label>
</RecordType>

force-app/main/default/globalValueSets/Data_Sources.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CEI</fullName>
    </customValue>
    <customValue>
        <fullName>QI</fullName>
    </customValue>
    <masterLabel>Data Sources</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchOnceOffUpdateFileStageObj.cls
/**
* @Author             : smita kagde
* @Description        : Batch Class
* @Modification Log   :
* ---------------------------------------------------
* Date           Author                Details
* ---------------------------------------------------
* 29/04/2023     smita kagde    This Batch class for Once off, Need to run
								in prod for all File_Staging__c record where Catergory is CEI
*/
public with sharing class BatchOnceOffUpdateFileStageObj implements Database.Batchable<sObject> {

    public String query;
   	public  Database.QueryLocator start(Database.BatchableContext BC){
         query = 'SELECT Id,Reporting_Category__c,RecordTypeId ' +
                    'FROM File_Staging__c WHERE '+
                    'Reporting_Category__c = \'CEI\'';
        return Database.getQueryLocator(query);
    }

    public  void execute(Database.BatchableContext BC, List<sObject> scope){
        Id gsRecordTypeID = Schema.SObjectType.File_Staging__c.getRecordTypeInfosByName().get('CEI').getRecordTypeId();
    	List<File_Staging__c> fileStagingList = (List<File_Staging__c>)scope; //List of File_Staging__c
        system.debug('size ==> ' + scope.size());
        try{
            // update RecordType on File_Staging__c
            for(File_Staging__c thisFSList : fileStagingList ){
                thisFSList.RecordTypeId = gsRecordTypeID;
            }

            update fileStagingList;
        }catch(Exception exp){
        }
    }

    //Any post processing steps here
    public  void finish(Database.BatchableContext BC){
       system.debug('Record Type is Updated for all exsiting FileStaging reord for all Reporting_Category__c= CEI');
    }

}