force-app/main/default/objects/File_Staging__c/File_Staging__c.object-meta.xml
<CustomObject>
    <description>This is the object for File Staging</description>
    <label>File Upload</label>
    <nameField>
        <label>File Upload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Uploads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Staging__c/fields/Reporting_Category__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Category__c</fullName>
    <label>Reporting Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Sources</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>File Stagings</relationshipLabel>
    <relationshipName>File_Stagings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/recordTypes/CEI.recordType-meta.xml
<RecordType>
    <fullName>CEI</fullName>
    <active>true</active>
    <label>CEI</label>
</RecordType>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Data_Sources.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CEI</fullName>
    </customValue>
    <customValue>
        <fullName>QI</fullName>
    </customValue>
    <masterLabel>Data Sources</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchOnceOffUpdateFileStageObjTest.cls
@isTest
private class BatchOnceOffUpdateFileStageObjTest {
     @testSetup
  static void setupData() {
    ContentVersion testContVer = new ContentVersion();  
    User testUser = createTestUser();
    System.runAs(testUser) {
      // Create Reporting_Period__c record
      String year = 'Year';
      Reporting_Period__c reportingPeriodList = TestDataFactory.createReportingPeriod(
        year
      );
      insert reportingPeriodList;
 
      //Populate and create ContentVersion
      testContVer.Title = 'Test Docs';
      testContVer.PathOnClient = 'SF_ELO_Code.txt';
      testContVer.VersionData = Blob.valueOf('Test Content');
      testContVer.IsMajorVersion = true;
      insert testContVer;
    }
  }
  public static User createTestUser() {
    String uniqueUserName =
      'AdminFileUploaduser' +
      DateTime.now().getTime() +
      '@testorg.com';
    Profile prof = [
      SELECT Id, Name
      FROM Profile
      WHERE Name LIKE 'Project Administrator'
    ];
    User user = new User();
    user.firstName = 'test2';
    user.lastName = 'test3';
    user.ProfileId = prof.Id;
    user.Username = uniqueUserName;
    user.email = 'test@test.com';
    user.Alias = 'tst';
    user.TimeZoneSidKey = 'Australia/Sydney';
    user.LocaleSidKey = 'en_AU';
    user.EmailEncodingKey = 'UTF-8';
    user.LanguageLocaleKey = 'en_US';
    insert user;
    return user;
  }

    @isTest
    static void testBatchUpdateRecordType() {
      ContentVersion testContVer = new ContentVersion();  
   	 User testUser = createTestUser();
    System.runAs(testUser) {
      String year = 'Year';
      Reporting_Period__c reportingPeriodList = TestDataFactory.createReportingPeriod(
        year
      );
      insert reportingPeriodList;

      //Populate and create ContentVersion
      testContVer.Title = 'TestDocs.csv';
      testContVer.PathOnClient = 'SF_ELO_Code.txt';
      testContVer.VersionData = Blob.valueOf('Test Content');
      testContVer.IsMajorVersion = true;
      insert testContVer;
      Id reportingPeriodId = [SELECT Id FROM Reporting_Period__c LIMIT 1].Id;
      Id contentDocumentId = [
        SELECT ContentDocumentId
        FROM ContentVersion
        WHERE Title = 'TestDocs.csv'
      ]
      .ContentDocumentId;
       SrqiCSVFileReadLWCController.insertFileEntryFields(
        contentDocumentId,
        reportingPeriodId,
        '12345T'
      );
    }
	//List<File_Staging__c> fileStagingList= [select Id,Reporting_Category__c,RecordType.Name,RecordTypeId from File_Staging__c WHERE Reporting_Category__c ='CEI'];
        // Instantiate batch class
        BatchOnceOffUpdateFileStageObj batchObj = new BatchOnceOffUpdateFileStageObj();

        // Call Database.executeBatch()
        Test.startTest();
        Database.executeBatch(batchObj);
        Test.stopTest();
      
    }
}