force-app/main/default/objects/File_Staging__c/File_Staging__c.object-meta.xml
<CustomObject>
    <description>This is the object for File Staging</description>
    <label>File Upload</label>
    <nameField>
        <label>File Upload Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>File Uploads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Staging__c/fields/File_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>File_CreatedDate__c</fullName>
    <description>This field will hold the CreatedDate of the csv file that inserted from LWC custom comp to content document object. Also used to record the date/time in which a bulk upload file was submitted.</description>
    <label>File_CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/File_Id__c.field-meta.xml
<CustomField>
    <fullName>File_Id__c</fullName>
    <description>this filed will hold the ContnetDocumentId after the file insertion</description>
    <label>File_Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/HDP_File_Ref__c.field-meta.xml
<CustomField>
    <fullName>HDP_File_Ref__c</fullName>
    <description>HDP File reference number needed for CEI file upload</description>
    <inlineHelpText>HDP File reference number needed for CEI</inlineHelpText>
    <label>HDP File Ref</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Reporting_Category__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Category__c</fullName>
    <label>Reporting Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Sources</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>File Stagings</relationshipLabel>
    <relationshipName>File_Stagings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Staging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Ready To Publish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Staging__c/recordTypes/CEI.recordType-meta.xml
<RecordType>
    <fullName>CEI</fullName>
    <active>true</active>
    <label>CEI</label>
</RecordType>

force-app/main/default/objects/File_Staging__c/recordTypes/QI.recordType-meta.xml
<RecordType>
    <fullName>QI</fullName>
    <active>true</active>
    <label>QI</label>
</RecordType>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/Current_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Current_Reporting_Period__c</fullName>
    <description>Displays true if current reporting period.</description>
    <formula>IF( TODAY( ) &gt;= Start_Date__c &amp;&amp; TODAY( ) &lt;= End_Date__c, True, False )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Short__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Short__c</fullName>
    <description>Shortened version or Reporting Period to match Siebel</description>
    <formula>IF( ISPICKVAL(Reporting_Period_Type__c, &apos;Quarter&apos;),
&apos;Quarter &apos; &amp;
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3 ,&apos;3&apos;,
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6 ,&apos;4&apos;,
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9 ,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12 ,&apos;2&apos;,null) ) ) ) &amp;
&apos; FY &apos; &amp;
IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1), 2),
RIGHT( TEXT(YEAR(Start_Date__c)), 2)) &amp; &apos; - &apos; &amp;
IF(MONTH(End_Date__c) &gt;= 7, RIGHT( TEXT(YEAR(End_Date__c) +1), 2),
RIGHT( TEXT(YEAR(End_Date__c)), 2)),

TEXT(YEAR(Start_Date__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporting Period Short</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Data_Sources.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CEI</fullName>
    </customValue>
    <customValue>
        <fullName>QI</fullName>
    </customValue>
    <masterLabel>Data Sources</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SrqiCSVFileReadLWCController.cls
/**
 * @author Rami Zuhairi
 * @date 06/2022
 * @objects Reporting_Period__c, ContentDocument, File_Staging__c
 * @description developed APEX class for file upload LWC component that will read values of both CER and QI and insert the value to file staging.
 */
public with sharing class SrqiCSVFileReadLWCController {
    // Method to get the Current year of Reporting_Period
    @AuraEnabled(Cacheable=true)
    public static List<Reporting_Period__c> getRecordsRP() {
        List<Reporting_Period__c> nameRPList;
        try {
            nameRPList = [
               SELECT Reporting_Period_Short__c FROM Reporting_Period__c Where Current_Reporting_Period__c   = true AND Reporting_Period_Type__c = 'Year' ORDER BY Reporting_Period__c DESC LIMIT 1
            ];
            return nameRPList;
        } catch (Exception ex) {
            dohagedcare.Logger.error(ex.getMessage(), ex, 'QISR').log();
            throw new AuraHandledException('Error in getting reporting period. Please refresh page or contact system administrator');
        }
    }

    @AuraEnabled
    public static List<File_Staging__c> insertFileEntryFields(
        Id contentDocumentId,
        Id reportingPeriodId,
        String hdpFileRefNum
    ) {
        try {
            ContentVersion contentVersionObj = [
                SELECT ContentDocumentId, CreatedById, Title, CreatedDate
                FROM ContentVersion
                WHERE ContentDocumentId = :contentDocumentId
            ];

            List<File_Staging__c> fsList = new List<File_Staging__c>();
           	// Adding record type as a part of 308014 requirment
            File_Staging__c fileStatingObj = new File_Staging__c();
            Id ceiRecordTypeID = Schema.SObjectType.File_Staging__c.getRecordTypeInfosByName().get('CEI').getRecordTypeId();

            fileStatingObj.File_Id__c = contentVersionObj.ContentDocumentId;
            fileStatingObj.OwnerId = contentVersionObj.CreatedById;
            fileStatingObj.Name = contentVersionObj.Title;
            fileStatingObj.File_Name__c = contentVersionObj.Title;
            fileStatingObj.File_CreatedDate__c = contentVersionObj.CreatedDate;
            fileStatingObj.Status__c = 'Ready To Publish';
            fileStatingObj.Reporting_Period__c = reportingPeriodId;
            fileStatingObj.Reporting_Category__c = 'CEI';
            fileStatingObj.RecordTypeId = ceiRecordTypeID;
            fileStatingObj.HDP_File_Ref__c = hdpFileRefNum;
            fsList.add(fileStatingObj);

            if (!fsList.isEmpty()) {
                insert fsList;
                ContentDocumentLink cDocLink = new ContentDocumentLink();
                cDocLink.ContentDocumentId = contentDocumentId;//Add ContentDocumentId
                cDocLink.LinkedEntityId = fsList[0].Id;//Add attachment parentId
                cDocLink.ShareType = 'I';//V - Viewer permission. C - Collaborator permission. I - Inferred permission.
                cDocLink.Visibility = 'InternalUsers';//AllUsers, InternalUsers, SharedUsers
                insert cDocLink;
            }
            return fsList;
        } catch (Exception ex) {
            dohagedcare.Logger.error(ex.getMessage(), ex, 'QISR').log();
            throw new AuraHandledException('Error in updating staging file. Please try again or contact system administrator.');
        }
    }
}