force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{00000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/GPMS_Proposed_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Proposed_Transfer_Date__c</fullName>
    <label>Proposed Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to show the Status of the Event.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting Response to Notice to Resolve</fullName>
            </value>
            <value>
                <fullName>Vetoed</fullName>
            </value>
            <value>
                <fullName>Transfer: Activated</fullName>
            </value>
            <value>
                <fullName>Transfer: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Pending RFI</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not Revoked</fullName>
            </value>
            <value>
                <fullName>Revoked: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cessation Applied</fullName>
            </value>
            <value>
                <fullName>Automatic Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Vetoed by Department</fullName>
            </value>
            <value>
                <fullName>Vetoed by AAT</fullName>
            </value>
            <value>
                <fullName>Variation: Activated</fullName>
            </value>
            <value>
                <fullName>Variation: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Variation: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Approved by Department</fullName>
            </value>
            <value>
                <fullName>Not Approved by AAT</fullName>
            </value>
            <value>
                <fullName>Approved: Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status_Date__c.field-meta.xml
<CustomField>
    <fullName>Status_Date__c</fullName>
    <label>Status Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <description>Places: Transfer - S16-13/S16-1</description>
    <label>Transfer</label>
</RecordType>

force-app/main/default/classes/GPMSTransferEventPendingBatchTest.cls
@isTest
public class GPMSTransferEventPendingBatchTest {
    @TestSetup
    static void makeData(){
        Event__c event = new Event__c(Status__c = 'Pending', GPMS_Proposed_Transfer_Date__c = Date.today());
        insert event;
    }




    @isTest
    static void testBatch(){
        User user = createTestUser();
        System.runAs(user) {           
            Test.startTest();
            GPMSTransferEventPendingBatch batch = new GPMSTransferEventPendingBatch(); 
            Database.executeBatch(batch);
            Test.stopTest();
            Event__c event = [SELECT Id, Status__c,  Status_Date__c FROM Event__c WHERE GPMS_Proposed_Transfer_Date__c <= TODAY AND Status__c = 'Automatic Transfer: Pending Activation'];
            System.assertEquals(event.Status_Date__c, Date.today());
        }
    }

    public static User createTestUser() {
        Profile prof = [SELECT Id, Name FROM Profile WHERE Name LIKE 'System Administrator'];
        User user = new User();
        user.firstName = 'test1';
        user.lastName = 'test2';
        user.ProfileId = prof.Id;
        user.Username = 'tester1@unittest.com';
        user.email = 'test@test.com';
        user.Alias = 'tst';
        user.TimeZoneSidKey = 'Australia/Sydney';
        user.LocaleSidKey = 'en_AU'; 
        user.EmailEncodingKey = 'UTF-8'; 
        user.LanguageLocaleKey = 'en_US';
        insert user;
        return user;
    }
}