force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{00000000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Batch_Event_Completed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Event_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Event Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Cessation_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Cessation_Effective_Date__c</fullName>
    <label>Cessation Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Care_Setting_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Care_Setting_Effective_Date__c</fullName>
    <description>The date to change the care setting</description>
    <label>Care Setting Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Conversion_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Conversion_Effective_Date__c</fullName>
    <description>The date to convert care level mix</description>
    <label>Conversion Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Date_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Date_Effective_From__c</fullName>
    <description>Indicates the date that the ceasing took effect.</description>
    <label>Date Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Proposed_Operational_Date__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Proposed_Operational_Date__c</fullName>
    <description>The proposed operation date for bring online event</description>
    <label>Proposed Operational Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Proposed_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Proposed_Transfer_Date__c</fullName>
    <label>Proposed Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GPMS_Proposed_Variation_Day__c.field-meta.xml
<CustomField>
    <fullName>GPMS_Proposed_Variation_Day__c</fullName>
    <label>Proposed Variation Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to show the Status of the Event.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Not Approved: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Awaiting Response to Notice to Resolve</fullName>
            </value>
            <value>
                <fullName>Vetoed</fullName>
            </value>
            <value>
                <fullName>Transfer: Activated</fullName>
            </value>
            <value>
                <fullName>Transfer: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Pending RFI</fullName>
            </value>
            <value>
                <fullName>Vetoed: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not Revoked</fullName>
            </value>
            <value>
                <fullName>Revoked: Under Reconsideration</fullName>
            </value>
            <value>
                <fullName>Revoked: Under AAT Reconsideration</fullName>
            </value>
            <value>
                <fullName>Cessation Applied</fullName>
            </value>
            <value>
                <fullName>Automatic Transfer: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Vetoed by Department</fullName>
            </value>
            <value>
                <fullName>Vetoed by AAT</fullName>
            </value>
            <value>
                <fullName>Variation: Activated</fullName>
            </value>
            <value>
                <fullName>Variation: Pending Activation</fullName>
            </value>
            <value>
                <fullName>Variation: Not to be Activated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Not Approved by Department</fullName>
            </value>
            <value>
                <fullName>Not Approved by AAT</fullName>
            </value>
            <value>
                <fullName>Approved: Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Bring_Online.recordType-meta.xml
<RecordType>
    <fullName>Bring_Online</fullName>
    <active>true</active>
    <description>Used for record the bring online</description>
    <label>Bring Online</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/Change_Care_Setting.recordType-meta.xml
<RecordType>
    <fullName>Change_Care_Setting</fullName>
    <active>true</active>
    <description>Event triggered when care settings are changed in an allotment</description>
    <label>Change Care Setting</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/GPMS_Cease_Places.recordType-meta.xml
<RecordType>
    <fullName>GPMS_Cease_Places</fullName>
    <active>true</active>
    <description>Used for recording Ceased places</description>
    <label>Cease Places</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/GPMS_Cease_S14_9_Places.recordType-meta.xml
<RecordType>
    <fullName>GPMS_Cease_S14_9_Places</fullName>
    <active>true</active>
    <description>Used to record the event for S14-9 ceased places</description>
    <label>Cease S14-9 Places</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/GPMS_Deed_of_Variation.recordType-meta.xml
<RecordType>
    <fullName>GPMS_Deed_of_Variation</fullName>
    <active>true</active>
    <description>Deed of variation event for convert care mix function</description>
    <label>Deed of Variation</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/GPMS_Relinquish.recordType-meta.xml
<RecordType>
    <fullName>GPMS_Relinquish</fullName>
    <active>true</active>
    <description>Relinquish Event</description>
    <label>Relinquish Places</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/NATSIFAC_Cease_Places.recordType-meta.xml
<RecordType>
    <fullName>NATSIFAC_Cease_Places</fullName>
    <active>true</active>
    <label>NATSIFAC Cease Places</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/NATSIFAC_Reinstate_Places.recordType-meta.xml
<RecordType>
    <fullName>NATSIFAC_Reinstate_Places</fullName>
    <active>true</active>
    <label>NATSIFAC Reinstate Places</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/Revoke.recordType-meta.xml
<RecordType>
    <fullName>Revoke</fullName>
    <active>true</active>
    <label>Revoke</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/Surrender.recordType-meta.xml
<RecordType>
    <fullName>Surrender</fullName>
    <active>true</active>
    <label>Surrender</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <description>Places: Transfer - S16-13/S16-1</description>
    <label>Transfer</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/Variation.recordType-meta.xml
<RecordType>
    <fullName>Variation</fullName>
    <active>true</active>
    <label>Variation</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/Variations_by_Provider_Secretary.recordType-meta.xml
<RecordType>
    <fullName>Variations_by_Provider_Secretary</fullName>
    <active>true</active>
    <label>Variations by Provider &amp; Secretary</label>
</RecordType>

force-app/main/default/objects/Places_Allotment__c/Places_Allotment__c.object-meta.xml
<CustomObject>
    <label>Places Packet</label>
    <nameField>
        <displayFormat>BAID-{000000}</displayFormat>
        <label>Places Packet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places Packets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Places_Allotment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Places_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Delivery_Area__c/Service_Delivery_Area__c.object-meta.xml
<CustomObject>
    <label>Service Delivery Area</label>
    <nameField>
        <displayFormat>SDA-{0000000}</displayFormat>
        <label>Service Delivery Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Delivery Area</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Delivery_Area__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Service Delivery Area</relationshipLabel>
    <relationshipName>Service_Delivery_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Delivery_Area__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Non-current</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Approved-not activated</fullName>
            </value>
            <value>
                <fullName>Not approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GPMSScheduledEventActionsBatch.cls
/****************************************************************************************************
* @CreatedBy   : Yohan Perera
* @CreatedDate : 16-Dec-2022
* @Description : Handles the logic to perform event actions when GPMS_Proposed_Operational_Date__c
                 is lapsed on the Event.
* @Test Class  : GPMSScheduledEventActionsBatchTest
*****************************************************************************************************/
public with sharing class GPMSScheduledEventActionsBatch implements Database.Batchable<SObject>,Schedulable {

    private static Map<String, Schema.RecordTypeInfo> recordTypeInfos = Schema.SObjectType.Event__c.getRecordTypeInfosByDeveloperName();

    public static final Id RT_EVENT_CEASE_S14_9 = recordTypeInfos.get('GPMS_Cease_S14_9_Places').getRecordTypeId();
    public static final Id RT_EVENT_CHANGE_CARE_SETTING = recordTypeInfos.get('Change_Care_Setting').getRecordTypeId();
    public static final Id RT_EVENT_DEED_OF_VARIATION = recordTypeInfos.get('GPMS_Deed_of_Variation').getRecordTypeId();
    public static final Id RT_EVENT_CEASE = recordTypeInfos.get('GPMS_Cease_Places').getRecordTypeId();
    public static final Id RT_EVENT_VARIATION = recordTypeInfos.get('Variation').getRecordTypeId();
    public static final Id RT_EVENT_RELINQUISH = recordTypeInfos.get('GPMS_Relinquish').getRecordTypeId();
    public static final Id RT_EVENT_REVOKE = recordTypeInfos.get('Revoke').getRecordTypeId();
    public static final Id RT_EVENT_SURRENDER = recordTypeInfos.get('Surrender').getRecordTypeId();
    public static final Id RT_EVENT_TRANSFER = recordTypeInfos.get('Transfer').getRecordTypeId();
    public static final Id RT_EVENT_BRING_ONLINE = recordTypeInfos.get('Bring_Online').getRecordTypeId();
    public static final Id RT_EVENT_NATSIFAC_REINSTATE_PLACES = recordTypeInfos.get('NATSIFAC_Reinstate_Places').getRecordTypeId();
    public static final Id RT_EVENT_NATSIFAC_CEASE = recordTypeInfos.get('NATSIFAC_Cease_Places').getRecordTypeId();
    public static final Id RT_EVENT_VARIATION_PA = recordTypeInfos.get('Variations_by_Provider_Secretary').getRecordTypeId();

    public static final String EVENT_STATUS_PENDING = 'Pending';
    public static final String EVENT_STATUS_APPROVED = 'Approved';
    public static final String EVENT_STATUS_VARIATION_ACTIVATED = 'Variation: Activated';
    public static final String EVENT_STATUS_TRANSFER_ACTIVATED = 'Transfer: Activated';
    public static final String EVENT_STATUS_APPROVED_ACTIVATED = 'Approved: Activated';
    public static final String EVENT_STATUS_REVOKED = 'Revoked';

    public static final String HOME_CARE = 'Home Care';
    public static final String RESIDENTIAL = 'Residential';

    public static final String INPUT = 'input';
    public static final String OUTPUT = 'output';

    private String queryString;
    private Set<Id> recIdSet;
    private Date today;

    ////////* -------- SCHEDULE -------- *//////////
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new GPMSScheduledEventActionsBatch());
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, RecordTypeId FROM Event__c WHERE'
            + ' ((RecordTypeId = :RT_EVENT_CEASE_S14_9 AND Status__c = :EVENT_STATUS_PENDING AND Cessation_Effective_Date__c <= TODAY) OR' //PBI-284159
            + ' (RecordTypeId = :RT_EVENT_DEED_OF_VARIATION AND Status__c = :EVENT_STATUS_PENDING AND GPMS_Conversion_Effective_Date__c < TODAY) OR' //PBI-284204
            + ' (RecordTypeId = :RT_EVENT_CHANGE_CARE_SETTING AND Status__c = :EVENT_STATUS_PENDING AND GPMS_Care_Setting_Effective_Date__c < TODAY) OR' //PBI-284420
            + ' (RecordTypeId = :RT_EVENT_NATSIFAC_CEASE AND Status__c = :EVENT_STATUS_APPROVED AND GPMS_Date_Effective_From__c < TODAY) OR' //PBI-284889
            + ' (RecordTypeId = :RT_EVENT_VARIATION AND Status__c = :EVENT_STATUS_VARIATION_ACTIVATED AND GPMS_Proposed_Variation_Day__c <= TODAY) OR' //PBI-283643
            + ' (RecordTypeId = :RT_EVENT_RELINQUISH AND Status__c = :EVENT_STATUS_APPROVED AND GPMS_Date_Effective_From__c < TODAY) OR' //PBI-284337
            + ' (RecordTypeId = :RT_EVENT_REVOKE AND Status__c = :EVENT_STATUS_REVOKED AND GPMS_Date_Effective_From__c < TODAY) OR' //PBI-284307 / 284304
            + ' (RecordTypeId = :RT_EVENT_SURRENDER AND Status__c = :EVENT_STATUS_PENDING AND GPMS_Date_Effective_From__c < TODAY) OR' //PBI-284425
            + ' (RecordTypeId = :RT_EVENT_TRANSFER AND (Status__c = :EVENT_STATUS_TRANSFER_ACTIVATED OR Status__c = :EVENT_STATUS_APPROVED_ACTIVATED) AND GPMS_Proposed_Transfer_Date__c < TODAY) OR' //PBI-273243 //PBI-351953
            + ' (RecordTypeId = :RT_EVENT_BRING_ONLINE AND Status__c = :EVENT_STATUS_APPROVED AND GPMS_Proposed_Operational_Date__c < TODAY) OR' //PBI-283580
            + ' (RecordTypeId = :RT_EVENT_NATSIFAC_REINSTATE_PLACES AND Status__c = :EVENT_STATUS_APPROVED AND GPMS_Date_Effective_From__c < TODAY) OR' //PBI-284893
            + ' (RecordTypeId = :RT_EVENT_VARIATION_PA AND Status__c = :EVENT_STATUS_APPROVED AND GPMS_Proposed_Variation_Day__c < TODAY))' //PBI-284179
            + ' AND Batch_Event_Completed__c = FALSE';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Event__c> scope) {
        GPMSPerformEventAction performAction = new GPMSPerformEventAction();

        try {
            Map<String, Event__c> bringOnlineInputEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> ceaseS14EventsMap = new Map<String, Event__c>();
            Map<String, Event__c> natsifacCeaseEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> surrenderEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> relinquishEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> revocationEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> deedOfVariationEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> changeCareSettingsEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> natsifacReinstateEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> ceaseEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> transferEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> variationEventsMap = new Map<String, Event__c>();
            Map<String, Event__c> paVariationEventsMap = new Map<String, Event__c>();

            for (Event__c event : scope) {
                if (event.RecordTypeId == RT_EVENT_BRING_ONLINE) {
                    bringOnlineInputEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_CEASE_S14_9) {
                    ceaseS14EventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_NATSIFAC_CEASE) {
                    natsifacCeaseEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_SURRENDER) {
                    surrenderEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_RELINQUISH) {
                    relinquishEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_REVOKE) {
                    revocationEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_DEED_OF_VARIATION) {
                    deedOfVariationEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_CHANGE_CARE_SETTING) {
                    changeCareSettingsEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_NATSIFAC_REINSTATE_PLACES) {
                    natsifacReinstateEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_TRANSFER) {
                    transferEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_VARIATION) {
                    variationEventsMap.put(event.Id, event);
                } else if (event.RecordTypeId == RT_EVENT_VARIATION_PA) {
                    paVariationEventsMap.put(event.Id, event);
                } else {
                    //Do nothing
                }
            }

            List<Places_Allotment__c> placesToUpdateList = new List<Places_Allotment__c>();
            List<Service_Delivery_Area__c> sdasToUpdateList = new List<Service_Delivery_Area__c>();
            List<Event__c> eventsToUpdateList = new List<Event__c>();

            performAction.processBringOnlineEvents(bringOnlineInputEventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processCeaseS14_9Events(ceaseS14EventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processSurrenderEvents(surrenderEventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processRelinquishEvents(relinquishEventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processRevocationEvents(revocationEventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processDeedOfVariationEvents(deedOfVariationEventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processChangeCareSettingsEvents(changeCareSettingsEventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processNATSIFACCeaseEvents(natsifacCeaseEventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processNATSIFACReinstateEvents(natsifacReinstateEventsMap, placesToUpdateList, eventsToUpdateList, false);
            performAction.processTransferEvents(transferEventsMap, placesToUpdateList, sdasToUpdateList, eventsToUpdateList, false);
            performAction.processPAVariationEvents(paVariationEventsMap, placesToUpdateList, sdasToUpdateList, eventsToUpdateList, false);
            performAction.processVariationEvents(variationEventsMap, placesToUpdateList, sdasToUpdateList, eventsToUpdateList, false);

            if(!placesToUpdateList.isEmpty()) {
                Map<Id, Places_Allotment__c> pasToRemoveDuplicatesMap = new Map<Id, Places_Allotment__c>();
                for (Places_Allotment__c pa : placesToUpdateList) {
                    pasToRemoveDuplicatesMap.put(pa.Id, pa);
                }
                Database.update(pasToRemoveDuplicatesMap.values(), false);
            }

            if(!eventsToUpdateList.isEmpty()) {
                Database.update(eventsToUpdateList, false);
            }

            if(!sdasToUpdateList.isEmpty()) {
                Database.update(sdasToUpdateList, false);
            }

        } catch (Exception exp) {
            dohagedcare.Logger.error(exp.getMessage(),exp,'GPMS').Log();
        }
    }

    /////////* ------------ FINISH ------------- */////////
    public void finish(Database.BatchableContext bc) {
       //Do nothing
    }
}