force-app/main/default/objects/Service_Compliance_History__c/Service_Compliance_History__c.object-meta.xml
<CustomObject>
    <description>Holds a history of all Regulatory Decisions for a Service/Provider</description>
    <label>Service Compliance History</label>
    <nameField>
        <displayFormat>SCRH-{000000}</displayFormat>
        <label>SCR History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Compliance Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Compliance_History__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Compliance_History__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Service Compliance Historys</relationshipLabel>
    <relationshipName>Service_Compliance_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceComplianceHistoryTriggerService.cls
/****************************************************************************************************
* @CreatedBy   : Yohan Perera
* @CreatedDate : 1-11-2022
* @Description : 
* @Test Class  : 
*****************************************************************************************************/
public with sharing class ServiceComplianceHistoryTriggerService {
    
    public static void shareServiceComplianceHistoryRecords(Map<Id, Service_Compliance_History__c> newMap) {
        Map<Id, String> schToGroupMap = new Map<Id, String>();
        Map<String, Group> groupNameToGroupMap = new Map<String, Group>();
        List<Service_Compliance_History__share> sharesList = new List<Service_Compliance_History__share>();
        
        for (Id schId : newMap.keySet()) {
            schToGroupMap.put(schId, 'SRV_' + newMap.get(schId).Service__c);
        }
        
        for (Group g : [SELECT Id, DeveloperName FROM Group WHERE DeveloperName IN :schToGroupMap.values()]) {
            groupNameToGroupMap.put(g.DeveloperName, g);
        }
        
        for (Id schId : schToGroupMap.keySet()) {
            //Checks if a real group exists for the SCH Name
            if (groupNameToGroupMap.containsKey(schToGroupMap.get(schId))) {
                Group newGroup = groupNameToGroupMap.get(schToGroupMap.get(schId));
                
                Service_Compliance_History__share schShare = new Service_Compliance_History__share();
                schShare.ParentId = schId;
                schShare.UserOrGroupId = newGroup.Id;
                schShare.RowCause = Schema.Service_Compliance_History__share.RowCause.Provider__c;
                schShare.AccessLevel = 'Read';
                sharesList.add(schShare);
            }
        }
        
        if (!sharesList.isEmpty()) insert sharesList;
    }

}