force-app/main/default/objects/AccountContactRelation/fields/AccountRecordType__c.field-meta.xml
<CustomField>
    <fullName>AccountRecordType__c</fullName>
    <formula>Account.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountRecordType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Care_Type__c.field-meta.xml
<CustomField>
    <fullName>Care_Type__c</fullName>
    <label>Care Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home Care</fullName>
            </value>
            <value>
                <fullName>Flexible</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commonwealth Home Support Programme</fullName>
            </value>
            <value>
                <fullName>National Aboriginal and Torres Strait Islander Flexible Aged Care Program</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Quality_Indicator_Summary__c.field-meta.xml
<CustomField>
    <fullName>Quality_Indicator_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quality Indicator Summary</label>
    <referenceTo>Quality_Indicator_Summary__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BusinessLicense/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Service Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Care_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>Pre-operational</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Offline-Temporary Closure of Facility</fullName>
                <label>Offline - Temporary closure of facility</label>
            </value>
            <value>
                <fullName>Offline-Permanent Closure of Facility</fullName>
                <label>Offline - Permanent closure of facility</label>
            </value>
            <value>
                <fullName>Service Record Closed</fullName>
            </value>
            <value>
                <fullName>Closed-Combined</fullName>
                <label>Closed - Combined</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-Operational</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Pre-Operational End</fullName>
            </value>
            <value>
                <fullName>Pre-Operational Start</fullName>
            </value>
            <value>
                <fullName>Offline - Permanent Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Permanent Closure of Facility</label>
            </value>
            <value>
                <fullName>Offline - Temporary Closure of Facility</fullName>
                <isActive>false</isActive>
                <label>Offline - Temporary Closure of Facility</label>
            </value>
            <value>
                <fullName>Suspended</fullName>
                <isActive>false</isActive>
                <label>Suspended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailNotificationSetting__mdt/EmailNotificationSetting__mdt.object-meta.xml
<CustomObject>
    <label>RatingPublishNotification</label>
    <pluralLabel>RatingPublishNotifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/EmailNotificationSetting__mdt/fields/QINotifications__c.field-meta.xml
<CustomField>
    <fullName>QINotifications__c</fullName>
    <defaultValue>true</defaultValue>
    <label>QINotifications</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/Quality_Indicator_Summary__c.object-meta.xml
<CustomObject>
    <label>Quality Indicator Summary</label>
    <nameField>
        <displayFormat>QIS-{000000}</displayFormat>
        <label>Quality Indicator Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Indicator Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/REPORTING_PERIOD__c.field-meta.xml
<CustomField>
    <fullName>REPORTING_PERIOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reporting Period</label>
    <referenceTo>Reporting_Period__c</referenceTo>
    <relationshipLabel>Quality Indicator Summary</relationshipLabel>
    <relationshipName>Quality_Indicator_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Indicator_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Late Submission</fullName>
            </value>
            <value>
                <fullName>Updated After Due Date</fullName>
                <label>Submitted - Updated After Due Date</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/Reporting_Period__c.object-meta.xml
<CustomObject>
    <label>Reporting Period</label>
    <nameField>
        <displayFormat>RP-{000}</displayFormat>
        <label>Reporting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reporting Periods</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Period__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Reporting Period</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Previous_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Previous_Reporting_Period__c</fullName>
    <description>Displays true if dates match previous reporting period</description>
    <formula>IF( ISPICKVAL (Reporting_Period_Type__c, &quot;Quarter&quot;), 
IF( ADDMONTHS( TODAY( ), -3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ), -3 ) &lt;= End_Date__c, True, False ),
IF( ADDMONTHS( TODAY( ), -12 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ), -12 ) &lt;= End_Date__c, True, False )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Previous Reporting Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/QI_Submission_Due_Dt__c.field-meta.xml
<CustomField>
    <fullName>QI_Submission_Due_Dt__c</fullName>
    <description>capture the QI submission due date</description>
    <label>QI Submission Due Dt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period__c</fullName>
    <formula>IF(ISPICKVAL(Reporting_Period_Type__c, &apos;Year&apos;), TEXT(YEAR(Start_Date__c)), &apos;Quarter &apos; &amp; 
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3,&apos;3&apos;, 
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6,&apos;4&apos;, 
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12,&apos;2&apos;,null) ) ) ) 

&amp; &apos; FY &apos; &amp; 

IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1),
2),RIGHT( TEXT(YEAR(Start_Date__c)),
2)) &amp; &apos; - &apos; &amp; IF(MONTH(End_Date__c) &gt;= 7,RIGHT( TEXT(YEAR(End_Date__c) +1),
2),RIGHT( TEXT(YEAR(End_Date__c)),
2)))

&amp; &apos; (&apos; &amp; 

TEXT( DAY( Start_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(Start_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( Start_Date__c ) ) &amp; &apos; - &apos; &amp; TEXT( DAY( End_Date__c ) ) &amp; &apos; &apos; &amp; CASE(MONTH(End_Date__c ),
1,
&quot;January&quot;,
2,
&quot;February&quot;,
3,
&quot;March&quot;,
4,
&quot;April&quot;,
5,
&quot;May&quot;,
6,
&quot;June&quot;,
7,
&quot;July&quot;,
8,
&quot;August&quot;,
9,
&quot;September&quot;,
10,
&quot;October&quot;,
11,
&quot;November&quot;,
12,
&quot;December&quot;,
&quot;None&quot;) &amp; &apos; &apos; &amp; TEXT( YEAR( End_Date__c ) ) &amp; &apos;)&apos; &amp; IF( TODAY() &gt;= Start_Date__c &amp;&amp; TODAY() &lt;= End_Date__c, &apos; - Current reporting period&apos;, IF( ADDMONTHS( TODAY( ),
-3 ) &gt;= Start_Date__c &amp;&amp; ADDMONTHS( TODAY( ),
-3 ) &lt;= End_Date__c, &apos; - Previous reporting period&apos;,
null ) )</formula>
    <label>Reporting Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Short__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Short__c</fullName>
    <description>Shortened version or Reporting Period to match Siebel</description>
    <formula>IF( ISPICKVAL(Reporting_Period_Type__c, &apos;Quarter&apos;),
&apos;Quarter &apos; &amp;
IF( MONTH(Start_Date__c) &gt;= 1 &amp;&amp; MONTH(End_Date__c) &lt;= 3 ,&apos;3&apos;,
IF( MONTH(Start_Date__c) &gt;= 4 &amp;&amp; MONTH(End_Date__c) &lt;= 6 ,&apos;4&apos;,
IF( MONTH(Start_Date__c) &gt;= 7 &amp;&amp; MONTH(End_Date__c) &lt;= 9 ,&apos;1&apos;,
IF( MONTH(Start_Date__c) &gt;= 10 &amp;&amp; MONTH(End_Date__c) &lt;= 12 ,&apos;2&apos;,null) ) ) ) &amp;
&apos; FY &apos; &amp;
IF(MONTH(Start_Date__c) &lt; 7,RIGHT( TEXT(YEAR(Start_Date__c) -1), 2),
RIGHT( TEXT(YEAR(Start_Date__c)), 2)) &amp; &apos; - &apos; &amp;
IF(MONTH(End_Date__c) &gt;= 7, RIGHT( TEXT(YEAR(End_Date__c) +1), 2),
RIGHT( TEXT(YEAR(End_Date__c)), 2)),

TEXT(YEAR(Start_Date__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporting Period Short</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Reporting_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Period_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reporting_Period__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Reporting Period</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/Service_Account_Relationship__c.object-meta.xml
<CustomObject>
    <label>Service Account Relationship</label>
    <nameField>
        <displayFormat>SACR-{0000000}</displayFormat>
        <label>Service Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <label>Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Approved Provider, Commonwealth Home Support Programme, National Aboriginal and Torres Strait Islander Flexible Aged Care Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attached Services</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Account_Relationship__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Name</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Provider Details</relationshipLabel>
    <relationshipName>Service_Account_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QISubmissionReminderBatch.cls
/**
* author: Neha Malik
* date: 23/03/2023
* description: Fetch the records from Quality_Indicator_Summary__c. Then send the Provider Notifications
**/
public with sharing class QISubmissionReminderBatch implements Database.Batchable<sObject>{
    private static final String SUBMIT_TEMPLATE = 'QI_Date_Submission_Reminder';
    private static final String SUBMIT_TEMPLATE_SERVICE = 'QI_Submission_Reminder_Service_User';
    private static final String QISTATUS = 'Submitted';
    private static final String QI_SUBMIT = 'submitQI';
    private static final String ORG_ROLE = 'QI Role - Org';
    private static final String SERVICE_ROLE = 'QI Role - Service';
    private static final String OPERATIONAL = 'Operational';
    private static final String OFFLINE = 'Offline';
    private static final String RESIDENTIAL = 'Residential';
    private static final String APPROVED_PROVIDER = 'Approved_Provider';
    private static final String EMAIL_SUBJECT = 'The QI results for the most recent reporting period due soon [SEC = OFFICIAL]';
    private static final String CONTACT = 'Contact';
    private static final String FIRST_DAY = 'First';
    private Integer numberOfContacts;
    private String batchDay = '';
    List<Reporting_Period__c> prevRepPeriod = [SELECT ID,Name, Start_Date__c, End_Date__c, QI_Submission_Due_Dt__c,Reporting_Period_Short__c From Reporting_Period__c WHERE Previous_Reporting_Period__c = true AND Reporting_Period_Type__c = 'Quarter'];

     public QISubmissionReminderBatch(Integer numberOfCt,String batchExecutionDay){
        numberOfContacts = numberOfCt;
        batchDay = batchExecutionDay;
    }

    public Database.QueryLocator start(Database.BatchableContext bc){
         String query;
        Map<String, EmailNotificationSetting__mdt> mapEmailNotf = EmailNotificationSetting__mdt.getAll();
        if(mapEmailNotf.get('Send_Email').QINotifications__c) {
            if(batchDay!= null && batchDay.equalsIgnoreCase(FIRST_DAY)){
                query = 'SELECT AccountId, ContactId, AccountRecordType__c, Roles, Contact.Email FROM AccountContactRelation '+
                	'WHERE IsActive = true AND AccountRecordType__c =  :APPROVED_PROVIDER '+
                	' AND Contact.Email != null AND Roles INCLUDES (\'QI Role - Service\',\'QI Role - Org\') ' +
                	'AND AccountId IN (select Provider_Name__c from Service_Account_Relationship__c WHERE '+
                	'(Service_Name__r.Status__c = :OPERATIONAL OR Service_Name__r.Status__c = :OFFLINE ) AND '+
                	'Service_Name__r.Care_Type__c = :RESIDENTIAL AND (Association_End_Date__c = null OR Association_End_Date__c >= TODAY))';
            } else {
                 query = 'SELECT Contact.Name,AccountId, ContactId, AccountRecordType__c, Roles, Contact.Email, IsActive '+
            	'FROM AccountContactRelation WHERE IsActive = true AND AccountRecordType__c = :APPROVED_PROVIDER '+
            	' AND Contact.Email != null AND Roles INCLUDES (\'QI Role - Service\',\'QI Role - Org\') AND ContactId '+
            	'NOT IN(select RelationId from EmailMessageRelation WHERE EmailMessage.Subject = :EMAIL_SUBJECT '+
            	' AND RelationObjectType = :CONTACT AND CreatedDate = LAST_N_DAYS:10  ) AND AccountId IN '+
            	'(select Provider_Name__c from Service_Account_Relationship__c WHERE (Service_Name__r.Status__c = :OPERATIONAL '+
            	' OR Service_Name__r.Status__c = :OFFLINE ) AND Service_Name__r.Care_Type__c = :RESIDENTIAL '+
            	' AND (Association_End_Date__c = null OR Association_End_Date__c >= TODAY))';
            }
            if(numberOfContacts >0 ){
                query = query + ' LIMIT :numberOfContacts';
            }
        }
        return Database.getQueryLocator(query);
     }

     public void execute(Database.BatchableContext bc,List<AccountContactRelation> acrRelnList) {
     	if(acrRelnList.size()>0){
        	QIRemindersService qiService = new QIRemindersService();
            String dueDate = qiService.calculateQIReminderDate(prevRepPeriod);
            if(dueDate.equals(QI_SUBMIT)){
            	List<AccountContactRelation> serviceRoleList = new List<AccountContactRelation>();
                List<AccountContactRelation> orgRoleList = new List<AccountContactRelation>();
                for(AccountContactRelation acr:acrRelnList){
                	if(acr.Roles.contains(ORG_ROLE)){
                    	orgRoleList.add(acr);
                    } else if(acr.Roles.contains(SERVICE_ROLE) && !acr.Roles.contains(ORG_ROLE)){
                    	serviceRoleList.add(acr);
                    }
                }
          		try {
                    List<EmailTemplate> etList = qiService.fetchQISubmitTemplate();
                    if(etList.size()>0){
                        if(orgRoleList.size()>0){
                            for(EmailTemplate et:etList){
                                if(et.DeveloperName.equals(SUBMIT_TEMPLATE)){
                                    qiService.prepareAccountData(orgRoleList,prevRepPeriod,et,dueDate);
                                }
                   			}
                        }
                        if(serviceRoleList.size()>0){
                            for(EmailTemplate et:etList){
                                if(et.DeveloperName.equals(SUBMIT_TEMPLATE_SERVICE)){
                                    qiService.prepareContactData(serviceRoleList,prevRepPeriod,et,dueDate);
                                }
                   			}
                    	}
                    }
                } catch(Exception exp) {
            		dohagedcare.Logger.error(exp.getMessage(),exp,'QISubmissionReminderBatch').Log();
        		}
            }
         }
     }

    //Invoking the QISubmissions Batch from finish method
    public void finish(Database.BatchableContext bc){
        try{
            Database.executeBatch(new QIOverdueRemindersBatch(numberOfContacts,batchDay) ,100);
        } catch(Exception exp){
            dohagedcare.Logger.error(exp.getMessage(),exp,'QISubmissionReminderBatch').Log();
        }
    }
}